### ISSUE TITLE
jx --harmony

### ISSUE THREAD

**Issue by moshir** [jxcore/jxcore#102]
Is jx compatible with --harmony flag ?
As per the doc, there's a little example showing usage with the harmony flag.
But, when i tried, i got an unexpected token error.

Any clue ?

**Comment by treasurebox** [comment]
Will be cool :+1:

**Comment by ktrzeciaknubisa** [comment]
An old thread refreshed by @treasurebox :)

SpiderMonkey JXcore already runs ES6 scripts (e.g. with [gerenarators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)) without a problem, and `--harmony` is not even needed. 

As for V8 engine - the new [V8 3.28](https://github.com/jxcore/jxcore/blob/0.3.1.0/doc/HOW_TO_COMPILE.md#v8-328) version that we're adding to the latest 0.3.1.0 can also do this. In this case one should add the `--harmony` option.

**Comment by treasurebox** [comment]
Ah!
Actually, I just wanted Object.observe() (with SM), which I thought is an ES6 feature. But now I realize it's an ES7 proposal! Current node does it anyway, not sure about ffox. Not a high priority (for me).

**Comment by obastemur** [comment]
Closest thing A.T.M is that JXcore SM does have `Proxy` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy . However V8 latest will be part of 0.4.x anyways.

**Comment by treasurebox** [comment]
Cool! A quick google search revealed a Proxy-based Object.observe() polyfill, in case anyone interested: https://gist.githubusercontent.com/ebidel/1b553d571f924da2da06/raw/4b52bae7a52f951b423b799433aede06e284dcfc/object-observe-proxy-polyfill.js

**Comment by Grigoriy74** [comment]
I could not find how to add an option -harmon to JX or JXP
Please, help
