### ISSUE TITLE
where to configure http.setMaxHeaderLength

### ISSUE THREAD

**Issue by smoebody** [jxcore/jxcore#119]
I dont know if its an issue or if its just absence of knowlegde.

I use jxcore with the plesk-extension in my virtual server. i can run my cms [apostrophe](https://github.com/punkave/apostrophe) but on file upload i get the error 

```
Request is denied for security reasons. Maximum allowed header size is configured to 32768 bytes. You may replace it from http.setMaxHeaderLength
```

now i dont know, where to set it. Can anyone help?

**Comment by dottodot** [comment]
I'm trying to add this to my sailsjs and I can access http using  sails.hooks.http but if I try ```sails.hooks.http.setMaxHeaderLength( 1e7 );``` I get an error of has no method 'setMaxHeaderLength', and I also tried 

```
var http = require('http');
http.setMaxHeaderLength( 1e7 ) ;
```
and got the same error

**Comment by ktrzeciaknubisa** [comment]
Are you sure, that your app is launched with `jx` and not with `node`?

**Comment by dottodot** [comment]
Possibly not, how do I make that happen?

**Comment by ktrzeciaknubisa** [comment]
How do you run it then? From the command line or Plesk's extension? If this is `sails lift` then I guess it is node.

**Comment by dottodot** [comment]
I run it using the Plesk extension

**Comment by ktrzeciaknubisa** [comment]
If you have any shell access, possibly you can check with 
```bash
ps aux | grep my_domain.com
```

Or from inside the application:
```js
console.log("INFO", process.jxversion, typeof require('http').setMaxHeaderLength)
```
Here the output should be written into app log file accessible from domain's panel.

**Comment by dottodot** [comment]
It's ok I've sorted it.

**Comment by ktrzeciaknubisa** [comment]
Glad to hear it. I'm curious though - what was the problem?

**Comment by dottodot** [comment]
It needed to be 

```
var http = require('http');
http.setMaxHeaderLength( 1e7 ) ;
```
rather than
```
sails.hooks.http.setMaxHeaderLength( 1e7 );
```

**Comment by ktrzeciaknubisa** [comment]
But you've said "got the same error" when doing this...?

**Comment by dottodot** [comment]
Yes sorry it was because it was on my local environment which isn't running jx, sorry been having a manic morning fixing thing so heads all over the place.
