### ISSUE TITLE
Any option to exclude files

### ISSUE THREAD

**Issue by delagen** [jxcore/jxcore#131]
Need to exclude file in root folder or subfolder in root folder.

**Comment by leanderlee** [comment]
What happens if your subdirectory has the same name as a parent directory? For example, I would like to ignore `src/a/b/src`... but I cannot use `-slim src`...

**Comment by ktrzeciaknubisa** [comment]
`-slim b/src` should work :)

**Comment by leanderlee** [comment]
So it does :+1: Thanks!

**Comment by leanderlee** [comment]
Oh hmm.. I'm not sure if it does.

In my case I am trying to ignore everything in `src/a/b/src`. Using `-slim b/src` it doesn't seem to ignore `b/src/c/file.js`

**Comment by leanderlee** [comment]
```
$ mkdir -p src/a/b/src/c
$ touch src/a/b/src/hidden.js
$ touch index.js
$ jx package index.js test -slim b/src
Processing the folder..
JXP project file (test.jxp) is ready.

preparing the JX file..
Compiling test 1.0
adding script index.js
adding script src/a/b/src/hidden.js
[OK] compiled file is ready (test.jx)
```

**Comment by ktrzeciaknubisa** [comment]
Thanks, I'm going to check it and will let you know.

**Comment by leanderlee** [comment]
Appreciate it! Let me know how I can help.

**Comment by leanderlee** [comment]
Seems like `checkOff` is just comparing results from `readdirSync`, so it wouldn't match properly. https://github.com/jxcore/jxcore/blob/master/src/node.js#L1394-L1408

**Comment by ktrzeciaknubisa** [comment]
You were right. I extended slim capability to receive also relative and absolute paths. It's here: a74e0e40efe9af26c6a0599174d282a2a3375712.

Now you can provide as `-slim` also:
- src/a/b/src
- ./src/a/b/src
- /users/me/folder/src/a/b/src

Still you can combine them with a colon.

**Comment by obastemur** [comment]
@ktrzeciaknubisa we will need a test case for the additional functionality

**Comment by ktrzeciaknubisa** [comment]
Ready in ed70e039c084a3402220d96c8d3d0f98e2772962.

**Comment by leanderlee** [comment]
Nice. Have you considered using a globbing library like (node-globule)[https://github.com/cowboy/node-globule] or (node-glob)[https://github.com/isaacs/node-glob]? I noticed you mentioned adding some similar functionality in #213.

Looking forward to see this in the new jx binaries. Appreciate your hard work @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
Thanks @leanderlee :)

As for #213 - it's on the way. However we haven't decided yet, if we want to use globs there. That would mean either embedding one of the libraries into JXcore or rewriting their functionality. What do you think @obastemur ?

**Comment by obastemur** [comment]
`Have you considered using a globbing library like node-globule or node-glob? `

Even if we benefit glob, we can use that only when we create the jx package definition file. Creating a .jxp file is something can be improved by an external module. Imagine a jxcore / node module 'betterjxp' that creates the jxp file using glob etc..

**Comment by ktrzeciaknubisa** [comment]
You guys might be interested in new packaging feature, that has just been implemented: wildcards for `-slim` ad `add` option for packaging: [#213](https://github.com/jxcore/jxcore/issues/213#issuecomment-94777140).
