### ISSUE TITLE
This operating system is not supported

### ISSUE THREAD

**Issue by Juelcf** [jxcore/jxcore#133]
Hi there, I'm getting an error when i try to run "jx install" in my ubuntu.

Any solution?

Tks

------------------------------

#jx install
Preparing NPM for JXcore (v Beta-0.2.3.6) for the first run

_jx_utils.js:83
        throw new Error("This operating system is not supported ("+info+")");
              ^
Error: This operating system is not supported (linux LinuxHost 3.10.23-xxxx-std-ipv6-64 x86_64)
at Object.exports.OSInfo (_jx_utils.js:83:15)
    at Object.<anonymous> (/root/.jx/index.js.jx:41:27)
    at Module._compile (module.js:525:26)
    at readX (module.js:1209:4)
    at Object.Module._extensions..jx (module.js:1638:9)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Function.Module.runMain (module.js:704:12)
    at startup (node.js:323:14)
    at node.js:2114:1

#lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

**Comment by sepp1974** [comment]
Hi, I still have the same problem on gentoo amd64.
# cat /etc/gentoo-release
Gentoo Base System release 2.2

# uname -a
Linux wolfgang 3.17.0-pf4-sepp2 #2 SMP PREEMPT Mon Feb 2 12:34:52 CET 2015 x86_64 AMD FX(tm)-8350 Eight-Core Processor AuthenticAMD GNU/Linux

# cat /proc/version
Linux version 3.17.0-pf4-sepp2 (root@wolfgang) (gcc version 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9) ) #2 SMP PREEMPT Mon Feb 2 12:34:52 CET 2015

# mkdir ~/test && cd ~/test
# jx install express
Preparing NPM for JXcore (v Beta-0.2.3.7) for the first run

_jx_utils.js:83
        throw new Error("This operating system is not supported ("+info+")");
              ^
Error: This operating system is not supported (linux wolfgang 3.17.0-pf4-sepp2 x86_64
)
    at Object.exports.OSInfo (_jx_utils.js:83:15)
    at Object.<anonymous> (/home/wolfgang/.jx/index.js.jx:41:27)
    at Module._compile (module.js:525:26)
    at readX (module.js:1225:4)
    at Object.Module._extensions..jx (module.js:1654:9)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Function.Module.runMain (module.js:720:12)
    at startup (node.js:323:14)
    at node.js:2115:1

# jx -e "console.log(jxcore.utils.OSInfo())"
_jx_utils.js:83
        throw new Error("This operating system is not supported ("+info+")");
              ^
Error: This operating system is not supported (linux wolfgang 3.17.0-pf4-sepp2 x86_64
)
    at Object.exports.OSInfo (_jx_utils.js:83:15)
    at [eval]:1:26
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:525:26)
    at evalScript (node.js:882:25)
    at startup (node.js:232:7)
    at node.js:2115:1

# npm install express
express@4.11.2 node_modules/express
├── utils-merge@1.0.0
├── merge-descriptors@0.0.2
├── methods@1.1.1
├── fresh@0.2.4
├── cookie@0.1.2
├── escape-html@1.0.1
├── range-parser@1.0.2
├── cookie-signature@1.0.5
├── finalhandler@0.3.3
├── vary@1.0.0
├── media-typer@0.3.0
├── parseurl@1.3.0
├── serve-static@1.8.1
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.0
├── qs@2.3.3
├── on-finished@2.2.0 (ee-first@1.1.0)
├── etag@1.5.1 (crc@3.2.1)
├── debug@2.1.1 (ms@0.6.2)
├── proxy-addr@1.0.6 (forwarded@0.1.0, ipaddr.js@0.1.8)
├── send@0.11.1 (destroy@1.0.3, ms@0.7.0, mime@1.2.11)
├── type-is@1.5.7 (mime-types@2.0.9)
└── accepts@1.2.3 (negotiator@0.5.0, mime-types@2.0.9)

works fine, but not jx install. I tested it as root as well. Same output.

kind regards

**Comment by obastemur** [comment]
@sepp1974 do you have an access to same OS ? 

can you send me both `uname -msrn` and `/proc/version` outputs ?

**Comment by sepp1974** [comment]
# uname -msrn
Linux wolfgang 3.17.0-pf4-sepp4 x86_64

# cat /proc/version
Linux version 3.17.0-pf4-sepp4 (root@wolfgang) (gcc version 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9) ) #4 SMP PREEMPT Tue Feb 17 15:47:04 CET 2015

**Comment by obastemur** [comment]
This should be fixed on latest commit. Appreciate if you can confirm that!
