### ISSUE TITLE
`jx uninstall` doesn't work?

### ISSUE THREAD

**Issue by tomByrer** [jxcore/jxcore#135]
```
λ jx uninstall

module.js:667
    throw err;
          ^
Error: Cannot find module 'I:\gh\design\cropit-CS\uninstall'
    at Function.Module._oldRes (module.js:665:15)
    at Function.Module._resolveFilename (module.js:1515:16)
    at Function.Module._load (module.js:291:25)
    at Function.Module.runMain (module.js:704:12)
    at startup (node.js:323:14)
    at node.js:2114:1

λ jx -jxv
v Beta-0.2.3.6
```
I previously `jx install` with version Beta-0.2.3.2 IIRC.

**Comment by ktrzeciaknubisa** [comment]
We have just added `jx npm [command]` support. So now you can call `jx npm uninstall module-name`. This applies to any other npm command. 

The old way (e.g. `jx install -uninstall module_name`) for now is still available, but may be removed in future: [docs](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-command-install.markdown#npm).

`jx install module_name` still works and will stay this way.
