### ISSUE TITLE
Package error

### ISSUE THREAD

**Issue by abdullah-feroz** [jxcore/jxcore#140]
Hi,

I am facing following problem:

"Warning! ....es\ws\build\Release\validation.node
Adding a .node (native) file into package may fail
Check the related discussion from https://github.com/Nubisa/jxdocs/issues/101
[OK] compiled file is ready (securetool.jx)"

I don't know what is the relation of my problem with the problem mentioned by madhurjain. Kidnly let me know what is the problem. Because when I run my application using "jx securetool.jx" it does nothing.

**Comment by ktrzeciaknubisa** [comment]
Anyone who wants to try new packaging partial extraction feature allowing to run packages containing native modules (*.node* files) - see https://github.com/jxcore/jxcore/issues/370#issuecomment-131396697.
