### ISSUE TITLE
Changing package icon

### ISSUE THREAD

**Issue by madhurjain** [jxcore/jxcore#144]
Is there a way to set a custom icon for the native package generated using JXCore ?

**Comment by brunobg** [comment]
It would be nice to have this supported natively, anyway.

**Comment by obastemur** [comment]
@ktrzeciaknubisa ?

**Comment by ktrzeciaknubisa** [comment]
Well, there is a nice C# project under MIT licence: [InsertIcons](https://github.com/einaregilsson/InsertIcons). After some modification I was able to use it and to replace the icon from a command line.

@obastemur would that approach be ok? Just one more exe file (200 kB) added to windows setup.

**Comment by obastemur** [comment]
better not (C# dependency). We can instead put a tutorial / doc etc. and link it to here.

**Comment by ktrzeciaknubisa** [comment]
But that still would not be a native support.

There are also c++ solutions available, I wonder if we can make an addon out of it.

**Comment by diogobernini** [comment]
It'd be nice not having to tweak the icons all the time, but instead having them as a field maybe on the jxp to be automatically added.

**Comment by diogobernini** [comment]
For those of you who didn't succeed using the InsertIcons (since JX already sets the default icon), just do the following and it'll work:
    Download http://www.angusj.com/resourcehacker/resource_hacker.zip (Portable App).
    File -> Open -> Select the executable.
    Action -> Replace Icon -> Open File with new Icon -> Select the new Icon.
    Save.

**Comment by plika** [comment]
@diogobernini are you doing this to the final compiled app ?

**Comment by diogobernini** [comment]
Yes.

**Comment by ktrzeciaknubisa** [comment]
> For those of you who didn't succeed using the InsertIcons (since JX already sets the default icon)

Yes. By default InsertIcons adds new icon files (does not replace). However I was able to change this behavior by forcing`GetMaxIconId()` to return 0.

**Comment by diogobernini** [comment]
Instead of forcing changes on the InsertIcons code, I'm using Resource Hacker from the command line in a bash script, that calls the jx compile and then changes the icon.

**Comment by ktrzeciaknubisa** [comment]
Alright. To summarize everybody's effort, here are two command-line options for changing package icon.

1. [ResourceHacker](http://www.angusj.com/resourcehacker/resource_hacker.zip) (thanks to @diogobernini for link) can be used that way:

    ```bash
> ResourceHacker.exe -addoverwrite "test.exe", "test.exe", "icon.ico", ICONGROUP, MAINICON, 0
```

2. [InsertIcons](https://github.com/ktrzeciaknubisa/InsertIcons) - the link goes to fork of original [repo](https://github.com/einaregilsson/InsertIcons). Fork adds support for `--replace` argument, and so it can be called this way:

    ```bash
> InsertIcons.exe test2.exe "icon.ico" --replace
```
   For those, who don't want to bother with C# compilation, I uploaded executable compiled in release mode: [InsertIcons.exe](https://github.com/ktrzeciaknubisa/InsertIcons/raw/master/bin/Release/InsertIcons.exe).

***

In my opinion the 1st option is better. The second way (InsertIcons) removes some file attributes/permissions and makes the file private: please note the padlock on `test2.exe` icon:

![files](https://cloud.githubusercontent.com/assets/5946844/9941911/91b6e20e-5d78-11e5-85ba-59523f79b4f6.png)

I'm closing this issue for now.
