### ISSUE TITLE
Sails.js gets wrong domain name under JX

### ISSUE THREAD

**Issue by curcuz** [jxcore/jxcore#147]
running a sails.js based application under JXcore makes that framework fail to determine the hostname: it gets actually the hostname but with a prefix appended like **"jxcore_target_+domain_name"**

to reproduce the issue, you can install on the domain root of your Plesk installation a [Sails.js](http://sailsjs.org) application, configure under the JXcore panel the domain, and run it. Any link or path providing functions will be broken
![screen shot 2014-11-14 at 12 40 59](https://cloud.githubusercontent.com/assets/2338223/5045337/b3b2b8f2-6bfb-11e4-97cc-9a9ada37d6f4.png)

**Comment by ktrzeciaknubisa** [comment]
Hi, the Plesk team has just published updated version of [JXcore Plesk Extension for Node 2.5.1](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). We gave up on upstream usage inside nginx configuration for domains and it seems to work well.

@curcuz Any feedback whether it solves your problem or not will be much appreciated.

**Comment by curcuz** [comment]
wow, never seen these updates until today, wtf. Sorry about that @ktrzeciaknubisa, unfortunately we no longer use the plesk stack so i'm unable to help testing here

**Comment by ktrzeciaknubisa** [comment]
No problem, thanks :) 
Anyway it is supposed to be already solved, so I'm closing the issue.
