### ISSUE TITLE
JXCore Package seems to fail handling require.js

### ISSUE THREAD

**Issue by madisonsmith** [jxcore/jxcore#151]
Hi, I am trying to package my application using jxcore. Everything goes pretty well until I try to actually run the executable. I am using the node sentiment module with require.js and when I run the packaged executable I get the following error.

``` bash
d.sentiment = sentiment(d.text);
                          ^
TypeError: object is not a function
```

However, if I run the application normally from the command line by simply executing jx "my application" everything operates normally. When I log the sentiment object I get the following:

``` bash
{ '$JXP': [Getter] }
```

If I run the server from the command line as expected it logs that the sentiment object is a function. The package command I am running is:

``` bash
jx package "myapplication" "executable name" -native
```

I have also tried without the native flag and put the dependencies in the package.json and get the same results. 

I have tried on both OSX and Windows with the same results. The version is Beta-0.2.3.7. 

Love the program and any support you could give would be great!

**Comment by ktrzeciaknubisa** [comment]
Yes, you're right. The file name conflict came obvious only recently. See #158. It's there as a bug.
