### ISSUE TITLE
Jxcore exception with edge module

### ISSUE THREAD

**Issue by gberthalon** [jxcore/jxcore#160]
An exception occurs with edge module : https://github.com/tjanczuk/edge
this module provide .Net execution with nodejs
My app works fine with node.js

this is my exception :
unhandled exception : System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at continueOnV8Thread(uv_async_s* handle, Int32 status)

**Comment by ktrzeciaknubisa** [comment]
Hi @gberthalon . I know, it's been some time, but when I try to run your sample against few **node** versions (0.10.22, 0.10.38) it doesn't work as well, so probably there is something missing in it?

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
```

**Comment by gberthalon** [comment]
Hi,

perhaps reinstall edge module? :
npm install edge

**Comment by ktrzeciaknubisa** [comment]
Not really. Does it work for you?

**Comment by gberthalon** [comment]
Hi, yes it work, 
.Net 4.5 framework and edge module must be installed
result :
![capture d ecran 2015-04-27 a 22 05 31](https://cloud.githubusercontent.com/assets/1839524/7356614/a237542a-ed29-11e4-98b5-a88ad3fffc15.png)

**Comment by gberthalon** [comment]
With jxcore :
![capture d ecran 2015-04-27 a 22 08 17](https://cloud.githubusercontent.com/assets/1839524/7356667/fcf4e832-ed29-11e4-9797-9045e2276bc4.png)

**Comment by ktrzeciaknubisa** [comment]
Ok, I was able to observe the difference between running the sample with node (which works eventually) and latest jxcore (0.3.0.4), although I don't get any error. The process just exists on my Win 7 x64 platform without any kind of output. Just the `%errorlevel%` is -1073741819 (0xc0000005, which is the code for STATUS_ACCESS_VIOLATION).

I was trying to debug the problem and it fails **silently** on `edge.js#L51`:

```js
edge = require(".\\native\\win32\\x64\\0.10.0\\edge.node");
```
Try/catch block is not able to catching this.

Further inspection shows, that it calls `module.js: process._dlopen()` which fails at [node.cc#L1216](https://github.com/jxcore/jxcore/blob/master/src/node.cc#L1216):
```c
mod->register_func(exports, module);
```

That's all I know for now.

**Comment by ktrzeciaknubisa** [comment]
BTW. `jx install edge` works much better now than at the time when this issue was created (we introduced few `jx install` improvements in the meantime), however it still outputs an error (but completes anyway):

```bash
> edge@0.10.1 install C:\jxcore\jxcore-issues\jxcore\x160\node_modules\edge
> c:\jxcore\jxcore_64v8\Release\jx.exe tools/install.js

***************************************
[Error: The specified procedure could not be found.
c:\jxcore\jxcore-issues\jxcore\x160\node_modules\edge\lib\native\win32\x64\0.10.0\edge.node]
***************************************
Success: platform check for edge.js: node.js x64 v0.10.39
edge@0.10.1 node_modules\edge
├── edge-cs@0.2.7
└── nan@1.8.4_modules\edge\lib\native\win32\x64\0.10.0\edge.node]
***************************************
```
Those things might be related.

**Comment by obastemur** [comment]
jxcore perfectly installs edge on Windows but edge comes with pre-compiled binaries (under lib\native) and uses them. At this point we have nothing to do. This needs to be reported on edge side. i.e. they could let 'jx install' or 'npm install' compile it on installation.
