### ISSUE TITLE
--v8-options in native build

### ISSUE THREAD

**Issue by jiangzhuo** [jxcore/jxcore#165]
I use the native compile feature compiled my app into native.
jx -max_old_space_size=42000 app.js           work
when compiled into native 
appNative --max_old_space_size=42000       not work

How can I compile my app into native and still use --v8-options

**Comment by ktrzeciaknubisa** [comment]
Sorry, but native packages are not receiving v8 options or any other arguments known in node as `process.execArgv`. Therefore all of the arguments go into `process.argv`.
