### ISSUE TITLE
jx file is not created

### ISSUE THREAD

**Issue by westor21** [jxcore/jxcore#166]
Hi there, I've installed JXCore a windows 32 bit machine. I tryed to make a package of my complete gulp dev environment like this: "jx package node_modules\gulp\bin\gulp.js gulpStart"
That took a long time (ca 1 hour) and brought me a jxf file of 7.5 MB, but I'm missing the jx file. No error was printed out, and also a "jx compile gulpStart" does not create the file.
Are there any limits in size? If I try to make a small module, everything works fine.

**Comment by obastemur** [comment]
when you call 'jx package' it collects everything (starting from) the folder you are in. Perhaps, this wasn't something you wanted? you may create a folder with the exact content of your project and then create the package.. i.e. (jx package gulp.js gulpStart)

**Comment by westor21** [comment]
yes, that is what I expected. The jxp file contains the structure of all items my project has. But there is no .jx file created. If I understood the doc, both files should be created by package command (and by compile package, if jxp alreday exists).

**Comment by ktrzeciaknubisa** [comment]
I'm not aware about size limit of jx package, however the issue you get might be environment related (memory amount, management etc.). The jxp file gets created as first, and jx file afterwards. Maybe the packaging process was killed by the system? Are you sure you haven't receive any error message? 

I tried to follow your scenario and create jx package with even greater size of jxp file as yours (mine had 13.5 MB) and already after few minutes I was able to notice dramatic drop down of speed of the packaging process. I guess we just didn't focus much on this kind of package sizes.

Also, please check our blog post [Better Resource Management for JXcore Packaging](http://jxcore.com/better-resource-management-for-jxcore-packaging) where we try to describe the subject. Especially this line:

*If the binary’s size is: let’s say, 50 MB, it would consume in the best case at least the same amount of memory.*

Which means that even if you will be able to create a jx package as you excected, it will eat your RAM for at least as much as your jx file size is.

**Comment by westor21** [comment]
Ah, ok - thank you for that information.

Meanwhile I stripped down my directory to that, what we don't want to bring into version control.
What we want to do, is to install a dev environment to several developers without the need to set up a node environment with git and firewall rules to access public repos.
The resulting jxp file is now 5,7 MB and the package process ist working fine. I used the -native option, and the windows exe file is now 85 MB. It takes some time to start, but it works.

I noticed another issue: All the js files with the line
#!/usr/bin/env node
are causing the application to crash.

I removed these line in my windows node files, but it would be great, if you could find a way to handle that. Should I open another issue for that?

**Comment by ktrzeciaknubisa** [comment]
> I noticed another issue: All the js files with the line #!/usr/bin/env node are causing the application to crash.

Yes, we know about this bug but it applies only to jx/native packages. Plain JavaScript files having the shebang line run properly with JXcore, so if you'll ever consider to deliver your project unpacked - you don't have to remove those lines.

**Comment by obastemur** [comment]
I'd fixed on latest master, can we check it?

**Comment by ktrzeciaknubisa** [comment]
@obastemur Do you mean the shebang error? Still an error:

```bash
./jx test/run.js -file test/jxcore/test-shebang.js -p
```

**Comment by ktrzeciaknubisa** [comment]
@westor21 The shebang problem should be definitively fixed: f3fa8d0b41b803fe9b81b775aea6250634b56f5e .

**Comment by ktrzeciaknubisa** [comment]
Closing this as it is considered as solved.
