### ISSUE TITLE
Nginx directives issues

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#171]
I'm trying to add some settings using the Nginx directives for example using the code from https://gist.github.com/thoop/8165802

If I just try adding the location settings like

```
location / {
        try_files $uri @prerender;
    }
 
    location @prerender {
        #proxy_set_header X-Prerender-Token YOUR_TOKEN;
        
        set $prerender 0;
        if ($http_user_agent ~* "baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }
        if ($uri ~ "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff)") {
            set $prerender 0;
        }
        
        #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;
 
        if ($prerender = 1) {
            
            #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
            set $prerender "service.prerender.io";
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://$prerender;
        }
        if ($prerender = 0) {
            rewrite .* /index.html break;
        }
    }
```

I get an error of 
```Provided directives failed on test. Cannot parse options: SyntaxError: Unexpected token```

**Comment by ktrzeciaknubisa** [comment]
Hi, yes, it requires an update from last friday (not released yet) to skip this parsing error. But another thing is, that 'nginx directives' field on domain's form is suplementary to default config, which means, that it appends to it (not replaces). So for example, since default config already defines behavior for `location /` - you will not be able to define another one like in your sample.

**Comment by dottodot** [comment]
OK makes sense, only just started using nginx so still working it out. I have found that the nginx directive on the domain allows me to post certain things but has no effect as I assume jxcore overrides it but I then can't paste them in the jxcore setting as I get various errors.

**Comment by ktrzeciaknubisa** [comment]
Various errors - do you mean others than "Cannot parse options: SyntaxError: Unexpected token" ?

**Comment by dottodot** [comment]
Sorry should have said, yes been getting that error.

**Comment by dottodot** [comment]
Sorry forgot to ask, do you know when the parsing error fix will be released?

**Comment by ktrzeciaknubisa** [comment]
We've found also other related issue, and we still work on it. The fix should be available these days. In a meantime you can try to follow the hack from #170 (remove `\n`, `\r` and add something like `gzip_proxied any;` at the end of your directives. Sorry for inconvenience.

**Comment by dottodot** [comment]
OK thanks ```gzip_proxied any;``` seems to partly work however after trying to convert some htaccess still throws errors that don't occur when adding them in the domain addition nginx directives. For example

```
if (!-f $request_filename) { set $rule_0 1$rule_0; } gzip_proxied any;if (!-d $request_filename) { set $rule_0 2$rule_0; } gzip_proxied any; if ($rule_0 = "21") { rewrite ^/[\w/-]+$ /index.html last; } gzip_proxied any;
```
Gives the error
```Provided directives failed on test. Cannot parse options: SyntaxError: Unexpected number```

**Comment by ktrzeciaknubisa** [comment]
That's why it needs a fix :) It is a matter of string escaping plus few other internal things. Minor redesign is needed, so we're on it at the moment. I'd like to send you a beta version once it's ready (before the release), can I use for this the mail address from your profile?

**Comment by dottodot** [comment]
Yes that would be good.

**Comment by ktrzeciaknubisa** [comment]
Hi, the Plesk team has just published updated version of [JXcore Plesk Extension for Node 2.5.1](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). Nginx directive issue is resolved there.

One thing was not changed though, as it is part of the design:

> since default config already defines behavior for `location /` - you will not be able to define another one like in your sample.
