### ISSUE TITLE
Using with prerender the url is wrong

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#172]
When using with prerender the url received by prerender is in the format of http://jxcore_target_test.example.com rather than http://test.example.com

In my sailsjs I'm using the express prerender-node middleware as below

```
module.exports.http = {
  customMiddleware: function(app) {
    app.use(require('prerender-node').set('prerenderServiceUrl', 'http://prerender.example.com:3000'));
  }
};
```
I'm a bit confused as to how I get the correct url sent to prerender.

**Comment by dottodot** [comment]
So I've found that if I manually modify the conf file so is uses something like ```proxy_pass http://127.0.0.1:10002;``` rather than the upstream everything works.

Obviously I'm going to lose this setting if I save anything so is there a way round this.

**Comment by ktrzeciaknubisa** [comment]
Thanks, that's useful info. We might give up on upstream since someone else also mentioned a problem: #147. I'll try to add this to the fix I'm currently working on.

**Comment by dottodot** [comment]
Ok great, should be able to manage hacking it until the update is available.

**Comment by ktrzeciaknubisa** [comment]
Hi, the Plesk team has just published updated version of [JXcore Plesk Extension for Node 2.5.1](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). 

We gave up on upstream usage inside nginx configuration for domains and it seems to work well.
