### ISSUE TITLE
Custom Locations

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#174]
I'm finding that various settings that I want the add to my site require adding a location option for example if I want to add cache busting something like the below would do this.

```
location ~* (.+)\.(?:\d+)\.(js|css|png|jpg|jpeg|gif)$ {
   try_files $uri $1.$2;
}
```

However this can't be added using nginx directives so I'm at a bit of a loss as to how I would add such customisations.

**Comment by ktrzeciaknubisa** [comment]
Hi, the Plesk team has just published updated version of [JXcore Plesk Extension for Node 2.5.1](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). Nginx directive issue is resolved there.

**Comment by paulcanning** [comment]
I am unable to add nginx directives on v 0.3.1.0. I get the following error in the JXCore logs `Spawner error: Nginx config dir does not exists.`

**Comment by ktrzeciaknubisa** [comment]
@paulcanning It looks like you don't have nginx default `/etc/nginx/jxcore.conf.d/` folder ? Was the nginx installed at any custom location?

**Comment by paulcanning** [comment]
The server we rent is an Ubuntu VM, with Plesk installed. It does use NGINX, but seems like its a weird custom install (typical!) I don't really want to do anything to jeopardise the server setup (I already nuked it once by installing NodeJS)

**Comment by ktrzeciaknubisa** [comment]
> Can I safely make the jxcore.conf.d folder?

There should not be a need for this, as JXcore Extension creates it on install. I would suggest to reinstall JXcore Extension at first.

**Comment by paulcanning** [comment]
Well for what ever reason, the folder was not created, so I made it manually. After that, every thing came together.
