### ISSUE TITLE
using C++ addon with JXCore

### ISSUE THREAD

**Issue by rdesh11** [jxcore/jxcore#175]
I am on Windows Operating system
I have created my own addon named "SystemInfo" in C++ using VS2010.
I have SystemInfo.node file created with me.

Now I am trying to use it in app,js file like below. 

var addon = require('./build/SystemInfo');
console.log(addon.getDiskSpace('C'));

Now when I am creating an executable using JXCore by below command
jx package app.js myapp -slim build -native

myapp.exe is getting created, but when I am trying to execute it I am getting below error. 

node.js:642
    var gpath = process._dlopen(module, filename);
                        ^
Error: %1 is not a valid Win32 application.
c:\bench\svn\123\build\systeminfo.node
    at Object.process.dlopen [as .node] (node.js:642:25)
    at Module.load (module.js:369:35)
    at Function.Module._load (module.js:336:12)
    at Module.require (module.js:388:17)
    at require (module.js:405:17)
    at Object.<anonymous> (C:\bench\svn\123\temp.js.jx:3:13)
    at Module._compile (module.js:525:26)
    at readX (module.js:1225:4)
    at Object.Module._extensions..jx (module.js:1654:9)
    at Module.load (module.js:369:35)

I have also tried renaming myapp.exe to node.exe, but same result.
Can anyone help me what I am missing here.

**Comment by ktrzeciaknubisa** [comment]
Did you try to use [dren.js](https://github.com/jxcore/jxcore/blob/master/samples/jx_packaging/dren.js) trick from #118? Also, which is your Node.JS version?

**Comment by rdesh11** [comment]
Yes, I have tried renaming output as node.exe. (as given in #118)
My node js version 0.10.26

**Comment by ktrzeciaknubisa** [comment]
Not just renaming. Let me quote @obastemur :

> Native modules expecting the process name as 'node.exe' on windows in order to load the required references etc. Using below application, you may alter the executable name inside the modules. (You must limit your applications name to 4 letters + .exe though)

> https://github.com/Nubisa/jxdocs/blob/master/samples/jx_packaging/dren.js

**Comment by rdesh11** [comment]
Thank you for pointing it out.
but I am confused now.

Do I need to create test.exe first using 
jx package app.js myapp -slim build -native this command and then use the dren.js?

Can you please provide sequence of actions.

**Comment by ktrzeciaknubisa** [comment]
Ok, sorry for not being clear enough :) As far as I understand a problem, if renaming myapp.exe to node.exe did not work, you can try the "dren.js" trick, which alters .node files. So, for example:

1.  `jx package app.js test -slim build -native`
(note, that this will create test.exe - file name with 8 chars including extension, as written in comments of [dren.js](https://github.com/Nubisa/jxdocs/blob/master/samples/jx_packaging/dren.js) )
2. run `jx dren.js * "test.exe"`, which will alter .node files
3. now you can try to run the app.

**Comment by obastemur** [comment]
@ktrzeciaknubisa seems like we've deleted dren.js. could you please relocate that with the documentation ?

**Comment by ktrzeciaknubisa** [comment]
@obastemur Sure. Uploaded.
