### ISSUE TITLE
ASM.JS command line option

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#177]
Right now we are able to run ASM.JS code with ```require.withAsmJS``` but It could be handy to have an option like ```jx --asm asm_script_file.js```

**Comment by obastemur** [comment]
SpiderMonkey team have taken care of this. We no longer need an extra naming for asmjs scripts. 

@ktrzeciaknubisa removing `withAsmJS` extra from the codes, please update the docs accordingly.

**Comment by ktrzeciaknubisa** [comment]
Codes and docs updated.
