### ISSUE TITLE
(Plesk) Ignore directory to prevent application restart

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#180]
Is it possible to ignore a directory, so that any changes don't restart the app.

**Comment by ktrzeciaknubisa** [comment]
Unfortunately not for the moment. However since changes are detected only for `.js` and `.jx` files, you try to go around this by writing your code into files with different extension, e.g. `.jx_` (if it's not too inconvenient for you).

**Comment by ktrzeciaknubisa** [comment]
Another hack would be to have your app in subfolder like *app/index.js* of domain root (then you should also provide this path on domain's configuration page), and other files outside the *app* directory, e.g.: in domain root or *files/file.js* etc.

**Comment by ktrzeciaknubisa** [comment]
The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).

@dottodot Now you can easily define **Ignored Paths** on **Restart Manager** tab at domain's configuration page of the JXcore extension.
