### ISSUE TITLE
Ability to codesign the executable

### ISSUE THREAD

**Issue by mleedavies** [jxcore/jxcore#181]
Provide a configuration file so that executable can be codesigned

**Comment by ktrzeciaknubisa** [comment]
The signing of native packages have been added. 

There is a new `sign` field in .jxp file (and `-sign` switch in `jx package` command). It's documented [here](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-feature-packaging-code-protection.markdown#-sign).
