### ISSUE TITLE
Suggestion: Todo List

### ISSUE THREAD

**Issue by Ben007** [jxcore/jxcore#182]
There are and will be lots of good ideas on features and other stuff. I recommend a collaborative TODO list similar to [Known Issues](https://github.com/jxcore/jxcore/blob/master/known_issues.md) document.

**Comment by obastemur** [comment]
Actually the current known issues list plays a 'TODO' role. I think I got your point. We might use a separate list for desired features right?

**Comment by obastemur** [comment]
Closing this in favor of roadmap document.
