### ISSUE TITLE
Tests: Unicode test is broken

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#183]
When running 

```
./jx test/run.js -file test/jxcore/test-unicode2.js –p
```
it gives an error. but If I package the sample code individually, it works fine. I don't see any problem with SpiderMonkey unicode packaging.

**Comment by obastemur** [comment]
Same goes for the below one on OSX. If the intention was for Windows (better the test doesn't run unix at all)

```
./jx test/run.js -file test/jxcore/test-others-__dirname.js -n
```

**Comment by ktrzeciaknubisa** [comment]
They were failing for OSX, but now it looks like they all are already fixed. Checked with SM and V8.
