### ISSUE TITLE
Why are jxcoreIOS* directory in my root?

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#187]
I just built following https://github.com/jxcore/jxcore/blob/master/doc/iOS_Compile.md and was looking for the jxcoreIOS* directories. I eventually found them, in my root directory! Seems like an odd place to put them.

**Comment by obastemur** [comment]
Indeed it's not the best way to locate the final binaries but it's consistent with the documentation. 

The best option looks like storing all of them inside the project's root folder (i.e. under ios_out).  Do you think it's okay?

**Comment by obastemur** [comment]
Commit 
https://github.com/jxcore/jxcore/commit/12b12d59148377f91c8699dfb4621ba25bfd8ec0
should fix this problem. Documentation is also updated to comply with the latest script.
