### ISSUE TITLE
replace embedjs.py or get rid of which dependency

### ISSUE THREAD

**Issue by jsbee** [jxcore/jxcore#188]
I'm trying make SM build compiling on Windows. So far the 'which' module dependency is a headache. Can we get rid of that ?

**Comment by obastemur** [comment]
I don't think it's a good idea to patch a SpiderMonkey build processing file we may forgot later. Currently we will be benefiting from mozilla-build tools for Windows SpiderMonkey builds and AFAIK the package has everything needed. Actually, SpiderMonkey Windows compile support is quite straight-forward. (some changes on gyp files and that's it)

For Windows-RT / Windows ARM builds, we will be disabling SpiderMonkey helper threads and related parts hence mingw won't be needed there.  

One another possibility is to update POSIX_NSPR / pthread stuff with corresponding Windows API but I don't have time for that for now and I think it's better to check that with SpiderMonkey team first.

**Comment by obastemur** [comment]
this problem is not relevant anymore. SM Windows build will be using nsprpub and which is no longer a case on windows.
