### ISSUE TITLE
fail when run build_scripts/ios-compile.sh on mac osx 10.9.5

### ISSUE THREAD

**Issue by iwater** [jxcore/jxcore#190]
../deps/uv/src/unix/loop.c:73:5: error: use of undeclared identifier 'stdout'
../deps/uv/include/uv.h:282:23: note: expanded from macro 'KICKPRINT'
    if (flush) fflush(stdout); \
                      ^
../deps/uv/src/unix/loop.c:78:5: error: use of undeclared identifier 'stdout'
    KICKPRINT(1, "MUTEX INIT - %s", "libuv loop.c");
    ^
../deps/uv/include/uv.h:282:23: note: expanded from macro 'KICKPRINT'
    if (flush) fflush(stdout); \
                      ^
../deps/uv/src/unix/loop.c:84:5: error: use of undeclared identifier 'stdout'
    KICKPRINT(1, "ASYNC INIT - loop.c (libuv) err: %s",
    ^
../deps/uv/include/uv.h:282:23: note: expanded from macro 'KICKPRINT'
    if (flush) fflush(stdout); \
                      ^
2 warnings and 3 errors generated.
make[1]: *** [/Users/iwater/Codes/jxcore/out/Release/obj.target/libuv/deps/uv/src/unix/loop.o] Error 1
make: *** [jx] Error 2
Compilation aborted

**Comment by ktrzeciaknubisa** [comment]
That's because you should compile it on the target platform (iOS).

**Comment by obastemur** [comment]
After cleanup mess. Fixed. Thanks for letting us know!

**Comment by ktrzeciaknubisa** [comment]
After the fix I've got this one:

> In file included from ../deps/mozjs/incs/mozilla/double-conversion/bignum.cc:28:
In file included from ../deps/mozjs/incs/mozilla/double-conversion/bignum.h:31:
../deps/mozjs/incs/mozilla/double-conversion/utils.h:73:2: error: Target architecture was not detected as supported by Double-Conversion.
#error Target architecture was not detected as supported by Double-Conversion.
 ^
1 error generated.
make[1]: *** [.../jxcore/out/Release/obj.target/mozjs/deps/mozjs/incs/mozilla/double-conversion/bignum.o] Error 1
make: *** [jx] Error 2
Compilation aborted

OSX 10.9

**Comment by obastemur** [comment]
@ktrzeciaknubisa couldn't reproduce your problem. Try a clean build.

**Comment by ktrzeciaknubisa** [comment]
I have tried a clean build by removing out*_ios folders - still the same error. I'll try to update Xcode. Cannot take the latest version, since it is available for OSX 10.9.4 or later, so I'll try to find lower version.

**Comment by ktrzeciaknubisa** [comment]
Ok. It's good now. 

For my OSX 10.9 I've updated Xcode to version 6.0.1 manually (while the latest available through App Store now is 6.1.1 which I couldn't install as I wrote before).

Now iOS compilation works great.
