### ISSUE TITLE
Discuss: WinRT Support. What are the challenges in supporting WinRT devices?

### ISSUE THREAD

**Issue by ukadakal** [jxcore/jxcore#194]

**Comment by obastemur** [comment]
On my side, we have SpiderMonkey build is ready. After the urgent items, we may turn back to whole RT support.

**Comment by ktrzeciaknubisa** [comment]
That's really exciting. 
I just got an idea to construct a basic **ROADMAP.md** file and put all things that we have on mind, including RT, Cordova etc. Also as an answer to #153.

**Comment by obastemur** [comment]
Sounds good to me.

**Comment by ukadakal** [comment]
Good idea! Let's do it.

**Comment by ktrzeciaknubisa** [comment]
I've uploaded a draft available from main [README](https://github.com/jxcore/jxcore) file.
