### ISSUE TITLE
Discuss: Running JXcore with Cordova

### ISSUE THREAD

**Issue by ukadakal** [jxcore/jxcore#195]

**Comment by obastemur** [comment]
I propose a plugin for cordova and phonegap (which is almost ready). Something like;

```
$ > cordova plugin add jxcore
``` 
And that's it. Now you can use node.js / jxcore with cordova/phonegap application.

 - use all the jxcore/node features
 - run time taking etc. JavaScript operations on a separate jxcore thread. 
 - use embedded packaging 
.. and more.

Perhaps best if we simply open this plugin project on a separate repository.

**Comment by yaronyg** [comment]
Yeah, separate repositories are the easiest to think about. Just stick it under the parent so something like jxcore/jxcore-cordova.

**Comment by jsbee** [comment]
+1

**Comment by Nicolab** [comment]
+1

**Comment by Mithgol** [comment]
+1

**Comment by obastemur** [comment]
Here is a starter project. Now iOS works, working on Android part. 
https://github.com/jxcore/jxcore-cordova
