### ISSUE TITLE
cmdSync: remove negative exit codes

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#202]
We've been using negative exit codes in order to measure the custom operations managed by core. We should replace them to proper numbers. (for custom exit codes use the positive version of the actual one)

@ktrzeciaknubisa I'm keeping a terrible hack at cmdSync to cover this. (jxutils_wrap.cc / exec) You can remove that after the cleanup.

**Comment by ktrzeciaknubisa** [comment]
Cleanup performed and it seems working [3bd08d9f](https://github.com/jxcore/jxcore/commit/3bd08d9f9e7a93eae6523d9d35033f4c13430851).
