### ISSUE TITLE
How to run jxcore in Android?

### ISSUE THREAD

**Issue by sequoiar** [jxcore/jxcore#203]
Is jxcore android built as executable binary, or jar library? How to use it in android?

**Comment by obastemur** [comment]
When you follow the build documentation, you will have the static libraries for different cpu architectures (intel and arm). You can use them as you wish. 

Regardless, Very soon we will be sharing the samples to make things very easy.

**Comment by ktrzeciaknubisa** [comment]
@sequoiar There is a [JXcore / Node.JS for Android sample](https://github.com/obastemur/jxcore-android-basics) already published.
