### ISSUE TITLE
Native modules included in JXcore

### ISSUE THREAD

**Issue by ukadakal** [jxcore/jxcore#206]
Native modules will not work with SpiderMonkey due to API changes. We have included some of the most common native modules in the project to ensure compatibility. 

Since SpiderMonkey option is for mobile and IoT devices, it makes sense to include modules useful in mobile apps. We'd like to hear suggestions on which native modules to include in JXcore.

**Comment by yaronyg** [comment]
I actually looked at what native modules are most popular. Please check out http://www.goland.org/node-gyp-and-node-js-on-mobile-platforms/

For entertainment purposes I expanded the analysis to also mark any modules that have an OS or CPU restriction as being 'native' and it didn't change the results in the article in any meaningful way. So the list (assuming my heuristic is correct and the code isn't buggy) at the very end of the article should give a pretty good list of the most interesting native modules to look at.

For the Thali project we need LevelDB for our PouchDB dependency.

**Comment by ukadakal** [comment]
@yaronyg thanks for the link!

**Comment by obastemur** [comment]
@ukadakal we have only sqlite3 embedded. I'm against to force anything else into base build (unless node.js side makes an attempt) We can instead give a compile time option (to embed) for supported native modules. This way, we could also improve our binary packaging feature.

**Comment by ukadakal** [comment]
@obastemur I agree with your idea! We certainly don't want to increase the size and complexity of our base build unnecessarily. Adding such a functionality to packaging will be the most flexible approach.

**Comment by urbien** [comment]
Our app needs node's dgram and net modules on iOS, Android, OSX. Are they included?

**Comment by ktrzeciaknubisa** [comment]
@urbien I believe that all core modules coming from Node.JS are included, so the answer is: yes. It's easy to check anyway:

```js
console.log(require('dgram'));
console.log(require('net'));
```

**Comment by urbien** [comment]
Node.JS does not provide implementation of dgram and net modules on iOS and Android. So I wonder if jxcore crew did this work, before I dig into building and testing jxcore app on iOS and Android.

**Comment by obastemur** [comment]
All the core features should be fine but may not be stable yet.

**Comment by obastemur** [comment]
This topic has no place left to go. Closing. Thanks for all the contribution here.

**Comment by urbien** [comment]
thank you for answers, you are doing an amazing job, node on mobile is the next evolution of the software stack. It would be great to see some confirmation - dgram and net tests working on mobiles though.

**Comment by ktrzeciaknubisa** [comment]
Currently we're preparing a test base for mobile targets. Soon enough we should know if they really work and are stable.

**Comment by urbien** [comment]
awesome!
