### ISSUE TITLE
How to check JS engine used

### ISSUE THREAD

**Issue by JesusIslam** [jxcore/jxcore#208]
How to check if a jx build is using Spidermonkey or V8?

**Comment by ktrzeciaknubisa** [comment]
Hi, you can check `process.versions.sm` or `process.versions.v8` values. They contain versions of used engines. One of them is always 0.

For example SM:

```bash
$ ./jx -e "console.log(process.versions)"
{ http_parser: '1.0',
  node: '0.10.36',
  jxcore: 'Beta-0.3.0.0',
  v8: 0,
  sm: 340,
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1i' }
```

**Comment by obastemur** [comment]
@ktrzeciaknubisa can we have this documented or we already have it ?

**Comment by ktrzeciaknubisa** [comment]
Good idea. I've just updated [process.versions](https://github.com/jxcore/jxcore/blob/master/doc/api/process.markdown#processversions).

**Comment by JesusIslam** [comment]
Thanks alot guys
