### ISSUE TITLE
jx install & grunt-cli

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#209]
Following command doesn't produce a working `grunt-cli`
```
jx install -g grunt-cli
```

however it should result as same as `npm install -g grunt-cli`

**Comment by ktrzeciaknubisa** [comment]
While working on `jx install` improvements let's keep in mind some suggestions from #135 to provide more natural support for other npm commands like `jx install -uninstall` which we have now.

**Comment by ktrzeciaknubisa** [comment]
For me the grunt was installing allright with `jx install`, only the printed output was somewhat shorter and it lacked "npm http" lines, like in the example below. 

The above commit takes care of this. We can also have it colorized, like npm does, but that probably requires using `spawn()` instead of `exec()`.

```bash
npm http GET https://registry.npmjs.org/grunt-cli
npm http 304 https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
```

**Comment by ktrzeciaknubisa** [comment]
Closer look into `jx install` and `npm install` differences shows up, that the first output mismatch reason is that our `~/.jx/npm` is using own version of `npmrc` config, thus some of our settings may override npm's settings.

I've implemented an approach to copy (prior the `jx install` call)  npm's effective config (it is a compilation of [npmrc Files](https://docs.npmjs.com/misc/config#npmrc-files) also with their default values and `npm config ls -l` command returns this) and it seems working well. It also respects user preferences (`~/.npmrc`), even if changed afterwards.

So my question is if we want to bundle this update into jxcore or you see any contraindications? @obastemur ? @plika ?

**Comment by ktrzeciaknubisa** [comment]
This 809833730064ce59fb8624aaf1f367c5de393e36 commit takes care of `jx install` printing output to be consistent with `npm install`. Tested on posix and windows.

**Comment by ktrzeciaknubisa** [comment]
@obastemur Is there anything else more to do here? I mean apart from printed output differences, which have been already taken care of?

**Comment by obastemur** [comment]
LGTM. Thanks
