### ISSUE TITLE
not generated jx execute file with --compress-internals option on mac osx 10.10

### ISSUE THREAD

**Issue by iwater** [jxcore/jxcore#210]
./configure --prefix=/jxcoreV8 --compress-internals
make
 ......
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/adler32.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/adler32.o ../deps/zlib/adler32.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/compress.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/compress.o ../deps/zlib/compress.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/crc32.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/crc32.o ../deps/zlib/crc32.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/deflate.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/deflate.o ../deps/zlib/deflate.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/gzio.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/gzio.o ../deps/zlib/gzio.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/infback.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/infback.o ../deps/zlib/infback.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inffast.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inffast.o ../deps/zlib/inffast.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inflate.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inflate.o ../deps/zlib/inflate.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inftrees.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inftrees.o ../deps/zlib/inftrees.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/trees.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/trees.o ../deps/zlib/trees.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/uncompr.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/uncompr.o ../deps/zlib/uncompr.c
  cc '-D_DARWIN_USE_64_BIT_INODE=1' -I../deps/zlib -I../deps/zlib/contrib/minizip  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /Users/iwater/Codes/jxcore/out/Release/.deps//Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/zutil.o.d.raw  -c -o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/zutil.o ../deps/zlib/zutil.c
  rm -f /Users/iwater/Codes/jxcore/out/Release/libchrome_zlib.a && ./gyp-mac-tool filter-libtool libtool  -static -o /Users/iwater/Codes/jxcore/out/Release/libchrome_zlib.a /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/contrib/minizip/ioapi.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/contrib/minizip/unzip.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/contrib/minizip/zip.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/adler32.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/compress.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/crc32.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/deflate.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/gzio.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/infback.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inffast.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inflate.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/inftrees.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/trees.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/uncompr.o /Users/iwater/Codes/jxcore/out/Release/obj.target/zlib/deps/zlib/zutil.o
  LD_LIBRARY_PATH=/Users/iwater/Codes/jxcore/out/Release/lib.host:/Users/iwater/Codes/jxcore/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /Users/iwater/Codes/jxcore/out/Release/obj/gen; jx tools/minify.js "/Users/iwater/Codes/jxcore/out/Release/obj/gen/jx_natives.h" lib/jx/_jx_subs.js lib/jx/_jx_memStore.js lib/jx/_jx_tasks.js lib/jx/_jx_utils.js lib/jx/_jx_multiplier.js lib/jx/_jx_monitor.js lib/jx/_jx_monitorHelper.js lib/jx/_jx_loadEmbedded.js lib/jx/_jx_http_helper.js lib/jx/_jx_config.js lib/jx/_jx_incoming.js lib/jx/_jx_parsers.js lib/jx/_jx_timers.js lib/jx/_jx_source.js lib/jx/_jx_marker.js lib/external/sqlite3.js src/node.js lib/_debugger.js lib/_linklist.js lib/assert.js lib/buffer.js lib/child_process.js lib/console.js lib/constants.js lib/crypto.js lib/cluster.js lib/dgram.js lib/dns.js lib/domain.js lib/events.js lib/freelist.js lib/fs.js lib/http.js lib/https.js lib/module.js lib/net.js lib/os.js lib/path.js lib/punycode.js lib/querystring.js lib/readline.js lib/repl.js lib/stream.js lib/_stream_readable.js lib/_stream_writable.js lib/_stream_duplex.js lib/_stream_transform.js lib/_stream_passthrough.js lib/string_decoder.js lib/sys.js lib/timers.js lib/tls.js lib/tty.js lib/url.js lib/util.js lib/vm.js lib/zlib.js ./config.gypi
/bin/sh: jx: command not found
make[1]: *** [/Users/iwater/Codes/jxcore/out/Release/obj/gen/jx_natives.h] Error 127
make: *** [jx] Error 2

**Comment by iwater** [comment]
works if without --compress-internals option, which wrote on doc/HOW_TO_COMPILE.md

**Comment by obastemur** [comment]
This option requires a 'jx' binary is available. You should;
- first compile without that option.
- make sure the resulting 'jx' binary is accessible from the build path (i.e.you may put it into /usr/local/bin) 
- now you can compile with the compress-internals option

Hope the steps are clear.

**Comment by iwater** [comment]
clear, sorry for that
