### ISSUE TITLE
Sending unicode characters through process.sendToThread in spidermonkey not working

### ISSUE THREAD

**Issue by dschaadt** [jxcore/jxcore#212]
Hi,
I am trying to send a JSON object containing unicode characters such as ä or 我. The following code only works with V8 but not with spidermonkey:

```js
jxcore.tasks.setThreadCount(2);
jxcore.tasks.runOnThread(1, function() { 
	jxcore.tasks.on('message', function (threadId, message) {
		console.log('received: ' + message.text);
	});
});
setTimeout(function() {
	var message = { text: '我' };
	process.sendToThread(1, message);
}, 1000);
```

In spidermonkey, nothing arrives (only ascii characters).
It would be great if you could fix this issue since the code should work with text in any language and there escaping characters is not really an option.
Thank you!

**Comment by ktrzeciaknubisa** [comment]
Yes, we have encountered this issue recently. Should be fixed soon. It applies not only to message methods like `sendToThread`, `sendToMain`, but also `addTask` itself (and friends) if you will pass unicoded params, like: 

```js
jxcore.tasks.addTask(function(str) {}, "норм чё”);
```

**Comment by obastemur** [comment]
Thanks for details. https://github.com/jxcore/jxcore/commit/814b4f57bed3f3a26a7e0a9cf9668cd343516d45 fixes it.

**Comment by ktrzeciaknubisa** [comment]
Well, we'll almost there. Unicode looks fixed, however there is still something about string made from buffer, when some of the buffer characters are not initialized, for example:

```js
var buf = new Buffer(20);
buf.write("some string", 0);  // less than 20
var str = buf.toString();
```
Now `process.sendToThreads(str)` will not pass an exact string to `jxcore.tasks.on('message')`.

We have a test case for this: 

```bash
./jx test/run.js -file test/jxcore/test-mt-sendToThreads-buffer.js
```

which runs the test with `mt-keep`.

**Comment by obastemur** [comment]
@ktrzeciaknubisa that test case is wrong. Buffer `write` is not going to add `\0` null ending at the end of the `some string` data. As a result remaining bytes from `20 bytes` can be anything and we can't be sure what we are sending to the threads. if you call `buf.fill(32);` before `buf.write` it should work fine.

**Comment by ktrzeciaknubisa** [comment]
I understand, but I'm not convinced :) I feel, that at the moment, when I call `var str = buf.toString()` and from now on I operate only on the `str` string (**I don't use buffer any more**) - the string should stay intact no matter into which method I pass it). 

So let's forget about buffer for a while and do a test like this:

```js
// below string is a result of var str = buf.toString();
str = 'some string\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000';
process.sendToThreads(str);
```
Then it passes. 

Those are my doubts :)
