### ISSUE TITLE
Promise is undefined in SpiderMonkey build

### ISSUE THREAD

**Issue by iwater** [jxcore/jxcore#214]
$ node
> typeof Promise
'function'

$ jx
> typeof Promise
'undefined'

Promise defaule on firefox version 29

any mistake here? build with ./configure --prefix=/jxcoreSM --engine-mozilla

**Comment by ktrzeciaknubisa** [comment]
I've just checked the following code against SM build and it looks fine on OSX:

```js
var Promise = require('promise');
console.log(typeof Promise);
// function
```
Is that what you're trying? Which is your platform?

However SpiderMonkey build in a way is expected not to go along with native modules. Here is discussion on that matter: #206 .

**Comment by obastemur** [comment]
**ES6 promises** are not supported with the any version of SpiderMonkey yet. Firefox gives that ability as an extra. As far as I know (Till Schneidereit from SM answered it) SpiderMonkey will have **ES6 job queue** implemented first and then promises.
