### ISSUE TITLE
release binaries for Android at http://jxcore.com/downloads/

### ISSUE THREAD

**Issue by Mithgol** [jxcore/jxcore#215]
Android support (#103) seems to require some compilation ([`Android_Compile.md`](https://github.com/jxcore/jxcore/blob/814b4f57bed3f3a26a7e0a9cf9668cd343516d45/doc/Android_Compile.md)).

Would you eventually release Android binaries of JXcore at http://jxcore.com/downloads/ like you released the binaries for the oher systems?

**Comment by obastemur** [comment]
Indeed. For both iOS, and Android like all the others. The package sizes will be a problem though.

**Comment by ktrzeciaknubisa** [comment]
The standalone binaries for android are already available at http://jxcore.com/downloads/.
