### ISSUE TITLE
Windows SpiderMonkey build

### ISSUE THREAD

**Issue by martinies** [jxcore/jxcore#216]
vcbuild.bat compiles for V8 target successfully but fails for spidermonkey. Perhaps it's a known issue since it fails on several machines.

**Comment by ktrzeciaknubisa** [comment]
Yes, looks like it **is** a known issue still present as no 1 at [known_issues.md](https://github.com/jxcore/jxcore/blob/master/known_issues.md#1) :)

**Comment by martinies** [comment]
Can we update this item's priority ? Can I make an assumption that JX package compiled script will available everywhere with spider-monkey builds ?

**Comment by obastemur** [comment]
I have to add couple of stuff  more into native interface to open a better way for mobile applications. Right after that, Windows SM build is in my list.

For your second question. I'm not sure. That would make the desktop side packages inconsistent. You can create a new Github issue with this discussion and see.

**Comment by obastemur** [comment]
This has been implemented recently and SM build works on Windows too.
