### ISSUE TITLE
Packaging availability on mobile targets

### ISSUE THREAD

**Issue by martinies** [jxcore/jxcore#219]
From the source codes, seems the packaging is also supported for mobile targets. Can you confirm it?

We are planning to have some mid-critical information inside the JavaScript source codes. jxcore's packaging is must to have (especially on Android).

**Comment by obastemur** [comment]
Yes. This is one of the reasons why we implemented packaging at the first place. Packaging for mobile targets will also have the compiled SpiderMonkey bit code instead of the source codes.

**Comment by martinies** [comment]
Looking forward to use it.
