### ISSUE TITLE
Can jxcore build static library e.g. .a or .jar?

### ISSUE THREAD

**Issue by katopz** [jxcore/jxcore#223]
for use later with native code via iOS and Android.

**Comment by jsbee** [comment]
Check the docs. It's all given; 
[Compiling](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md)
[Embedding] (https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_Basics.md)

**Comment by katopz** [comment]
@jsbee awesome!!! next question would be... 
Is that possible to build https://github.com/evantahler/actionhero as native lib?

**Comment by obastemur** [comment]
@katopz what do you mean as native lib? seems like it works for node 0.10+ so It should work with JXcore without a problem.

**Comment by katopz** [comment]
@obastemur I mean native static lib e.g. actionhero.a and antionhero.jar for iOS and Android client,
it also use vary of protocol http://www.actionherojs.com/docs/#actionhero-sections

![](http://www.actionherojs.com/img/connection_flow.png)

and plenty of required modules so i'm not sure it will just work.

**Comment by jsbee** [comment]
I believe it's doable but AFAIK there is no command line interface to make it easy for you. You should follow the instructions and compile jxcore as a static library. Use the native api for loading actionhere or anything else.

**Comment by katopz** [comment]
cool i'll try, many thanks!
