### ISSUE TITLE
Cannot compile c++ sample for Android

### ISSUE THREAD

**Issue by srichal** [jxcore/jxcore#224]
I am trying to compile the sample C++ file that was provided in the Embedding_Basics.md.

I first compiled JXCore for Android using the steps in https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md. I executed the below commands from directory /home/srikanth/Android/JXCore/jxcore which has the JXCore code from git hub.

1) build_scripts/android-configure.sh /home/srikanth/Android/android-ndk-r10d 
2) build_scripts/android_compile.sh /home/srikanth/Android/android-ndk-r10d 
      Got “out_android/android” folder with bin, include & share folders
      "bin" has all the .a files
      "include/node" has the .h files

I then tried to execute the provided sample C++ code using the steps in https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_Basics.md.

I executed the below commands from the same /home/srikanth/Android/JXCore/jxcore directory as before.

1) ./configure --static-library –prefix=/home/srikanth/Android/JXCore/jxcore/out_android/android 
2) make install 
3) g++ /home/srikanth/Android/JXCore/Test_Code/sample.cpp -stdlib=libstdc++ -lstdc++ -m32 -std=c++11 -O3 -I/home/srikanth/Android/JXCore/jxcore/out_android/android/include/node/public /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libcares.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libjx.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libsqlite3.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libchrome_zlib.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libuv.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libhttp_parser.a /home/srikanth/Android/JXCore/jxcore/out_android/android/bin/libopenssl.a -Wl -o sample

I got these two errors:
      g++: error: unrecognized command line option ‘-stdlib=libstdc++’ 
      g++: error: unrecognized command line option ‘-Wl’

**Comment by obastemur** [comment]
I don't know which OS you were working on so I've updated the documentation for both OSX and Linux separately. Please try again with the updated scripts and sample.

**Comment by srichal** [comment]
Thanks for the updated scripts. BTW, I am working on Linux (Ubuntu) which is running on a VM on my Windows 8.1 PC (x64).

I executed all the below steps from the root "jxcore" (/home/srikanth/Android/JXCore_March_8th/jxcore) directory.

	1) build_scripts/android-configure.sh /home/srikanth/Android/android-ndk-r10d
	2) build_scripts/android_compile.sh /home/srikanth/Android/android-ndk-r10d
	3) ./configure --static-library --prefix=/home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android (for V8)

	4) g++ /home/srikanth/Android/Test_Code/sample.cpp -lstdc++ -std=c++11 -pthread -O3 -Wno-write-strings -I/home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/include/node/public -fno-rtti /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libjx_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libsqlite3_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libchrome_zlib_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libv8_base_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libv8_nosnapshot_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libuv_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libhttp_parser_x64.a /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libopenssl_x64.a -ldl /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libcares_x64.a -o sample

This time the build actually started. But I encountered a lot of errors which say that "__assert2", "__errno" and "__sF" are undefined. The builds stops after a couple of seconds. Here is the last part of the build log.

/home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/libcares_x64.a(ares_destroy.o): In function `ares_destroy':
/home/srikanth/Android/JXCore_March_8th/jxcore/out/../deps/cares/src/ares_destroy.c:65: undefined reference to `__assert2'
/home/srikanth/Android/JXCore_March_8th/jxcore/out/../deps/cares/src/ares_destroy.c:69: undefined reference to `__assert2'
/home/srikanth/Android/JXCore_March_8th/jxcore/out/../deps/cares/src/ares_destroy.c:62: undefined reference to `__assert2'
collect2: error: ld returned 1 exit status

**Comment by obastemur** [comment]
If you are compiling for android target; you should use the compile tools from android toolkit. What you are doing is pretty complicated to simplify into a line of script. Why don't you do it by Android NDK project under eclipse ?

Android.mk file
```
LOCAL_PATH := $(call my-dir)
JXCORE_OUT_ANDROID := /home/srikanth/Android/JXCore_March_8th/jxcore/out_android/android/bin/

include $(CLEAR_VARS)
LOCAL_MODULE := cares
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)/libcares_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)/libcares_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := chrome_zlib
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libchrome_zlib_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libchrome_zlib_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := http_parser
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libhttp_parser_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libhttp_parser_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := openssl
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libopenssl_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libopenssl_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := sqlite3
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libsqlite3_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libsqlite3_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libuv
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libuv_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libuv_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libv8
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libv8_base_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libv8_base_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libv8no
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libv8_nosnapshot_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libv8_nosnapshot_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := jxcore_native
ifeq ($(TARGET_ARCH),x86)
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libjx_ia32.a
else
LOCAL_SRC_FILES := $(JXCORE_OUT_ANDROID)libjx_arm.a
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
NDK_TOOLCHAIN_VERSION := 4.8
LOCAL_CFLAGS := -std=gnu++11
APP_STL := gnustl_static
LOCAL_MODULE    := jxcore
LOCAL_C_INCLUDES := $(JXCORE_OUT_ANDROID)
LOCAL_SRC_FILES := source_file1.cpp source_file2.cpp
LOCAL_LDLIBS := -llog \
                -lz \
                -ldl \
                -landroid
LOCAL_STATIC_LIBRARIES := cares openssl
LOCAL_WHOLE_STATIC_LIBRARIES := chrome_zlib http_parser sqlite3 libuv libv8 libv8no jxcore_native
include $(BUILD_SHARED_LIBRARY)
```

Application.mk file;
```
APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -std=gnu++11
APP_ABI := armeabi armeabi-v7a x86
APP_PLATFORM := android-10
```

If you want to use x64 ABI, you should make sure the NDK version is at least 21.

**Comment by srichal** [comment]
I am using the Android app sample you provided separately. I am now able to generate the “libjxcore.so” file. But I am not able to build the sample app yet due to missing libraries like “gson-2.2.4-javadoc.jar”.

**Comment by obastemur** [comment]
It's a very common library available on the web. However, it's an unnecessary dependency. Assuming you are on eclipse, right click to project -> properties -> java build path -> Libraries and remove it.

**Comment by martinies** [comment]
@srichal Android sample ? Where did you find that ? @obastemur  ?

**Comment by obastemur** [comment]
@martinies  The sample @srichal mentioning is something internal and has no use case for anyone else. I will make it available on Github very soon.

**Comment by martinies** [comment]
@obastemur I see. Any timeline for the sample?

**Comment by obastemur** [comment]
Android 'hello world' sample is now available under https://github.com/obastemur/jxcore-android-basics with the instructions.
