### ISSUE TITLE
v8 native interface: assertion failed

### ISSUE THREAD

**Issue by yumwang** [jxcore/jxcore#226]
I'm playing with the native interface on OSX 10.9. (v8 x64 static library build)

When I run the logic under main function on a separate pthread, I receive;

**Assertion failed: (iso->node_isolate != NULL && "This shouldn't be null, beware using a thread Id before destroying " "the previous one"), function setCommons, file ../src/jx/commons.cc, line 132.**

**Comment by obastemur** [comment]
good catch. fixed https://github.com/jxcore/jxcore/commit/64aa41a02408add4a8e315f78d03e0d1ebdc8ce7 thanks!
