### ISSUE TITLE
jx.h vs node.h

### ISSUE THREAD

**Issue by yumwang** [jxcore/jxcore#227]
I do understand the well reasoning behind a dependency free interface. Do you have a plan to make this interface also available for addons ? or it will be embedding only interface? I'm trying to develop a native node addon and it's very complicated in details. You are expected to be a V8, and libuv expert in addition to node's api.

**Comment by obastemur** [comment]
That is not the intention with the new interface. We want to keep our node.js native addon interface compatibility intact. 

The new public API over 'jx.h' intends to make things easier when embedding jxcore/node etc. 

JXcore has a very easy to use multi engine interface for addons. Please take a look at any of the modules under `wrappers` folder. Besides, `sqlite` (under the 'src/external' and 'lib/external' folders) is an actual node addon (node-sqlite3) rewritten using the macro support. That can be a good starting point.

**Comment by yumwang** [comment]
jxcore 2.3.7 from the website has native bson addon embedded but I couldn't find that in the latest source codes.You are not going to embed this addon anymore? Is it possible to add bson in addition to sqlite3 ?

**Comment by ktrzeciaknubisa** [comment]
We had started a discussion #206 on which modules to include into JXcore. Probably this will end up in introducing compile-time option for choosing modules to be embdedded.
