### ISSUE TITLE
SM: scope difference 

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#231]
So there is this test coming from node's originals, which passes for V8 and fails for SM:

```bash
$ ./jx test/simple/test-cluster-send-deadlock.js
ReferenceError: onclose is not defined
```

The reason is trivial: the `onclose` method is defined after it is first used:
```js
client1.on('close', onclose);
client2.on('close', onclose);
function onclose() {
   // ...
}
```

When I switch the order, obviously it works:
```js
function onclose() {
   // ...
}
client1.on('close', onclose);
client2.on('close', onclose);
```

But I'm not sure it it wasn't intentional and why it works for V8. Furthermore, I tried to run the same logic, but without clusters, and it works for SM as well:

```js
var assert = require('assert');
var net = require('net');

var server = net.createServer(function(socket) {});

server.listen(2001, function() {
  var client1 = net.connect({ host: 'localhost', port: 2001 });
  var client2 = net.connect({ host: 'localhost', port: 2001 });
  client1.on('close', onclose);
  client2.on('close', onclose);
  function onclose() {
    console.log("onclose");
  }
  setTimeout(function() {
    client1.end();
    client2.end();
    server.close();
  }, 50);
});
```

**Comment by obastemur** [comment]
@ktrzeciaknubisa I'm aware of that difference in general. Perhaps the issue is somewhere inside SM compileAndGo stuff. I'm taking care of this.

**Comment by obastemur** [comment]
I have a basic test case reproducing this issue. It also fails for Firefox. I've reported this problem to SpiderMonkey team. You may update the test case since it's purpose is testing something else.

```
var q = 1;

if (q) {
  var client1 = {on:function(){}};
  client1.on('close', onclose);
  function onclose() {
    console.log('dummy2');
}
```
}

**Comment by obastemur** [comment]
Seems this issue is a no go. The broken case is not an Ecma spec. accepted definition and SM can not go for it by design.

**Comment by ktrzeciaknubisa** [comment]
No problem, the test is updated anyway to avoid the problem.
