### ISSUE TITLE
SpiderMonkey JIT is ready for Android. Any argument?

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#232]
SpiderMonkey JIT is going to replace V8 on Android. I was keeping the compile script etc. for it to make sure it's okay. At the moment, my initial tests showed it's ready. Any argument on this? 

SM Pros:
- ES6
- Same experience on all the mobile platforms
- Compiled JavaScript for mobile applications. (bytecode)

V8 Pros:
- Mature and more stable

Performance wise, there are scenarios SM is the winner, same applies to V8. Even if one of them is winner, max difference I saw was 20%.

**Comment by Ben007** [comment]
How about keeping this optional ? maybe a compile time argument to choose v8 or sm?

**Comment by martinies** [comment]
I don't see any reason to keep v8 in the options. Multi platform consistency is the key-point here. 
+1 for SM only. It's not a rocket science to customize that back to v8 (for any reason)

**Comment by obastemur** [comment]
Android build script is updated to SM JIT https://github.com/jxcore/jxcore/commit/5edb46908290c109318c4a43337692498e3ac9da 

I do agree with @martinies . If you really need to do it with V8 engine, perhaps it should not be tricky after all.
 
Thanks!

**Comment by ktrzeciaknubisa** [comment]
@obastemur + @martinies There would be still lots of developers out there who would want (for any reason) to have v8 on android and maybe not all of them would be able to bring it back. I think, that If we have it now, and it is not "calling for food" - can be kept in place as well?

**Comment by obastemur** [comment]
it's already there https://github.com/jxcore/jxcore/blob/master/build_scripts/android_compile_v8.sh

**Comment by yaronyg** [comment]
I think there is actually a really important question hiding here. But it's hard to see.

Question #1 - Should JXCore default to v8 or SM on Android?
   This question doesn't bother me much one way or the other.

Question #2 - Should JXCore support more than one engine?
   This is the question that I think is important. JXCore's message is 'we support pluggable engines'. For that message to be real it must be falling off a log easy to support multiple engines. Such support however has two parts. The first part are things like android_compile_v8.sh. I'm super happy to see it! It's awesome! But it's not mentioned, for example, in https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md. That makes it a hidden feature, not a primary feature. I think we need https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md to be edited to make it absolutely clear that you can use SM, you can use V8. They are both supported.
   But every bit as important is also having a testing framework that is constantly exercising all supported plugins for all releases! I can't stress how critical this is if the message about multi-engine support is to be taken seriously. This means that every Android test is run twice, once on V8 and once on SM.

**Comment by obastemur** [comment]
`This is the question that I think is important. JXCore's message is 'we support pluggable engines'.`
@yaronyg This makes sense. Thanks for this helpful contribution. I will update the documents.
