### ISSUE TITLE
Please give us a switch to build v8 on Android

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#234]
I just did a fetch and tried to build on Android and I got a failure. But more importantly this is how I found out that android_compile.sh now only seems to build Spidermonkey. But for now I'm testing using v8. So I'd really like a switch to the script to specify if I want Spidermonkey or V8.

For now I've worked around by reverting the changes just to the android_compile.sh file and that seems to be working.

**Comment by obastemur** [comment]
I'd opened a discussion on this -> https://github.com/jxcore/jxcore/issues/232 , please check that. Indeed, It's not a big deal to have v8 option but is there any particular reason for keeping v8 option on mobile ?

**Comment by ktrzeciaknubisa** [comment]
I don't know about @yaronyg , however I think there will be always needs for one-user solutions. I've heard of many cases when someone wanted to build an app for himself which would control e.g. heating system at his home or opening fence/garage gate by pressing a button in mobile app while sitting in a car. V8 might be more of use here considering at least native modules support, to begin with.

**Comment by obastemur** [comment]
I don't think today's `node native module` design is something suitable for the future. Once we are done with stabilization, I think we have lots of tools to improve that area too. v8 build script is available under builds_scripts folder.
