### ISSUE TITLE
How to handle a.b and a.b.gz conflict in Android?

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#235]
There is a limitation in Android packaging that if you have two files in the same directory, one called a.b and the other called a.b.gz then they will be seen as duplicates and cause a packaging failure. I'm running into this now with semver.min.js.gz and semver.browser.js.gz. They will exist in directories as two versions, semver.min.js/semver.browser.js and semver.min.js.gz/semver.browser.js.gz. Thus triggering a packaging failure.

But this conflict isn't a flaw in node.js. It's a flaw in Android. And if we are going to have portable Cordova plugins then we need Android not to freak out about it. I tried to work around it (e.g. using -u) but finally I just had to delete the *.gz files (and hope that doesn't break anything since I have run into other issues).

**Comment by obastemur** [comment]
Issue must be somewhere in the sample project (https://github.com/obastemur/jxcore-android-basics) not the core. Let me check what's happening there.

**Comment by yaronyg** [comment]
The issue is related to #236. Because of how JXCore decides to package Node.js files it runs into issues that Android has with assets. If JXCore decides to resolve #236 by using the warning then this issue won't apply since there won't be any gz files allowed. But if JXCore decides to fix #236 then this issue will come back. I already ran into it during normal node.js development.
