### ISSUE TITLE
addTask and require don't seem to like each other on Android using v8

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#237]
I tried a test where I added the following to app.js:

```node
jxcore.tasks.addTask(function() {
  require("./perfTest.js");
});
```
It failed with:

```console
03-15 16:39:41.326  30448-30466/com.nubisa.jxcore E/jxcore-log﹕ restarting thread 0 due to error Error: Cannot find module './perfTest.js'
03-15 16:39:42.097  30448-30468/com.nubisa.jxcore W/jxcore-log﹕ (JX_Evaluate) Did you start the JXEngine instance for this thread?
```

I tried a variant with require("perfTest.js") and that failed as well.

perfTest.js, btw, is just a .js file sitting in the same directory as app.js.

Also note that if I remove addTask and call require("./perfTest.js") then everything works fine.

**Comment by obastemur** [comment]
This is not a bug. I've checked the sample and seems the `fs` extension is only defined for the main instance. So, the other instances has no access to any of the javascript files.

**Comment by yaronyg** [comment]
So if I want to use addTask I can't use any NPM modules or any secondary .js files? That seems pretty buggy to me. But I suppose it's all in the eye of the beholder. But in any case I'll avoid addTask.

**Comment by obastemur** [comment]
No, you can surely use node modules from NPM (under a task). The problem is that the sample doesn't have it implemented. I'm gonna make this available on the sample and update this issue.

Thanks

**Comment by yaronyg** [comment]
AAAAHHHHHH!!!!!!! I apologize. I didn't understand the distinction you were drawing. Just to be clear:

addTask - Supports NPM
The sample I'm using - Doesn't support NPM for addTask

So the bug isn't in JXCore, it's in the sample. Gotcha! Sorry I didn't get that distinction from your first response.

**Comment by ktrzeciaknubisa** [comment]
@obastemur I'm not sure about this, this looks like a bug after all. I've tried and `fs` is accessible under the task on android. From what I saw, the reason is, that `require('./something.js')` inside a task constructs search paths starting from */system/bin* (this is the value for both `process.cwd()` and `__dirname`), while in a main this is proper.

**Comment by obastemur** [comment]
There is no fix for it. `process.natives` is not defined for JS powered sub instances. Besides, if you check main.js, you will see a logic registers an extension to 'fs' which is not enabled for sub instances either. 

This is not a bug.

**Comment by obastemur** [comment]
All the required features for this item are currently implemented into the core. 

 - Automatically register proxy methods into sub JS instances
 - Register a multi-tasking behavior for any possible future instance

I'll be updating the sample project accordingly.
