### ISSUE TITLE
Android doesn't like express-pouchdb

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#238]
I tried an experiment where I did a npm install express-pouchdb. This installed it into node_modules. I didn't call the code at all. I just installed it and ran some other code that otherwise runs fine. Before anything I can run I get the error:

```console
03-15 16:50:53.632  31975-31975/com.nubisa.jxcore E/SELinux﹕ Function: selinux_android_load_priority [0], There is no sepolicy file
03-15 16:50:53.642  31975-31975/com.nubisa.jxcore E/SELinux﹕ Function: selinux_android_load_priority , loading version is VE=SEPF_SAMSUNG-SGH-I337_4.3_0024
03-15 16:50:53.642  31975-31975/com.nubisa.jxcore E/SELinux﹕ selinux_android_seapp_context_reload: seapp_contexts file is loaded from /data/security/spota/seapp_contexts
03-15 16:50:53.642  31975-31975/com.nubisa.jxcore D/dalvikvm﹕ Late-enabling CheckJNI
03-15 16:50:53.732  31975-31975/com.nubisa.jxcore D/dalvikvm﹕ Trying to load lib /data/app-lib/com.nubisa.jxcore-1/libjxcore.so 0x42a10630
03-15 16:50:53.742  31975-31975/com.nubisa.jxcore D/dalvikvm﹕ Added shared lib /data/app-lib/com.nubisa.jxcore-1/libjxcore.so 0x42a10630
03-15 16:50:53.742  31975-31975/com.nubisa.jxcore D/jxcore_app_log﹕ JniHelper::setJavaVM(0x418ba168), pthread_self() = 1074851836
```

This is on a Samsung S5 running 4.3.

For chuckles I tried this also on a Nexus 7 running 4.4.4 and got:

```console
03-15 16:53:56.293    2371-2371/com.nubisa.jxcore D/dalvikvm﹕ Late-enabling CheckJNI
03-15 16:53:56.384    2371-2371/com.nubisa.jxcore D/dalvikvm﹕ Trying to load lib /data/app-lib/com.nubisa.jxcore-1/libjxcore.so 0x41e3e860
03-15 16:53:56.394    2371-2371/com.nubisa.jxcore D/dalvikvm﹕ Added shared lib /data/app-lib/com.nubisa.jxcore-1/libjxcore.so 0x41e3e860
03-15 16:53:56.394    2371-2371/com.nubisa.jxcore D/jxcore_app_log﹕ JniHelper::setJavaVM(0x414a5f00), pthread_self() = 1074008404
03-15 16:54:44.821    2371-2371/com.nubisa.jxcore D/dalvikvm﹕ GC_FOR_ALLOC freed 431K, 5% free 9061K/9524K, paused 17ms, total 17ms
```

In both cases I ended up with the JXCore app running with a black screen and being unresponsive.

**Comment by yaronyg** [comment]
Aha! I had a suspicion so I left both the Samsung and the Nexus running. The Samsung is still hung but the Nexus eventually came around and is now working. Somehow putting a large number of files causes unbelievably system slow down. I checked it took 14 minutes to become responsive and this single sub-directory only had 23.3 mbs. For full pouchdb the total size would be in the 100s of megabytes. Help!

**Comment by obastemur** [comment]
@yaronyg the sample app uses `assets.list` to grab the list of files under the apk/assets. This builtin Android SDK method is famous with its terrible performance and unfortunately not much alternative around. 

However, this is something fixable, and I took this item on my list.

**Comment by obastemur** [comment]
This one is fixed on the Android sample.
