### ISSUE TITLE
JXcore dead locks when expiring items out of the memory store

### ISSUE THREAD

**Issue by xtelinco** [jxcore/jxcore#240]
I have been having problems with jxcore deadlocking and only being killable by a SIGKILL.

I think I have tracked down the issue to src/wrappers/jxtimers_wrap.cc, let me explain what I think is happening. In the checkKeys() method you initially lock the timers lock, so you can run the list of timers, when you find an entry to remove, you lock the store lock. However in the modifier functions in src/wrappers/memory_wrap.cc you do it the other way around. You initially lock the store lock, then to update the expiration time, you then lock the timers lock, through ExpirationKick. This creates a race condition, where one thread will gain one lock, and another thread will gain the other lock, but neither thread will be able to complete their process as they cannot gain both locks.

I am currently testing a patch that hopefully will fix the issue. I haven’t checked the code to see if this race condition happens in other places, it possibly could. Here’s my patch

```
diff --git a/src/wrappers/jxtimers_wrap.cc b/src/wrappers/jxtimers_wrap.cc
index bf2b3ad..4b645c5 100644
--- a/src/wrappers/jxtimers_wrap.cc
+++ b/src/wrappers/jxtimers_wrap.cc
@@ -21,6 +21,8 @@ namespace node {
 static bool watcher_alive_ = false;
 
 void JXTimersWrap::checkKeys() {
+  std::queue<std::string> todelete;
+
   if (XSpace::Timers() == NULL) return;
 
   XSpace::LOCKTIMERS();
@@ -36,9 +38,7 @@ void JXTimersWrap::checkKeys() {
       if (node::commons::process_status_ != JXCORE_INSTANCE_ALIVE) break;
 
       if (timer.start + timer.slice < total) {
-        XSpace::LOCKSTORE();
-        XSpace::Store()->erase(it->first);
-        XSpace::UNLOCKSTORE();
+        todelete.push(it->first);
         timers->erase(it->first);
         counter = 1;
         break;
@@ -52,6 +52,14 @@ void JXTimersWrap::checkKeys() {
     }
   }
   XSpace::UNLOCKTIMERS();
+  if(!todelete.empty()) {
+    XSpace::LOCKSTORE();
+    while(!todelete.empty()) {
+      XSpace::Store()->erase(todelete.front());
+      todelete.pop();
+    }
+    XSpace::UNLOCKSTORE();
+  }
 }
 
 void JXTimersWrap::Watcher(void *w) {
```

**Comment by obastemur** [comment]
I see the problem here is that `endit` is no longer an end to the map. I know this problem with `btree` but this one looks like passed through me. Seems you have a solution to the problem. Feel free to commit your fix (pull request)  

Thanks!

**Comment by xtelinco** [comment]
I have a system that quite heavily tests this bit of functionality. It has been running for the last 12 hours without issue, however the deadlock doesn't happen that often. Once I am happy that it is stable and fixed, I will push my change, if you are happy.

Cheers.

**Comment by obastemur** [comment]
@xtelinco sounds good!
