### ISSUE TITLE
SM: array range check and type compatibility with V8

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#241]
One of pummel tests fails for SM, while works for V8.

```bash
$ ./jx test/pummel/test-buffer-big.js 
```

It expects a `RangeError` exception when creating an array of exceeded size:

```js
assert.throws(function() { new Int8Array(0x3fffffff + 1) }, RangeError);
assert.throws(function() { new ArrayBuffer(0x3fffffff + 1) }, RangeError);
assert.throws(function() { new Float64Array(0x7ffffff + 1) }, RangeError);
```

Below is an expected error message for V8:
> RangeError: length > kMaxLength

I believe that `kMaxLength` is defined in *src/wrappers/node_buffer.h*:
```c
static const unsigned int kMaxLength = 0x3fffffff;
```
***
Now, for SM it seems like it's **double** capacity. Below lines are not rising an exception, and the values used here apparently are maximum allowed sizes for SM (and they are **double** than for V8):
```js
new Int8Array(0x3fffffff * 2);
new Float64Array(0x7ffffff * 2);
new ArrayBuffer(0x3fffffff * 2 + 1);  // not just double: also +1
```

Then finally some errors occur:
```js
// raises: [InternalError: size and count too large],
// but not RangeError:
new Int8Array(0x3fffffff * 2 + 1);
new Float64Array(0x7ffffff * 2 + 1);

// Yep! Only this one raises RangeError!
new ArrayBuffer(0x3fffffff * 2 + 2);
```

**Comment by obastemur** [comment]
I don't think this is something we should look for a v8 compatibility. On this case V8 is behind of SpiderMonkey. Besides, SpiderMonkey doesn't have 32 bit memory limitation.

**Comment by ktrzeciaknubisa** [comment]
Fair enough. I updated the test, so it will not fail for SM.

**Comment by ktrzeciaknubisa** [comment]
Since this is explained it looses its status of an issue.
