### ISSUE TITLE
Packaged Express Application Won't Function

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#245]
I'm coming up to speed with JXCore (very nice!) and have been kicking the tires. As an experiment I created a boilerplate express application as follows (Note... I'm using npm to install packges because jx install doesn't work through our http proxy):
```
sudo npm install -g express-generator@4
mkdir jxplay
cd jxplay
express .
npm install
jx package bin/www expdemo
jx expdemo.jx
```
This results in:
```
buffer.js:157
      throw new TypeError('First argument needs to be a number, '
            ^
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:157:13)
    at _xo (module.js:767:12)
    at Module._compile (module.js:490:40)
    at readX (module.js:1233:5)
    at Object.Module._extensions..jx (module.js:1628:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:373:18)
    at node.js:2209:3
```
If I run like so:
```
jx bin/www
```
It works as expected as does `node bin/www`.

If I package the application as native with `jx compile expdemo.jxp -native` and launch it I get:
```
node.js:1929
          var ind = (buffer + "").indexOf('jxcore.bin(?@@!!$<$?!*)     if (ind
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
```
I'm running on Ubuntu 14.04LTS 64 bit. I `./configure`d and compiled commit `10c5c7f Merge pull request #243 from yaronyg/patch-1` of GitHub's master branch.

**Comment by ktrzeciaknubisa** [comment]
Well, I saw an exact output to one of yours (related to **-native**):

```
node.js:1933
          var ind = (buffer + "").indexOf('jxcore.bin(?@@!!$<$?!*)     if (ind
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
```

while running one of our tests (Ubuntu 13.10 x64):

```bash
$ ./jx test/jxcore/test-node_path_start.js native
```

But I haven't go down yet to track it.

This occurs for both SM and V8. I've compiled the latest commit in my case.

**Comment by ktrzeciaknubisa** [comment]
@DLLarson I've tested your sample and it seems like the first issue is related with "bin/www" path. Apparently lack of .js extension raises the TypeError, which you've quoted. Once I renamed "www" into "www.js" I never saw this error any more. 

However another issue occurred ("shebang" problem known from e.g. #166), which is still unresolved, but once i removed the first line from "www.js" it looks like expdemo.jx is finally running.

Still the `-native` problem exists as it is a separate thing.

**Comment by DLLarson** [comment]
I did find the shebang problem but it was the `bin/www` -> `www.js` that got things running for me. 

I see the file was segregated into the assets area of the jxp file. Perhaps that caused the problem.

Thanks for the assistance!

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/017bdf17fd76475cbec2b5cefed4387d6fd6beff commit adds a check that a developer can not use none '.js' entry file.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/f3fa8d0b41b803fe9b81b775aea6250634b56f5e fixes shebang problem for good. Thanks for the details
