### ISSUE TITLE
"jx install <pkg>" Doesn't Function Behind HTTP Proxy

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#246]
Our only access the internet is through a corporate http proxy that requires credentials. 

My proxy credentials are supplied by the `http_proxy` and `https_proxy` environment variables. It works without issue with other programs that respect those vars.

If I use `npm install express` the package is installed as expected.

When I use JXcore to do the install via `jx install express` it fails with the following output:
```
Preparing NPM for JXcore (v Beta-0.3.0.0) for the first run

node.js:838
            throw ee;
                  ^
Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)
```
My workaround is to use `npm` directly.

-Dale

**Comment by obastemur** [comment]
We should take care of this a.s.a.p.  option a) provide a command line parameter for proxy settings b) provide an alternative way to install it.

ping @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
The command line parameter support is almost ready. Will be posted soon. Once it's ready - I guess an alternative way will not be necessary any more?

**Comment by DLLarson** [comment]
I'm ready to try it out when your done.

**Comment by ktrzeciaknubisa** [comment]
I've just posted proxy implementation for `jx install` (e8019ce367082258ceb110437b06293b6e798a21)  . Should work for proxies set with or without user authentication. 

```bash
$ jx install express --https-proxy http://user1:pwd1@192.168.1.100:8081
```

Please let us know, if that works for you.

**Comment by DLLarson** [comment]
I tested both modes through our corporate firewall. It works! 

The use of option name `--https-proxy` suggests it's always using TLS. Is this true?

**Comment by ktrzeciaknubisa** [comment]
Thanks for the feedback. 

No, that does not imply using always SSL. I guess it depends on the package, from where the jx/npm is downloading. However `jx install` command gets the `npm` tool through HTTPS protocol prior to actual <pkg> download. 

BTW. did you encounter any npm package, which you needed to download before by using `npm install --proxy` instead of `npm install --https-proxy` ?

**Comment by DLLarson** [comment]
>BTW. did you encounter any npm package, which you needed to download before 
>by using npm install --proxy instead of npm install --https-proxy?

I never used either. I believe npm picked it up from my environment defined in my .bashrc:
```
export http_proxy="http://NAME:PWD@10.xx.xx.xx:8080
export https_proxy=$http_proxy
```
I really wasn't aware of the proxy options in npm.

It makes sense to mimic what npm does.

-Dale

**Comment by ktrzeciaknubisa** [comment]
Well I've made `jx install` patch sensitive only to command line parameters, while `npm` (as we can read [here](https://docs.npmjs.com/misc/config)) "gets its configuration values from 6 sources", and .bashrc is one of them.

This can be always improved if there's a need, though.

**Comment by obastemur** [comment]
Agree. This is for the first install only. Kris can we turn this into a small tutorial on blog?

**Comment by ktrzeciaknubisa** [comment]
Allright. It's here: [NPM package install through proxy with JXcore](http://jxcore.com/npm-package-install-through-proxy-with-jxcore).

Closing this issue until further improvement suggestions will pop up.
