### ISSUE TITLE
You need a 'jx' binary for the compress build.

### ISSUE THREAD

**Issue by war10ck-efz** [jxcore/jxcore#247]
A problem occurred when I compiled with ./configure --prefix=/jxcoreV8 --compress-internals.

error log:
You need a 'jx' binary for the compress build.
make[1]: *** [/xxx/jxcore/out/Release/obj/gen/jx_natives.h] Error 1
make[1]: Leaving directory `/xxx/jxcore/out'
make: *** [jx] Error 2

ps:
I have compiled the jxcore on ubuntu-64 with -prefix=/jxcoreV8. 
And there is a  binary jx under /usr/local/bin, also can use jx in console.

**Comment by obastemur** [comment]
could you please tell me what exactly you receive after `jx -jxv` ?

**Comment by obastemur** [comment]
I can confirm it works on ubuntu. steps;

```
sudo rm /usr/local/bin/jx
sudo ./configure --prefix=/jxcoreV8
sudo make install
sudo ln -s /jxcoreV8/bin/jx /usr/local/bin/jx
sudo ./configure --prefix=/jxcoreV8 --compress-internals
sudo make install
```

and you have it.

**Comment by war10ck-efz** [comment]
thx, it works.
