### ISSUE TITLE
Is it possible to 'retain' js functions or objects in a callback for later use?

### ISSUE THREAD

**Issue by treasurebox** [jxcore/jxcore#249]
I am looking into embedding possibilities. I understand that JXResult s are freed right away after a callback returns.
One workaround I can think of is to maintain a table of objects in JS-land that we want to use in the future. This might work, but a little cumbersome.
Is there a more straightforward way?
Thank You.

**Comment by obastemur** [comment]
The very next update on the native interface (I'm currently working on) will be turning a JXResult into persistent native object. For the other stuff please see the discussion https://github.com/jxcore/jxcore/issues/225

**Comment by treasurebox** [comment]
Great to hear, keep up the good work!

**Comment by obastemur** [comment]
JX_MakePersistent & JX_ClearPersistent along with the internal requirements are implemented. Sample usage & test case are also available from `test/native-interface/persistent-call`

Seems the original issue is no longer a case ? closing it for now. Thanks!

**Comment by treasurebox** [comment]
Thanks, I dig it!
