### ISSUE TITLE
Smallest application size?

### ISSUE THREAD

**Issue by katopz** [jxcore/jxcore#251]
After build i got
```shell
400K	libcares.a
304K	libchrome_zlib.a
 40K	libhttp_parser.a
 11M	libjx.a
324M	libmozjs.a
 12M	libopenssl.a
2.9M	libsqlite3.a
640K	libuv.a
```
Is this mean when i pack to ipa all this will also packed am i right?
So final ipa should be pretty huge? Or maybe i miss something here.

Please correct me.

**Comment by obastemur** [comment]
No. It adds aprox. 10-14 Mb

**Comment by ktrzeciaknubisa** [comment]
How about `libsqlite3.a` - is it critical or could be made optional? It's not that big, but still...

**Comment by obastemur** [comment]
It adds only some hundreds of KB to final product size. I bet if there is any other issue here ?. Closing for now.
