### ISSUE TITLE
V8: build fails on Windows

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#253]
I'm trying to compile V8 on Windows and received the following error:

>   Assembling C:\jxcore\jxcore\deps\openssl\openssl\crypto\bn\asm\x86_64-win32-masm.asm to Release\obj\openssl\x86_64-win32-masm.obj.
**MASM : fatal error A1000: cannot open file : C:\jxcore\jxcore\deps\openssl\openssl\crypto\bn\asm\x86_64-win32-masm.asm** [C:\jxcore\jxcore\deps\openssl\openssl.vcxproj]
C:\jxcore\jxcore\deps\openssl\openssl.targets(28,5): error MSB3721: The command "call ml64.exe "/Zi" "/Fo" "Release\obj\openssl\x86_64-win32-masm.obj" "/c" "C:\jxcore\jxcore\deps\
openssl\openssl\crypto\bn\asm\x86_64-win32-masm.asm"" exited with code 1. [C:\jxcore\jxcore\deps\openssl\openssl.vcxproj]

My platform is:
* Win 7 x 64
* VS 2013 Ultimate
* Python27

BTW. The compilation script continues and finishes (obviously without jx binaries generated), maybe it's best if it would stop?

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/7e4a8f7f3636061fedeef5b77c3c448e9bccdaea should fix this problem.

**Comment by ktrzeciaknubisa** [comment]
Reopening this one, since another error shows up (both Win x64 and x32):

```bash
src\win\core.c(404): error C2039: 'wq_mutex' : is not a member of 'uv_loop_s' [C:\jxcore\jxcore\deps\uv\libuv.vcxproj]
          C:\jxcore\jxcore\deps\uv\include\uv.h(1983) : see declaration of 'uv_loop_s'
src\win\core.c(404): error C2198: 'uv_mutex_lock' : too few arguments for call [C:\jxcore\jxcore\deps\uv\libuv.vcxproj]
src\win\core.c(405): error C2039: 'wq' : is not a member of 'uv_loop_s' [C:\jxcore\jxcore\deps\uv\libuv.vcxproj]
          C:\jxcore\jxcore\deps\uv\include\uv.h(1983) : see declaration of 'uv_loop_s'
          C:\jxcore\jxcore\deps\uv\include\uv.h(1983) : see declaration of 'uv_loop_s'
src\win\core.c(408): error C2039: 'wq_mutex' : is not a member of 'uv_loop_s' [C:\jxcore\jxcore\deps\uv\libuv.vcxproj]
          C:\jxcore\jxcore\deps\uv\include\uv.h(1983) : see declaration of 'uv_loop_s'
src\win\core.c(408): error C2198: 'uv_mutex_unlock' : too few arguments for call [C:\jxcore\jxcore\deps\uv\libuv.vcxproj]
```
