### ISSUE TITLE
Callback of addTask fired before whole work of the task is finished

### ISSUE THREAD

**Issue by Bowser** [jxcore/jxcore#255]
Here I am, again! (Sorry)
I've just run into another no through road.

**jxcore.tasks.addTask()** let you define a callback to be fired when the task finishes its work. Everything works great until you define an evented subTask, for example a FileSystem read, to be run inside your task. In this case the task returns before its sub finishes (this is the default behavior of closures, of course), but it also fire the callback on the main thread.
This happens **even** if I set process.keepAlive(), to specify that my Task hasn't finished its work.

Of course someone could to send another message from the subtask through **process.sendToMain**, but this way I loose the reference of the task in my main thread, making it to me difficult to answer to client requests than using the comfortable callback with obj context. This way I need to distinguish between different messages that arrive from subthreads and connect them to their original requests.

One idea could be to set up an optional return value as a parameter of process.release() to be returned as task result for the callback, obviously used only when process.keepAlive is set.

What do you think? Perhaps I forgot something?

**Comment by ktrzeciaknubisa** [comment]
Some sample code of your scenario would be useful. However if you run async methods inside a task, probably you need to implement [waitLogic](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-tasks.markdown#tasksaddtaskobject-param-callback-obj). But then - please note the below sentence from the linked docs:

> There is one important thing to be noted here: the `callback` is invoked only when there is no `waitLogic` defined or when it evaluates to false (see `waitLogic` description below).

**Comment by Bowser** [comment]
This is my scenario:

```javascript
function task(){
        // supposing fs already defined into this subThread

        var fileContent;

        //do some things

        fs.readFile('./test.txt',function(err,data){
                fileContent = data;

                // do some things on fileContent

                result = fileContent;

                //I need the callback in the main to be fired now!
                process.release();
        });

        //I'm not ready to end the task, I need to return fs value
        process.keepAlive();
}

function cb(obj, result){
        obj.res.end(r);
}

//http already defined
http.createServer(function(req,res){
        var obj = {'req':req,'res':res};
        jxcore.tasks.addTask(pippo, null, cb, obj);
}).listen(8000);
```

**Comment by ktrzeciaknubisa** [comment]
The `addTask()` callback can only receive an immediate value as a result of `return xxx` called inside a task and it is `undefined` in your case (there is no `return` statement). Anyway this would not be useful, since `readFile()` is async.

How about using `mt-keep` instead of a task?

```js
var http = require("http");
var fs = require("fs");

http.createServer(function(req,res){

  fs.readFile('./test.txt',function(err,data){
    fileContent = data;
    res.end(data);
  });

}).listen(8000);
```

You can run it this way:
```bash
$ jx mt-keep test.js
```

**Comment by Bowser** [comment]
**mt-keep** could be useful if I had less libraries to depend on, having all of them loaded in all the threads. I decided to "manually" take advantage of the thread environment, dividing threads by different libraries they will load and assigning them tasks depending on the requests (one goes to one thread that has some libraries, another goes to another thread).

**Comment by ktrzeciaknubisa** [comment]
All right then. With JXcore you cad do it in multiple ways. Let's come back to the tasks, but instead of a callback, let's use `process.sendToMain()`:

```js
var responses = {};

function task(id) {

  var fs = require("fs");
  fs.readFile('./test.txt', function (err, data) {
    process.sendToMain({id: id, result: data.toString()});
    process.release();
  });

  process.keepAlive();
}

jxcore.tasks.on('message', function (threadId, obj) {
  if (responses[obj.id]) {
    responses[obj.id].end(obj.result);
    delete responses[obj.id];
  }
});


var http = require("http");
http.createServer(function (req, res) {
  var id = jxcore.utils.uniqueId();
  responses[id] = res;
  jxcore.tasks.addTask(task, id);
}).listen(8000);
```

**Comment by Bowser** [comment]
This is a very great solution for now, thank you very much! :+1:

**Comment by Bowser** [comment]
I continued to investigate on this issue (I know, I'm stubborn).
I succeeded in letting the callback on the main thread be fired directly, returning values through **process.release()**:

It is still an unripe system: it requires some expedients in the task method to work properly. But I think it could be a good starting point, because letting tasks able to fire callback and return even deferred/async value, without implementing an alternate message system (and memory duplication), can be a very powerful feature of JX from my point of view. 
Lets start analyzing our new scenario:

```javascript
function task(obj){
        obj.cbId = arguments.callee.caller.arguments[0];

        fs = require('fs');
        var htmlContent = '<html>';
        // do some things
        // I need to dynamically read a file to answer the request
        fs.readFile('./'+obj.url ,function(err,data){
                htmlContent += data;
                // do some other things on htmlContent
                //I need the callback in the main to be fired now!
                htmlContent += '</html>';
                process.release(1, [obj.cbId, htmlContent]);
        });
        //I'm not ready to end the task, I need to work on data from fs.readFile
        process.keepAlive();

        return '_deferCb';
}
function cb(obj, result){
        obj.res.end(result);
}

require('http').createServer(function(req,res){
        var obj = {'req':req,'res':res};
        jxcore.tasks.addTask(task, {'url':req.url}, cb, obj);
}).listen(8000);
```

I want to bring your attention to just three points of the code above:
* **obj.cbId = arguments.callee.caller.arguments[0];**
 * First we need the callback Id to keep the reference with the cb() function in the main thread. This is not so elegant but seems to work properly (I verified the system actually does pass the cbId), even if some better way could be implemented with just a bit of goodwill (for example explicitly defining cbId in the scope of task's parent).
* **process.release(1, [obj.cbId, htmlContent]);**
 * This is expected, since we need a way to return a value for the callback on the main thread. I thought a simple (additional) param of process.release() should be the best way since it serves already to communicate to the main thread when deferred/async works are finished on the task.
* **return '_deferCb';**
 * This should work as a keyword to let the main thread not execute (and destroy) the callback immediately (gcc @ _jx_tasks.js). Instead we want the callback to wait until our work will be finished before being fired.
 
At this point, implemented this behavior with just some minor changes to JX, at this point, detailed in this commit on my repo:
https://github.com/Bowser/jxcore/commit/24ce36a792540aab9edd1069a85977e7ce709f76

Let me know if you're interested in implementing this scenario, sure there is still the need to improve it.

**Comment by ktrzeciaknubisa** [comment]
Thanks for your time and effort! Much appreciated. I think, that's an interesting idea.

But we should also keep in mind scenarios for define/logic tasks, where not necessarily we want to use `process.keepAlive()` + `process.release()`. Take a look here: #198 . 

Plus I'm not sure, if we should involve `process.release()` for passing return values, as it is used not only in tasks, but also in `mt`/`mt-keep`. But it's still some concept.

My personal feelings are that maybe the best would be to find a way to introduce callback invocation from inside a task, something like:

```js
function task(obj, cb){
  setTimeout(function() {
    cb("result");
  }, 1000);
  // this could be a constant value instead of a string "_deferCb":
  return jxcore.tasks.deferCb;  
}
```

Well, this would rock. And it's totally javascript convention.

**Comment by Bowser** [comment]
I think it'll be very difficult to directly send the whole callback function (maybe with some non-stringifable object as http.ServerResponse) to another thread. I read from the code that it does already a lot of very complex operations to send just the task function source properly. JX works, if I understood properly, passing just a reference of the callback to the task's thread, then returns some values (together with the reference) back to the main thread (that has the right variable context to execute it). But if some big changes are going to be introduced in JX (so everything will be exchangeable between thread), maybe with SpiderMonkey integration, all our struggles will ends. 

Talking about define/logic tasks, the problem is that waitLogic seems to me poorly useful in our scenario, since define method is executed just once. It's very very good to have the possibility to instantiate objects like database connection having a method as define is. And I truly understand the need of a way to let the "first" logic execution wait until, for example, the database connection is established or the async file reading is done. But then? Just logic is executed following times, and db/file read has been already done. So logic then have to follow a behaviour very similar to the classical function-based task.
So process.keepAlive() and process.release() would have still an usage inside of it and our work could be useful even to fix the issue of the cb not invoked when waitLogic is set.

**jxcore.tasks.deferCb** seems to be much more professional, so it'll be very good choice.
It could go very well with, for example, a new method to obtain the cbId (as with other infos) named for example process.getTaskInfo() or, as I said, having these details being defined in the parent function of task (that, as a closure, can have access the memory space of its parent).

About mt/mt-keep I think we should not care too much, aren't they mainly used when we want a process to keep executing (as an http server that should stay working and never exit)? Their usage of keepAlive/release should be minimal, done (especially the second one) only in the case somethink happens (for example when some thread is going to be closed).
It is possible however to define another method, like process.endTask() not to disturb "normal" usage of process.release (even if I think is normally to expect it could transmit some data).
We have definetly to do somethink to clean the code and make it more clear.

**Comment by ktrzeciaknubisa** [comment]
Thanks for your elaboration! :)

> I think it'll be very difficult to directly send the whole callback function

Of course, and I didn't literally mean it. I was thinking more like sending `cbId` between threads, however `cb()` inside a task could be just an artificial the-same-thread-callback which would make indirectly main-thread-callback invoked. I know, it raises the complexity, however may be more user friendly (and keeping js standards).

As for the define/logic - you're generally right, and we don't want to mix callbacks with `continueLogic()`. What I meant is that for `waitLogic : true` returning value from the `logic()` is not implemented and I just pointed that out to remember when doing any callback improvements.

**Comment by obastemur** [comment]
`I think it'll be very difficult to directly send the whole callback function (maybe with some non-stringifable object as http.ServerResponse) to another thread`

If I understood correct. It's not just difficult. It's also not possible. Multi-thread here corresponds to totally isolated multi-instance.

Why do you need something like below ? Maybe we can approach to main problem from another direction.

```
require('http').createServer(function(req,res){
        var obj = {'req':req,'res':res};
        jxcore.tasks.addTask(task, {'url':req.url}, cb, obj);
}).listen(8000);
```
This can't work. It's not just about underlying JS engine, contexts etc. 

However, I do agree that the interface is very hard to use when it comes to waitLogic etc. stuff. We should definitely make it more developer friendly.

**Comment by Bowser** [comment]
@obastemur: It does work now, with some expedients shown here. I can use it on my platform.
At the same time the main process receives requests, I can have different task workers that process them depending on what user requested (and even do async works, keeping the possibility to return values to main thread to send the Response, as what I was proposing into this issue).

The main problem I was saying here is just to let the task to return even deferred values (deriving from async work into the task, like file system reads or queries).

@ktrzeciaknubisa We can arrange it this way:
```javascript
// This happens in the function that does directly call task() into the subThread:
task(param, function(result){
	process.release(null, [cbId, result]); //or another method dedicated to do this
});

// This is supposed to be the "user-friendly" way to handle it.
function task( param, cb ){
	asyncWork(function(data){
		cb(data);
	});

	return jxcore.tasks.deferCb;
}

jxcore.tasks.addTask(task,param,function(result){
	//dome some things on main thread with result
});
```
I think this solution could be great. cb that way is even an optional param, letting the user not even care of it if he doesn't need it when defines the task:
```javascript
function task( param ){ // I don't need the callback so I don't define the second parameter 
	var result = doSomething(param);
	return result;
}
```
What do you think about it?

**Comment by obastemur** [comment]
`I can have different task workers that process them depending on what user requested (and even do async works, keeping the possibility to return values to main thread to send the Response, as what I was proposing into this issue).`

This one is okay. Still, there will be a lot performance loss comparing to what mt mt-keep does. 

`The main problem I was saying here is just to let the task to return even deferred values (deriving from async work into the task, like file system reads or queries).`

I think callback thing is doable. We do have the callbackId mechanism and extending what it does shouldn't be a problem. For the file system reads etc. I do insist adding multithread ArrayBuffer/node Buffer delivery support. 

Sounds good?
