### ISSUE TITLE
os.tmpdir() on Android returns a bad path

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#262]
Right now if you call os.tmpdir() on Android it returns "/tmp" which isn't the right path. I would guess getCacheDir() is the right result although the fact that Android will auto-delete those files might be surprising to some. But whatever is returned, shouldn't it be a path the app can use?

**Comment by obastemur** [comment]
jxcore has a unique mobile only property under process that shows the application directory. iOS provides this location under process.env but Android doesn't. The fix checks process.env for a possible tmpdir. If there is no defined, it gives back process.userPath instead of the hard coded '/tmp'
