### ISSUE TITLE
Monitoring native app is not working

### ISSUE THREAD

**Issue by plexipi** [jxcore/jxcore#265]
I followed these infos and compiled the 3.0 version on Ubuntu Linux:
https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md

First, compiled the normal version, then the compressed one in order to create native packedges, as recommended. So, using the open sourced JX core (3.0 beta version), the native app can connect to the monitoring service (using jxcore.monitor.followMe). After starting the monitoring service, when I run the native app, in the monitoring log (http://127.0.0.1:17777/logs) I see:
...
Received data from process. {"pid":29540,"path":"path to native file","argv":["path to native file"],"config":null,"threadIDs":[-1],"IsEmbedded":true}
Respawned process. Old pid : 29540 with args ["path to native file"]
Monitor received request: /logs

But, when I try to check the JSON infos (http://127.0.0.1:17777/json), I can just see an empty array, no info at all.
As far as I understood, the monitoring service should restart the native app when it fails, but this part is not working, the crashed app is not restarted.

What do you think? Where is the problem?

**Comment by ktrzeciaknubisa** [comment]
Thanks for the input! 

This may depend on your scenario (how you perform the app crash), but my first thought is, that your app **does get** restarted (as this entry suggests: *Respawned process. Old pid : 29540 [...]*), but the new instance does not subscribe back (does not call `monitor.followMe()` after the restart) and eventually crashes again - this time for good.

Plus, if the crash happens before `start_delay` (default 2 secs) as mentioned in the [monitor.followMe()](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-monitor.markdown#monitorfollowmecallback-waitcallback) docs - the app cannot subscribe back to the monitor and that explains an empty array at http://127.0.0.1:17777/json.

I have a native app in front of me right now and it restarts as expected, so the issue might be related with app logic. Or different operating system. Which is yours?

We're still here to assist you further :)

**Comment by ktrzeciaknubisa** [comment]
It doesn't look like an issue, and since there is no update from the user, I'm closing it. 
@plexipi If you'll have any other questions, just let us know. Thanks.
