### ISSUE TITLE
Native packages fail to run (Ubuntu/Windows)

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#266]
This was seen at specific scenarios (e.g #245) with the following output when running **native** package:

```bash
$ ./test
node.js:1929
          var ind = (buffer + "").indexOf('jxcore.bin(?@@!!$<$?!*)     if (ind
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
```

But now it looks like any native package doesn't run on Ubuntu/Windows. Sample code:
```js
console.log("ok");
```

SM on Ubuntu crashes at the same line, however ends up with Segmentation Fault.

**Comment by obastemur** [comment]
native packaging was requiring a jx binary with 'compress-internals'. Perhaps that's why it was failing on your check. However https://github.com/jxcore/jxcore/commit/b62efb2b8de9720003e9cf731cb16419d6c706f2 changes this requirement. It should work without the compressed build.
