### ISSUE TITLE
Show a friendly message for incompatible jx packages

### ISSUE THREAD

**Issue by dragonation** [jxcore/jxcore#267]
At least, using the static linked library could not handle the compiled .jx file in iOS both simulator and devices.

Is the .jx file only available in the jx executable environment?

**Comment by dragonation** [comment]
JS(64189,0x11bb56000) malloc: *** mach_vm_map(size=18446744073674829824) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Package is corrupted test.jx

**Comment by obastemur** [comment]
What's the size of test.jx ? and are you trying to use it as an entry point? some more details please.

**Comment by dragonation** [comment]
The jx file is only 609 KB. Just includes express and start a simple server.
I have tested in the executable environment, all is OK, and ensured that the jx file could be required by other module.

While embedding the library, according to the guide, I define the home directory, and with the main script:

require('test.jx')

**Comment by dragonation** [comment]
However embedding environment shows the error for malloc

**Comment by dragonation** [comment]
Got it.
The jx file packaged by the prebuilt binary downloaded from jxcore.com is different from the one packaged by the open source version.
It seems add a note in the docs to tell users the difference will be much better, I think.

**Comment by obastemur** [comment]
Ohh. you built the jx package with the binary from downloads and used it on embedded one? This explains the issue.
