### ISSUE TITLE
Android Express App Crashes SpiderMonkey

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#268]
I've put together a small Express test program based in the `jxcore-android-basics` sample application:

https://github.com/DLLarson/jxcore-android-basics/tree/expdemo2

When the app launches on the x86 emulator a seg fault occurs:

![jxcorefault-2015-03-27](https://cloud.githubusercontent.com/assets/175455/6870890/fc26623a-d46c-11e4-9300-e21a499b663b.png)

-Dale

**Comment by obastemur** [comment]
Android emulators are inconsistent devils. Try another version of the base OS for the emulator. (i.e. run away from 4.3 and it's variations) I do test on a x86 device and it works without a problem.

**Comment by DLLarson** [comment]
>Try another version of the base OS for the emulator. (i.e. run away from 4.3 and it's variations)

I'm building and running against 5.1 api 22. 

I should note that I'm running on a debug specific build of the source code in the latest (yesterday) JXcore repo.

Is there a specific version I should use?

-Dale

**Comment by DLLarson** [comment]
> I do test on a x86 device and it works without a problem.

But did you test what I just submitted--which is a modified version the android sample? 

The normal sample runs fine on my emulator (both arm and x86.) My new code crashes which is why I included the link to the code. I modified no native code. Just added the express stuff and hooked it in as best I could figure out.

-Dale

**Comment by obastemur** [comment]
Thanks for the details. I'll be looking into it as soon as possible.

**Comment by ktrzeciaknubisa** [comment]
Dale, a "small Express test program" would be something like this below :)

```js
var app = require('express')();
var http = require('http');
var path = require('path');


app.get('*', function(req, res){
  res.sendfile( path.resolve(__dirname + '/test.js') );
});

http.Server(app).listen(10500, function(){
  console.log('listening on *:10500');
});
```

I inserted those few lines into `app.js` and it runs smoothly. Then I entered my device's url (like http://192.168.1.102:10500) in a browser and it got my request.

Could you try if that works for you?

Your scenario is more complex, uses more node dependencies (modules). Is it possible for you to disable them one by one and reduce to the bare bone until the very reason will be exposed?

**Comment by obastemur** [comment]
@ktrzeciaknubisa did you try @DLLarson scenario on your device ? What happened?

**Comment by ktrzeciaknubisa** [comment]
I got bunch Eclipse's compilation issues when working directly on Dale's files. I ended up with manual moving app logic into my working sample. App crashed, however not in the same manner as for Dale. I didn't go much into this yet - I was eager to find out if we can run a really basic express app.

**Comment by DLLarson** [comment]
Hi,

>I got bunch of Eclipse's compilation issues when working directly on Dale's files.

That is probably my fault. 

I forgot to mention I stripped the `jxcore-binaries` folder libraries from the git branch. I was rebuilding the jxcore stuff to get debug versions of the libraries and didn't want to clog Github with huge binaries.

I put a `README` in the directory but it's definitely not obvious.

I'm rebuilding all the stuff on my home machine so I can be tooled up. To get my eclipse crash I used debug .a files. I also used eclipse to launch the session with the Debug as...>Android Native Application menu command.

My eclipse is Luna.

-Dale

**Comment by DLLarson** [comment]
>I was eager to find out if we can run a really basic express app.

After setting up my build environment I first verified that my example (`expdemo2`) still crashes in the same manner and it does.

Next I replaced the sample's `app.js` content with the small express example provided above and ran it in that directory with `jx app.js` to ensure it worked. In the web browser I'm presented with the contents of `test.js` (which is the renamed original `app.js`.)

Finally I built the android sample and ran in on an x86 emulator. The result was this:

![expdemo3-webview](https://cloud.githubusercontent.com/assets/175455/6881651/0a4caebc-d537-11e4-9673-43c803e53a1c.png)

Although it didn't seg-fault it had some issues. You can find the exact code (named `expdemo3`) of the test here:

https://github.com/DLLarson/jxcore-android-basics/tree/expdemo3

To create the crashing express test code `expdemo2` I used the procedure described in issue  #245.

-Dale

**Comment by obastemur** [comment]
I've found the the reason for the crash. There was a problem with one of the persistent roots. Your initial scenario triggers the major GC in a very early point. This wasn't a case on desktop since we do have a different set of configuration. I'm testing the other scenarios before applying the fix.

Thanks for all the details.

**Comment by obastemur** [comment]
The GC issue is fixed. Beware one thing;
```
/jxcore-droid/assets/jxcore/node_modules/jade/node_modules/transformers/node_modules/uglify-js/lib/utils.js

line:214
Change:
if (!(words instanceof Array)) words = words.split(" ");

To:
if (!(Array.isArray(words)) words = words.split(" ");
```

This is a separate issue (https://github.com/jxcore/jxcore/issues/275)
I've tested your original app on an Android device and it works now.

Closing. Reported issue is resolved. Thanks for all the details
