### ISSUE TITLE
Incorrect module cache when module name is already defined in the Object prototype

### ISSUE THREAD

**Issue by dragonation** [jxcore/jxcore#269]
For example, requiring a module named watch will return undefined, because there is already a function named watch in the Object prototype.

Fix:

  NativeModule.getCached = function (id) {
    if (NativeModule._cache.hasOwnProperty(id))
    {
      return NativeModule._cache[id];
    }
    else
    {
      return null;
    }
  };

in the src/node.js:1314

**Comment by dragonation** [comment]
Mostly occurred in SpiderMonkey, which has watch function in Object prototype. However, I think V8 has this issue too, if we define a module named constructor

**Comment by obastemur** [comment]
I didn't test this yet but LGTM. Did you test it ? BTW; feel free to commit this patch. Thanks!

**Comment by dragonation** [comment]
Just test to run forever, but it failed with 2 bugs, one is for jx, the other is for optimist. Both of the bugs caused by the watch function without test of hasOwnProperty.

The official pre-built version has no bugs, it may be built with V8, I think.

**Comment by obastemur** [comment]
So it works with hasOwnProperty patch?

**Comment by dragonation** [comment]
It seems works to me

**Comment by obastemur** [comment]
same here. feel free to send a push request. Thanks!

**Comment by obastemur** [comment]
@dragonation ping! we are going to close 0.3.0.0 branch. It could be nice to have this fix in the package.
