### ISSUE TITLE
Simple Express Application Generates JSTrace on Android

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#271]
Moved from issue #268 @ktrzeciaknubisa

>Dale, a "small Express test program" would be something like this below :)
>```
>var app = require('express')();
>var http = require('http');
>var path = require('path');
>
>app.get('*', function(req, res){
> res.sendfile( path.resolve(__dirname + '/test.js') );
>});
>
>http.Server(app).listen(10500, function(){
>  console.log('listening on *:10500');
>});
>```
>I inserted those few lines into app.js and it runs smoothly. Then I entered my device's url (like >http://192.168.1.102:10500) in a browser and it answered my request.
>
>Could you try if that works for you?

After setting up my build environment I first verified that my example (`expdemo2`) still crashes in the same manner and it does.

Next I replaced the sample's `app.js` content with the small express example provided above and ran it in that directory with `jx app.js` to ensure it worked. In the web browser I'm presented with the contents of `test.js` (which is the renamed original `app.js`.)

Finally I built the android sample and ran it on an x86 emulator. The result was this:

![expdemo3-webview](https://cloud.githubusercontent.com/assets/175455/6881651/0a4caebc-d537-11e4-9673-43c803e53a1c.png)

Something gets goofed up and it delivers some internal info which I'm guessing is a stack trace.

You can find the exact code (named `expdemo3`) of the test here:

https://github.com/DLLarson/jxcore-android-basics/tree/expdemo3

-Dale

**Comment by ktrzeciaknubisa** [comment]
It's not really stack trace or anything. It is what express returns on first request, which is "/" (when *index.html* calls the jxcore part of the sample) and `app.get('*')` serves this. And now, since we have the #242 bug (related with express working on SM) the result is exactly as on your printscreen.

I don't remember now, if my previous "simple express" on android was using V8 binaries and the problem did not occur. However until the mentioned bug is fixed, you may want replace `sendfile()` in favour of `send()`:

```js
app.get('*', function(req, res){
	  res.send(fs.readFileSync(path.resolve(__dirname + '/test.js')).toString());
});
```

**Comment by DLLarson** [comment]
Thanks for the analysis. I'm not that up-to-speed on the Javascript side of Node.

>However until the mentioned bug is fixed, you may want to replace sendfile() in favour of send():

Would using V8 correct the problem as well? 
If so, is there any downside for the short term?

-Dale

**Comment by obastemur** [comment]
Would using V8 correct the problem as well? 
A> Yes
If so, is there any downside for the short term?
B>  No

**Comment by DLLarson** [comment]
I've rebuilt my libraries using v8 instead of SpiderMonkey and retested the simple Express app. It still had problems but the output is shorter and was triggered by hitting a TypeError:
```
TypeError: argument entity must be string, Buffer, or fs.Stats
   at etag (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/etag/index.js:55:11)
   at SendStream.setHeader (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/send/index.js:739:15)
   at SendStream.send (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/send/index.js:507:8)
   at onstat (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/send/index.js:600:10)
   at fs.js:83:15
   at Object.fs.stat (fs.js:719:7)
   at SendStream.sendFile (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/send/index.js:590:6)
   at SendStream.pipe (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/node_modules/send/index.js:479:8)
   at sendfile (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/lib/response.js:1029:8)
   at ServerResponse.res.sendfile (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/express/lib/response.js:471:3)
```

Running the app from `assets/jxcore` with `jx app` or `node app` work as expected.

-Dale

**Comment by obastemur** [comment]
This is no longer an issue. https://github.com/jxcore/jxcore/commit/f72d3d3ec9e392a5a0b70297e6a78f951ad3beee fixes the confusion

**Comment by ktrzeciaknubisa** [comment]
Not entirely the truth. Few more details on issue [242](https://github.com/jxcore/jxcore/issues/242#issuecomment-88423226).
