### ISSUE TITLE
Tasks not running parallel

### ISSUE THREAD

**Issue by liebig** [jxcore/jxcore#272]
I am sorry, if this is a foolish beginner question, but I don't get Tasks running parallel. I have this JavaScript file:

```javascript
jxcore.tasks.setThreadCount(5);

var method = function () {
    console.log("thread started", process.threadId);
    for(var i = 0; i < 2000000000; i++) {
        // Do nothing!
    }
    console.log("thread finished", process.threadId);
};

jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
```

but when running `jx thread.js` I get this console output:
```
thread started 0
thread finished 0
thread started 0
thread finished 0
thread started 0
thread finished 0
thread started 0
thread finished 0
thread started 0
thread finished 0
```

I would expect, that the console ouput should be something like:
```
thread started 0
thread started 1
thread started 2
thread started 3
thread started 4
thread finished 0
thread finished 1
thread finished 2
thread finished 3
thread finished 4
```
I know that I can't `assume the tasks will be executed in the order of which they were added` or that `there is no guarantee, that each of them will run in its own subthread`. This is no problem. But I assume that the next task is not waiting until the previous task is finished. I assume that they run parallel in different threads.

I am using jxcore in version Beta-0.2.3.7 with Windows 7 (64 Bit).

Thank you,
Marc

**Comment by ktrzeciaknubisa** [comment]
Well, not sure why this happens for 0.2.3.7. I never saw this before until now :) And looks like it only applies to Windows.

However for current open sourced 0.3.0.0 runs your code exactly as you would expect it. I've just tried.

We highly encourage to the use current version (for now from a master branch), as it is constantly updated.

**Comment by obastemur** [comment]
This was a design decision on pre 0.3.0.0. If you set the tasks in async manner (real app scenario) it will be working as you were expecting. However, this is no longer a problem for 0.3.0.0 +

Seems tomorrow we are releasing 0.3.0.0 and the prebuilt binaries will on the website.

**Comment by DLLarson** [comment]
>Seems tomorrow we are releasing 0.3.0.0 and the prebuilt binaries will on the website.

It would be great if you guys would tag the release code when it's locked down. Right know it's difficult to know where the releases line up.

Thanks!
-Dale

**Comment by obastemur** [comment]
`It would be great if you guys would tag the release code when it's locked down. Right know it's difficult to know where the releases line up.`

Sure

**Comment by liebig** [comment]
Thank you for the fast reply. I tried to compile it by the git sources. I downloaded the ZIP, extracted it and ran `vcbuild.bat` but I only get this error message:
```
  File "configure", line 339
    '''
      ^
SyntaxError: Missing parentheses in call to 'print'
Failed to create vc project files.
```
Strange error message... Any ideas?

**Comment by ktrzeciaknubisa** [comment]
Hi, for VS 2013 this would be: [Visual C++ Redistributable Packages for Visual Studio 2013](http://www.microsoft.com/en-us/download/details.aspx?id=40784). 

I'm adding this to prerequisites at [HOW_TO_COMPILE](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md).

**Comment by liebig** [comment]
Hi, I installed the Visual C++ Redistributable Packages for Visual Studio 2013 but still get the error:
```
>vcbuild.bat
  File "configure", line 339
    '''
      ^
SyntaxError: Missing parentheses in call to 'print'
Failed to create vc project files.
```

**Comment by ktrzeciaknubisa** [comment]
All right, which Python version have you got installed? It looks to me like you have 3.X installed, instead of 2.6 or 2.7.

**Comment by liebig** [comment]
You were right and I am sorry. But now I installed Python 2.7.9. After running `vcbuild.bat` the process stopped with this error message:
```
     Bibliothek "D:\Frameworks\jxcore-20150401\Release\jx.lib" und Objekt "D:\F
  rameworks\jxcore-20150401\Release\jx.exp" werden erstellt.
libuv.lib(poll.obj) : error LNK2001: Nicht aufgel÷stes externes Symbol "_uv_msa
fd_poll@12". [D:\Frameworks\jxcore-20150401\jx.vcxproj]
D:\Frameworks\jxcore-20150401\Release\jx.exe : fatal error LNK1120: 1 nicht auf
gel÷ste Externe [D:\Frameworks\jxcore-20150401\jx.vcxproj]
```
In english it is something like
```
     Library "D:\Frameworks\jxcore-20150401\Release\jx.lib" and object "D:\F
rameworks\jxcore-20150401\Release\jx.exp" will be created.
libuv.lib(poll.obj) : error LNK2001: Not resolved external symbol "_uv_msa
fd_poll@12". [D:\Frameworks\jxcore-20150401\jx.vcxproj]
D:\Frameworks\jxcore-20150401\Release\jx.exe : fatal error LNK1120: 1 not resolved 
external [D:\Frameworks\jxcore-20150401\jx.vcxproj]
```
Can you help again?

Thank you,
Marc

**Comment by ktrzeciaknubisa** [comment]
I assume, that you took Python installer from the python.org main page which appears to be x86 version (python-2.7.9.msi).

I've stumbled upon the same issue as yours, and in my case the solution was to install on Win x64 the following python:
[Windows x86-64 MSI installer](https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi) (**python-2.7.9.amd64.msi**) rather than 
[Windows x86 MSI installer](https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi) (**python-2.7.9.msi**).

They all are available on [Python Releases for Windows](https://www.python.org/downloads/windows/).

**Comment by liebig** [comment]
Thank you, for your fast great support @ktrzeciaknubisa! The x64 package did it. Now my `thread.js` works like I expect:
```
thread started 2
thread started 1
thread started 0
thread started 3
thread started 4
thread finished 1
thread finished 0
thread finished 4
thread finished 2
thread finished 3
```
Maybe you add the information about the python package to the HOW_TO_COMPILE file. Thank you for this awesome library. Please don't stop making jxcore more awesome ;)

Thank you,
Marc

**Comment by liebig** [comment]
Sorry, I have to reopen this. If I run the script again and again from command shell sometimes the `thread finished` messages do not appear. So I assume that the tasks will be terminated. I added `process.keepAlive();` and `process.release();` but it doesn't help. If I run the script 5 times, it only displays one time the `thread finished` messages.

`thread.js`
```javascript
jxcore.tasks.setThreadCount(5);

var method = function () {
    process.keepAlive();
    console.log("thread started", process.threadId);
    for(var i = 0; i < 2000000000; i++) {
        // Do nothing!
    }
    console.log("thread finished", process.threadId);
    process.release();
};

jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
jxcore.tasks.addTask(method);
```

`console`
```
D:\jxcore>jx thread.js
thread started 2
thread started 0
thread started 3
thread started 1
thread started 4

D:\jxcore>jx thread.js
thread started 2
thread started 0
thread started 3
thread started 1
thread started 4

D:\jxcore>jx thread.js
thread started 0
thread started 3
thread started 4
thread started 1
thread started 2

D:\jxcore>jx thread.js
thread started 2
thread started 0
thread started 1
thread started 3
thread started 4
thread finished 2
thread finished 1
thread finished 0
thread finished 3
thread finished 4

D:\jxcore>jx thread.js
thread started 0
thread started 1
thread started 2
thread started 3
thread started 4
```

I am running Windows 7 (64 bit) with jxcore built from sources yesterday.

Thank you,
Marc

**Comment by ktrzeciaknubisa** [comment]
Hi Marc, nice to see you again :)

The thing you describe is tricky - I couldn't reproduce this until I reduced my VM to use only 1 processor. I that your case too?

**Comment by liebig** [comment]
Thank you :) I am not using a VM, I am using a Dell Latitude E6520 with i8-2640M (4 cores), Windows 7 Ultimate (64 bit) and 8,00 GB RAM.
Another strange thing: If I start cmd as administrator, in 5 executions the threads will be terminated only one time. This is a better rate, but it still happens.

**Comment by obastemur** [comment]
@liebig  You don't need process.keepAlive and process.release for your case. There is no callback there and task controller knows sub instance is busy. 

BTW; the issue you were having supposed to be fixed. Please pull the latest from Github and give it a shot. Thanks!

**Comment by ktrzeciaknubisa** [comment]
> Maybe you add the information about the python package to the HOW_TO_COMPILE file. Thank you for this awesome library. Please don't stop making jxcore more awesome ;)

@liebig Thanks for your kind words. Also the note about python package version was added as you suggested. Thanks for using JXcore! :)

**Comment by obastemur** [comment]
Ping @liebig @ktrzeciaknubisa ! do we have an open issue left here?

**Comment by ktrzeciaknubisa** [comment]
From my part its clear. Issue seems to be fixed. I've checked also on 1 processor Win 7 VM, where it occurred before and all looks fine.

**Comment by liebig** [comment]
I am very sorry for the late reply. I downloaded and built the sources today and now everything seems to work. Thank you for your awesome support!

**Comment by ktrzeciaknubisa** [comment]
Thank you very much!

**Comment by ktrzeciaknubisa** [comment]
Just a quick note regarding an error posted in this thread by @liebig : 

```
>vcbuild.bat
  File "configure", line 339
    '''
      ^
SyntaxError: Missing parentheses in call to 'print'
Failed to create vc project files.
```
It was related to Python 3.X installed instead of 2.6 or 2.7. The `vcbuild.bat` was just updated and since now is checking for the required Python's version:

```bash
C:\jxcore>vcbuild.bat
You need Python 2.6 or 2.7 for the script to run. Currently installed version: 3.4.3
```

**Comment by liebig** [comment]
You guys do a great job!
