### ISSUE TITLE
Windows V8 Build for ia32 fails on Windows x64

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#273]
Today I was trying to make a build ia32 on Win x64:

```bash
> vcbuild.bat ia32
``` 

It was working for quite a time until I got this:

> Creating library C:\jxcore\jxcore_ia32\Release\jx.lib and object C:\jxcore\jxcore_ia32\Release\jx.exp
libuv.lib(poll.obj) : error LNK2001: unresolved external symbol _uv_msafd_poll@12 [C:\jxcore\jxcore_ia32\jx.vcxproj]
C:\jxcore\jxcore_ia32\Release\jx.exe : fatal error LNK1120: 1 unresolved externals [C:\jxcore\jxcore_ia32\jx.vcxproj]

This is the same machine, on which build x64 runs ok.

My platform is:

* Win 7 x 64
* VS 2013 Ultimate
* Python27

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/811d1aaa4b5306da73e0c21e25ff1c64b9174028 Fixes this issue.
