### ISSUE TITLE
jx won't run as 32-bit on 64-bit windows

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#279]
Hi,
I'm trying to run a 32-bit version of jx on win-8.1 64-bit. Node offers separate installers, but I can't work out how to force the jxcore installer to install for 32-bit.
Thanks.

**Comment by obastemur** [comment]
You can not do that. But you have some options;
a - compile it for 32-bit from the sources 
b - use an extractor tool (I didn't try but it should work) (link)[http://www.softpedia.com/get/Compression-tools/InnoExtractor.shtml]
c - install it on 32 bit Windows. 

Hope one of these options may help. @ktrzeciaknubisa we might offer Windows executable in a zip form separately (for the upcoming version)

**Comment by zamb3zi** [comment]
Thanks. On your suggestion I installed into a 32-bit virtual machine and then copied the installed files into my 64-bit host. All working fine. Cheers.

**Comment by ktrzeciaknubisa** [comment]
Yes, it might be useful if we'll allow to install also x32 binaries on x64 Windows systems. We can either create two installers each for x32/x64 or add the checkbox to the current installer (something like "Force 32-bit installation" - and this would be visible only on x64 for platform).

**Comment by obastemur** [comment]
let's stick with installer and zip package option. This is a common approach and also useful when it's not possible to install anything to the system (admin rights etc.)

**Comment by ktrzeciaknubisa** [comment]
Hi @zamb3zi . The windows setup for the newest JXcore v.0.3.0.0 has now option to install x32 binaries on 64-bit machines. Plus, you can also choose between SM or V8 engine during the setup.

Apart from the installer, there are also available separate zips per each engine/arch on [download](http://jxcore.com/downloads/) page.

**Comment by zamb3zi** [comment]
That's great. Thank you.
