### ISSUE TITLE
JX_GetString crashes when embedding jx.dll

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#284]
I'm now having partial success embedding jx.dll. I had to modify the public interface to export the symbols to the DLL. I defined this in jx_result.h:
```c++
#ifdef _WIN32
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif
```
Then all the function definitions and declarations needed to be prefixed with `EXPORT`. Using the default `cdecl` calling convention rather than `stdcall` seems to be [preferred](http://stackoverflow.com/questions/6511096/cdecl-or-stdcall-on-windows). Now I can call into the API following the [Embedding Basics](https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_Basics.md) example. Everything is working so far except for `JX_GetString` which fails in `HandleScope::HandleScope` with `"Entering the V8 API without proper locking in place"`. `JX_GetInt32` etc are working fine.
I set up the engine with calls to `JX_Initialize`, `JX_InitializeNewEngine`, `JX_DefineMainFile`, `JX_StartEngine`. Then I call `JX_Evaluate` with `'testing'\n`. Calling `JX_GetDataLength` on the result works fine, but `JX_GetString` fails as above.
Thanks for any help.

**Comment by obastemur** [comment]
I'm looking into this a.s.a.p. Thanks

**Comment by obastemur** [comment]
@zamb3zi I couldn't reproduce the issue on my run. That sample was specifically given for POSIX not Windows. Can you share the file you've been working on?

**Comment by zamb3zi** [comment]
I've packaged my files and put them on [dropbox](https://dl.dropboxusercontent.com/u/10137755/bug.zip).

As I mentioned, I modified all 4 of the files in `src/public` to add the required `__declspec(dllexport)`. I've included these files as well as my build of `jx.dll` made with VS2013 and `.\vcbuild.bat --shared-library`. My test environment is AutoHotKey, but it should behave the same with any others. I guess I could have used `jx + ffi` instead for extra recursion points. I've included the interpreter, but if you prefer to download it you can get it [here](http://www.autohotkey.net/~HotKeyIt/AutoHotkey/files/AutoHotkey-txt.html). You want version 1.1 and just extract `Win32w\AutoHotKey.exe` from the zip file.

Run the test case with `AutoHotKey.exe bug.ahk`. It loads `jx.dll` from the same directory and generates the following message boxes:
```
double value = 3.141593
string length = 7
*crash*
```

Note: the callback is never called but using `JX_DefineExtension` I can call back into AHK no problem.

**Comment by zamb3zi** [comment]
Also, I should mention that although the test exits without error message, I was able to find the `"Entering the V8 API without proper locking in place"` error using the debug build and attaching to the process while the `string length = 7` message box is showing.
It calls successfully into `JX_GetString` and then aborts inside line 128 `ret = strdup(STRING_TO_STD(wrap->value_));`.

**Comment by zamb3zi** [comment]
Here's the same test case written in javascript with `ffi`. I think you'll agree this is a nice way to demonstrate embedding. The behaviour is the same as the AHK test however, outputting:
```
Hello world!
3.141592653589793
string length = 7
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
```

```javascript
var ffi = require('ffi'), ref = require('ref'), StructType = require('ref-struct');

var jxValue = StructType({
	com_: 'pointer',
	persistent_: ref.types.bool,
	data_: 'pointer',
	size: ref.types.size_t,
	type_: ref.types.uint32
});

var jxValueP = ref.refType(jxValue);
var _void = ref.types.void;

var jx = new ffi.Library('./jx', {
	JX_Initialize: [_void, ['string', 'pointer']],
	JX_InitializeNewEngine: [_void, []],
	JX_DefineMainFile: [_void, ['string']],
	JX_StartEngine: [_void, []],
	JX_StopEngine: [_void, []],
	JX_LoopOnce: [ref.types.bool, []],
	JX_Evaluate: [ref.types.bool, ['string', 'string', jxValueP]],
	JX_GetInt32: [ref.types.int32, [jxValueP]],
	JX_GetDouble: [ref.types.double, [jxValueP]],
	JX_GetBoolean: [ref.types.bool, [jxValueP]],
	JX_GetString: ['string', [jxValueP]],
	JX_GetDataLength: [ref.types.uint32, [jxValueP]],
	JX_Free: [_void, [jxValueP]],
});

function convertJXValue(result) {
	switch(result.type_) {
		case 1: // RT_Int32
			return jx.JX_GetInt32(result.ref());
		case 2: // RT_Double
			return jx.JX_GetDouble(result.ref());
		case 3: // RT_Boolean
			return jx.JX_GetBoolean(result.ref());
		case 7: // RT_Undefined
			return 'undefined';
		case 8: // RT_Null
			return 'null';
		case 10: // RT_Function
		case 4: // RT_String
		case 5: // RT_JSON
		case 6: // RT_Buffer
		case 9: // RT_Error
			console.log('string length =', jx.JX_GetDataLength(result.ref()));
			return jx.JX_GetString(result.ref());
	}
}

var callback = ffi.Callback(
	_void, [jxValueP, ref.types.uint32],
	function(results, argc) {
		console.log('Callback', results, argc);
	}
);
jx.JX_Initialize(__filename, callback);

jx.JX_InitializeNewEngine();
jx.JX_DefineMainFile("console.log('Hello world!');");
jx.JX_StartEngine();
while(jx.JX_LoopOnce())
	console.log('Sleeping...');

var result = new jxValue;
jx.JX_Evaluate("Math.PI", 'myscript', result.ref());
console.log(convertJXValue(result));
jx.JX_Free(result.ref());

jx.JX_Evaluate("'testing'", 'myscript', result.ref());
console.log(convertJXValue(result));
jx.JX_Free(result.ref());

while(jx.JX_LoopOnce())
	console.log('Sleeping...');

jx.JX_StopEngine();
```

**Comment by obastemur** [comment]
There is one big problem using with 'ffi'. You perhaps run it on either 'jxcore' or 'node.js' and trying to load 'jx' shared library that also hosts V8. I don't know how it survives at all. 

BTW; https://github.com/jxcore/jxcore/commit/2ed0fbe17c2134d83d5e07132cc9b9e50923543c adds extern to headers for Windows. Besides, I've shared a sample Visual Studio solution from https://github.com/obastemur/JXcoreWindowsEmbedded . 

It works without a problem Debug/Release X86 or X64.. Please let me know if it's okay now.

**Comment by zamb3zi** [comment]
I don't think there's any problem with the ffi approach. `jx.exe` doesn't load `jx.dll`. Both of them link to their own copies of all the relevant static libraries, making them independent.

Thanks for the update to the headers, that's working great for me.

Your JXcoreWindowsEmbedded solution is also working fine for me. However, if I modify it to make the same calls as my bug example, it fails in exactly the same way. Try this simplified version:

```c++
#include "stdafx.h"

using namespace std;
#if defined(_MSC_VER)
// Sleep time for Windows is 1 ms while it's 1 ns for POSIX
// Beware using this for your app. This is just to give a
// basic idea on usage
#include <windows.h>
#else
#include <unistd.h>
#define Sleep(x) usleep(x)
#endif

#include "jx.h"

#define flush_console(...)        \
  do {                            \
    fprintf(stdout, __VA_ARGS__); \
    fflush(stdout);               \
        } while (0)

void ConvertResult(JXValue *result, std::string &to_result) {
  switch (result->type_) {
  case RT_Null:
    to_result = "null";
    break;
  case RT_Undefined:
    to_result = "undefined";
    break;
  case RT_Boolean:
    to_result = JX_GetBoolean(result) ? "true" : "false";
    break;
  case RT_Int32: {
    std::stringstream ss;
    ss << JX_GetInt32(result);
    to_result = ss.str();
  } break;
  case RT_Double: {
    std::stringstream ss;
    ss << JX_GetDouble(result);
    to_result = ss.str();
  } break;
  case RT_Buffer: {
    to_result = JX_GetString(result);
  } break;
  case RT_JSON:
  case RT_String: {
    to_result = JX_GetString(result);
  } break;
  case RT_Error: {
    to_result = JX_GetString(result);
  } break;
  default:
    to_result = "null";
    return;
  }
}

void callback(JXResult *results, int argc) {
  // do nothing
}

int main(int argc, char **args) {
  char *path = args[0];
  // Call JX_Initialize only once per app

  JX_Initialize(args[0], callback);
  JX_InitializeNewEngine();
  char *contents = "console.log('hello world');";
  JX_DefineMainFile(contents);
  JX_StartEngine();

  while (JX_LoopOnce() != 0) Sleep(1);

  JXValue result;
  std::string str_result;

  JX_Evaluate("Math.PI", "myscript", &result);
  ConvertResult(&result, str_result);
  str_result += "\n";
  flush_console("%s", str_result.c_str());
  JX_Free(&result);

  str_result.clear();
  JX_Evaluate("'testing'", "myscript", &result);
  ConvertResult(&result, str_result);
  str_result += "\n";
  flush_console("%s", str_result.c_str());
  JX_Free(&result);

  while (JX_LoopOnce() != 0) Sleep(1);

  JX_StopEngine();
}
```

Note: the `Math.PI` section isn't necessary but it just demonstrates that it's something specific to string values.

**Comment by zamb3zi** [comment]
Conversely, if my `bug.js/ffi` example conforms to your embedding example, it works just fine:
```js
var extension = ffi.Callback(
	_void, [jxValueP, ref.types.uint32],
	function(results, argc) {
		console.log('Extension', convertJXValue(results.deref()), argc);
	}
);
jx.JX_DefineExtension('myext', extension);
var result = new jxValue;
jx.JX_Evaluate("process.natives.myext('testing')", 'myscript', result.ref());
jx.JX_Free(result.ref());
```

**Comment by obastemur** [comment]
@zamb3zi Thanks!. I confirm the problem and fixed. jx-ni interface test cases are available under `test/native-interface`. Please feel free to contribute in case you stumbled into anything else.

**Comment by zamb3zi** [comment]
Awesome, thanks Oguz! I can confirm my test cases are working perfectly now.
Hopefully as I get more familiar with the code, I might be able to make some contributions.
