### ISSUE TITLE
Update JXcore Plesk extension for upcoming release

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#285]
JX file format is a bit different on master comparing to latest stable 2.3.7. We need to update Plesk extension and test it properly with master. 
@ktrzeciaknubisa ping!

**Comment by ktrzeciaknubisa** [comment]
Right. It will be ready once we'll release new jx binaries.

**Comment by ktrzeciaknubisa** [comment]
Will that be V8 build for Plesk or SM? 

What about both? Is there any need for providing an option? (**Reinstall** button on extension's `JXcore Configuration` tab).

![reinstall](https://cloud.githubusercontent.com/assets/5946844/7026964/2dfa9dd8-dd4d-11e4-9733-38b350e6c21f.png)

**Comment by obastemur** [comment]
For now v8 only. SM side is not ready for production

**Comment by ktrzeciaknubisa** [comment]
The new version [JXcore Plesk Extension v2.0.6](http://jxcore.com/jxcore-plesk-extension-v2-0-6/) has just been published. The provided link describes the most important changes. The most important of them is support for JXcore 0.3.0.0.

Updated extension itself can be taken from [here](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support).
