### ISSUE TITLE
Array/Object prototype methods vs for...in loop

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#287]
This came out today. Defining new methods with `Array.prototype` or `Object.prototype` adds them into the iteration results of `for...in` loop of particular array/object instances, for example:

```js
Object.prototype.doSomething = function () {};
for (var o in ["one", "two"]) console.log(o);
//0
//1
//doSomething
```

Since we use `for...in` loop for arrays, it may lead to unexpected bugs like this one: [JXcore throw error when add task](http://stackoverflow.com/questions/29462596/jxcore-throw-error-when-add-task) which is fixed 11baebe9f311a91c05501cadc62961ca701f9fc0 now (or actually patched for this particular issue).

Even if we would turn each `for...in` array iteration into regular `for` loops , the problem remains when you iterate any other object `{}` as well.

***

The problem is generally known, as it originates from JavaScript, however I wonder whether we should perform some precautions for this, e.g. add warnings in case if someone uses prototyping?

**Comment by obastemur** [comment]
`add warnings in case if someone uses prototyping?` No. We have limited number of places can trigger the situations like that. Better make our implementation better.

**Comment by brodybits** [comment]
I would like to see a test for this one. PR #528 partially broke this one and I had to issue PR #532 to fix it. I will work on this if I get a chance.
