### ISSUE TITLE
Sub-thread starves all other sub-threads

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#292]
Hi,
I'm just trying to understand the multithreading behaviour. I'm curious about the following example:
```javascript
jxcore.tasks.setThreadCount(4);
var tasks = jxcore.tasks;
var task = function() {
	console.log('starting on thread', process.threadId);
	while(true)
		;
};
var thread_id = 0;
var i = setInterval(function() {
	console.log('run on thread', thread_id);
	tasks.runOnThread(thread_id, task);
	if(++thread_id >= 4)
		clearInterval(i);
}, 250);
```
The output is:
```
run on thread 0
starting on thread 0
run on thread 1
run on thread 2
run on thread 3
```
Is this what you would expect? The task never becomes idle, but it doesn't starve the main thread (which continues to run, adding the other 3 tasks). The remaining 3 sub-threads are totally starved however and never start their tasks.

I'm running on a quad-core processor with 8 hyperthreads (win8.1 64-bit on i7-3630QM).

Thanks,
John

**Comment by zamb3zi** [comment]
Ah never mind! Maybe this has been fixed recently? This was the behaviour of my installed jxcore v0.10.32, however I just tested again with the version compiled from source (v0.10.38) and the output was:
```
run on thread 0
starting on thread 0
run on thread 1
run on thread 2
starting on thread 2
starting on thread 1
run on thread 3
starting on thread 3
```

**Comment by ktrzeciaknubisa** [comment]
Oh, yes, there are multiple improvements made (also on tasks) since that version. 

BTW. the version number you mention is a version of forked node (probably read by `jx -v`). JXcore has its own versioning `jx -jxv`. I assume that what you mean by v0.10.32 (-v) is JXcore 2.3.7 (-jxv). That would explain much, why your code behaved as you described.

**Comment by zamb3zi** [comment]
That's right, it was `jx -jxv = v Beta-0.2.3.7`.
Everything is working great with an up-to-date build, thanks.
