### ISSUE TITLE
'message' from process.sendToMain(param) problems

### ISSUE THREAD

**Issue by thuanduong** [jxcore/jxcore#293]
Hi,
I'm trying to create a Server with database, and i can't understand this: 
- i have a method, it will send a message to main thread whenever it's called, example:
```javascript
var taskcall = {
	define: function(){
		console.log("define");
	},
	logic : function(param){
		console.log("logic ", param);
		process.sendToMain(param);
		process.release();		
	}
};
```
- When a Client sends request, Server will add the method to tasks and wait until Main Thread receive a message sent from sub-thread
```javascript
// json is parameter 
jxcore.tasks.addTask(taskcall, json);
jxcore.tasks.on("message", function(threadId, obj){
	console.log("ee ", obj);
	console.log("threadId ", threadId);
});
jxcore.tasks.on('emptyQueue', function () {
	console.log('all of the added tasks have been processed');
});
```
And when i run Server
-  input :
```javascript
jxcore.tasks.addTask(taskcall, { name: "zero", password: "123", type: "2" }); 
jxcore.tasks.addTask(taskcall, { name: "iris", password: "123", type: "2" }); 
jxcore.tasks.addTask(taskcall, { name: "admin", password: "123", type: "2" }); 
jxcore.tasks.addTask(taskcall, { name: "root", password: "123", type: "2" }); 
```
- output: 
![output](https://cloud.githubusercontent.com/assets/11506321/7131358/83167516-e2a8-11e4-9ff5-609bdfab65a7.png)

The Problem is : whenever i add a new task, Main thread will receive more messages but there is only one process run. 
 - 1st task will recv 1 message
 - 2nd task will recv 2 messages
 - 3rd task will recv 3 messages 
 - 4th task will recv 4 messages

What i want is the main thread only recv 1 message when a task is processed. 

Please help me. 
Thanks

**Comment by ktrzeciaknubisa** [comment]
From the snippets you posted I don't observe the same behavior. 

Are you sure, that you don't subscribe to `jxcore.tasks.on("message")` more than once? I'm asking, because in fact I **was able** to reproduce exactly the same output as yours, but only with a code which contains conceptual mistake, which is multiple subscribing to `on('message')` in return callback of each task, like so:

```js
var taskcall = {
  define: function(){
    console.log("define");
  },
  logic : function(param){
    console.log("logic ", param);
    process.sendToMain(param);
    process.release();
  }
};


var subscribe = function() {
  jxcore.tasks.on("message", function(threadId, obj){
    console.log("ee ", obj);
    console.log("threadId ", threadId);
  });
};

subscribe();

jxcore.tasks.addTask(taskcall, { name: "zero", password: "123", type: "2" }, subscribe);
jxcore.tasks.addTask(taskcall, { name: "iris", password: "123", type: "2" }, subscribe);
jxcore.tasks.addTask(taskcall, { name: "admin", password: "123", type: "2" }, subscribe);
jxcore.tasks.addTask(taskcall, { name: "root", password: "123", type: "2" }, subscribe);
```

**Comment by thuanduong** [comment]
Thank you so much, that was what i did, i called it everytime i add new task. Sorry for my stupidity.

**Comment by ktrzeciaknubisa** [comment]
Oh, don't be too harsh for yourself :) I'm glad that I could help:) 

And thanks for using JXcore!
