### ISSUE TITLE
PLESK - error raised: Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#294]
When I start my sailsjs app I'm getting the following error in my logs. 

```
error raised: Error: listen EADDRINUSE

Server doesn't seem to be starting.

Troubleshooting tips:

 -> Is something else already running on port 10000 ?
```

The app does actually run but I'd like to resolve this.

**Comment by ktrzeciaknubisa** [comment]
Hi Marcus. Do you remember our previous conversation #169? It was also related to sails app. Can you check if [removing flashsocket works](https://github.com/jxcore/jxcore/issues/169#issuecomment-73204862) as it did last time?

**Comment by dottodot** [comment]
Just checked my setup and that has already been removed.

**Comment by dottodot** [comment]
Restarting jxcore fixed this issue.

**Comment by ktrzeciaknubisa** [comment]
Which extension version are you using?

**Comment by dottodot** [comment]
0.2.5 release 1

**Comment by ktrzeciaknubisa** [comment]
All right, that's the newest one.
