### ISSUE TITLE
Android JXCore Example Resolves Internal File Names Improperly

### ISSUE THREAD

**Issue by DLLarson** [jxcore/jxcore#298]
I've been struggling to get our Express node.js app running in the Android example app (old news by now ;)). The example has problems synthesizing names. When `main.js` calls `require('server/app.js')` the first file queried from the JNI file mapping code is `server/app.js/package.json`. For some reason the `app.js` is assumed to be a directory.

I've captured the situation in the following screen shot:

![jxcore-android-path-error-20150414](https://cloud.githubusercontent.com/assets/175455/7144596/384bbcfe-e2ac-11e4-85ab-1ff4722ca79e.png)

Of course the file doesn't exist so my application won't launch.

I've created a simple reproduction here on branch `mapgw-bug` in my forked android example:

https://github.com/DLLarson/jxcore-android-basics/tree/mapgw-bug

-Dale

**Comment by obastemur** [comment]
I've reproduced the problem and improving this part. Thanks for the details

**Comment by obastemur** [comment]
I've just realized that you removed jxcore folder from the assets and trying to reach directly to server folder. The whole sample assumes everything jxcore node.js related are located under assets/jxcore folder. i.e. -> [check this piece of code](https://github.com/DLLarson/jxcore-android-basics/blob/droidwork/jxcore-droid/src/com/nubisa/jxcore/MainActivity.java#L117) 

So, the application is not able to find the source files. One other problem is that you reach 'process.stderr' from app.js. There is no 'process.stderr' available for a mobile platform.  console.error is the only 'error' access to LogCat on Android or console output on iOS.

I don't see anything else here. If you move server folder under jxcore folder, it should be fine. If you don't want to use 'jxcore' main folder, there you should replace the references inside the Java files and main.js.

**Comment by DLLarson** [comment]
I had accounted for this here:

https://github.com/DLLarson/jxcore-android-basics/blob/mapgw-bug/jxcore-droid/src/com/nubisa/jxcore/MainActivity.java

I had other problems when rooting the application in `assets/jxcore` and the whole scheme appeared otherwise arbitrary so I'm reducing the problem space to its essentials. 

I see no reason that it shouldn't work except it's not.

Please have a closer look at the pipeline in my bug repo if you can. 

-Dale

**Comment by obastemur** [comment]
I see, my bad. But, It works without a problem if you just locate the server folder under jxcore.

**Comment by DLLarson** [comment]
>But, It works without a problem if you just locate the server folder under jxcore.

It does but our code doesn't work. It gets confused with paths so I reduced it down to this to understand the problem.

I had problems with paths like this (LogCat):

```
04-16 07:28:17.496: D/jxcore_app_log(2381): JniHelper::setJavaVM(0xb4681200), pthread_self() = -1216904864
04-16 07:28:25.789: W/jxcore-log(2381): Initializing JXcore engine
04-16 07:28:25.789: W/jxcore-log(2381): JXcore engine is ready
04-16 07:28:31.210: W/jxcore-log(2381): Starting JXcore engine
04-16 07:28:31.202: W/m.nubisa.jxcore(2381): type=1400 audit(0.0:17): avc: denied { ioctl } for path="socket:[2944]" dev="sockfs" ino=2944 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_dgram_socket permissive=0
04-16 07:28:31.202: W/m.nubisa.jxcore(2381): type=1400 audit(0.0:18): avc: denied { ioctl } for path="socket:[3187]" dev="sockfs" ino=3187 scontext=u:r:untrusted_app:s0 tcontext=u:r:zygote:s0 tclass=unix_dgram_socket permissive=0
04-16 07:28:31.202: W/m.nubisa.jxcore(2381): type=1400 audit(0.0:19): avc: denied { ioctl } for path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=29 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0
04-16 07:28:31.202: W/m.nubisa.jxcore(2381): type=1400 audit(0.0:20): avc: denied { ioctl } for path="socket:[9367]" dev="sockfs" ino=9367 scontext=u:r:untrusted_app:s0 tcontext=u:r:su:s0 tclass=unix_stream_socket permissive=0
04-16 07:28:31.793: E/jxcore-log(2381): fs.js:688
04-16 07:28:31.793: E/jxcore-log(2381):   return binding.readdir(pathModule._makeLong(path));
04-16 07:28:31.795: E/jxcore-log(2381): Error: ENOENT, no such file or directory './shared/schemas' <<===== This does exist!
04-16 07:28:31.795: E/jxcore-log(2381):     at Object.fs.readdirSync (fs.js:688:18)
04-16 07:28:31.795: E/jxcore-log(2381):     at readdirSyncRecursive (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/wrench/lib/wrench.js:37:23)
04-16 07:28:31.795: E/jxcore-log(2381):     at Object.exports.readdirSyncRecursive (/data/data/com.nubisa.jxcore/files/jxcore/node_modules/wrench/lib/wrench.js:51:20)
04-16 07:28:31.795: E/jxcore-log(2381):     at module.exports (/data/data/com.nubisa.jxcore/files/jxcore/shared/schemas/index.js:16:30)
04-16 07:28:31.795: E/jxcore-log(2381):     at Object.<anonymous> (/data/data/com.nubisa.jxcore/files/jxcore/server/lib/schemavalidator/index.js:8:57)
04-16 07:28:31.795: E/jxcore-log(2381):     at Module._compile (module.js:519:26)
04-16 07:28:31.795: E/jxcore-log(2381):     at Object.Module._extensions..js (module.js:549:10)
04-16 07:28:31.795: E/jxcore-log(2381):     at Module.load (module.js:346:36)
04-16 07:28:31.795: E/jxcore-log(2381):     at Function.Module._load (module.js:313:12)
04-16 07:28:31.795: E/jxcore-log(2381):     at Module.require (module.js:378:17)
04-16 07:28:31.795: E/jxcore-log(2381): Error: EROFS, open 'tangerine.log'
04-16 07:28:31.796: E/jxcore-log(2381): events.js:55
04-16 07:28:31.796: E/jxcore-log(2381):         throw arg1; // Unhandled 'error' event
04-16 07:28:31.796: E/jxcore-log(2381): Error: EROFS, open 'socketio.log'
04-16 07:28:31.796: E/jxcore-log(2381): Error: EROFS, open 'userservice.log'
04-16 07:28:31.796: E/jxcore-log(2381): events.js:55
04-16 07:28:31.796: E/jxcore-log(2381):         throw arg1; // Unhandled 'error' event
04-16 07:28:31.796: E/jxcore-log(2381): Error: EROFS, open 'branding'
04-16 07:28:31.796: E/jxcore-log(2381): Error: EROFS, open 'oreconnection'
04-16 07:28:31.796: W/jxcore-log(2381): JXcore engine is started
```

(I also ran into problems opening write-able files in the same file-space but that's another issue.)

What I'm hearing from your response that `jxcore` as the root of the site is the design moving forward?

-Dale

**Comment by obastemur** [comment]
`What I'm hearing from your response that jxcore as the root of the site is the design moving forward?`
No. The sample project was designed that way. 

`(I also ran into problems opening write-able files in the same file-space but that's another issue.)`
I'm working on this to see If we can virtually show the APK contents under user documents folder. So it wouldn't be a problem to write a file there. Indeed, we need fs extensions supporting write operations. 

`I had problems with paths like this (LogCat):`
If by any chance you can narrow down the issue to something I can play with, it could be a life saver.

**Comment by DLLarson** [comment]
>I'm working on this to see If we can virtually show the APK contents under user documents 
>folder. So it wouldn't be a problem to write a file there. Indeed, we need fs extensions 
>supporting write operations.

It kinda needs a copy-on-write idea since the initial file content may need to be read from the APK.

>If by any chance you can narrow down the issue to something I can play with, it could be a life saver.

I'll see what I can strip it down to..

-Dale

**Comment by obastemur** [comment]
[JXcore cordova plugin for Android](https://github.com/jxcore/jxcore-cordova) is ready. Please see if this issue is fixed there.

**Comment by DLLarson** [comment]
I'll do that!

Dale

**Comment by DLLarson** [comment]
See: jxcore/jxcore-cordova/issues/10

-Dale

**Comment by obastemur** [comment]
I belive this is no longer an issue.
