### ISSUE TITLE
SM: process.on('exit') not always called for mt-keep

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#300]
The code below does not always call `process.on('exit')`:

```js
if (process.subThread)
  process.release();

process.on("exit", function (code) {
    jxcore.utils.console.write("ok", process.threadId, " ");
});
```
This comes visible when running the test in a loop (with `mt-keep`):

```bash
for i in {1..10}; do printf "$i:"; jx mt-keep test.js; printf "\n"; done
1:ok 0  ok 1  
2:ok 1  ok 0  
3:
4:ok 0  ok 1  
5:ok 0  ok 1  
6:ok 0  ok 1  
7:ok 1  ok 0  
8:
9:ok 1  ok 0  
10:ok 1  ok 0  
```
3 and 8 has no output. I saw it on Ubuntu and Suse (both x64).

**Comment by obastemur** [comment]
Process.on(exit) is not guaranteed for sub threads when the main process starts closing everything. We may improve this in the future though but there are many edge cases where process.onExit is a headache. I can say that we don't support this entirely at the very moment. 

It might be behaving much better on previous version but it wasn't intentionally. 

Reason:
Thread 1 goes off, and Thread 2 spends more time somehow on process.onExit. While threads are designed to recover back, Thread 1 comes back and gives another onExit.. On the main thread level, we know when everything else start destructing but we don't know if there was a timer / async operation may keep main thread for a while and that async operation depends something from another thread...

So, once the main thread goes off, we don't care about the sub thread events anymore.

**Comment by ktrzeciaknubisa** [comment]
Would be it some idea to introduce e.g. `process.on('exitMain)` for `mt`/`mt-keep` processes? Or maybe better: to make `process.on('exit')` to be invoked only by a main thread, since we cannot rely on sub threads? Just thinking...
