### ISSUE TITLE
 EADDRINUSE issue when run compiled package

### ISSUE THREAD

**Issue by ArifRathod** [jxcore/jxcore#302]
step 1- i make an sample node app which is run on some port using express

step2 :- jx package index.js hello world -native  
using this command turn into executable package

step 3: - if i run this in node using child process from another node app
here is the code snnipet: -

    var exec = require('child_process').exec;
    var command = "./hello world
    var child = exec(command);
    child.stdout.on('data', function (data) {
    });
    child.stderr.on('data', function (data) {
    });
    child.on('close', function (code) {
    });

step 4: - if i this executable package from another node app using child process then its run every time 
so thats why its give me error= " EADDRINUSE, Address already in use - Kill server "

**Comment by ktrzeciaknubisa** [comment]
If you call exec("./helloworld") few times, then it is expected, that each of this instance would want to create its own http server. But only one server can be running on one specific port, so that's why it fails for other instances.

If I didn't understand your point exactly, could you highlight the problem?

**Comment by ktrzeciaknubisa** [comment]
Or perhaps you mean, that you're calling the second `exec("./helloworld")` after the first one was supposed to be closed/terminated?

**Comment by ArifRathod** [comment]
Or perhaps you mean, that you're calling the second exec("./helloworld") after
the first one was supposed to be closed/terminated?

yes its not terminate when i am calling second time ,child process doesnt
emit close/exist event when i am using executables package

so thats why its gives everytime EADDERINUSE error

how to prevent this......

On Thu, Apr 16, 2015 at 3:34 PM, Krzysztof Trzeciak <
notifications@github.com> wrote:

> Or perhaps you mean, that you're calling the second exec("./helloworld")
> after the first one was supposed to be closed/terminated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93698256>.
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ktrzeciaknubisa** [comment]
But you **are** exiting from inside executable package, e.g. by calling `process.exit()`, right? Because if you leave *./helloworld* running without explicit exit, child process has no reason to terminate it.

**Comment by ArifRathod** [comment]
1) i just create one node app
2) convert that node app into executable package using jxcore..
3) now run that executables package from another node app which is gives
some output

 so executables package loads everytime while i am calling that
./helloworld from another node App using node child process
so thats why its give me EADDRINUSE error

let me know ,if you are not understand my point now exactly,


On Thu, Apr 16, 2015 at 5:05 PM, Arif Rathod <arifrathod7@gmail.com> wrote:

> Or perhaps you mean, that you're calling the second exec("./helloworld") after
> the first one was supposed to be closed/terminated?
>
> yes its not terminate when i am calling second time ,child process doesnt
> emit close/exist event when i am using executables package
>
> so thats why its gives everytime EADDERINUSE error
>
> how to prevent this......
>
> On Thu, Apr 16, 2015 at 3:34 PM, Krzysztof Trzeciak <
> notifications@github.com> wrote:
>
>> Or perhaps you mean, that you're calling the second exec("./helloworld")
>> after the first one was supposed to be closed/terminated?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93698256>.
>>
>
>
>
> --
>  <https://www.freelancer.in/affiliates/email/7415991/>
> Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>
>
> FullStack javascript Developer with MEAN.IO
>
> *M:* 9978350327
>
> *E:* arifrathod7@gmail.com
> *A:*
>
> 419/1,sector=13-A, Gandhinagar, 382016, IN
>  Hire me on Freelancer.com
> <https://www.freelancer.in/affiliates/email/7415991/>
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ArifRathod** [comment]
if i am using executable package then its not fire process.exit()


On Thu, Apr 16, 2015 at 5:12 PM, Arif Rathod <arifrathod7@gmail.com> wrote:

> 1) i just create one node app
> 2) convert that node app into executable package using jxcore..
> 3) now run that executables package from another node app which is gives
> some output
>
>  so executables package loads everytime while i am calling that
> ./helloworld from another node App using node child process
> so thats why its give me EADDRINUSE error
>
> let me know ,if you are not understand my point now exactly,
>
>
> On Thu, Apr 16, 2015 at 5:05 PM, Arif Rathod <arifrathod7@gmail.com>
> wrote:
>
>> Or perhaps you mean, that you're calling the second exec("./helloworld") after
>> the first one was supposed to be closed/terminated?
>>
>> yes its not terminate when i am calling second time ,child process doesnt
>> emit close/exist event when i am using executables package
>>
>> so thats why its gives everytime EADDERINUSE error
>>
>> how to prevent this......
>>
>> On Thu, Apr 16, 2015 at 3:34 PM, Krzysztof Trzeciak <
>> notifications@github.com> wrote:
>>
>>> Or perhaps you mean, that you're calling the second exec("./helloworld")
>>> after the first one was supposed to be closed/terminated?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93698256>.
>>>
>>
>>
>>
>> --
>>  <https://www.freelancer.in/affiliates/email/7415991/>
>> Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>
>>
>> FullStack javascript Developer with MEAN.IO
>>
>> *M:* 9978350327
>>
>> *E:* arifrathod7@gmail.com
>> *A:*
>>
>> 419/1,sector=13-A, Gandhinagar, 382016, IN
>>  Hire me on Freelancer.com
>> <https://www.freelancer.in/affiliates/email/7415991/>
>>
>
>
>
> --
>  <https://www.freelancer.in/affiliates/email/7415991/>
> Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>
>
> FullStack javascript Developer with MEAN.IO
>
> *M:* 9978350327
>
> *E:* arifrathod7@gmail.com
> *A:*
>
> 419/1,sector=13-A, Gandhinagar, 382016, IN
>  Hire me on Freelancer.com
> <https://www.freelancer.in/affiliates/email/7415991/>
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ktrzeciaknubisa** [comment]
Did you try to run this executable package from the shell, like below?

```bash
$ ./helloworld
```

Does it ever exits back to the shell?

**Comment by ArifRathod** [comment]
yes i checked there ,its works in shell

On Thu, Apr 16, 2015 at 5:40 PM, Krzysztof Trzeciak <
notifications@github.com> wrote:

> Did you try to run this executable package from the shell, like below?
>
> $ ./helloworld
>
> Does it ever exits back to the shell?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93718733>.
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

On Thu, Apr 16, 2015 at 5:40 PM, Krzysztof Trzeciak <
notifications@github.com> wrote:

> Did you try to run this executable package from the shell, like below?
>
> $ ./helloworld
>
> Does it ever exits back to the shell?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93718733>.
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ktrzeciaknubisa** [comment]
Thanks, but I'm asking whether it exits back to the shell (process terminates) or not?

**Comment by ArifRathod** [comment]
no process not terminated in this ...process not terminated even new
request comes then its run again

On Fri, Apr 17, 2015 at 2:03 PM, Krzysztof Trzeciak <
notifications@github.com> wrote:

> Thanks, but I'm asking whether it exits back to the shell (process
> terminates) or not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93943420>.
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ktrzeciaknubisa** [comment]
So that's clear. If your `./helloworld` never exits (does not terminate as you said), when you try to `exec()` it again - it throws EADDERINUSE.  

What you need to do is to exit from your `./helloworld,` for example by calling `process.exit()`.

**Comment by ArifRathod** [comment]
after some changes in process calling function and using process.exit() in
child process of node ...its works fine for me and that "EADDERINUSE" error
solved now for me....

thanks Krzysztof Trzeciak



On Fri, Apr 17, 2015 at 3:00 PM, Krzysztof Trzeciak <
notifications@github.com> wrote:

> So that's clear. If your ./helloworld never exits (does not terminate as
> you said), when you try to exec() it again - it throws EADDERINUSE.
>
> What you need to do is to exit from your ./helloworld, for example by
> calling process.exit().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/302#issuecomment-93952114>.
>



-- 
 <https://www.freelancer.in/affiliates/email/7415991/>
Arif Aathod <https://www.freelancer.in/affiliates/email/7415991/>

FullStack javascript Developer with MEAN.IO

*M:* 9978350327

*E:* arifrathod7@gmail.com
*A:*

419/1,sector=13-A, Gandhinagar, 382016, IN
 Hire me on Freelancer.com
<https://www.freelancer.in/affiliates/email/7415991/>

**Comment by ktrzeciaknubisa** [comment]
Thanks! I'm glad, that I could help!
