### ISSUE TITLE
Error LNK2001 while installing node-canvas

### ISSUE THREAD

**Issue by liebig** [jxcore/jxcore#303]
I am trying to install the great [node-canvas library](https://github.com/Automattic/node-canvas) but I am getting the error `error LNK2001: Nicht aufgelöstes externes Symbol ""`. I know that this library is difficult to install and it needs a global installation of node-gyp, Python 2.7 for Windows, Microsoft Visual C++ 2010 and GTK. But everything is installed and when I use `npm install canvas` instead of `jx install canvas` everything works great.

I am running Windows 7 (x64) and here is the stack trace:
```
Canvas.obj : error LNK2001: Nicht aufgelöstes externes Symbol ""__declspec(dllim
port) public: static class node::Buffer * __cdecl node::Buffer::New(char const *
,unsigned __int64,class node::commons *)" (__imp_?New@Buffer@node@@SAPEAV12@PEBD
_KPEAVcommons@2@@Z)". [D:\canvas\node_modules\canvas\build\canvas.vcxproj]
D:\canvas\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 1 nicht aufgelöste Externe [D:\canvas\node_modules\canvas\build\canvas.vcxproj]
gypnpm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "jx" "D:\\Users\\U519642\\.jx\\npm" "install" "canvas"
npm ERR! cwd D:\canvas\jxcore
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm
D:\canvas\jxcore>jx install canvas > output.txt
npm WARN package.json gameboy@0.2.0 No repository field.
gypnpm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "jx" "D:\\Users\\U519642\\.jx\\npm" "install" "canvas"
npm ERR! cwd D:\canvas\jxcore
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm
```

`jx -v`: `v0.10.38`
`jx -jxv`: `v Beta-0.3.0.0`

`node -v`: `v0.10.28`
`npm -v`: `1.4.9`

I don't know if you can help me with this, because it could be a problem with the node-canvas library. But I want to give it a try.

Thank you,
Marc

**Comment by ktrzeciaknubisa** [comment]
Thanks, I was able to reproduce the problem and we will see into that.

**Comment by obastemur** [comment]
Windows lib files under jxb300 were not updated. That's the reason for the error. I'm going to update them a.s.a.p. and update the thread.

**Comment by obastemur** [comment]
I've updated the jxb300. In order to retry, please delete the jxb300 folder under `Users\<Your Username>\.node-gyp\` On your next call to `jx install` it will download the updated one.

Please let me know if it works after this update.

**Comment by liebig** [comment]
I tested this and I am able install the canvas package now. Thank you again for your awesome support. But I have another question. How can I make a package file with this external Canvas library included? I ran `jx package canvas.js "Canvas"` and tried to start the compiled file with `jx Canvas.jx` but I am getting this error message:
```
    , canvas = new Canvas(200,200)
               ^
TypeError: object is not a function
    at Object.<anonymous> (D:\canvas\jxcore\canvas.js.jx:7:16)
    at Module._compile (module.js:519:26)
    at readX (module.js:1235:5)
    at Object.Module._extensions..jx (module.js:1653:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:378:18)
    at node.js:2352:3
```

canvas.js
```javascript
console.log("Start");

var Canvas = require('canvas')
    , Image = Canvas.Image
    , canvas = new Canvas(200,200)
    , ctx = canvas.getContext('2d');

ctx.font = '30px Impact';
ctx.rotate(.1);
ctx.fillText("Awesome!", 50, 100);

var te = ctx.measureText('Awesome!');
ctx.strokeStyle = 'rgba(0,0,0,0.5)';
ctx.beginPath();
ctx.lineTo(50, 102);
ctx.lineTo(50 + te.width, 102);
ctx.stroke();

console.log('<img src="' + canvas.toDataURL() + '" />');
```

Thank you,
Marc

**Comment by ktrzeciaknubisa** [comment]
@liebig Interesting, since I've got a different output with jx 0.3.0.0:

```bash
Start

fs.js:740
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\jxcore\tmp\canvas2\node_modules'
    at Object.fs.lstatSync (fs.js:740:18)
    at Object.realpathSync (fs.js:1357:21)
    at tryFile (module.js:119:15)
    at tryExtensions (module.js:127:20)
    at Function.Module._findPath (module.js:162:20)
    at Function.Module._oldRes (module.js:684:25)
    at Function.Module._resolveFilename (module.js:1535:17)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
```
This will be taken care of.

However it looks, like you were using jx 2.3.7 for canvas packaging/running, because only then I get the exact output as yours.

**Comment by liebig** [comment]
I downloaded the master branch today and built it from sources:
`jx -v`: `v0.10.38`
`jx -jxv`: `v Beta-0.3.0.0`

Your output with `jx 0.3.0.0` looks better because it prints `Start`. So the Canvas module was found.

**Comment by ktrzeciaknubisa** [comment]
> Your output with jx 0.3.0.0 looks better because it prints Start. So the Canvas module was found.

Not really. "Start" gets printed before `require('canvas')` :)

**Comment by liebig** [comment]
Ehm, yes, you are right :)

**Comment by ktrzeciaknubisa** [comment]
All right. There are few problems stacking here. 

@liebig Can you please check again, if the package was compiled against v0.3.0.0 (e.g. by calling `console.log(process.jxversion)` before "Start" ? I'd like to make sure, that we don't talk about the following error:

```
    , canvas = new Canvas(200,200)
               ^
TypeError: object is not a function
```

#### Now:

1. It looks like `require("canvas")` works after all: the *node_modules\canvas\lib\canvas.js* file gets loaded and the error `Error: ENOENT, no such file or directory 'C:\jxcore\tmp\canvas2\node_modules'` comes later. I've just described it here: #304;
2. Once we get through the 1. error (e.g. by creating *node_modules/dummy.txt* and repacking the app), there is another problem:

```bash
node.js:706
    var gpath = process._dlopen(module, filename);
                        ^
Error: The specified module could not be found.
c:\jxcore\tmp\canvas2\node_modules\canvas\build\release\canvas.node
    at Object.process.dlopen [as .node] (node.js:706:25)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
```
It's about *.node* file. You surely had a warning while creating a package:
```bash
Warning! ....es\canvas\build\Release\canvas.node
Adding a .node (native) file into package may fail the application
Check the related discussion from https://github.com/jxcore/jxcore/issues/101
```
It's here #101 and here #140. As far as I know nothing changed in that matter. @obastemur ?

**Comment by liebig** [comment]
Okay, I added `console.log(process.jxversion);` to the head of `canvas.js` and I separate node_modules folder from the package via `jx package canvas.js "Canvas" -slim node_modules`. But I am still facing the error `TypeError: object is not a function`.

`jx install canvas`
```
> canvas@1.2.1 install D:\canvas\node_modules\canvas
> node-gyp rebuild
...
canvas@1.2.1 node_modules\canvas
└── nan@1.5.3
```

`jx package canvas.js "Canvas" -slim node_modules`
```
Processing the folder..
JXP project file (Canvas.jxp) is ready.

preparing the JX file..
Compiling Canvas 1.0
adding script canvas.js
[OK] compiled file is ready (Canvas.jx)
```

`jx Canvas.jx`
```
v Beta-0.3.0.0
Start

D:\canvas\canvas.js.jx:8
    , canvas = new Canvas(200,200)
               ^
TypeError: object is not a function
    at Object.<anonymous> (D:\Privat\canvas\canvas.js.jx:8:16)
    at Module._compile (module.js:519:26)
    at readX (module.js:1235:5)
    at Object.Module._extensions..jx (module.js:1653:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:378:18)
    at node.js:2352:3

```

**Comment by liebig** [comment]
Ah okay, I found the error: it is a name conflict! Don't name the js or jx file like the library:
`jx package canv.js "Canv"`

```
Compiling Canv 1.0
adding script canv.js
adding script node_modules\canvas\index.js
adding script node_modules\canvas\lib\bindings.js
...
adding asset node_modules\canvas\util\lib_lookup.sh
Warning! ....es\canvas\build\Release\canvas.node
Adding a .node (native) file into package may fail the application
Check the related discussion from https://github.com/jxcore/jxcore/issues/101
[OK] compiled file is ready (Canv.jx)
```

So I have to run `jx install canvas` on every system now? Because of the error:
```
node.js:706
    var gpath = process._dlopen(module, filename);
                        ^
Error: The specified module could not be found.
c:\jxcore\tmp\canvas2\node_modules\canvas\build\release\canvas.node
    at Object.process.dlopen [as .node] (node.js:706:25)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
```

**Comment by obastemur** [comment]
`So I have to run jx install canvas on every system now? Because of the error:` 

Native modules are not packable. You can use [pre-install feature](http://jxcore.com/jx-package-pre-installation-steps/)

**Comment by ktrzeciaknubisa** [comment]
> Ah okay, I found the error: it is a name conflict! Don't name the js or jx file like the library:

What do you mean? I do it most of the time and never saw a problem?

**Comment by liebig** [comment]
Thank you, I will use the pre-install feature.
@ktrzeciaknubisa: The error `TypeError: object is not a function` does only appear if the js file is called `canvas.js`:
`jx package canvas.js "canv" -slim node_modules`
```
Processing the folder..
JXP project file (canv.jxp) is ready.

preparing the JX file..
Compiling canv 1.0
adding script canvas.js
[OK] compiled file is ready (canv.jx)

```

`jx canv.jx`
```
v Beta-0.3.0.0
Start

D:\Privat\canvas\canvas.js.jx:8
    , canvas = new Canvas(200,200)
               ^
TypeError: object is not a function
    at Object.<anonymous> (D:\Privat\canvas\canvas.js.jx:8:16)
    at Module._compile (module.js:519:26)
    at readX (module.js:1235:5)
    at Object.Module._extensions..jx (module.js:1653:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:735:12)
    at startup (node.js:378:18)
    at node.js:2352:3
```

But if I rename `canvas.js` to `canv.js` it is working:
`jx package canv.js "canvas" -slim node_modules`
```
Processing the folder..
JXP project file (canvas.jxp) is ready.

preparing the JX file..
Compiling canvas 1.0
adding script canv.js
[OK] compiled file is ready (canvas.jx)

```
`jx canvas.jx`
```
v Beta-0.3.0.0
Start
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAA
....
```

So the name of the javascript file must not have the name of a used module. The name of the jx file does not matter.

So, thank you for your time, thank you for the great support. Have a nice weekend!

**Comment by ktrzeciaknubisa** [comment]
@liebig Thanks for your nice words :) Nice weekend for you too!

> The error TypeError: object is not a function does only appear if the js file is called canvas.js:

I understand now. I'm surprised however, because it was fixed some time ago. And still today I was not able to reproduce it. But I see it now.

**Comment by ktrzeciaknubisa** [comment]
All right, there shouldn't be name conflict any more when calling `require("canvas")` from inside `canvas.js` while *node_modules* stay on file system (ada3d02cd9ef319bce85dda62eb37796915d3118). 

The previous fix I was thinking about was applied to *node_modules* embedded inside a package, but this was not the case now.
