### ISSUE TITLE
Packaging: fs stat functions fail for folder not containing any file

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#304]
Let's say we have the following directory structure:

- dir1
 - dir2
   - file2.txt
- index.js

The *index.js*:
```js
var fs = require('fs');
// ok:
console.log(fs.statSync(__dirname + "/dir1/dir2/file2.txt"));

// Error: ENOENT, no such file or directory:
console.log(fs.statSync(__dirname + "/dir1"));
```
It looks like stat function fail for directory, which may contain other folders, but do not contain any file. Once we create *dir1/file1.txt*, the package runs smoothly.

**Comment by obastemur** [comment]
Similar to Android APK, we do not pack empty folders or store information for them.
