### ISSUE TITLE
Failure to load sub-package

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#305]
I'm having trouble getting `unit.js` to work with jxcore. I believe the problem is that sub-packages fail to load. To reproduce:
```
jx install unit.js
jx -p require('unit.js').should
```
This prints `undefined`. You can run the package as installed with node instead:
```
node -p require('unit.js').should
```
prints the function correctly. The relevant locally installed files are:
```
./node_modules/unit.js/src/index.js:
    22: var should         = require('should');
./node_modules/unit.js/node_modules/should/index.js
```
In case the problem was something to do with `.js` in the module name, I renamed it but the problem remains. Thanks for any help.

**Comment by obastemur** [comment]
Please let us know if it's all fine on your end. Thanks!

**Comment by zamb3zi** [comment]
Working perfectly now. Thanks!
