### ISSUE TITLE
Sample code for embedding JXCore in windows desktop application

### ISSUE THREAD

**Issue by kmgkv** [jxcore/jxcore#309]
Hi,
Is there any sample code that explains how to embed JXCore in a windows desktop application?

**Comment by obastemur** [comment]
There is Visual Studio project sample. [check this repo](https://github.com/obastemur/JXcoreWindowsEmbedded)

**Comment by kmgkv** [comment]
@obastemur thanks for sharing that.. actually I'm interesting in loading/embedding JX package in a windows desktop application... just doing require('package.jx') in JX_DefineMainFile is not working...

Keeping the JX package file in the application executable directory is not working. Do we need to use FS extension API (readFileSync, readdirSync and existsSync) like the way you have used in Android project to embed JX package?

**Comment by obastemur** [comment]
```require('./package.jx')``` ?  Can you share the the error you've received?

**Comment by kmgkv** [comment]
Initializing JXcore engine
JXcore engine is ready
Starting JXcore engine

module.js:696
    throw err;
          ^
Error: Cannot find module './sample.jx'
    at Function.Module._oldRes (module.js:694:15)
    at Function.Module._resolveFilename (module.js:1352:19)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at Object.<anonymous> (main.js:1:97)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..js (module.js:549:10)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
JXcore engine is started
Destroying JXcore engine
JXcore engine is destroyed

I have tested the same package file i.e. sample.jx on Android and iOS, it works on those two platforms

**Comment by obastemur** [comment]
Seems like you give the home folder wrong. 
```JX_Initialize(const char *home_folder, JX_CALLBACK callback);```

The first parameter you should define the home folder. Check how we do with Android and iOS samples.

**Comment by kmgkv** [comment]
@obastemur I'm passing path of the folder where application executable is present and in that folder only sample.jx is present.
For example :
If say application executable and sample.jx files are present inside D:\Code\JXCoreWinEmbedd\Debug, then I'm passing "D:\Code\ThirdParty\JXCoreWinEmbedd\Debug" to the home folder

**Comment by obastemur** [comment]
I've updated the sample project with the latest 32/64 bit binaries and tested your scenario. It works. Could you please give it a shot and let me know?

**Comment by kmgkv** [comment]
Yup, it works!
