### ISSUE TITLE
IsEmbedded / IsPackaged

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#314]
In relation to this commit: 7f671c79fa6585e9b9e7983278d80811e0947145 I would have two suggestions:

1. while `IsPackaged` is applying now to `-native` binaries, can we also have similar flag for regular jx packages? So many times I needed to know, whether a code is running from inside a jx package. For that I was using until now `if (exports.$JXP && !process.IsEmbedded)`. 

    So my suggestion is to have **two separate flags** for native and jx packages (or `IsPackaged` can have three states: `false`, `jx` and `native`).
2. I propose to stick to camelCase, since `IsEmbedded` / `IsPackaged` are the only fields in JXcore's api starting from upper case (apart from `jxcore.utils.OSInfo()`)

**Comment by obastemur** [comment]
Code running from a jx package or not is not open to outside of the package. We can't locate it to process.

commit https://github.com/jxcore/jxcore/commit/8fcd5074b9b28cfd18093670601b922731bf782a takes care of the camel casing.

**Comment by ktrzeciaknubisa** [comment]
> Code running from a jx package or not is not open to outside of the package.

"outside of the package" ? I meant using `isPackaged` **inside** of the package. From packaged code. 

Thanks for camel casing. I'll update the docs.

**Comment by obastemur** [comment]
But if we attach it to process it will be global..

**Comment by sreesharp** [comment]
@ktrzeciaknubisa @obastemur What would be the best way to detect whether a node module is executing within JXCore or not.  I need to apply patch to Winston(https://github.com/thaliproject/winston) so that the log is delivered on the console as well.  Current I have the following options to detect whether it is running in JXCore or not..  Let me know if there is any better way
1) process.isEmbedded
2) if ( typeof ‘jxcore’ !== ‘undefined’ )

**Comment by ktrzeciaknubisa** [comment]
Hi @sreesharp . I would use the second option, but without quotes on `jxcore`, that is: 
```js
if (typeof jxcore !== "undefined")
```

**Comment by plika** [comment]
Executing within JXcore on mobile(embedded) and Desktop sometimes a bit different. I would still consider using process.isEmbedded to see if it's running as part of JXcore embedded
