### ISSUE TITLE
Is JXCore package broken?

### ISSUE THREAD

**Issue by kmgkv** [jxcore/jxcore#324]
Hi,
With the latest code base, I'm not able to run a jxcore package properly. If the package contain only single file i.e. just the main.js, then it is running fine whereas if the package has multiple files, i.e. if the main.js require another module(s), then JXCore is failing to refer other module in the package.

For example : 
Say I have two files named main.js and SampleModule.js, main.js require SampleModule.js. 
I copied these two files in folder and created a JXCore package by running following command in that folder:
<b>jx.exe package main.js jxsample.jx </b>

After running jxsample.jx (<b> jx.exe jxsample.jx </b>) we are getting following errors:
<b>
module.js:697
    throw err;
          ^
Error: Cannot find module 'SampleModule'
    at Function.Module._oldRes (module.js:695:15)
    at Function.Module._resolveFilename (module.js:1544:17)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at Object.<anonymous> (filepath where main.js and SampleModule.js was kept\main.js.jx:6:19)
    at Module._compile (module.js:519:26)
    at readX (module.js:1236:5)
    at Object.Module._extensions..jx (module.js:1662:10)
    at Module.load (module.js:346:36)
    </b>
Getting the same error even if we embed the JXCore engine in standalone app! 
With code earlier, I was able to run the same package successfully, both in standalone as well as embedded application.

<h3>main.js and SampleModule.js code</h3>
<b>main.js</b>
console.log("testing embedded modules");
// Using SampleModule
var Logger      = require('SampleModule').Logger,
    // Our custom module expose a concat function
    concatFun   = require('SampleModule').concat;

// Creating and invoking Logger
var objLog = new Logger("main.js");
objLog.log('Hello world sample log');

// Invoking concat function
var left    = "Hello ",
    right   = "World !",
    cnct    = "";
cnct = concatFun(left, right);
objLog.log('String concat returns : ' + cnct);

<b>SampleModule.js</b>
// Example module that expose a logger
function LogWrapper(name) {
    if (!(this instanceof LogWrapper))
        return new LogWrapper(name);
    this.name = name;
}

// Methods for the module
LogWrapper.prototype.log = function(msg) {
    console.log("[" + this.name + "]:" + msg);
};

// Exporting LogWrapper class with name Logger
module.exports.Logger = LogWrapper;

// Exporting a test concatentate function
module.exports.concat = function(left, right) {
    return left+""+right+"";
};

<b>JXCore Version</b>
jx -jxv
v Beta-0.3.0.0
jx -v
v0.10.38

**Comment by obastemur** [comment]
FYI; this scenario doesn't work even if you don't package it. You should however require SampleModule.js file using i.e. require('./SampleModule.js')

When you do this update, it works for both packaged and plain.

**Comment by kmgkv** [comment]
@obastemur yup, thanks.. it worked...just read about it here http://jxcore.com/docs/jxcore-feature-packaging-code-protection.html, though I'm not sure why with earlier build it works even without './' prefix..
