### ISSUE TITLE
Android 5 PIE enforcement

### ISSUE THREAD

**Issue by dcerisano** [jxcore/jxcore#327]
Just tried to run the jx_androidARMsm on Android 5.1
Got the following:
``error: only position independent executables (PIE) are supported.``
Any advice?

**Comment by ktrzeciaknubisa** [comment]
We've just added Android 5 binaries to the [downloads](http://jxcore.com/downloads/), so you might want to check it. Please let us know about the result.

**Comment by obastemur** [comment]
closing this since I've tested it on multiple 5.0 and 5.1 devices. @dcerisano feel free to open it back if you think it's not resolved.

**Comment by dcerisano** [comment]
Thanks for the amazing response on this. I must have posted just as you were uploading the new files.
I am going to try to use jxcore to do some "mad science" and will let you know how it goes.
Thanks again.
