### ISSUE TITLE
How to use mycppextend.node in compile native binary

### ISSUE THREAD

**Issue by qq188818520** [jxcore/jxcore#328]
as title said.  I make a nodejs proj witch used to tcp game logic server, in the proj ，I use nodejs cpp extend encapsulate some calculate into mycppextend.node, But I make a native binary according to jx tutorials , it failed. If I get rid of the part of mycppextend.node in code ，it's ok. so who can tell me how to solve this problem。（excuse me，my eg is poor）

**Comment by ktrzeciaknubisa** [comment]
Please correct me if I don't get this right: are trying to embed *.node* file inside jx package created with `-native` option?

**Comment by qq188818520** [comment]
I just enter cmd “ jx compile app.jxp -native”  ，it‘s failed(the .exe execute failed,because app cannot find mycppextend.node )， but how to embed ./node inside jx package

**Comment by qq188818520** [comment]
thank for your help , I solve it

**Comment by ktrzeciaknubisa** [comment]
Could you write few words what was your solution, so the other users in future might benefit from it?

**Comment by qq188818520** [comment]
ok， I just be Misguided by compile info, it tips " Adding a .node <native> file into package may fail the application", when it tips I remove my xxx.node  from "assets". But It's wrong。so I ignore the tips, and the .exe is ok!
