### ISSUE TITLE
Android fails on require jx module

### ISSUE THREAD

**Issue by edwinvanderham** [jxcore/jxcore#331]
When I try to load a packaged jx module from a javascript file inside a cordova application with the jxcore-cordova plugin, I see the following error message:

Package is either corrupted or not compatible with this JX binary

example app.js:
```javascript
var msg = require('mymodule.js');
cordova('log').call(msg());
```
example mymodule.js:
```javascript
module.exports = function() {
	return 'Hello android';
}
```

This example works fine when I use the raw mymodule.js. But when I compile mymodule using
```jx package mymodule.js -add```
and include the mymodule.jx file instead of the js file, I get the error message stated above.

05-07 16:07:23.042  29027-29082/io.cordova.hellocordova E/jxcore-log﹕ Package is either corrupted or not compatible with this JX binary. (/data/data/io.cordova.hellocordova/files/mymodule.jx)
05-07 16:07:23.042  29027-29082/io.cordova.hellocordova E/jxcore-log﹕ (module.js 1655:14)
05-07 16:07:23.042  29027-29082/io.cordova.hellocordova E/jxcore-log﹕ at Module._extensions[".jx"] (module.js:1655:15)
            at Module.prototype.load (module.js:346:7)
            at Module._load (module.js:313:5)
            at Module.prototype.require (module.js:378:10)
            at require (module.js:396:12)
            at /data/data/io.cordova.hellocordova/files/app.js:14:14
            at cordova.executeJSON (main.js:122:12)
            at JX_Evaluate:1:1

**Comment by plika** [comment]
The reason is that you have a previous jxcore version is installed on your system. Probably 2.3.7 and using the jx package with latest JXcore on Android. update JXcore to latest from our [downloads page](http://jxcore.com/downloads) 

Feel free to close this issue if it's solved after the update.

**Comment by ktrzeciaknubisa** [comment]
I thought similar and so I was trying the same scenario with jx package created by JXcore 0.3.0.0 and I got the same result as @edwinvanderham . Anyway I didn't figure out how to replace jxcore internal binaries for android app. The *jxcore-cordova/io.jxcore.node/bin* seems relevant only for iOS.

**Comment by obastemur** [comment]
@plika can you track down this problem and fix it?

**Comment by edwinvanderham** [comment]
I did use the lastest jxcore binaries (0.3.0.0). I tried with both the V8 version and the SpiderMonkey version. I can successfully require the jx module from a plain text js file in the standalone node runner.

@ktrzeciaknubisa I don't think you can easily replace the android jxcore binaries. The included .so files are the result of a JNI compilation and the source code is not included in the plugin itself.

**Comment by plika** [comment]
@ktrzeciaknubisa @edwinvanderham source codes are there. 

If you have android ndk tools is installed,  steps are easy;

- update .a and .h files under jxcore-binaries folder (io.jxcore.node/src/android)
- call 'ndk-build' (it's actually located under android-ndk)

There you have the .so files are recompiled.

**Comment by ktrzeciaknubisa** [comment]
Thanks @plika 

I was able to recompile .so files by calling `ndk-build` but the trick was to find out from which folder should I run it. So the below worked for me:

```bash
$ cd jxcore-cordova/io.jxcore.node/src/android/jni
$ ~/android-ndk/ndk-build
[armeabi] Compile++ thumb: jxcore <= JniHelper.cpp
[armeabi] Compile++ thumb: jxcore <= jxcore.cpp
[armeabi] SharedLibrary  : libjxcore.so
[armeabi] Install        : libjxcore.so => libs/armeabi/libjxcore.so
[armeabi-v7a] Compile++ thumb: jxcore <= JniHelper.cpp
[armeabi-v7a] Compile++ thumb: jxcore <= jxcore.cpp
[armeabi-v7a] SharedLibrary  : libjxcore.so
[armeabi-v7a] Install        : libjxcore.so => libs/armeabi-v7a/libjxcore.so
[x86] Compile++      : jxcore <= JniHelper.cpp
[x86] Compile++      : jxcore <= jxcore.cpp
[x86] SharedLibrary  : libjxcore.so
[x86] Install        : libjxcore.so => libs/x86/libjxcore.so

$ cordova run
```

After that the app started correctly, thus the following error does not occur anymore:

> Package is either corrupted or not compatible with this JX binary." 



@edwinvanderham Could you please check it on your side?

**Comment by ktrzeciaknubisa** [comment]
@edwinvanderham 

> I don't think you can easily replace the android jxcore binaries. 

We have just updated README.md with relevant steps for [updating JXcore binaries](https://github.com/jxcore/jxcore-cordova#updating-jxcore-binaries).

**Comment by edwinvanderham** [comment]
I managed to make it work now, thanks!
