### ISSUE TITLE
compilation for ios: fails to import  which module...

### ISSUE THREAD

**Issue by DimaFr** [jxcore/jxcore#332]
Hello, i am trying to compile jxcore for ios but compilation fails at the below stage:
''
Traceback (most recent call last):
  File "src/builtin/embedjs.py", line 42, in <module>
    import which
ImportError: No module named which
make[1]: *** [deps/mozjs/src/builtin/Utilities.js] Error 1
make: *** [jx] Error 2
compilation aborted for ia32 target
''
i have looked into folders and which.js  is there at:
/deps/npm/node_modules/which 
Could you advice how to fix this, thanks.

**Comment by obastemur** [comment]
You need 'easy install' for python installed for OSX.  
Installing easy install on OSX: `curl https://bootstrap.pypa.io/ez_setup.py -o - | python`

Then you need to run below command under the root folder of jxcore (as given from [how to compile page](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md))

`sudo easy_install tools/which-1.1.0-py2.7.egg`

**Comment by DimaFr** [comment]
Thank you, its running. I have also noticed that you already put a bin folder in jxcore-cordova plugin! will try it!

**Comment by plika** [comment]
seems like this problem is solved. Thanks @DimaFr @obastemur
