### ISSUE TITLE
Conform to node-style callbacks

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#334]
[Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) are coming in ECMAScript 6 (Harmony) and can be used now with [bluebird](https://github.com/petkaantonov/bluebird) where [promisification](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification) provides promise-aware versions of existing asynchronous APIs. For this to work for `jxcore.tasks`, the `addTask`/`runTask` methods would need to conform to node-style callbacks. That means the callback needs to be the final parameter (rather than `obj`) and it needs to accept `err` as the first parameter to the callback. In that case we could write:
```javascript
var Promise = require('bluebird');
Promise.promisifyAll(jxcore.tasks);
var tasks = jxcore.tasks;

tasks.addTaskAsync(work, param)
	.then(function(result) {
		console.log('result = ' + result);
	})
	.catch(function(err) {
		console.error(err);
	});
```

Currently, promisification has to be done manually along these lines:
```javascript
var addTaskAsync = Promise.promisify(function(method, param, obj, callback) {
	tasks.addTask(method, param, function(result) {
		if(result.err)
			callback(result.err);		// <-- goes to our catch handler.
		else
			callback(null, result);		// <-- goes to our then handler.
	}, obj);
});
```

**Comment by jsbee** [comment]
+1 for this update.

**Comment by obastemur** [comment]
@zamb3zi thanks for the suggestion. We should indeed make all the callbacks etc. are matching with other core modules in style etc. Do you think that you can contribute on this item ?

**Comment by zamb3zi** [comment]
Sure, I can contribute. This would be a backwards-incompatible change. Another thing that would bring the callbacks into line with node is to deprecate the `obj` parameters. Other callback APIs generally don't provide the `obj` functionality as they leave it to the caller to arrange for themselves if needed and avoid the overhead for those who don't need it. This would have the following benefits:
* `addTask(method, param, callback)` is more succinct than `addTask(method, param, undefined, callback)`
* More efficient since currently we have a separate `objects[cbId]` mapping with extra book-keeping.
* We can detect deprecated calls easily with:
```javascript
exports._addTask = function (method, param, cb) {
  if (arguments.length > 3) {
    // issue deprecation warning?
    var obj = arguments[3];
    var depr_cb = cb;
    cb = function(err, result) {
      if(err) throw err;
      depr_cb(obj, result);
    };
  }
  ...
```
* New-style tasks can retain the `obj` functionality with any of the following:
```javascript
tasks.addTask(method, param, callback.bind(obj)) // obj is available as this.
tasks.addTask(method, param, function(err, result) {
  callback(err, obj, result);
});
require('sugar');
tasks.addTask(method, param, callback.fill(obj));
```
What do you think?

**Comment by obastemur** [comment]
@zamb3zi sounds good. How about the other methods (runOnThread etc..) ? They all depend to same proxy method.

**Comment by zamb3zi** [comment]
@obastemur Yes, I'll update all together. Just getting to this today.
