### ISSUE TITLE
jx install problem and/or guidelines (win7 32-bit JXcore beta 0.0.3 SM)

### ISSUE THREAD

**Issue by petitben** [jxcore/jxcore#337]
Hi,

I can't figure out how to configure the **jx install** command with my fresh downloaded version of JXcore (windows 7 32bit SpiderMonkey).

It tries to install NPM for the first time but after downloading the .tar.gz in **%Profile%\\.jx\**, it fails. It seems the decompression doesn't occur because it complains it can't found the **node_modules** directory.

![jxcore-install-fail](https://cloud.githubusercontent.com/assets/378035/7549707/725ea804-f641-11e4-8a04-d03adc9ae18e.png)

I don't know how I can debug it (I manually installed npm but I can't still use the jx install command of course).

By the way is there any way to configure jx to install npm in another directory than **%Profile%\\.jx\** ?
I saw it is possible to specify env variables but it's not so clear how to use it and how it modifies the global behaviour.

Thanks!

**Comment by plika** [comment]
I'm trying to figure out what's the problem. Is it possible for you to check it with V8 build ? 

Although you can install jxcore npm into another folder, every time you call 'jx install' it is going to check for user's home folder.

Maybe we could implement 'JXCORE_NPM' environment parameter to see if it's user's home or somewhere else. /cc @obastemur looks like a usable feature request.

@petitben I appreciate any additional information on the problem. Thanks!

**Comment by petitben** [comment]
@plika same problem with the V8 version. But it's clearly more verbose than with SM (see below).

![jxcore-v8-install-fail](https://cloud.githubusercontent.com/assets/378035/7550637/c815a0fe-f669-11e4-8dfb-6ec357c69582.png)

**Comment by ktrzeciaknubisa** [comment]
@petitben Could you please check if the latest commit 82817fec525b3bbb95345ae87d1575dc3957a388 fixes that issue for you? I've checked it on my side and it works.

**Comment by petitben** [comment]
I can confirm it's OK now! thanks!
