### ISSUE TITLE
Can we merge jxcore.utils.console into console ?

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#338]
I was thinking, that this would be a good idea to apply color modifier to original `console.xxx()` methods and give up on `jxcore.utils.console.log()` / `jxcore.utils.console.write()`. 

I've already implemented this in my local environment and this was fairly easy.

The last color argument could be passed with a special prefix (e.g. "@")  in order not to interfere much with user intentions:

```js
console.log("hello", "@red");
```

Or even without the "@" prefix at all. 

This way we can colorize all console methods: `log()`, `info()`, `error()`, `warn()`, etc.

What do you guys think about this?

**Comment by petitben** [comment]
Actually **console.log()** on last versions of Chrome and Firefox already supports *styles*.
An example here: http://stackoverflow.com/a/13017382

So in your special case and regarding terminal limitations you could for instance simply limit css parsing to basic values for **background-color** and **color** properties (thus no rgb, rgba hex, but only basic string parsing).

... but that's just my opinion of course :-) !

**Comment by obastemur** [comment]
JXcore's core node functionality shouldn't behave different than node.js. I believe a single line of code is not that hard ; `console.clog = jxcore.utils.console.log` whenever needed.

**Comment by ktrzeciaknubisa** [comment]
Alright then. In this case I allowed myself to add `info()`, `error()` and `warn()` to `jxcore.utils.console` (as they exists in `console` object) and they all got default color assigned ("green", "red" and "magenta" respectively) if none was provided as the last argument.

For example:
```js
jxcore.utils.console.info("this is green");
jxcore.utils.console.info("but this is yelow and bold", "yellow+bold");
```

This is the commit: 6f8a3f24a42f3d4ae0396e0819b462116ef9fc21

BTW: @petitben Thanks for the link, the idea is interesting!
