### ISSUE TITLE
Android: Error when attempting first jx install

### ISSUE THREAD

**Issue by dcerisano** [jxcore/jxcore#339]
Making some progress. Using the latest V8 jx binary for ARM, I am getting an error in the ADB root shell:

    root@mako:/data # ls -l
    drwxrwx--x system   system            2015-05-09 18:41 app
    ...
    -rwx------ root     root     15279044 2015-05-09 23:30 jx
    -rw------- root     root           24 2015-05-09 23:31 jx.config
    ...

    root@mako:/data # cat jx.config    
    {
        "npmjxPath":"/data"
    }

    root@mako:/data # ./jx install
    Preparing NPM for JXcore (v Beta-0.3.0.1) for the first run
    node.js:848
                throw ee;
    Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:15:11)
        at Object.onanswer [as oncomplete] (dns.js:97:16)

Maybe I am missing an environment variable? File permissions?

**Comment by dcerisano** [comment]
More progress.
Without doing anything except rebooting the desktop and android, the above errors have disappeared, making me think this was a permissions issue with adb server.

However, now I am getting another problem - no errors or messages at all when using jx install:

    127|root@mako:/data # ./jx install express                                     
    Preparing NPM for JXcore (v Beta-0.3.0.1) for the first run
    root@mako:/data # 

No matter what package I try,  jx install just returns as above.

**Comment by ktrzeciaknubisa** [comment]
I was able to reproduce this behavior and made a fix here ee0c4b6d4216807726683b43beb6d987cf85c64e. @dcerisano Could you please try it on your side and let us know?

**Comment by plika** [comment]
@ktrzeciaknubisa were you able to run jx install on Android ? I thought we don't support it.

**Comment by ktrzeciaknubisa** [comment]
@plika We can [Compile as a Standalone Process](https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md#compile-as-a-standalone-process). Also the standalone binaries are available on [downloads](http://jxcore.com/downloads/) page.

**Comment by ktrzeciaknubisa** [comment]
Oh sorry, I didn't answer the question directly. Yes, finally I was able to install, after the fix applied.

**Comment by dcerisano** [comment]
I am currently not building the jx binaries, just downloading them from your links.
I am wading through the build curve now and will get back when I have tested this.

Until then, I submitted a pull request containing some missing favicons for your JX sites.

**Comment by dcerisano** [comment]
More progress.
I have successfully built the executable ARM V8 binary.
My deployment platfrom is Android 5 (Lollipop)
I am getting this error:

    ./jx install
    error: only position independent executables (PIE) are supported.

We hit this before and you published a PIE.

What did you do to the built scripts to build a PIE?

**Comment by dcerisano** [comment]
More progress, got the PIE to build for 5.0 (temp mod of jx.gyp to include compiler flags)
Now getting another path error (think we are almost there ...)

    127|root@mako:/data # ./jx install                                             
    Preparing NPM for JXcore (v Beta-0.3.0.1) for the first run
    Downloading NPM for JXcore
    ..
    NPM for JX is ready.
    executing... please wait.
    npm ERR! install Couldn't read dependencies
    npm ERR! package.json ENOENT, open '/data/package.json'
    npm ERR! package.json This is most likely not a problem with npm itself.
    npm ERR! package.json npm can't find a package.json file in your current directory.
    npm ERR! System Linux 3.4.0-perf-g16e203d
    npm ERR! command "/data/jx" "/data/.jx/npm" "install" "--loglevel" "http"
    npm ERR! cwd /data
    npm ERR! node -v v0.10.38
    npm ERR! npm -v 1.4.14
    npm ERR! path /data/package.json
    npm ERR! code ENOPACKAGEJSON
    npm ERR! errno 34
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /data/npm-debug.log
    npm ERR! not ok code 0

**Comment by dcerisano** [comment]
I finally got this to install. I had to rebuild the PIE and a few other things which I will give here:

1) Follow instructions in this thread to build the standalone JX
2) For Android 5+ the JX must be a PIE, so edit the following in jx.jyp:

     'cflags!': ['-ansi -pie -fPIE'],
    'ldflags': ['-pthread -pie -fPIE'],

3) build and copy the resulting ARM V8 file to /data directory of your android
4) chmod 777 jx
5) in the /data directory make a new file called jx.config containing this:

    {
        "npmjxPath":"/data"
    }

6) in the /data directory make a new file called package.json containing this:

    {
      "name": "myapp",
      "version": "0.0.1",
      "dependencies": {
        "express": "4.0.0"
      }
    }

7)

    setenv HOME /data

8)

    /data/jx install
    /data/jx install express

That is all for this thread!

**Comment by ktrzeciaknubisa** [comment]
Thanks for detailed description! I was using Android 4.1.2, so did not have to go through the same way exactly. 

However here are my notes:

* why did you need chmod 777? Built jx already has sufficient permissions, no?
* did you really need *jx.config* with `npmjxPath` = `/data`? It looks, like this path is used anyway.
* also `setenv HOME /data` was not necessary for me

**Comment by dcerisano** [comment]
I am on rooted Nexus 4 (Mako) with Android 5.0 using root user.
When copied over usb, permissions must be restored.
Absolutely must have jx.config because JX cannot write to default root user home directory (/)
Absolutely needs to set $HOME dir for same reasons.

I am trying the static library build now, which should not have any of these issues.
