### ISSUE TITLE
Windows: jx install command fails due to require('tar.gz')

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#341]
This is not related strictly to `jx install`, although it occurs with this command when there is no `~/.jx/npm` folder. The problem has popped up recently in various scenarios and has much to do with jx packages and asset folders, which does not contain any file. We saw it here: #304 and here: #330. 

JXcore 0.3.0.0 also suffers this problem if there is no `~/.jx/npm` present (otherwise it works fine):

```bash
fs.js:740
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\Users\nubisa_krzs\.jx\node_modules'
    at Object.fs.lstatSync (fs.js:740:18)
```

The fix applied for #330 was not meant to solve it, but it moves the error forward:

```bash
fs.js:2158
    dir = NativeModule.Roots[dir][bs];
                                 ^
TypeError: Cannot read property 'tar.gz' of undefined
    at __hasFile (fs.js:2158:34)
    at __existJX (fs.js:2169:16)
```

From what I saw this happens after *Downloading NPM for JXcore* when the following command is executed:

*jxcore/tools/npmjx/index.js#173*:
```js
  var targz = require('tar.gz');
```

**Comment by obastemur** [comment]
Let's start testing and release 0.3.0.1 ?

**Comment by ktrzeciaknubisa** [comment]
I'm reopening since one of users still has a problem with it: https://github.com/jxcore/jxcore-addon/issues/3

**Comment by ktrzeciaknubisa** [comment]
@csapoadam Could you please help me debugging the problem and perform the following steps:

1. take the file [npmjxv1_5.jx](https://github.com/ktrzeciaknubisa/jxcore-issues/blob/master/jxcore/x341/csapoadam/npmjxv1_5.jx)
2. put into `%HOME%/.jx`
3. run from there: `jx npmjxv1_5.jx --version`
4. paste the output

In fact, the `--version` number is irrelevant - the point of this test is to try to extract the npm.targ.gz prior to call `--version` command.

**Comment by csapoadam** [comment]
Hi, here is the output I get:

C:\Users\Adam\.jx>jx npmjxv1_5.jx --version
Downloading NPM for JXcore
..
NPM for JX is ready.
executing... please wait.
1.4.14

**Comment by ktrzeciaknubisa** [comment]
How about npm folder? it seems like it got extracted?

**Comment by csapoadam** [comment]
I think so. I am on mobile now I can double-check in a few hours.

**Comment by ktrzeciaknubisa** [comment]
No problem. Thanks. 

Also I would like to ask you to run the same command `jx npmjxv1_5.jx --version` against your previous `npmjxv1_5.jx`, that I saw on your print screen.

If you don't have it anymore, you can remove `./jx/npm` folder and call `jx install` which fails for you (as we already know), but at least it downloads the file `npmjxv1_5.jx`.

**Comment by csapoadam** [comment]
OK, I can confirm that using the npmjxv1_5.jx you sent worked and extracted the tar.gz.
Then I deleted the .jx folder, went back to the addon project folder, and called jx install. Again, the installation failed and the tar.gz wasn't extracted. So I went back to the .jx folder in the home directory, ran the command you sent and the tar.gz was extracted.

Here is the well-known error message I received again when installing from the addon folder.

Error: ENOENT, no such file or directory 'C:\Users\Adam\.jx\node_modules' (nativ
e:jxcore_js_object 3:11)
    at  (native:jxcore_js_object:3:12)

It seems to me that running jx npmjxv1_5.jx, the archive is extracted fine, but somehow doing this with jx install isn't working.

**Comment by ktrzeciaknubisa** [comment]
Thank you very much for details. This gives me some idea, which I need to verify.

**Comment by ktrzeciaknubisa** [comment]
Ok. The good news is that I was able to reproduce this in specific conditions, but there is some unclear connections between at least few factors:
1. whether user's name contains big cap or not (Adam/adam)
2. whether the user is admin or not
3. how long is total length of the path (I've touched the magic 34 numer, or 37 if we count `c:\`)

Those are result of my tests made in a folder with a name length 35 chars (which is supposed to fail sometimes):
```bash
c:\12345678901234567890123456789012345>rm -rf "%HOMEPATH%\.jx\npm"
c:\12345678901234567890123456789012345>jx install -ls

user name		type		32sm302		64sm303	64v8303	32sm303	32v8303
nubisa_krzs		admin		+ 			+ 		+ 		+		+
Adam 			admin		- 			+		+		+		+			
Adamu 			user		+ 			+		+		+		+
Adau			user		- 			+		+		+		+
pete			admin		-			+		+		+		+
peteu			user		+			+		+		+		+
petu			user		-			+		+		+		+
```
The minus sign `-` means that `jx install` failed with `Error: ENOENT, no such file or directory`, and plus means `+` that it worked.

So I was able to reproduce the problem with jx SMx32 3.0.2 (in some cases), but it looks like they all work with the current jx 3.0.3 from master. Are you able to build the sources an check this out?

Also they work with 3.0.2, but the path length should be max 37 chars including `c:\`, e.g. from:

```bash
C:\Users\Adam\Desktop\Development\maxwhere-tests
```
into:
```bash
C:\Users\Adam\Desktop\Development\max
```
:)

I really don't know why it is like this, but I don't go deeper since the master branch works.

**Comment by csapoadam** [comment]
Hi, yes, it seems that the length of the path has a lot to do with this. Placing the contents of my folder to the Desktop, instead of Desktop\Development helped fix this particular problem on the Windows machine.

On the Mac, I am still having the old problems though, even if the length of the path is only 28 characters long. Over there, the folder extracts but some parts are missing. Extracting manually works.

I'd like to ask you for some pointers regarding the linker errors I am getting in Windows, too. I don't know if this is the right venue for this... but when doing jx install on that very simple addon example, which works perfectly on Mac, I get a lot of linker errors on Windows, as shown on the screenshot at the bottom, even though I have jx.lib and jx.dll on the path. These are the pre-built libs and pre-built executable I downloaded yesterday.

![scr11](https://cloud.githubusercontent.com/assets/3015877/8190084/d0e2852a-1460-11e5-856f-668afbb3b649.png)

**Comment by csapoadam** [comment]
PS. Also when building the newest sources on Windows, I can build the shared libraries fine:
vcbuild --shared-library --engine-mozilla --ia32

but when I try to build the executable (same as last command, but without --shared-library), I receive some errors.

![scr12](https://cloud.githubusercontent.com/assets/3015877/8190431/b4fa5e44-1462-11e5-92e5-06f1acf4d1b0.png)

actually, I have gone through them earlier, The problem seemed to be that Visual Studio 2012 - which I am using - doesn't allow the declaration of variables to follow statements in a block: http://stackoverflow.com/questions/13336179/syntax-error-missing-before-type

putting the declarations earlier and making some minor changes used to work a few weeks ago, but I have since started using the precompiled version.

**Comment by csapoadam** [comment]
Hi @ktrzeciaknubisa , do you have any updates on this? Thanks!

**Comment by ktrzeciaknubisa** [comment]
Sorry, but no luck, yet. Only the path length issue seems to be resolved in 3.0.3 release (did you try that?) while the other things we did not manage to reproduce.

**Comment by csapoadam** [comment]
Hi, Yes, I can confirm that the path length issue is resolved on windows with the 3.0.3 release.
I used the binary available on the website. When I do

vcbuild --engine-mozilla --compress-internals

my windows machine doesn't compile an executable (or at least I cannot find it). The Release folder contains only a lib and obj subfolder, and an executable called jskwgen (I'm not sure what that does). Do you know where the compiled executable should be?

Still, the precompiled binary works OK on windows with the npm extraction.

I am still having problems with just the basic example given here ( https://github.com/jxcore/jxcore-addon ) on Windows. I download the precompiled binary, put it on the path (now jx works on the command line), extract the addon-master folder, and run jx install inside it. I receive these unresolved symbols, starting with "binding.obj: error LNK2001: unresolved external symbol "public: static void __cdecl MozJS::EngineHelper::CreateObject ..."

Should I open a different issue for this?
Thanks.

**Comment by obastemur** [comment]
```
vcbuild --engine-mozilla --compress-internals

my windows machine doesn't compile an executable (or at least I cannot find it). 
```

Make sure 'jx' is reachable from the PATH in order to use '--compress-internals' 

> Should I open a different issue for this?

I would really appreciate if you can file that under jxcore-addon project. (Thanks)

**Comment by ktrzeciaknubisa** [comment]
Yep. Maybe it's better to create separate issues for those (jxcore / jxcore-addon etc.), as they become mixed and difficult to follow. And if you're still having issue on Mac with proper extracting of npm during `jx install` - please create another issue too. 

The current issue here `Windows: jx install command fails due to require('tar.gz')` I'm closing for now as it seems to be no issue any more.
