### ISSUE TITLE
Problem packaging and running Node.js app that uses Kraken.js

### ISSUE THREAD

**Issue by JK006** [jxcore/jxcore#342]
I get the following error while trying to run a sample Node.js app created using Kraken.js generator and packaged by JXCore.

uncaughtException ENOENT, no such file or directory '/Users/zz/Development/krakenTest/node_modules/kraken-js/config/config.json.jx'
Error: ENOENT, no such file or directory '/Users/zz/Development/krakenTest/node_modules/kraken-js/config/config.json.jx'
    at Object.fs.openSync (fs.js:447:18)
    at Object.fs.readFileSync (fs.js:298:15)
    at shush (/Users/zz/Development/krakenTest/node_modules/kraken-js/node_modules/shush/index.js.jx:30:15)
    at resolve (/Users/zz/Development/krakenTest/node_modules/kraken-js/node_modules/confit/index.js.jx:248:25)
    at maybe (/Users/zz/Development/krakenTest/node_modules/kraken-js/node_modules/confit/index.js.jx:239:28)
    at confit (/Users/zz/Development/krakenTest/node_modules/kraken-js/node_modules/confit/index.js.jx:285:5)
    at Object.create (/Users/zz/Development/krakenTest/node_modules/kraken-js/lib/config.js.jx:63:19)
    at settings (/Users/zz/Development/krakenTest/node_modules/kraken-js/lib/settings.js.jx:127:19)
    at module.exports (/Users/zz/Development/krakenTest/node_modules/kraken-js/lib/bootstrap.js.jx:33:12)
    at EventEmitter.onmount (/Users/zz/Development/krakenTest/node_modules/kraken-js/index.js.jx:68:19)

My environment details:
----------------------------
jx -jxv: v Beta-0.2.3.7
jx -v: v0.10.32
node -v: v0.12.1
Kraken-js version: 1.0.5
Operating system: OS X Yosemite (10.10.2)

To reproduce the error, 
1. Create a sample project using the steps mentioned on krakenjs.com
2. Run the app, 'npm start' and notice it runs without any issues.
3. Now package the app using JXCore, 'jx package server.js krakenTest'
4. Run the packaged app 'jx krakenTest.jx' and you will get the error mentioned above.

I looked at the package log, lines 'adding asset ...' and noticed that the file mentioned in the error (without .jx extension i.e.) never gets added to the .jx package or at least didn't show up in the log.
Also, I checked to confirm that the file is present (of course without the .jx extension) in the node_modules directory.
Thanks.

**Comment by ktrzeciaknubisa** [comment]
@JK006 Thank you for very detailed description!

Looking at the following error line:
```bash
at Object.fs.openSync (fs.js:447:18)
```
I guess it applies to #331 issue.

**Comment by obastemur** [comment]
@ktrzeciaknubisa this looks like the 'empty folder' problem. I remember you had fixed this recently. After fixing the windows 'jx install' problem better we release 0.3.0.1

**Comment by ktrzeciaknubisa** [comment]
@obastemur I've checked with the fresh jx build, which already has the fix you mention, but the problem remains the same. My explanation is that the `fs.open(Sync)` just doesn't know how to open asset files.

**Comment by JK006** [comment]
@ktrzeciaknubisa  I'm new to JXCore so please excuse me if I'm not understanding this, but isn't the fact that the file never shows up while adding assets an issue? and hence fs.openSync() is bound to fail? I also noticed that there are other files in that package that never show up in the log either.

**Comment by JK006** [comment]
@ktrzeciaknubisa Please ignore my previous comments about missing asset from package. Just noticed this in the package log...
adding script node_modules/kraken-js/config/config.json

So it looks like the file indeed gets added to the package, as a 'script'. Still fails to run. I tried the latest version of JXCore too.

**Comment by ktrzeciaknubisa** [comment]
The latest feature of [partial package extraction](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-feature-packaging-code-protection.markdown#partial-extraction) (JXcore 0.3.0.6) fixes the above issue and allows to run the Kraken.js app as jx package, once the config files will be marked as extractable. The following worked for me:

```bash
$ jx package server.js krakenTest --extract-what "config" --extract-app-root --extract-verbose
```

This instructs the package to extract all *config* folders from packaged directory structure. Unfortunately this works only with V8 engine. SpiderMonkey has other kind of problem described in #346.

Since the original issue is resolved, I'm closing this one.
