### ISSUE TITLE
Windows x86 native ignores Version and other settings.

### ISSUE THREAD

**Issue by christianromeni** [jxcore/jxcore#344]
I tried to create an x86 exe on a Windows 8.1 (64bit) machine.
To do that, I downloaded the binary and ran compile.
It worked, my app is inside, but the .exe File has the wrong information:

![image](https://cloud.githubusercontent.com/assets/1358040/7576655/83c1fbc2-f840-11e4-921d-4ce2e83a1b6b.png)

If I compile with: jx compile ./myfile.jpx it works
If i compile with: jx.cmd compile ./myfile.jxp it does not work

jx is in my systems Path settings
jx.cmd is the cmd file from the installation copied into my app folder.

**Comment by christianromeni** [comment]
Ok, I found out you have to add the .ver file as well....

**Comment by obastemur** [comment]
@ktrzeciaknubisa Why we need to add .ver file ? It supposed to be transparent

**Comment by ktrzeciaknubisa** [comment]
I guess @christianromeni is talking about his own .ver file with his own version/company data?

**Comment by christianromeni** [comment]
Yep.. I wanted it to show the company info and version of my app...
I thought this is done by modifying the package.json file.
But this only works, if the .ver file is in the same directory as the jxcore executable.

**Comment by ktrzeciaknubisa** [comment]
Nope. None of `package.json` or `.jxp` files are designed for this. However this sounds like a nice idea.

**Comment by christianromeni** [comment]
Would be awesome.....
But I'm currently struggling with the missing Windows XP support :-/ So maybe I have to switch to nw.js for packaging :(

**Comment by ZeevM3** [comment]
Hi,
How can i compile an x86 version on a x64 window machine?
I downloaded the v8 file and tried but it didn't change anything.

**Comment by ktrzeciaknubisa** [comment]
Hi @ZeevM3 

Are you asking how to compile a 32bit native app with `-native` option? To do this on 64bit platform you should use jx compiled for ia32 processor.

So you should grab a x32 JXcore - either use the Windows Setup (x32/x64/SM/V8) (on x64 Windows you will have an option to install x32 JXcore binaries as well) or download the exact binary e.g. Windows 32 (V8) - all available on JXcore [download](http://jxcore.com/downloads/) page.

Then you can pack the app on 64bit Windows as usual:

```bash
c:\path_to_jx_32\jx package myapp.js MyApp -native
```

**Comment by ZeevM3** [comment]
No no, ignore this message i removed it. I open an issue and we're already talking there..

**Comment by ktrzeciaknubisa** [comment]
@christianromeni Right now all the version information from `.jxp` file should be written correctly into file header of native package executable. A note in the docs was added: [-native](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-feature-packaging-code-protection.markdown#-native)

> Ok, I found out you have to add the .ver file as well....

This is not necessary any more. It's enough if the `.ver` file will be available in %PATH% (and it is, if you have used Windows Setup to install JXcore). And yes, it can be present in current working directory, too.

**Comment by christianromeni** [comment]
:+1: Perfect! Thank you, great feature.
