### ISSUE TITLE
Android: JX is including wrong path in JS executable shebangs.

### ISSUE THREAD

**Issue by dcerisano** [jxcore/jxcore#345]
Got JX running from android command line (see issue #339)

It seems to be able to install anything that NPM can, awesome.

There are still some issues with Android filesystem paths:

All packages are installed to $HOME/node_modules/.bin, so that should be included in the PATH
These executables in the .bin directory are just links to the app.js files in the actual package directories.

These app.js files all start with:

    #!/usr/bin/env jx

Which is wrong. You get an error when trying to run from /usr (does not exist in Android)

It should read (with $PATH to .bin set):

    #!/system/bin/env jx

Then everything seems to run great. Is there a way to configure JX to do this?

**Comment by ktrzeciaknubisa** [comment]
Well I guess node modules are not designed to work with android and kind of replacement needs to be applied in that case. Thanks for noting!

**Comment by dcerisano** [comment]
I am thinking that with the static library approach, I can just include the npm node tree with my app, with any modifications (like above).

One last note about running from the Android command line:
 Android has mysterious process scheduling. Running JX out of process and communicating with an application via IP does not work. JX will halt and only run intermittently. 

Again, running the JX static libraries in process does not show this problem.  

In fact JX is blazingly fast.  

JX runs faster on my old Nexus 4 phone than NPM does on my quadcore laptop.
I would estimate around twice as fast on a device with 1/4 the processing power.

JX is a game changer as is going to enable a new kind of internet.

**Comment by obastemur** [comment]
@dcerisano can you elaborate on "Android has mysterious process scheduling. Running JX out-of-process and communicating with an onboard application via IP does not work. JX will halt and only run intermittently" Any basic sample that I can play with ?

**Comment by dcerisano** [comment]
Please contact me via my profile email address to discuss, thanks.
