### ISSUE TITLE
JXCore 0.3 for FreeBSD

### ISSUE THREAD

**Issue by tiagodexter** [jxcore/jxcore#347]
Hi,

The 0.2.3.7 is available for FreeBSD and version 0.3 wasn't.
Do you have any idea when is release for this O.S?

**Comment by ktrzeciaknubisa** [comment]
We will surely be back with FreeBSD binaries. This might be one of next releases.

**Comment by tiagodexter** [comment]
Thaks for reply.

It comes with -native option? Because one of things thai I think mistake on older version is that.

**Comment by ktrzeciaknubisa** [comment]
What do you mean? The `-native` option is available in 2.3.7 as well (yes, we've introduced some packaging improvements in 3.0.0 #213, but they are not stricte related to `-native`). 

Do you have any problem with `-native` from v2.3.7 ?

**Comment by tiagodexter** [comment]
In v2.3.7 -native option wasn`t work in FreeBSD. It says the FreeBSD doesn't supported.

# ../jx_bsd64/bsd10/jx package app.jx birdfilter -native
(...)

[Error: This operating system is not supported (freebsd-x64)]

**Comment by ktrzeciaknubisa** [comment]
Ah, right. We had some bugs related to this before. It is fixed in JXcore v0.3.0.0. You may try to compile JXcore by yourself and `-native` option should work for you.

**Comment by tiagodexter** [comment]
Thanks again.

I will wait for this new release.

**Comment by ktrzeciaknubisa** [comment]
Hi, JXcore 0.3.0.1 is now available for FreeBSD x64 on http://jxcore.com/downloads/. Also  `-native` option works as expected.
