### ISSUE TITLE
When execute jx package app.js -add ./app.js,../text.js, it cannot add ../text.js into app.jx

### ISSUE THREAD

**Issue by syter** [jxcore/jxcore#348]
Hello,
For example:
There is a nodejs project at path /user/me/test1_project and it is started by command : node /user/me/test1_project/app.js.
There is a special file need to required in app.js, but this file is at /user/me/test2_project not in the test1_project.
So i try to execute this at path /user/me/test1_project/ : jx package app.js -add ./app.js,../test2_project/special_file.js
The jx result is like below:

Processing the folder..
JXP project file (app.jxp) is ready.

preparing the JX file..
Compiling app 1.0
adding script app.js
[OK] compiled file is ready (app.jx)

Not include /user/me/test2_project/special_file.js !

Is there any solutions for this issue?

**Comment by ktrzeciaknubisa** [comment]
You cannot include into a package files located outside the project folder (which means outside the path, from which you execute `jx package`). But you can have it working by creating a package from a parent folder:

```bash
$ cd /user/me/
$ jx package ./test1_project/app.js -add ./test1_project/app.js,./test2_project/special_file.js
```

**Comment by syter** [comment]
It works. Thank you.
