### ISSUE TITLE
Node command line (--debug/--debug-bkr) problem

### ISSUE THREAD

**Issue by eajimmy** [jxcore/jxcore#350]
Hi all,
I've noted that, with the new version (0.3.0), I can't start a process with command line arguments e.g.:--debug, --debug-bkr (like i did before in the 0.2.3.7). It's possible to use this feauture again so I can debug my application with webstorm or there are other ways? (I've just saw the 'debug' options, but it's too "manual" :-) )
Thank you!

**Comment by obastemur** [comment]
Perhaps you have this problem with SM build. 'jx -jsv' should tell the built-in engine

**Comment by eajimmy** [comment]
@obastemur the result of the command is:
Google V8 v3.14.5.9.
So, it's the V8 :-).

**Comment by obastemur** [comment]
@eajimmy  Thanks for the details. 

/cc @ktrzeciaknubisa we should publish 0.3.0.1 asap if there is nothing holding.

**Comment by ktrzeciaknubisa** [comment]
@obastemur Generally I think we're ready. Just found this today: #358
