### ISSUE TITLE
Having Issues With Files in Folders

### ISSUE THREAD

**Issue by inampaki** [jxcore/jxcore#353]
Hi;
I have a project of more than 300 files with around 10 folders at root of Project. Files on Root of Project are Compiled fine but My Folders are not included in Compiled Version, I am getting Error ENOENT for the Folder Names if I try to run the Compiled File. It Works Fine if I run the .jx file from Project Source Code Location.
Error Details are :
fs.js:740
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\HIMS\After Integration\Patient Serology Clone\testing jx core\DBSchema'
    at Object.fs.lstatSync (fs.js:740:18)
    at Object.realpathSync (fs.js:1357:21)
    at tryFile (module.js:119:15)
    at tryExtensions (module.js:127:20)
    at Function.Module._findPath (module.js:162:20)
    at Function.Module._oldRes (module.js:685:25)
    at Function.Module._resolveFilename (module.js:1544:17)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)

**Comment by ktrzeciaknubisa** [comment]
Hi. Is `My Folders` a name of a directory? Is it located at root of the project or it's subfolders?

**Comment by inampaki** [comment]
I have no Such Folder name "My Folders", I thought its giving me the Error for Folder "DBSchema" which is Part of My Project, and Yeah I do remember I Copied the "DBSchema" Folder with all schema files Where I put .jx file for test Run then It gave the Error for next Folder which is "DBRepository".

**Comment by ktrzeciaknubisa** [comment]
> I have no Such Folder name "My Folders"

All right, I misunderstood your previous words:

> ... are Compiled fine but My Folders are not included ...

Anyway, is your "DBSchema" present in the root folder of the project at the moment of compiling the package?

**Comment by inampaki** [comment]
Yes It is

**Comment by ktrzeciaknubisa** [comment]
We need more info on that. I thought at first, that this might be related either with character casing or spaces in folder/files names, but my quick test did not show any misbehavior. So I would like to ask you for some more details:

1. simple project file structure, e.g.:
    * path to the folder
    * contents of the folder (output of `dir` command should be enough)
2. which command exactly are you using to create a package?
3. which version of JXcore are you using? (jx -jxv)
4. which engine? (jx - jsv)
5. javascript line of your code, which triggers the error

**Comment by inampaki** [comment]
1)
10/28/2013  22:59                36 .gitignore
04/29/2015  20:16    <DIR>          .idea
04/28/2015  12:47           315,053 app.js
04/29/2015  20:16    <DIR>          CentralizedDataTransfer
04/29/2015  20:16    <DIR>          controller
04/29/2015  20:16    <DIR>          custom_modules
04/29/2015  20:16    <DIR>          DBRepository
04/29/2015  20:16    <DIR>          DBSchema
04/29/2015  20:26    <DIR>          node_modules
03/13/2015  06:01               613 package.json
05/19/2015  09:44        47,626,889 Panacea.exe
05/19/2015  09:42        19,555,544 Panacea.jx
05/19/2015  09:43           114,079 Panacea.jxp
10/08/2013  01:56                40 Procfile
04/29/2015  20:18    <DIR>          routes
04/29/2015  20:18    <DIR>          smsHandler
04/29/2015  20:18    <DIR>          static
03/31/2015  15:59             3,677 transform.js
04/28/2015  19:47            11,050 userConfig.js
04/29/2015  20:19    <DIR>          views
04/27/2015  11:42             1,878 worker.js
04/29/2015  20:19    <DIR>          WorkerModules

2)
jx package app.js "Panacea" -native -slim node_modules,.idea,*.zip

3)
C:\HIMS\After Integration\Patient Serology Clone\jxcore>jx -jxv
v Beta-0.3.0.0

4)
C:\HIMS\After Integration\Patient Serology Clone\jxcore>jx -jsv
Google V8 v3.14.5.9

5)Please See yourself complete stack trace of error thrown it doesn't seem to be raised from my source code.
fs.js:740
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\HIMS\After Integration\Patient Serology Clone\testing jx core\DBSchema'
    at Object.fs.lstatSync (fs.js:740:18)
    at Object.realpathSync (fs.js:1357:21)
    at tryFile (module.js:119:15)
    at tryExtensions (module.js:127:20)
    at Function.Module._findPath (module.js:162:20)
    at Function.Module._oldRes (module.js:685:25)
    at Function.Module._resolveFilename (module.js:1544:17)
    at Function.Module._load (module.js:268:25)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)

**Comment by ktrzeciaknubisa** [comment]
Thank you for the details. However I still cannot find the problem on my test environment.

> error thrown it doesn't seem to be raised from my source code.

This may be true, but I suspect, that you might call in your code e.g. `readFileSync("./DBSchema/somefile.txt`) etc.

What's inside DBSchema? Are there any `node_modules`? If yes, this might be the reason for the failure, since you call `-slim node_modules` and it applies to subfolders too. I'm asking, because the stack trace has the following entry at the end: `at require (module.js:396:17)`.

**Comment by inampaki** [comment]
I serached my whole Project for use of readFileSync, but found No occurrence of it, DBSchema folder contains all the Domain related Schema / Models for Mongoose.

**Comment by inampaki** [comment]
:D I am wondering I copied All Folders Empty with exact Structure as in Project but without Source Code and it Worked already compiled Panacea.jx File working.

**Comment by ktrzeciaknubisa** [comment]
Panacea.jx or Panacea.exe? Because you were using `-native` for exe compilation.

**Comment by inampaki** [comment]
I tried Both options, Now both are Working with Empty Folder Structure.

**Comment by ktrzeciaknubisa** [comment]
Could you prepare a minimal project with only this contents which triggers the error? For example to add to Empty Folder Structure a minimal source code one by one/recompile/run until you'll get the error? Then you could send it to me. Otherwise I'm not able to see the problem.

**Comment by inampaki** [comment]
How can I send you files, github not allowing me to upload zip file

**Comment by ktrzeciaknubisa** [comment]
You can use my mail ktrzeciak [at] nubisa.com.

**Comment by ktrzeciaknubisa** [comment]
Hi @inampaki . Could you please try with the latest v0.3.0.1 release (published yesterday)? There were multiple fixes applied addressing "no such file or directory" inside a package. Please let us know if that works for you.

**Comment by inampaki** [comment]
Thanks @ktrzeciaknubisa for all the Help Yeah latest Version Resolved my issue.

**Comment by ktrzeciaknubisa** [comment]
Thank you @inampaki very much for the info.
