### ISSUE TITLE
No documentation how to run ES6 javascript with new class syntax

### ISSUE THREAD

**Issue by kzc** [jxcore/jxcore#356]
The JXCore documentation lists ES6 support. I can run the following code with iojs version 2.0.2 using the command `iojs --use_strict script.js`

    // script.js
    class Foo {
      constructor(a) { this.a = a; }
      hello() { console.log(this.a * 3); }
    }
    new Foo(11).hello();

When I try to run it with `jx` using the SpiderMonkey engine I get this error:

    SyntaxError: class is a reserved identifier

What syntax must I use or command line flag must I pass to `jx` to run this ES6 script?

**Comment by obastemur** [comment]
JXcore doesn't not require any special command line parameter to use ES6 features.

JXcore's ES6 support is based on SpiderMonkey. List of ES6 features supported by SpiderMonkey are available from [this link](https://developer.mozilla.org/en/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla). Although SpiderMonkey supports much more (64%) ES6 features comparing to V8 (48%) [source](https://kangax.github.io/compat-table/es6/) , class is expected to come with SM39. 

Please note that we did not bring JS engine based promises into JXcore. a) not actually a JS engine feature b) JS implementations works faster.

**Comment by kzc** [comment]
So just to be clear, jxcore cannot run the script above at this present time?

**Comment by obastemur** [comment]
Yes

**Comment by kzc** [comment]
I see. What version of SM does the latest jxcore use?

**Comment by ktrzeciaknubisa** [comment]
JXcore 0.3.0.0 displays the following:
```bash
$ jx -jsv
Mozilla SpiderMonkey v34
```

**Comment by obastemur** [comment]
We have stabilized the 0.3.0.0 with SM34. I'm working on SM38 update at the moment. So, SM39 as well as classes will be part of the update after the upcoming one. (SM40 or 42)

**Comment by kzc** [comment]
Cool. Thanks.
