### ISSUE TITLE
property pollution in user functions

### ISSUE THREAD

**Issue by kzc** [jxcore/jxcore#362]
Is the following behavior desirable in jxcore?

    $ jx -jsv
    Mozilla SpiderMonkey v34

    $ cat pollution.js
    function user_function(a,b) { return a * b; }
    for (p in user_function)
      console.log('user_function.' + p, 'is a', typeof user_function[p]);

    $ jx pollution.js
    user_function.runTask is a function
    user_function.runOnce is a function
    user_function._runTask is a function
    user_function._runOnce is a function
    user_function._checkModeProperty is a function
    user_function.isDirectory is a function
    user_function.isFile is a function
    user_function.isBlockDevice is a function
    user_function.isCharacterDevice is a function
    user_function.isSymbolicLink is a function
    user_function.isFIFO is a function
    user_function.isSocket is a function

io.js, by comparison, outputs nothing.

If this is done by design in jxcore, could you consider hiding these properties with Object.defineProperty() and {enumerable:false}?

**Comment by kzc** [comment]
jxcore in v8 mode behaves a bit differently:

    $ jx -jsv
    Google V8 v3.14.5.9
    
    $ jx pollution.js 
    user_function.runTask is a function
    user_function.runOnce is a function
    user_function._runTask is a function
    user_function._runOnce is a function

This makes a bit more sense, but I think these Function properties should not be enumerable.

**Comment by plika** [comment]
@kzc ` {enumerable:false}` doesn't hide the prototype members. @obastemur IMO we should remove runTask, runOnce and their privates from function prototype for good. Sending a PR to master.

@kzc A question; I couldn't reproduce the output with SM build. It was exactly the similar to v8 build. I did my test with master on OSX

**Comment by plika** [comment]
As far as I remember we were going to move jxcore.tasks into a separate module. Although this update means an API break, it can be considered as a step forward. PR: https://github.com/jxcore/jxcore/pull/363

**Comment by ktrzeciaknubisa** [comment]
@plika 

> A question; I couldn't reproduce the output with SM build. It was exactly the similar to v8 build. 

I get the same output as @kzc for SM build. Tested also with master on OSX.

**Comment by kzc** [comment]
I also tested a SM build against cdfb753ec1 on OSX.

@plika: regarding enumerable:false - it at least hides it from "for in" loops.  But to be honest, I don't think any of these properties should be on Function in the first place. An application that I was working on that worked on io.js did not run correctly on jxcore because of this.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/050e22023dae2a0dd3760370701e758de214c49f runTask and related stuff are removed from function prototype. I don't know the others. One possible thing is that somehow stat object mixed into results but I don't see it's happening on given test case.

**Comment by kzc** [comment]
latest master 02cb195470 on OSX:

    $ jx -jsv
    Mozilla SpiderMonkey v34

    $ jx pollution.js 
    user_function._checkModeProperty is a function
    user_function.isDirectory is a function
    user_function.isFile is a function
    user_function.isBlockDevice is a function
    user_function.isCharacterDevice is a function
    user_function.isSymbolicLink is a function
    user_function.isFIFO is a function
    user_function.isSocket is a function

I presume that the v8 build would be fine. 

It's not obvious how the properties above are mixed in.

**Comment by obastemur** [comment]
I've reproduced the problem and fix(https://github.com/jxcore/jxcore/commit/ea249dfd0dca18edb83d71487cb4a11a468d8bdc) is on master. I was going to introduce this change with the SM38 anyways. @kzc Thanks!
