### ISSUE TITLE
(Plesk) File not found error / unserialize error

### ISSUE THREAD

**Issue by chiefbrain** [jxcore/jxcore#369]
The installation of the plugin (v0.2.6-1 on plesk12, debian) works, but after agreeing the terms, the terms screen reappears and the following error shows in the plesk log:

>Exception: PHP Warning: chmod(): No such file or directory; File: /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php, Line: 922

>file: /opt/psa/admin/plib/Smb/Exception/Syntax.php
line: 56
code: 0
trace: #0 [internal function]: Smb_Exception_Syntax::handleError(2, 'chmod(): No suc...', '/opt/psa/admin/...', 922, Array)
#1 /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php(922): chmod('/opt/psa/var/mo...', 365)
#2 /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php(236): IndexController->download_JXcore('')
#3 /opt/psa/admin/externals/Zend/Controller/Action.php(516): IndexController->initAction()
#4 /opt/psa/admin/externals/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('initAction')
#5 /opt/psa/admin/externals/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /opt/psa/admin/plib/pm/Application.php(66): Zend_Controller_Front->dispatch()
#7 /opt/psa/admin/htdocs/modules/jxcore-support/index.php(6): pm_Application->run()
#8 {main}

Every next click on OK leads to the following errors in the log:

>PHP Warning: chmod(): No such file or directory; File: /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php, Line: 922
Exception: PHP Warning: chmod(): No such file or directory; File: /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php, Line: 922

>file: /opt/psa/admin/plib/Smb/Exception/Syntax.php
line: 56
code: 0
trace: #0 [internal function]: Smb_Exception_Syntax::handleError(2, 'chmod(): No suc...', '/opt/psa/admin/...', 922, Array)
#1 /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php(922): chmod('/opt/psa/var/mo...', 365)
#2 /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php(236): IndexController->download_JXcore('')
#3 /opt/psa/admin/externals/Zend/Controller/Action.php(516): IndexController->initAction()
#4 /opt/psa/admin/externals/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('initAction')
#5 /opt/psa/admin/externals/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /opt/psa/admin/plib/pm/Application.php(66): Zend_Controller_Front->dispatch()
#7 /opt/psa/admin/htdocs/modules/jxcore-support/index.php(6): pm_Application->run()
#8 {main}

>PHP Notice: unserialize(): Error at offset 1970 of 2000 bytes; File: /opt/psa/admin/plib/modules/jxcore-support/library/CustomStatus.php, Line: 33
>Exception: PHP Notice: unserialize(): Error at offset 1970 of 2000 bytes; File: /opt/psa/admin/plib/modules/jxcore-support/library/CustomStatus.php, Line: 33

>file: /opt/psa/admin/plib/Smb/Exception/Syntax.php
line: 56
code: 0
trace: #0 [internal function]: Smb_Exception_Syntax::handleError(8, 'unserialize(): ...', '/opt/psa/admin/...', 33, Array)
#1 /opt/psa/admin/plib/modules/jxcore-support/library/CustomStatus.php(33): unserialize('a:32:{i:0;a:2:{...')
#2 /opt/psa/admin/plib/modules/jxcore-support/library/CustomStatus.php(68): Modules_JxcoreSupport_CustomStatus->storeMessage('error', '')
#3 /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php(237): Modules_JxcoreSupport_CustomStatus->addMessage('error', '')
#4 /opt/psa/admin/externals/Zend/Controller/Action.php(516): IndexController->initAction()
#5 /opt/psa/admin/externals/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('initAction')
#6 /opt/psa/admin/externals/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /opt/psa/admin/plib/pm/Application.php(66): Zend_Controller_Front->dispatch()
#8 /opt/psa/admin/htdocs/modules/jxcore-support/index.php(6): pm_Application->run()
#9 {main}

The file /opt/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php exists. If the file rights are set to a+rwx, the error does not show up but the unserialize-error persists.

What have I done wrong? Are there any prerequisites?

**Comment by ktrzeciaknubisa** [comment]
Hi. Generally it is not needed to set the extra file permissions while using JXcore extension and there are no any prerequisites required. Let me see into this.

**Comment by ktrzeciaknubisa** [comment]
Thanks for the report. There was a directory structure difference inside the download zip files comparing to previous releases. It's corrected now and you can try again. BTW: I suggest you to take back the rights that you granted manually for the file.

**Comment by chiefbrain** [comment]
Thanks for the fix, now it works without errors.
