### ISSUE TITLE
when is jxcore LLVM available?

### ISSUE THREAD

**Issue by sequoiar** [jxcore/jxcore#37]

**Comment by g2graman** [comment]
@obastemur Unable to find documentation for it, but is jxcore LLVM available?

**Comment by siriux** [comment]
I'm also interested, is there any public code for the LLVM javascript frontend?

Thanks

**Comment by gardner** [comment]
Some work has been done one this: http://jxcore.com/jxcore-llvm-javascript-frontend-b

**Comment by gardner** [comment]
Please excuse me. The blog post is dated 2017 but that article landed years ago. See https://news.ycombinator.com/item?id=7224821
