### ISSUE TITLE
Emitting LLVM IR

### ISSUE THREAD

**Issue by g2graman** [jxcore/jxcore#371]
I was unable to find any documentation for it but is it possible to emit LLVM bitcode of a JX package? My motivation is to be able to do an analysis on a machine-independent IR, specifically LLVM, so I could use tools such as [KLEE](https://klee.github.io/) on the resulting bitcode.

**Comment by obastemur** [comment]
@g2graman JXcore can not emit LLVM bitcode and there is no short term plan to do so.
