### ISSUE TITLE
(Plesk) wrong OS detect

### ISSUE THREAD

**Issue by chiefbrain** [jxcore/jxcore#372]
On installing JXCore via Plesk on Debian, jx_rh64v8 is installed.
Since I'm in a container, /proc/version returns the host distro, not the container.

cat /proc/version
Linux version 3.2.41-042stab106.6 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Mon Apr 20 14:48:47 MSK 2015

**Comment by ktrzeciaknubisa** [comment]
> /proc/version returns the host distro, not the container.

How come? So the host is Red Hat and container Debian?

**Comment by chiefbrain** [comment]
Yes.

**Comment by ktrzeciaknubisa** [comment]
I may be missing something, but how `cat /proc/version` executed on container side may print the host distro? Plesk does the check through php, which means Apache server on Debian, if this is where Plesk is installed...

**Comment by obastemur** [comment]
Maybe we give an option to choose JXcore distro manually (optional) ?

**Comment by chiefbrain** [comment]
I thought checks are done in jx_install.sh, /proc/version is used there (bash, no php).
Can you give me a hint, which files/commands are used for version checking, I can't post the output on my system.

**Comment by ktrzeciaknubisa** [comment]
jx_install.sh is not used by Plesk's extension, however `/proc/version` is still checked by `IndexController.php` (at `/opt/psa/admin/plib/modules/jxcore-support/controllers`).

Anyway, if you could run `cat /proc/version` on Debian and paste the result - maybe this will clear something up.

**Comment by chiefbrain** [comment]
The output is in the first post :)

**Comment by ktrzeciaknubisa** [comment]
But this is from Red Hat, right? We seek the output from Debian :)

**Comment by chiefbrain** [comment]
This is the ouput in the container (Debian).

**Comment by ktrzeciaknubisa** [comment]
So how can you even prove from the command line, that you are inside Debian? It doesn't make sense to me :)

**Comment by chiefbrain** [comment]
I read something about distribution detection here: http://unix.stackexchange.com/questions/35183/how-do-i-identify-which-linux-distro-is-running

cat /etc/issue
Debian GNU/Linux 7 \n \l

lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

**Comment by ktrzeciaknubisa** [comment]
Is it possible, that you have overwritten somehow in the past `/proc/version` or altered it in any other way? If it does not correspond to other commands (e.g. `cat /etc/issue`) - that doesn't sound good. 

I myself have a VM with Debian (on OSX host) and `cat /proc/version` displays expected:
```bash
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.65-1
```

I know that could be painful, but can you setup fresh Debian container and see the difference?

**Comment by chiefbrain** [comment]
I did not alter /proc/version. Furthermore, this is not a VM, it is a virtual server.
/proc/version shows the OS the kernel compiled on not the distribution currently running.

**Comment by ktrzeciaknubisa** [comment]
Alright. That makes room for @obastemur suggestion: 

> Maybe we give an option to choose JXcore distro manually (optional) ?

However my opinion is not to put this into panel pages. I'm not sure how often would be needed to use this feature. Instead we could instruct the admins to place a text file e.g. `jx_deb64v8` somewhere and install procedure would use it instead of determining the distro by itself.

@chiefbrain In a meantime you can download jx for Debian manually, unzip and put `jx` into `/usr/local/psa/var/modules/jx`. Then just go to the panel for `Reinstall`. Your saved binary should be used instead of downloaded one.

**Comment by ktrzeciaknubisa** [comment]
The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).

@chiefbrain For you especially may be interesting **Custom JXcore version appliance** section of the article. You may use `jxos.ini` file to define custom distro platform/architecture, or replacement path `/opt/psa/var/modules/jxcore-support/jx` for manually downloaded binary.
