### ISSUE TITLE
Unhandled exception with access violation in Visual Studio

### ISSUE THREAD

**Issue by csapoadam** [jxcore/jxcore#374]
I've successfully compiled JXcore in Microsoft Visual Studio 2012 on my Windows7 computer. I configured it to build the static libraries, and was able to compile and link (to jx.lib) the example posted here: https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_Basics.md

Unfortunately when I run the program it crashes at this call:

JX_Initialize(args[0], callback);

with an "unhandled exception" due to "access violation". The point of failure is in a function named __crtFlsGetValue(...) in a file called winapisupp.c

Has anyone had a similar experience? In particular, I am wondering what the path in the first argument of JX_Initialize is expected to be (surely the second argument should be alright)? I was sure to pass a valid path, and have tried several alternatives, including the path to the js.exe executable.

Another interesting issue was that I was unable run the code until I added jx.exe to the path. Apparently the C++ program would run only if it was able to start the interpreter as a separate process. Is this also the case on the iOS platform? If so, then how can JXcore be embedded into a single app?

Thank you in advance.

**Comment by obastemur** [comment]
@csapoadam here is [the sample Visual Studio solution](https://github.com/obastemur/JXcoreWindowsEmbedded) for embedded JXcore application on Windows. It should answer for the most of the questions ?

There is no need for separate process. It should just work as is.

**Comment by csapoadam** [comment]
Thanks a lot, it's working! 
Changing just the lib helped. It could be that I forgot the -ia32 parameter... :S

**Comment by obastemur** [comment]
Good to hear it's working.
