### ISSUE TITLE
JXcore support for process.argv parsing

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#375]
I thought that would be a good idea to include support for `process.argv` parsing (e.g. into `jxcore.utils` namespace). There are multiple places in JXcoure source codes, where argv are parsed when needed, and each of those places uses separate logic for that. 

Having a dedicated method for argv parsing in JXcore sounds like a nice idea to me. Furthermore, it would parse just once (since there is no need to do it more often unless `process.argv` is altered) and that would help to save few CPU cycles.

Not to mention, that user's might also benefit from it.

How about embedding the [minimist](https://github.com/substack/minimist)? It is on-file-based module and looks more that sufficient for that subject.

**Comment by obastemur** [comment]
Let's also move all the command line parsing stuff from node.js file. It's totally useless for an embedded app (i.e. mobile)

**Comment by ktrzeciaknubisa** [comment]
Ok, I've made a first step for the argv parsing. 

```js
var parsed = jxcore.utils.argv.parse();
console.log(JSON.stringify(parsed));
```

```bash
$ jx test.js --one=1 --two 2 --three -abc -d 1 str1 str2 str3
{
    "_": {
        "str1": true,
        "str2": true,
        "str3": true
    },
    "_array": [],
    "one": "1",
    "two": "2",
    "three": true,
    "a": true,
    "b": true,
    "c": true,
    "d": "1"
}
```

Newly implemented #390 is already using it.

**Comment by obastemur** [comment]
Let's see how it may help us to reduce the size of 'node.js' file.

**Comment by ktrzeciaknubisa** [comment]
I've already started to do so. There are some changes already committed and will be more for other .js files as well. This can be closed now.

The docs are here: [argv Parsing](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-utils.markdown#argv-parsing).
