### ISSUE TITLE
Compiling native addon on linux fails (node-gyp typo)

### ISSUE THREAD

**Issue by kobalicek** [jxcore/jxcore#376]
I'm trying to port my native addon to jxcore, but I'm having problems even before the compilation. I'm using debian x64 with spidermonkey engine.

After executing `jx install` I get the following:

```
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack createConfigFile@/home/petr/.jx/npm/node_modules/node-gyp/lib/configure.js:214:1
gyp ERR! stack configure/createBuildDir/<@/home/petr/.jx/npm/node_modules/node-gyp/lib/configure.js:166:7
gyp ERR! stack mkdirP/<@/home/petr/.jx/npm/node_modules/mkdirp/index.js:20:1
gyp ERR! stack makeCallback/<@fs.js:84:12
gyp ERR! stack 
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "jx" "/home/petr/.jx/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/petr/_workspace/blendjs
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v0.13.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

I don't even know if this is `jxcore` problem or `node-gyp` problem, but since I can compile with node 0.12+ and with iojs 2+ just fine I think there is an issue in jxcore.

Thanks!

**Comment by obastemur** [comment]
@kobalicek native modules are mostly compatible with V8 version of JXcore. If your app depends on a native module you should use JXcore v8 build.

**Comment by kobalicek** [comment]
As a part of my module I developed an abstract JS interface that I'm using to talk to V8, this is the reason I'm trying jxcore with SM.

**Comment by kobalicek** [comment]
I think I found the issue, there is a typo in `node-gyp`'s `configure.js` line 214:

```
      } else if (isInfo.isLinux) {
```

It should be:

```
      } else if (osInfo.isLinux) {
```

**Comment by obastemur** [comment]
So you developed your own native module using JXcore's macro interface ?

**Comment by kobalicek** [comment]
No, I'm not using node macros neither jxcore macros. Fixing the typo solved my problem, I can now compile.

**Comment by kobalicek** [comment]
BTW where to report this issue, is node-gyp the right place or it's `node-gyp` modified by jxcore?

**Comment by obastemur** [comment]
that's the modified one, you can contribute by updating `https://github.com/jxcore/jxcore/blob/master/deps/npm/node_modules/node-gyp/lib/configure.js` file on master.

**Comment by kobalicek** [comment]
https://github.com/jxcore/jxcore/pull/377

**Comment by obastemur** [comment]
@kobalicek Thanks! Closing the issue then.

**Comment by kobalicek** [comment]
That was fast, thank you!
