### ISSUE TITLE
How to set a property to a JS object from native side?

### ISSUE THREAD

**Issue by coppercash** [jxcore/jxcore#381]
I am developing on iOS, so 'native side' means Objc/C side.

With JavaScriptCore, I can set property on to a JS object by using statements like following:
``` objc
JSContext *context = [[JSContext alloc] init];
    
[context evaluateScript:@"var myObject = {};"];
JSValue *myObject = context[@"myObject"];
myObject[@"one"] = @1;
    
[context evaluateScript:@"var three = myObject.one + 2;"];
if (3 == context[@"three"].toInt32) {
    NSLog(@"Cool!");
}
```

I have tried `JX_SetNamedProperty`. But because the `JXValue`s I can obtain via `JX_Evaluate` are only JSON represents, any following process is impossible.

I have looked into the issues, and guess this may be 'Due to isolation of the threads' (https://github.com/jxcore/jxcore/issues/16). But I still want to achieve this.

**Comment by obastemur** [comment]
@coppercash probably you want to use JXcore but not Cordova UI, right? I'm working on Android and iOS samples without Cordova UI. Perhaps you should see there properly. You may still inspect the sources from [this link to see how we used with Objective-C on our cordova plugin](https://github.com/jxcore/jxcore-cordova/blob/master/src/ios/JXcore.m)

**Comment by coppercash** [comment]
Yeah. I believe I have read all your articles and samples about how to use JXCore on iOS, include that one. 
But I want just JS but not HTML/CSS. So I decide to write my own Objc wrapper for JXCore.
I learned a lot from [JXcore.m](https://github.com/jxcore/jxcore-cordova/blob/master/src/ios/JXcore.m). But I can't find what I want (How to set a property to a JS object from native side).

**Comment by coppercash** [comment]
Maybe I should explain myself more clearly

```objc
JXValue userDefaults;
JX_Evaluate("var userDefaults = {}; userDefaults;", "eval", &userDefaults);
    
NSString *name = @"Mr. White";
JXValue userName;
JX_New(&userName);
JX_SetString(&userName, name.UTF8String, (int32_t)[name lengthOfBytesUsingEncoding:NSUTF8StringEncoding]);
    
JX_SetNamedProperty(&userName, "userName", &userName);
```

But I got 
`Assertion failed: (object->type_ == RT_Object && "object must be an Object"), function JX_SetNamedProperty, file ../src/public/jx_result.cc, line 645.`. 
Because what I can get from `JX_Evaluate` is a JSON object.

Really appreciate any help here!

**Comment by plika** [comment]
`JX_SetNamedProperty(&userName, "userName", &userName);`

I think the first 'username' supposed to be 'userDefaults' ?

**Comment by coppercash** [comment]
You are right. Updated. Thanks.
Any idea?

**Comment by obastemur** [comment]
I've added a new test case for (GetNamedProperty && GetIndexedProperty) and tried your scenario there. It just works. 

BTW; the Get methods are newly added. Better sync and get latest!

Any other problem left here ?

**Comment by coppercash** [comment]
Wow, cool! So excited to hear that. 
So JS objects are not returned as JSON anymore?

And there is still something bothers me.
In my test cases, I have statements like
```objc
    JXValue
    through,
    undefined,
    error;
    
    JX_Evaluate("var through = function (value) {"
                "  return value;"
                "};"
                "through;",
                "eval" , &through);

    JX_New(&undefined);
    JX_SetUndefined(&undefined);
    JXValue
    args_0[1] = {undefined},
    shouldBeUndefined;
    JX_CallFunction(&through, args_0, 1, &shouldBeUndefined);
    // shouldBeUndefined is actually RT_Null

    NSString
    *message = @"error message";
    char const
    *c_string = message.UTF8String;
    int32_t const
    length = (int32_t)[message lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
    JX_New(&error);
    JX_SetError(&error, c_string, length);
    JXValue
    args_1[1] = {error},
    shouldBeError;
    JX_CallFunction(&through, args_1, 1, &shouldBeError);
    // shouldBeError is actually RT_String

```

Just like I write in the comments, I get different value type after pass them through JS.
I am gonna try if it changed in the newly updated version.

**Comment by obastemur** [comment]
From the native interface, there is no strict difference between NULL or undefined. We should make this distinction straight. Same applies to Error type. We just mark type_ under JXValue to Error but the underlying JS type is actually string.

**Comment by coppercash** [comment]
1) I updated to the [lasted version](https://github.com/jxcore/jxcore-cordova/tree/master/bin). But the issue still remains. 
What troubles me is not `GetXXXProperty`, but `SetXXXProperty`. 
Because I am still getting `JXValue`s of `RT_JSON` type as represents of real JS objects, `SetXXXProperty` keep yelling
```
Assertion failed: (object->type_ == RT_Object && "object must be an Object"), function JX_SetNamedProperty, file ../src/public/jx_result.cc, line 645.
```
Maybe you can show me your new test case. I can't find it in the commits.

2) But I believe the behaviour of JXValue.type_ should be same with `typeof` in JS.
```
> node                                                                                                                                                                                                               
> typeof new Error("message");
'object'
> typeof "a string";
'string'
> typeof null;
'object'
> typeof undefined;
'undefined'
```

**Comment by obastemur** [comment]
@coppercash latest commit https://github.com/jxcore/jxcore/commit/b60cd9eeeb093078c2fc600da206c83436439de3 deprecates RT_JSON entirely and normalizes the assignments from JS_Null to JS_Undefined. 

Until GetXXXProperty support, RT_JSON was somehow making sense but now RT_JSON === RT_Object hence no reason left to keep it. 

To make it easier to update, I've replaced RT_JSON to RT_Object and removed old RT_Object entirely.

**Comment by coppercash** [comment]
1)
`JX_SetNamedProperty` works now. But `JX_GetNamedProperty` still fails because of 
```
Assertion failed: (object->type_ == RT_Object && "object must be an Object"), function JX_GetNamedProperty, file ../src/public/jx_result.cc, line 690.
```
I am using the binary from [jxcore-cordova](https://github.com/jxcore/jxcore-cordova/tree/master/bin).
Because I can't find anything wired in the code of [jx_result.cc](https://github.com/jxcore/jxcore/blob/b60cd9eeeb093078c2fc600da206c83436439de3/src/public/jx_result.cc), I am gonna try compile myself later.

2) 
Thanks a lot for the change of `undefined`.
Should I expect `Error` object will be returned as a JX_Object?

**Comment by obastemur** [comment]
FYI; JXcore binaries on jxcore cordova project updated to latest.

Error is a bit complicated. It can be either a string or Object.

**Comment by coppercash** [comment]
I have updated them too.

![screen shot 2015-06-07 at 10 41 26 am](https://cloud.githubusercontent.com/assets/3679052/8022404/e1b84648-0d01-11e5-8ac7-30440613d048.png)

See. `JX_SetNamedProperty` works. So I am sure nothing missed when I updated them.
But it still fails on `JX_GetNamedProperty`.

Anyway it is being compiled. Gonna figure out what is wrong after that.

**Comment by coppercash** [comment]
My bad. It should be
`JX_GetNamedProperty(&userDefaults, "age", &outValue);`
instead of
`JX_GetNamedProperty(&userName, "age", &outValue);`

Silly me.

Nothing left here now.

Reaaaaaaally appreciate your help!!!!

**Comment by obastemur** [comment]
Great. Closing then.
