### ISSUE TITLE
Native package error when using request module

### ISSUE THREAD

**Issue by rldcampbell** [jxcore/jxcore#382]
I'm using jxcore v Beta-0.3.0.1 on Windows (x64), js version Google V8 v3.14.5.9

I have created a very simple example program using the 'request' npm module:

```js
var request = require('request');

request.get({url: "http://google.co.uk"}, function(e, r, b) {
    console.log(b);
});
```

If I simply run this using the jx command all is fine and dandy.  I now want to create a native .exe, so run the following command:

```command
jx package test.js "test" -slim "test.exe,test.jxp" -native
```

however, running the resultant test.exe produces the following error:

```command
H:\node_modules\request\index.js.jx:0
(function (exports, require, module, __filename, __dirname, setTimeout, setInt
^
RangeError: Maximum call stack size exceeded
```

Any ideas as to why this is?

**Comment by ktrzeciaknubisa** [comment]
You're right. It happens on Windows, while it works in unix. Let me see into this.

**Comment by ktrzeciaknubisa** [comment]
Ok, it looks like `require('./request')` (node_modules/request/index.js#147) calls `request` module instead of `./request.js`. However it works when you'll append `.js` extension to that line: `require('./request.js')`. This would be a workaround until we fix this.

**Comment by rldcampbell** [comment]
Thanks very much - workaround works no problem

**Comment by ktrzeciaknubisa** [comment]
@rldcampbell The commit above should fix the issue. Could you please try your solution without workaround and let us know?

**Comment by rldcampbell** [comment]
Many thanks for this - it should be very useful, but I'm afraid I've got
other urgent work on at the moment - I will try to test the solution later
in the week though.

All the best,

Robbie

**Comment by ktrzeciaknubisa** [comment]
Thank you!

**Comment by rldcampbell** [comment]
Sorry for the long delay - everything is working just fine, thanks very much!

**Comment by ktrzeciaknubisa** [comment]
Thanks for the update!
