### ISSUE TITLE
jx: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by jx)

### ISSUE THREAD

**Issue by christertamm** [jxcore/jxcore#383]
Like most other people writing here, my goal is to make an executable out of my node.js program. It works excellenty on my Mac with OS X Yosemite, as well as on OpenSuse 13.2, but where I REALLY want to make an executable, on a commercial Suse Linux Enterprise Server 11 SP2 system, I get the error message in the title: "jx: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by jx)". 

SLES11SP2 has glibc version 2.11.3, not 2.14. I have been warned not to try to upgrade such a central part of the system to a newer version, since it WILL break things. 

Is there a way to circumvent this, and get jx to make executables for lower versions of glibc?

**Comment by obastemur** [comment]
Sure you can but you need to compile jxcore from sources there.You may follow [how to compile](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md) tutorial.

**Comment by christertamm** [comment]
I'll try that, thanks for the info!

**Comment by christertamm** [comment]
Compiling from source went fine. Thanx! I have however another problem, which I will report in another thread.
