### ISSUE TITLE
Windows XP Support

### ISSUE THREAD

**Issue by christianromeni** [jxcore/jxcore#385]
In the readme.md it says:
Windows XP+

but on the website it reads:
Windows XP/2003 and below is NOT supported.

Now I'm confused.. Is it now possible to build a x86 windows executable or not?
I HOPE its possible... Otherwise I'm completely out of ideas what to do :(

**Comment by obastemur** [comment]
@christianromeni WindowsXP and below is not supported. We could support it but I don't know if we can prioritize the effort needed for it.

**Comment by christianromeni** [comment]
What kind of effort are we talking about (hours/money).
What is the reason for the missing support? If I know correctly, node supports XP?

And I know XP is old, and should not be used.. But its impossible for me to ignore the people using it, since the target audience is sadly quite a bit behind...... :(

**Comment by obastemur** [comment]
@christianromeni aprox 2 weeks of work at least.. ( assuming SP2 is installed )

**Comment by micksatana** [comment]
Agree with @christianromeni that it's impossible to ignore those in XP. At first I thought it's not necessary until I released a product without XP support. End up, lots of client emails and calls came in until I need to decide moving to other tool. I like JXCore though, but cannot use it yet.

**Comment by ktrzeciaknubisa** [comment]
In fact JXcore was working on Win XP until some point, much before multi-engine support was added (before 2.3.7). I remember that I was able to compile it from sources successfully, but then the runtime was giving headaches by crashes.

If you guys have any wanting and time on your hands, you can try to compile JXcore on XP and see how it's going.

**Comment by obastemur** [comment]
JXcore is based on node.js and I am pretty sure that node.js v10 or v12 are not fully XP compatible. It may work somehow but I would not say it is a production grade.

Even if we make the changes to make JXcore compilable, there is much more to take care of. Besides, XP and XP sp2 are totally separate stories.

**Comment by micksatana** [comment]
@ktrzeciaknubisa I tested on XS sp3 doesn't work. XP will display as error "...not valid win32 application"

@obastemur  I think there's no need to support sp1 and sp2. Most of XP users can upgrade from sp2 to sp3.

Globally, XP usage as of June 2015 is 3.4%. But I got statistics in XP usage in developing country like Thailand in education industry, it's still at ~ 20%

**Comment by ktrzeciaknubisa** [comment]
@micksatana 
> "...not valid win32 application"

Did you compile on XP or you just took ia32 binaries from JXcore downloads page? With the second option - we know it doesn't work. At least I remember so.

**Comment by gitzalm** [comment]
Compiling of tag 3.0.6 is OK with a XP SP3 and VS2010, but exe is complaining about SRWLock which is a feature of kernel32 > Vista. After commenting all stuff about these locks and leaving the fallback locks, it starts and can run some helloworld scripts.
Is it the only known problem ? Using lock fallback impacts performance or also some multi-threading functionalities ?

**Comment by obastemur** [comment]
@gitzalm can you post the changes? i.e. Diff?

**Comment by gitzalm** [comment]
I pushed it here : https://github.com/gitzalm/jxcore/commit/e715cd79f26138a1c19c8ac495c082590edcb52f
It solves compiling and starting (no more dll linking error), yet I am not sure threads locks are still working.

**Comment by ohenepee** [comment]
Guys, to add to the problem... I'm in Africa and will speak for Africans... Windows XP (SP3) usage share is close to 95% and this is only Africa, talk of the other under-developed nation in other continents.

Windows XP SP3 support is a MUST not an OPTION! Besides not everyone will even be deploying to Windows XP, but what about if its your developing environment? I've noticed something about the world  of applications, most frameworks and apps not get popular when they neglect the recently unsupported platforms (e.g. Android 2.x and Windows XP)

**Comment by obastemur** [comment]
@gitzalm thanks for the work there. Instead of removing them all, can we use compile time + run time switches ? Would you like to PR WinXP initial support ?

**Comment by christianromeni** [comment]
That actually looks not that complicated.. Wondering why it would be worth 10.000 as offered to me when I asked for it :)

**Comment by obastemur** [comment]
Don't know business details though but just a reminder from my comment:
> Would you like to PR WinXP initial support ?

**initial support

There is no promise here for a problem free execution, we know there are lots of things need to be done. However we must let other people benefiting @gitzalm effort and carry it forward when it's possible. We do not own JXcore hence we should allow community touch to this project. 

I saw the problems back to node.js core source days. Somebody needs to address them + some of them are really open ended. IMHO, XP support is a long way to go.

Yet; This is an open source project and unfortunately WinXP is not a priority for any of our `sponsors`. We do need sponsort though! We do have life and bills to pay while spending our lives around JXcore. Considering the amount of work needs to be done for proper XP support and an average core developer salary.. I would say that number is seriously enthusiastic. It sounds like, give us a chance to push this forward. 

I'm not a business person. IMHO, I would really like to keep anything business outside the source code repos. Thanks for opening this Github issue and encouraging other people to contribute to a solution.

**Comment by lygstate** [comment]
Is the rwlock are the only problem that nodejs faced, this is easy to fixup with CriticalSection

**Comment by gitzalm** [comment]
Got some time to find an hint : why nodejs/uv 0.10.40 does not have the same starting problem than jxcore/uv 3.0.7 ?
Lack of SRW Locks issue on XP is due to some added functions uv_*ThreadKey in uv.h and winpthreads.h : it relies on pthread_rwlock_wrlock, calling SRW lock, which does not exists in kernel32.dll before Vista. In uv thread.c there is always a test:
if (HAVE_SRWLOCK_API())
Could jxcore use same fallback than uv and not use a winpthread that needs Vista+ kernel32 ?

**Comment by gitzalm** [comment]
Tryed ftp://sourceware.org/pub/pthreads-win32/dll-latest/ (replacing winthreads.h, adding lib for linking and dll in path) : it starts.

**Comment by obastemur** [comment]
> Got some time to find an hint : why nodejs/uv 0.10.40 does not have the same starting problem than jxcore/uv 3.0.7 ?

Because JXcore has multi-tasking

How about mutex fallback on XP ?

**Comment by gitzalm** [comment]
Yes that is what I am seeking, a pthread lib for Windows XP, the one from sourcewave.org is OK. Modifying winpthreads.h could also be done, I do not know how to replace SRW locks.
I also had an issue with a native module launching an uv thread, but that was because *.h came from ~/.node-gip/jxb304 and not from my modified jxcore/deps/uv (to remember if someone else wants to do the same : check node-gyp includes).
This hack is tricky but can be quite easily done, at least until XP users migrate to something newer (Linux, OSX, Windows, Android...) That is still the question about XP, how many dev time for supporting an abandonned OS.

**Comment by gitzalm** [comment]
But for 10000$ sure it can be done :smile:

**Comment by gitzalm** [comment]
By the way, how is the header archive jxb###.tar.gz generated ?

**Comment by lygstate** [comment]
Where is the 10000$ :smile:

**Comment by obastemur** [comment]
Thanks for updates. In case anyone into contributing the feature welcome. Closing this thread.
