### ISSUE TITLE
Server does not work with Mongoose in MEAN.js framework

### ISSUE THREAD

**Issue by zlatinejc** [jxcore/jxcore#388]
a). setup default MEAN.js project on Windows
b). run jx on server.js
c). require('mongoose') fails, with no error code

C:\Projekti\Razvoj\testMongoose\mean>jx server.js
-- blank -- "nothing happens"
C:\Projekti\Razvoj\testMongoose\mean>

d). It should be running a server like this:

MEAN.JS - Development Environment application started
Environment:                    development
Port:                           3000
Database:                       mongodb://localhost/mean-dev

**Comment by obastemur** [comment]
What was the result for   'jx -jsv' ?

**Comment by zlatinejc** [comment]
Google V8 v3.14.5.9

**Comment by obastemur** [comment]
It works; 

- Download MEAN.JS
- unzip and go under the folder on terminal
- sudo jx install
- jx server.js

probably you used 'npm install' instead of 'jx install'.

**Comment by zlatinejc** [comment]
No luck here. Still get the same void / "" no error report.

**Comment by zlatinejc** [comment]
It just could be some dependecies failure, I don't know.

**Comment by obastemur** [comment]
Did you try a clean install? Which platform by the way?

**Comment by zlatinejc** [comment]
yes, just did that. Windows 8 x64 is my working platform.

**Comment by zlatinejc** [comment]
although it works on Centos 7 :)

**Comment by ktrzeciaknubisa** [comment]
@zlatinejc Few questions for you:

1. when I type `jx server.js` indeed it acts like it does nothing for few secs. I was impatient and I wanted to CTRL+C it, but then suddenly the output came up "MEAN.JS - Development Environment application started". Are you sure that is not your case with terminating too fast?

2. how can you tell, that `require('mongoose')` fails? There is no output after all - were you trying to debug?

3. did `jx install` called from meanjs app succeeded for you? I myself have received few errors (they got lost in large console output), but running `jx install` again showed them back:

    ```bash
'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! phantomjs@1.9.17 install: `node install.js`
```
    I guess it is related to #290. Once I copied `jx.exe` into `node.exe` the installation went fine.

4. What are your steps for "setup default MEAN.js project on Windows". I've followed @obastemur steps and I never saw --blank-- output. Only the errors mentioned above.

**Comment by ktrzeciaknubisa** [comment]
@zlatinejc if you ever had a problem with no 3. mentioned above by me - it should be solved now with the commit. Perhaps you may try a clean `jx install` and see how it goes? (removing `~/.jx` folder is necessary before that).

**Comment by zlatinejc** [comment]
@ktrzeciaknubisa Sory for my late response, emergency node fix had to be done :)

It is working now, all i needed to do is upgrade my node.js version to the latest one.
After doing that I just ran jx install and the server started normally.

Tnx for your help.

**Comment by zlatinejc** [comment]
@ktrzeciaknubisa and to answer your questions:

1. in my case the console exited it's processing, no waiting is needed

2. I commented out a bunch of requirements in my app, so It led me to the mongoose module

3. install went through successfully

4. default steps were just getting the latest version of mean, install and run at the end

**Comment by ktrzeciaknubisa** [comment]
Thanks @zlatinejc 

> It is working now, all i needed to do is upgrade my node.js version to the latest one.

I'm confused :) Are you saying, that having **node** executable in %PATH% made your app working even with `jx server.js` command? JXcore should manage without any node binaries, could you try that?

**Comment by zlatinejc** [comment]
Yes it works even without having node executable in %PATH%.

Yes it works without any node binaries.

I do not know what I did beside installing newer version of node. Maybe my npm were a bit messy, I usually don't pay to much attention to them :( ?

**Comment by ktrzeciaknubisa** [comment]
Can you please do one more test: 
- remove also npm from %PATH% 
- do a fresh `jx install`  on your mean.js app
- try to start the app?

**Comment by zlatinejc** [comment]
Hi, ok so I got this after jx install

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\JXcore\\jx.exe" "C:\\Users\\nejct\\.jx\\npm" "install" "--loglevel" "http"
npm ERR! cwd C:\jxMeanTest\mean
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\jxMeanTest\mean\npm-debug.log

I ran the server.js with jx server.js and the server started normally.
I got:

MEAN.JS - Development Environment application started
Environment:                    development
Port:                           3000
Database:                       mongodb://localhost/mean-dev-

But my client (angular app) did not build successfully.
The client said: 
Uncaught ReferenceError: angular is not defined

So

**Comment by ktrzeciaknubisa** [comment]
Thank you for your effort @zlatinejc . The error "'node' is not recognized as an internal or external command," should be already resolved, probably you didn't remove `%HOME%\.jx` folder before `jx install` ? (I mentioned this few comments before).

For the angular - I wasn't checking it yet.

**Comment by ktrzeciaknubisa** [comment]
Is there anything left here to be solved? I just checked a simple MEAN.js app with the latest JXcore 0.3.0.4 and it didn't find any problems. I'm closing this. @zlatinejc If you'll have any further issues, just let us know!
