### ISSUE TITLE
performance ~

### ISSUE THREAD

**Issue by lordard** [jxcore/jxcore#389]
Actually , I awared jxcore several hours ago ...
I am pretty exciting about the porting of nodejs in spidermonkey 
So  , I have made some test to check the performance of jxcore
I wrote a test program which include file io and buffer operation.
Test result is  ... ( i just compare IOjs and Jx )
IOJS  2.2.1 : 21ms
Jx V8  0.302 : 17ms ( JxV8 0,302 equal to Nodejs 0.10.38 )
Jx SM 0.302 : 168ms
Why ?? SM is so .... slow ....

**Comment by ktrzeciaknubisa** [comment]
What exactly is doing your test program? Can you share with the code?

**Comment by obastemur** [comment]
@lordard See https://github.com/obastemur/NodeEngineBenchmark for a benchmark.

**Comment by lordard** [comment]
@ktrzeciaknubisa   I just  load a data file  which is around 164K bytes and parse it to create a lot of related small objects and copy data from raw to newly created objects' buffer memory.
I will upload the test codes and file later.

**Comment by plika** [comment]
@lordard Instead of doing a micro benchmark, what don't you run the benchmarks from @obastemur 's suggestion. Those are the benchmarks used by Google, Apple etc. to specifically test the JS engine performance. 

I'm looking forward to see the results though.

**Comment by lordard** [comment]
@plika  Sorry , I think I use the wrong  word "test".
The result is the real case of my program , not a program for "test" purpose.

**Comment by lordard** [comment]
The code and data file located at    https://github.com/lordard/ezDcmObj
you can check that by using     >node dcmtest.njs

**Comment by obastemur** [comment]
@lordard The reason is SM JIT and baseline compiler do not engage directly.  If you can turn your sample into something running for a longer time (i.e. 2k loops) the perf will be more visible. 

SM by default uses JIT after a ~1000 calls to a function. 

Actually, Sunspider and Octane [here](https://github.com/obastemur/NodeEngineBenchmark) already do the similar tests in a bigger scale.

**Comment by lordard** [comment]
@obastemur  Got it . thanks

**Comment by lordard** [comment]
@obastemur   I check the total items , I found there is more than 6000 calls to inner functions.
![result](https://cloud.githubusercontent.com/assets/12387337/8127001/395a752e-1126-11e5-9bba-163f27822a17.png)

**Comment by lordard** [comment]
@obastemur  I will make a loop test about that to check the result as well

**Comment by obastemur** [comment]
@lordard can you please use the approach from https://github.com/obastemur/NodeEngineBenchmark/blob/master/runTest.js to init the tests after all. This approach will discard the runtime related time consumption from the final result.

**Comment by lordard** [comment]
I know there is a lot of official test program and report about SM and V8.
But they are just "test" , not my application.
I am just wondering why JxSM is around 11X slower than JxV8.
Maybe my code is bad... but ...  why JxV8 running well ?
I don't know why ...11X slower ...

![running result](https://cloud.githubusercontent.com/assets/12387337/8146931/9a880480-1287-11e5-93dc-88faa7ec89bd.png)

**Comment by obastemur** [comment]
I see the reason. Buffer indexed access. ArrayBuffer is more cross engine friendly (in terms of performance).

**Comment by lordard** [comment]
@obastemur   I have modified my codes to use the ArrayBuffer , and the result is ...
in JxV8 :  from 34ms to 31ms/34ms ( almost the same ) 
in JxSM :  from 176ms to 214ms  ( worse )

I really don't know why

**Comment by obastemur** [comment]
@lordard can you please update your repo with the updated codes ? I would like to catch the issue

**Comment by lordard** [comment]
@obastemur  Thanks . 
 I will do some test in advance to lower your loading .

**Comment by lordard** [comment]
@obastemur  I found something strange.
If the codes create small objects after parsing but do not copy data from raw.
The Jxv8 2X faster than original. from 20ms to 10ms
The Jxsm improve a little .... from 168ms to 128ms

If codes create only one temp object to catch the data instead of the creation of small objects and the array push . The speed is almost the same.
JxV8 : 10ms
JxSM  : 122ms

Do you have any idea about this ?
