### ISSUE TITLE
We need a cleanup switch for 'jx install'

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#390]
Android APK doesn't support adding .gz files into assets. We can add a command line option to 'jx install` that will cleanup given extension/folder during the installation. For example, there is no point keeping all the docs / tests folder of a node module on a mobile application. 

```
jx install semver --autoremove '*.gz;doc/;help/;samples'
```

/cc @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
Implemented. Works for multiple modules, too, e.g.:

```bash
jx install semver jsm --autoremove '*.gz;doc;help;samples'
```

I disabled this option for `-g` / `--global` usage. Any need for this?

**BTW**: I had temptation to move install logic (`Installer()` method) out of `node.js` file, would that be ok?

**Comment by obastemur** [comment]
IMHO, that is totally fine but let's do it after 3.0.0.3 release.

**Comment by ktrzeciaknubisa** [comment]
One thought about `;` separator used in `--autoremove`: we have similar two cases when we use paths separated in command line (`jx package -slim` and `-add`), but there a comma `,` is used. 

Isn't it better to make it uniform? Can we leave comma as default (`-slim` and `-add` exits much longer in JXcore)? Plus we may provide an option for setting an env variable e.g. JX_ARG_SEP?

**Comment by obastemur** [comment]
Sounds good

**Comment by ktrzeciaknubisa** [comment]
Ok, this commit 3c087db7add528dbacb0ca911b1d7ce5901a2438 changes `--autoremove` semicolon separator into comma (default). 

Applying custom separator may be accomplished by setting env variable `JX_ARG_SEP`:

Unix platforms: 
```bash
export JX_ARG_SEP="@"; jx install semver jxm --autoremove "*.gz@samples"
```

Windows:
```bash
set JX_ARG_SEP="@" && jx install semver jxm --autoremove "*.gz@samples"
```

**Comment by obastemur** [comment]
did we documented this ? (jxcore.com/docs also need an update)

**Comment by ktrzeciaknubisa** [comment]
The docs updates are unfinished yet, I'm working to include them into 3.0.3.

**Comment by ktrzeciaknubisa** [comment]
> BTW: I had temptation to move install logic (Installer() method) out of node.js file, would that be ok?

Done now with 4163bbdd430701f76b32042cfe4d411053eccd26 .
