### ISSUE TITLE
JXCore in Android - (bool ThingIsPermanentAtom<JS::Symbol>(JS::Symbol*)+4)

### ISSUE THREAD

**Issue by oriharel** [jxcore/jxcore#401]
I began to get jxcore crashes in my Android app, when I call stopEngine().
This is what I see in the logs:

--------- beginning of crash
06-17 21:36:54.102      371-371/? I/DEBUG﹕ #00 pc 0036a19c  /data/app/org.capriza.local.store-2/lib/arm/libjxcore.so (bool ThingIsPermanentAtom<JS::Symbol>(JS::Symbol*)+4)

Any idea what is it?

**Comment by obastemur** [comment]
need rest of the log though but when you are calling stopEngine?

**Comment by oriharel** [comment]
It's the SyncAdapter scenario again. Sync is done periodically. When performSync is done, I'm stopping the engine.

**Comment by obastemur** [comment]
You shouldn't stop the initial instance. Please read to documentation given from https://github.com/jxcore/jxcore/issues/395
