### ISSUE TITLE
JXcore 0.4 Roadmap / Node 0.12

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#402]
This is an open item that we are going to bring the new API from 0.12 into JXcore. 

At the moment, most urgent module is 'crypto' and rest will follow. Any suggestions welcome.

**Comment by kzc** [comment]
By API, do you mean the JS API?

Any plans to upgrade the v8 engine?

**Comment by obastemur** [comment]
i.e. new crypto API etc. Consider 0.4 will be equivalent of 0.12 (including v8 version used)

**Comment by plika** [comment]
So initial quick list can be buffer, streams, crypto. Perhaps we are going to touch the other modules on the way. 

I don't expect much problem with newer v8 version. Are we going to add another abstraction for it or just replace it with the current one for 0.4 ?

**Comment by obastemur** [comment]
Update: The work for node 0.12.x is started under 0.4.0.0 branch.

**Comment by plika** [comment]
Started create work items: NPM - https://github.com/jxcore/jxcore/issues/439

**Comment by vanga** [comment]
Hello,
If I package a nodejs application using jxcore 0.3.x , what will be the version of node binary that gets packaged along?
I guess it will be what ever jxcore version is shipped with, not the latest nodejs. 
For Ex: If I package a nodejs app with this version http://jxcore.com/docs/ , Node version will be v0.10.39, right?

**Comment by obastemur** [comment]
@vanga Yes. P.S. Better ask / open that or next question or another comment with this subject under a new issue.

**Comment by brodybits** [comment]
Node.js has 4.0 RC which has cutting-edge performance enhancements from v8, among many other things: http://apmblog.dynatrace.com/2015/09/05/all-you-need-to-know-about-node-js-4-0/

Should we really put much more energy into supporting the old node version 0.12?

**Comment by obastemur** [comment]
closing this one in favor of https://github.com/jxcore/jxcore/issues/535
