### ISSUE TITLE
SM: --v8-options should show error message and exit

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#405]
SM build doesn't take '--v8-options' into account. Expected behavior is 'show error message and exit'

/cc @plika , @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
Then probably we should embed list of all available options `--v8-options` (only SM build)?

**Comment by obastemur** [comment]
no need. we can keep it limited to this one. rest is not going to function anyways
