### ISSUE TITLE
allowedResourceTypes error

### ISSUE THREAD

**Issue by frankglv** [jxcore/jxcore#408]
Hi,
I'm working on nodejs.
I'm trying to add new file types to JXM.io linkResourcesFromPath.
Following the documentation, this is my code:

server.allowedResourceTypes.csv = "text/csv";

Easy enough.
But the compiler says that allowedResourceTypes is undefined. 
I have also tried to overcome the undefined issue forcing the object creation:

server.allowedResourceTypes = {};
server.allowedResourceTypes.csv = "text/csv";

no way.
Any idea? Is this just a bug?

Thanks

**Comment by ktrzeciaknubisa** [comment]
Hi, thanks for reporting, even if [jxm/issues](https://github.com/jxcore/jxm/issues) would be a better place for this :)

Yeah, this might be a bug. Could you please edit `backend/jxm.js` file line 183 and change `mediaserver.types` into `mediaserver.mediaTypes` and see if this work for you?

**Comment by frankglv** [comment]
Sorry for the wrong github channel!

I have made the mediaserver.mediaTypes change you suggested. Now
the allowedResourceTypes object is not undefined anymore. But no way to add
a new file type via the documentation suggested way. But I have found a
solution inspecting the existing object keys:

This doesn't work:
server.allowedResourceTypes.csv = "text/csv"

This works:
server.allowedResourceTypes[".csv"] = "text/csv"

Now I can access the csv file!
So: thank you! Hope this helps :-)

Do I need to remove my original post?

Thanks,
Francesco



2015-06-19 16:30 GMT+02:00 Krzysztof Trzeciak <notifications@github.com>:

**Comment by ktrzeciaknubisa** [comment]
We can leave the post how it is. I'm glad that you found a way and it works for you.
Thank you once again for the report. We'll update `jxm.js` and docs!

**Comment by ktrzeciaknubisa** [comment]
[Docs](http://jxcore.com/docs/jxcore-messaging.html#allowedresourcetypes) updated. The `mediaType` property, too. However we're not releasing the update on npm yet (we have other pending fixes uncompleted), but we'll inform when it happens. 

Thanks!
