### ISSUE TITLE
How to get global object from the native side ?

### ISSUE THREAD

**Issue by agenthunt** [jxcore/jxcore#412]
How to get global object from the native side ?
or what is the equivalent of 
[JavaScriptCore's  JS_EXPORT JSObjectRef JSContextGetGlobalObject(JSContextRef ctx);](https://developer.apple.com/library/mac/documentation/JavaScriptCore/Reference/JSContextRef_header_reference/#//apple_ref/c/func/JSContextGetGlobalObject)

**Comment by obastemur** [comment]
Just added. Sync to latest and see [this test file](https://github.com/jxcore/jxcore/blob/master/test/native-interface/test-global/test-posix.cpp) for usage

**Comment by agenthunt** [comment]
Thanks @obastemur for the super quick add. Will check it out.

**Comment by obastemur** [comment]
NP. This was planned anyways ;)

**Comment by agenthunt** [comment]
Great!!!. Tested with ios. Seems to be working fine.
