### ISSUE TITLE
Support for babel js?

### ISSUE THREAD

**Issue by malkomalko** [jxcore/jxcore#413]
Is there an example of getting JXCore to work with Babeljs? https://babeljs.io

Ideally there would be an option where you don't have to transpile.  Thanks for JXCore, it is a great library.

Cheers

**Comment by obastemur** [comment]
@malkomalko Thanks. 

Too many libraries and impossible to prepare sample for every single of them. Babeljs is really nice it should work as is though. 

See https://babeljs.io/docs/setup/#node   (you might use 'jx install' instead of 'npm install' if it's not installed)
