### ISSUE TITLE
JX incorrectly states that "process" is a function in Android

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#415]
When calling:

```Node.js
{}.toString.call(process).toLowerCase()
```

One expects (and both Node.js and JX on the desktop will return) "[object process]".

But if one uses JX on Android then one gets "[object function]".

This discrepancy matters because projects like Bluebird (see [here](https://github.com/petkaantonov/bluebird/blob/6ef7cfa417b98f62f4a9fbf51b6974e0085f8c20/src/util.js#L295)) depend on this as a test of if they are running in Node.js.

I believe this is the exact same issue that @sreesharp ran nto so you may already have a resolution. But I do think that JX needs to return the right thing here.

**Comment by obastemur** [comment]
Is this 'process' only ?

**Comment by ktrzeciaknubisa** [comment]
Indeed there were differences for SM. Now the tests are passing:

```bash
$ sudo make test-jxcore-message
```
Which takes a jx binary from `out/Release/jx`. Or, having separately compiled different engines, we can test them this way:

```bash
$ jxsm test/run.js jxcore-message
$ jxv8 test/run.js jxcore-message
```
