### ISSUE TITLE
Jxcore Android sample?

### ISSUE THREAD

**Issue by tom91136** [jxcore/jxcore#416]
I see that there's a [project](https://github.com/jxcore/jxcore-ios-sample) going live a few hour ago about using jxcore on iOS without the Cordova plugin, are there any plans for Android as well? Will there be support for running jxcore on Android without any other plugins?
I've seen the old [sample](https://github.com/obastemur/jxcore-android-basics) which is spot on but the page says it's a bit dated though.

**Comment by obastemur** [comment]
@tom91136 This is on our short list @plika any update?

**Comment by oriharel** [comment]
@tom91136 check out https://github.com/oriharel/jxcore-android-sample.git

**Comment by tom91136** [comment]
:+1:
