### ISSUE TITLE
Failing to uninstall JXcore

### ISSUE THREAD

**Issue by GcodeS** [jxcore/jxcore#420]
I'm on Mac OSX Yosemite. When running `jx install -uninstall` I get this:
```
npm WARN invalid config local-address=undefined
npm ERR! npm uninstall <name>[@<version> [<name>[@<version>] ...]
npm ERR! npm rm <name>[@<version> [<name>[@<version>] ...]
npm ERR! not ok code 0
```

Not sure if I don't have the right command or if its an error.

**Comment by ktrzeciaknubisa** [comment]
When uninstalling something you need to provide a module name. This is a syntax of npm:

```bash
$ npm uninstall
npm ERR! npm uninstall <name>[@<version> [<name>[@<version>] ...]
npm ERR! npm rm <name>[@<version> [<name>[@<version>] ...]
npm ERR! not ok code 0
```

**Comment by GcodeS** [comment]
So your saying my command should be `npm uninstall jx` ? Thanks for the quick reply.

**Comment by ktrzeciaknubisa** [comment]
What in fact are you trying to do? Uninstall JXcore? 

The `jx install -uninstall` is not for this purpose. It is for uninstalling npm modules, e.g. `express`:

```bash
$ npm uninstall express
$ jx install -uninstall express // depreciated
$ jx npm uninstall express // actual
```

**Comment by GcodeS** [comment]
Yes, I am trying to uninstall JXcore. Apparently I must have misinterpreted something.  What is the proper way to uninstall JXcore then?

**Comment by ktrzeciaknubisa** [comment]
On Windows - remove a program from control panel. On unix systems - should be enough to remove a single `/usr/local/bin/jx` file.
