### ISSUE TITLE
v0.3.0.3 doesn't work

### ISSUE THREAD

**Issue by leejoo71** [jxcore/jxcore#421]
Hi,
 when I using v0.3.0.0 with jx mt:3 test1.js -m and it is work, but after install v0.3.0.3 and same command, it doesn't work with any error message return?

**Comment by obastemur** [comment]
@leejoo71 can you share the environment (OS), engine (SM or V8) and test1.js ?

**Comment by leejoo71** [comment]
Windows Server 2008 R2 Enterprise x64 i& 16.0GB RAM V8 installed

**Comment by ktrzeciaknubisa** [comment]
We need to know a little bit more about what your test1.js is doing? Is it small enough to be pasted here?

**Comment by leejoo71** [comment]
Hi ktrzeciaknubisa, I trace my code, it is the native modules cause it's halt, such as limdu & node-sqlserver. when calling limdu = require('limdu'); then program stop and return to command prompt. when I remark all modules with native code then it work again. it is work on v0.3.0.0

**Comment by ktrzeciaknubisa** [comment]
Could you please try to reinstall you native modules with `jx install` (not `npm install`) ?

**Comment by leejoo71** [comment]
ok thanks, I'll try it later. it is because some of modules are work in process

**Comment by ktrzeciaknubisa** [comment]
I'm testing on Windows 7 & 8 `var limdu = require('limdu');` (without any other dependencies) and it works regardless if i used `jx install limdu` or `npm install limdu`. 

Can you please check if this simple test passes on your platform?

Also, there is JXcore 0.3.0.4 published - you might want to try that too.

**Comment by leejoo71** [comment]
Hi,

Sorry for late. I just tested with the 0.3.0.4 with jx install limdu and npm install limdu and both are work with limdu

Thanks

**Comment by ktrzeciaknubisa** [comment]
Thanks, so the initial issue is solved, I guess? I'm closing this then.
