### ISSUE TITLE
JX install gives odd error when installing from local directory

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#428]
I ran 

```
jx install --autoremove "*.gz" [path to a directory with package.json]
```
The command appears to have worked correctly but at the end it gives me an error message:

```
Cannot find expected folder of installed module: [path to the directory I pointed it at above]
```

When I issued

```
npm install [path to a directory with package.json]
```

Everything worked fine without any error.

Just an FYI.

**Comment by ktrzeciaknubisa** [comment]
Oh, yeah. Looks like autoremove was implemented for cases when modules names are provided directly in `jx install` command (not through package.json). It was important to know exactly, where the modules were installed - it doesn't have to be cwd folder, it might be one of parent node_modules folders (so we check it by `jx npm -ls modulename`) to make sure, we don't autoremove things from somewhere else.

I guess we need to scan package.json and run the same check per each dependency. TODO.

**Comment by ktrzeciaknubisa** [comment]
The 0.3.0.5 branch (and current master) handles the issue. In order for this to work, the `~/.jx/` folder needs to be manually removed.

**Comment by yaronyg** [comment]
Do you mean we need to manually remove it forever or we need to manually remove it once because it's a left over from old code that isn't needed anymore?

**Comment by ktrzeciaknubisa** [comment]
I meant just once. This is because the npm for JXcore was updated, but if you're already using JXcore 0.3.0.5 - it will not force download npm, unless it is deleted. Just once :)

**Comment by obastemur** [comment]
FYI; (0.3.0.5) is not a released version.
