### ISSUE TITLE
edit file inside package

### ISSUE THREAD

**Issue by fithwith** [jxcore/jxcore#430]
after packaging my app can I use fs to modify a file inside the package ?

**Comment by obastemur** [comment]
@fithwith no, it's not supported.

**Comment by ktrzeciaknubisa** [comment]
However the workaround came to my mind: you may modify the in-memory copy of that file by your own means (plus store the result in your cache) and for later `fs.readSync()` you can use fs extension methods to read the file from that cache. How about that?

**Comment by fithwith** [comment]
yes but it will store the file outside the package, I already planned to use this method if there is no another solution.

anyway I will move to the plan B thank you for your quick reply :)

**Comment by ktrzeciaknubisa** [comment]
It the files are small and few, you may keep them in-memory as strings or buffers (no need to use `fs.write()` etc.). Or you may keep them in local sqlite db or even in [memory store](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-store.markdown).

**Comment by fithwith** [comment]
I encrypted the files and stored it ouside the package.

thank you for your advise guys :+1: 
you can close the ticket.

**Comment by ktrzeciaknubisa** [comment]
Thanks! Closing then.
