### ISSUE TITLE
Cracking jxcore

### ISSUE THREAD

**Issue by darrrk** [jxcore/jxcore#436]
Hey, it's not good if I can googling how to crack my protected code:
http://markhaase.com/2015/06/25/cracking-jxcore-again/

Maybe need complicate encrypt algorithm and hide source code of this part.

**Comment by obastemur** [comment]
Open source JXcore doesn't provide any encryption. JXcore's all source codes are accessible from Github and it's visible. That person clearly needs / after an attention and uses the open sourced version of JXcore.
