### ISSUE TITLE
Plesk logouts, cannot manage subscriptions

### ISSUE THREAD

**Issue by movingbits** [jxcore/jxcore#447]
I have been using jxcore for some time now without any problems. 

But today i noticed that when i try to manage jxcore from the plesk panel i get logged out of the panel after a few (3 or 4) clicks.

Because of this i can't manage my jxcore subscriptions anymore.

**Comment by ktrzeciaknubisa** [comment]
> But today i noticed ...

I suppose you didn't perform any manual update of JXcore binary or extension and it occurs just like that? Maybe your Plesk has updated itself recently and has problems with JXcore extension?

**Comment by movingbits** [comment]
No updates to JXcore. Yes Plesk updates itself, current version 11.5.30 Update #50

**Comment by obastemur** [comment]
Seems they did an update on Plesk extension API.

**Comment by movingbits** [comment]
WDo you that updating jxcore could help?

**Comment by ktrzeciaknubisa** [comment]
I don't think so. JXcore has nothing to do with logging out of the Plesk panel. I suspect unhandled bug in one of Plesk's updates. I'll try to observe it on our platforms, however if the problem is on their side, that issue should be reported to them.

**Comment by ktrzeciaknubisa** [comment]
Can you provide more details steps, what exactly are "few (3 or 4) clicks" ? Is it reproducible in specific click pattern or just clicking no matter what?

**Comment by movingbits** [comment]
It's jusst clicking random in the jxcore pages. The logout seems to be random, most of the time after pressing 3 or 4 buttons in the jxcorepages. My today highscore is  6 button presses.

Checked in Chrome and IE, both same problem so i guess it's a serverside thing.

**Comment by ktrzeciaknubisa** [comment]
Thanks. Ok then, so which buttons are we talking about? Buttons call some php code, I wonder if this affect the session somehow. Also: what happens if you don't click buttons, just the tabs?

**Comment by movingbits** [comment]
Looks like any button, tab or link can cause a logout. Clicking tabs 3 or 4 times also cuases logout

**Comment by ktrzeciaknubisa** [comment]
Do you have any other extensions installed? I was just thinking if going through their tabs will not trigger logout too?

**Comment by movingbits** [comment]
I only have some default parrallels extentensions installed on this server.

**Comment by ktrzeciaknubisa** [comment]
I just tested JXcore extension for Plesk on an exact version:

> Panel version 	11.5.30 Update #50, last updated at May 15, 2014 11:34 AM

but I am not witnessing any logouts and I was pressing each of the tabs and few buttons dozens times for few minutes.

Are you still having the problem?    

BTW. You haven't mentioned but which extension's version are you using?

**Comment by ktrzeciaknubisa** [comment]
@movingbits Hi, could you please try the unofficial [dev version 2.0.6.2](https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk_2.0.6.2.zip) of JXcore for Plesk extension and let us know if that works for you? We're going to make an official update beginning of next week.

**Comment by ktrzeciaknubisa** [comment]
@movingbits Also, after the extension's update, please upgrade JXcore to the latest 0.3.0.5. Thanks!

**Comment by ktrzeciaknubisa** [comment]
The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).

@movingbits Please let us know if you still have any problems.

**Comment by movingbits** [comment]
Updated JXcore to 0.2.7. But now i cannot start the manditory update because after three/four clicks i still get logged out. Is there a way to manualy update jxcore?

**Comment by movingbits** [comment]
Pressing the update to 0.3.0.5. button gives and http 400 response. This is a big problem because i can't get jxcore up and running on this server!

GENERAL
Remote Address:xxx.xxx.xxx.xxx.:8443
Request URL:https://xxx.xxx.xxx:8443/modules/jxcore-support/index.php/index/jxcore
Request Method:POST
Status Code:400 Bad Request

FORM DATA
forgery_protection_token: xyz
jx_binary_install_uninstall:install
jx_monitor_start_stop:nothing
jx_app_min_port:10000
jx_app_max_port:20000
hidden:

And this is followed by a logout.

In other random logouts i don't see http errors

**Comment by ktrzeciaknubisa** [comment]
You can try to download a binary manually from http://jxcore.com/downloads/ . Then see if you have any folder e.g. `jx_ub64v8` (may be different for your platform) under `/opt/psa/var/modules/jxcore-support/`. Put the unpacked binary there. But still, JXcore Monitor needs to be restarted, usually this is done from a Plesk panel, but since you have logouts, even this might be not possible for you.

Some though came to me, might be unrelated, but worth checking: navigate to Plesk / Server Management / Tools And Settings / IP Addresses. Then click Reread IP button and see on the list below if they are not marked with a warning?

**Comment by movingbits** [comment]
No problems or warnings with the ip adresses

**Comment by movingbits** [comment]
There is a jx_rh32 directory. Strange because the server is running Ubuntu 12.04.5 LTS. Which binary can i use?

**Comment by ktrzeciaknubisa** [comment]
You can download both (stick to V8 engine) and test `./jx -jxv`. If it works than use that one.

**Comment by movingbits** [comment]
So i should for example just unpack jx_rh64v8 in the jx_rh32 directory? Or should i add a jx_rh64v8 dir and remove jx_rh32 dir?

**Comment by movingbits** [comment]
Or is it better to replace it with Ubuntu version?

**Comment by ktrzeciaknubisa** [comment]
Better it is to leave how it was. Your apps on domains in JXcore extension were working before all that problems started, right? Then I assume they were working with jx_rh32 if you have that folder. Anyway you can go to "JXcore Configuration" tab and there is a path displayed there. 

Whatever binary you will use, put in into the existing folder (do not create new one, as ti will not be visible for JXcore extension).

**Comment by movingbits** [comment]
Apps where working fine. Path found, i understand. Just to make sure. there is no rh32 3.x.x version (Currently installed is rh32 2.3.7), can i just install/move jx_rh64v8 in the rh32 folder?

**Comment by ktrzeciaknubisa** [comment]
And what "JXcore Configuration" tab says about JXcore version? 2.3.7 too? And the path is `
/opt/psa/var/modules/jxcore-support/jxcore/jx_rh32` ?

If that's the case, you have a very old JXcore version. 

Yes, put it into rh32 folder. But I'm not sure whether jx_rh64v8 or jx_rh32v8. If 64 works for you, then I guess you may use that.

Please also reconsider if you it would be possible for you to uninstall the extension and install the latest from the scratch. You may though loose domains and subscription settings. But if you had just few apps/domains maybe this would not cause you trouble?

If not we can still go trying the manual way... (but still no guarantees that we succeed)

**Comment by movingbits** [comment]
I thought it would be the best option to remove and reinstall the extension.

But on extension install i get:

Error: Cannot download file https://jxcore.s3.amazonaws.com/0305/jx_rh32v8.zip. Please check the internet connection or whether this platform is supported or not.

It is still revering to rh32

This is my server

CPU	GenuineIntel, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Version Parallels Plesk Panel v11.5.30_build115130819.13 os_Ubuntu 12.04
OS Ubuntu 12.04.5 LTS

**Comment by movingbits** [comment]
cat /proc/version 

Linux version 2.6.32-042stab103.6 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Jan 21 13:07:39 MSK 2015

**Comment by ktrzeciaknubisa** [comment]
Well, that's because we offered compiled JXcore binaries for RedHat 32 only for v2.3.7... Your PHP installed somehow reports x32. 

But if this is 64 you may now do one of two things, both described on the blog post [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/) - the *Custom JXcore version appliance* section. 

So simply put a line `arch=64` into `/opt/psa/var/modules/jxcore-support/jxos.ini` file, then go into the extension and try to proceed. This will force any future updates to use 64 binaries instead of 32.

**Comment by movingbits** [comment]
I'm very sorry for al these questions, i'm not a linux expert... Obviously ;)

But i get: Error: Cannot execute `jx -jxv`. Is the binary downloaded for the right platform?

tried 
platform = ub & rh
arch = 64

Always get the same error

**Comment by movingbits** [comment]
in /opt/psa/var/modules/jxcore-support are 2 folders /jxcore and /jx-rh64v8 with both a jx file of the exact the same size.

**Comment by ktrzeciaknubisa** [comment]
So you may have x32 after all... Are you able to compile JXcore by yourself: [how to compile](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md)?

The two folders are all right The latest extension uses jx from ./jxcore. The other folder is temporary left after the download. And yes, they are the same files.

**Comment by movingbits** [comment]
Following https://github.com/jxcore/jxcore/issues/372

The host
cat /proc/version: Linux version 2.6.32-042stab103.6 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Jan 21 13:07:39 MSK 2015

The container
cat /etc/issue: Ubuntu 12.04.5 LTS

After some googling i found:
file /sbin/init: And that says the Ubuntu container is indeed 32bit. 

Compiling sounds a little scary, i will have to look into this.

**Comment by obastemur** [comment]
@ktrzeciaknubisa Why @movingbits is not able to run 32 ubuntu binary from downloads as is ?

**Comment by ktrzeciaknubisa** [comment]
Probably because it seems to be rh.

**Comment by movingbits** [comment]
Ooopss very sorry my fault.... I did not try Ubuntu 32. Thanks for asking the question and giving me the hint. I set /opt/psa/var/modules/jxcore-support/jxos.ini to platform = ub arch = 32 and it works again! Yeah

**Comment by ktrzeciaknubisa** [comment]
Glad to hear that... how about logouts?

And still I wonder, how previously rh 32 2.3.7 was working... Never mind I guess :)

**Comment by movingbits** [comment]
Logouts are gone...Yeah! Must be something incompatible rh related.

Thanks for all your support

**Comment by ktrzeciaknubisa** [comment]
Thank you for your cooperation :)
