### ISSUE TITLE
Sqlite performance issue

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#453]
I saw a problem with sqlite `db.each()` performance on cloud Ubuntu x64. At first I thought it is related to 1 CPU machine, but I was unable to reproduce this yet on another one to confirm this.

The following code takes a lot time to complete (to call `db.each()` callback). The more rows, the longer it takes.

```js
var sqlite3 = require('sqlite3').verbose();
var fs = require("fs");

var dbfile = 'file.db';
var remove = function() {
  if (fs.existsSync(dbfile))
    fs.unlinkSync(dbfile);
};

remove();
process.on('exit', remove);
var db = new sqlite3.Database(dbfile);

var cnt = jxcore.utils.argv.parse().cnt;
var count = cnt ? cnt.asInt : 100;

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
  for (var i = 0; i < count; i++) {
    stmt.run("Ipsum " + i);
  }
  stmt.finalize();

  var start = new Date();
  var end = false;
  db.each("SELECT rowid AS id, info FROM lorem", function(err, row) {
    if (!end) {
      end = new Date();
      console.log("Callback called after", end - start, "(", count, "rows )");
    }
  });
});

db.close();
```

Sample outputs:
```bash
$ jx test.js -cnt:10
Callback called after 1407 ( 10 rows )

$ jx test.js -cnt:100
Callback called after 12694 ( 100 rows )
```

Please note >12 sec in case of 100 rows.

Same for both SM and V8.

```bash
$ cat /proc/version
Linux version 3.2.0-80-virtual (buildd@batsu) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #116-Ubuntu SMP Mon Mar 23 17:28:52 UTC 2015
```

**Comment by ktrzeciaknubisa** [comment]
This happens on all our cloud VMs (Ubuntu, Suse, RH, Debian). They do have in common 1 CPU. 

However on local Ubuntu VM (also only 1 CPU) i don't get the issue. Also local FreeBSD 9 and 10 are ok.

**Comment by ktrzeciaknubisa** [comment]
Another updates:

- it occurs also for on Windows platforms
- it occurs only for filesystem databases (like in sample above) - not for `new sqlite3.Database(":memory")`.

**Comment by kzc** [comment]
It's likely a disk fsync issue. Computers on the cloud may have slow drives due to replication or other factors.

SQLite INSERT statements are implicit individual transactions. Every SQLite transaction invokes fsync to commit the data to disk. That is slow. To speed it up you need to group the inserts into a larger transaction to reduce the number of disk syncs:

    db.run("BEGIN");

    var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
    for (var i = 0; i < count; i++) {
      stmt.run("Ipsum " + i);
    }
    stmt.finalize();

    db.run("COMMIT");

**Comment by obastemur** [comment]
Seems this doesnt have much to do with JXcore. Lets keep this issue anyway. I would like to see if we can bring a trick that may improve Ghost blog performance on cloud hosting

**Comment by obastemur** [comment]
@kzc thanks for the tip!

**Comment by kzc** [comment]
If immediate data durability is not a concern you can disable `fsync` with

    pragma synchronous = off; 

after opening the connection to the database

See http://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by ktrzeciaknubisa** [comment]
@kzc Thank you for that. Going after your advice I ended up using the following:

```js
var db = new sqlite3.Database(dbfile);
db.run('PRAGMA synchronous = off');
```
And it does work. Thanks!
