### ISSUE TITLE
Writing GUI app?

### ISSUE THREAD

**Issue by nripendra** [jxcore/jxcore#458]
Can jxcore be used to write cross platfrom GUI app, something like what nwjs does with nodejs?

**Comment by obastemur** [comment]
For now, GUI is supported only on mobile. Desktop support is something we want to do though but not a priority at the moment.

**Comment by jackmcmorrow** [comment]
Hi there, I'm really interested in learning a bit more about creating mobile apps using jxcore, but I can't find much resources. I didn't find any section in the docs talking about it, can someone help out?

**Comment by jackmcmorrow** [comment]
Also: I never did any Android/Windows RT development. Should I learn their GUI stuff or is JXCore doing it's own thing?

**Comment by ktrzeciaknubisa** [comment]
@jackmcmorrow If you're going to use [jxcore-cordova](https://github.com/jxcore/jxcore-cordova) to write apps for iOS/Android, your GUI is a html page and you don't really need to know more about it, except of how to communicate between GUI and jxcore. 

But it's all there, in the link above. It has some samples too.

There is also an article, that we have published: [Develop an iOS Application with Node.js and Cordova ](http://modernweb.com/2015/03/19/develop-an-ios-application-with-node-js-and-cordova/).

**Comment by jackmcmorrow** [comment]
@ktrzeciaknubisa Oh! That sounds a lot more fun! Thanks!

**Comment by aurium** [comment]
@ktrzeciaknubisa, It looks deprecated now. Is there an official GUI example and specifically an Android GUI example?
