### ISSUE TITLE
JXCore Android platform binaries

### ISSUE THREAD

**Issue by oriharel** [jxcore/jxcore#465]
Can you please explain what to do with the Android binaries that can be downloaded from here? http://jxcore.com/downloads/. more explicitly - how to generate those .a files and .h files that you have in the cordova plugin under jxcore_cordova/bin folder.

Thanks.

**Comment by plika** [comment]
The files under the bin folder belong to iOS. In order to compile Android binaries see https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md

**Comment by oriharel** [comment]
But this will compile from the source. what is the jx file that is downloaded from here? http://jxcore.com/downloads/

**Comment by plika** [comment]
That's a standalone binary. If you ssh/adb shell to the device you can run jxcore there.

**Comment by oriharel** [comment]
so it has nothing todo with adding it to an application? what are the uses for this?

**Comment by oriharel** [comment]
Can you publish the Android binaries please?

**Comment by plika** [comment]
@ktrzeciaknubisa Can we publish Android /iOS FAT binaries (static libs) ?

**Comment by ktrzeciaknubisa** [comment]
FAT binaries are published on http://jxcore.com/downloads/ for both Android and iOS

**Comment by oriharel** [comment]
Thank You!! That's awesome
