### ISSUE TITLE
Not finding an asset file when running the compiled exe from another location

### ISSUE THREAD

**Issue by nKittie** [jxcore/jxcore#466]
Hi there,

The version of JXCore that we're using is 3.0.4.
This bug wasn't present in version 2.3.7.

I have a node project on Windows platform, which has "package.json" file in the root folder. This file is listed in the "assets" section of the JXP file. After the executable is compiled (in native mode), we need to run the exe from a different location - at which point I get an error that "package.json" file cannot be found. However running the exe via cmd from the same directory works.

Cheers,
Kate

**Comment by ktrzeciaknubisa** [comment]
I just tested `fs.readFileSync("./package.json")` under the jx package and works as expected.

Which OS are you using? And how are you accessing the file?

**Comment by nKittie** [comment]
OS:  Windows 8.1 Pro
This is how I run the executable from command line:

c:\portal>Renderer\EmailTemplateRenderer.exe
Error: ENOENT, no such file or directory 'c:\portal\package.json' (native:jxcore
_js_object 3:11)
    at  (native:jxcore_js_object:3:12)
    at fs.openSync (fs.js:451:10)
    at fs.readFileSync (fs.js:288:12)
    at module.exports.init (c:\portal\Renderer\modules\app\inde
x.js.jx:77:34)
    at c:\portal\Renderer\index.js.jx:5:4
    at Module.prototype._compile (module.js:520:10)
    at readX (module.js:1273:3)
    at Module._extensions[".jx"] (module.js:1700:10)
    at Module.prototype.load (module.js:3

**Comment by obastemur** [comment]
> c:\portal>Renderer\EmailTemplateRenderer.exe

> Error: ENOENT, no such file or directory 'c:\portal\package.json'

package.json is located under __dirname + 'package.json'

**Comment by ktrzeciaknubisa** [comment]
Yeap, you run the exe file from other directory than the exe is located. So if you call by a relative path e.g. `./package.json` it is constructed from current working dir, not from where the exe root dir, and you need to use `__dirname + path.sep + 'package.json'` as @obastemur mentioned.

**Comment by nKittie** [comment]
Ahha, found the code where the relative path was being used! Many thanks for your help.

**Comment by ktrzeciaknubisa** [comment]
Other way would be probably to call `process.chdir(__dirname)` in main app file (e.g. `index.js`) at the beginning. BTW. I'm just thinking if we can implement this feature based on specific ENV variable? If defined, then `process.chdir()`will be called internally?
