### ISSUE TITLE
Invoking JS functions from native

### ISSUE THREAD

**Issue by kmgkv** [jxcore/jxcore#468]
Hi,
Is there any way for native code to invoke JS functions (JS callback from native code)?

My use case is : 
Use JX_DefineExtension API to create a native callback function, and while invoking that function from JS land, I would like to pass JS functions along with some other arguments, so that, depending upon some success and failure scenario in native side, I can invoke appropriate JS callback function from native side.

For example :

JAVASCRIPT
-----------------
var test='abc';
function successCallback = { // handle success };
function errorCallback = { // handle error };
function invokeNative() {
    //....................
    process.natives.sampleNative(successCallback, errorCallback, 'someParam', [someData]);
    //....................
}

NATIVE
-----------
void my_callback(JXValue *args, int argc) {
   // Some processing
   // success and failure decision
   // get success or failure JS callback fucntion from args[]
   // invoke success or failure JS callback
}
JX_DefineExtension("sampleNative", my_callback);

**Comment by plika** [comment]
See https://github.com/jxcore/jxcore/blob/master/test/native-interface/function-call/test-posix.cpp#L9-L28

**Comment by kmgkv** [comment]
@plika Thanks for sharing the details... this is exactly like the way I imagined it to be.. will try this now!!!
