### ISSUE TITLE
Using jxcore Issue

### ISSUE THREAD

**Issue by zeeshanjan82** [jxcore/jxcore#472]
I am using jxcore to compile my nodejs application which uses Sequelize as ORM and I am able to get the .exe file but I get the error defineCall is not a function when I run the .exe file
![error](https://cloud.githubusercontent.com/assets/8342604/8888050/7515671c-32ba-11e5-8074-d3ab36eb55df.png)

**Comment by zeeshanjan82** [comment]
The error is coming in this code in sequelize.js under lib folder in node_modules
Sequelize.prototype.import = function(path) {
// is it a relative path?
if(Path.normalize(path) !== Path.resolve(path)){
// make path relative to the caller
var callerFilename = Utils.stack()[1].getFileName()
, callerPath = Path.dirname(callerFilename);

  path = Path.resolve(callerPath, path);
}

if (!this.importCache[path]) {
  var defineCall = (arguments.length > 1 ? arguments[1] : require(path));
  this.importCache[path] = defineCall(this, DataTypes);
}

return this.importCache[path];
};

**Comment by zeeshanjan82** [comment]
Further analyzing the issue. It is coming because I am using following like in my index.js file which is present inside models folder to load all my models.
var model = sequelize['import'](path.join(__dirname, file));

**Comment by zeeshanjan82** [comment]
Further analyzing the issue. It is coming because I am using following like in my index.js file which is present inside models folder to load all my models.
var model = sequelize['import'](path.join(__dirname, file));

**Comment by zeeshanjan82** [comment]
The application runs properly when running jx server.js

Issue comes only when I run the .exe file.

**Comment by ktrzeciaknubisa** [comment]
Hi, could you prepare a minimal code for reproduction, so we can see it on live example? The best would be something that uses SQLITE, as this doesn't require to install any extra engine libraries.

**Comment by zeeshanjan82** [comment]
Thanks @ktrzeciaknubisa  I was able to fix the issue. Actually it was something related to the javascript code in my index.js file in the models folder. Now the issue is fixed.
