### ISSUE TITLE
Please support npm init

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#477]
JXCore attempts to emulate NPM through the "--install" switch. Can there also be an "--init" switch to emulate `npm init`?

**Comment by ktrzeciaknubisa** [comment]
> JXCore attempts to emulate NPM through the "--install" switch.

Where did you get the double slash? Single slash - yes (`jx -install`), but this is going obsolete, as mentioned in the docs [npm](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-command-install.markdown#npm).

> Can there also be an "--init" switch to emulate npm init?

JXcore already supports all npm commands.

```bash
$ jx npm init
```

**Comment by ktrzeciaknubisa** [comment]
As an additional note, `install` is a special command and does not require `npm` in front of it (as opposite to all other npm commands), so the two following work the same:

```bash
$ jx install
$ jx npm install
```

**Comment by yaronyg** [comment]
Awesome!!! You guys rock! I'm updating our docs to make it clear that you can use jx for everything!

**Comment by ktrzeciaknubisa** [comment]
> that you can use jx for everything!

Well, jx still cannot open a bottle of beer. Yet :) 
Thanks!
