### ISSUE TITLE
Updating to latest version has broken sites

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#479]
After updating to the latest version and installing the latest Plesk extension my site now just load the Apache 2 Test Page

**Comment by dottodot** [comment]
Ok for some reason this dev version works https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk.zip for the none dev one doesn't https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support

**Comment by ktrzeciaknubisa** [comment]
Interesting. So which were your exact steps? Did you have Plesk extension before (which version and JXcore version) or you installed the extension for the first time on that platform?

> After updating to the latest version 

I assume you mean JXcore update, probably to 0.3.0.4 ?

**Comment by dottodot** [comment]
This happen on 2 different servers. One was on an earlier version of 0.3 and I selected update to 0.3.0.4 and it then broke.

The other server was on 0.2.3.6 I think, so I uploaded the latest extension and it then broke.

It was only by chance that I had downloaded the dev version as I wanted to use ENV variables and on uploading this extension it all worked again on both servers.

On the second server I even removed the extension and reinstalled and got the same issue.

**Comment by ktrzeciaknubisa** [comment]
I wasn't able to observe this on our platforms after JXcore update. The other thing is however, that due to multiple changes in process monitoring feature, older extensions may not be same stable, but that should have nothing to do with Apache 2 Test Page. 

Anyway we're going to send these days the extension to Plesk team for official release.

**Comment by ktrzeciaknubisa** [comment]
The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).
