### ISSUE TITLE
Fatal signal 11 (SIGSEGV) on Android 4.3 Samsung S3

### ISSUE THREAD

**Issue by oriharel** [jxcore/jxcore#494]
I got a fatal signal when running on Android 4.3 . attached is the log file link (native log). look for jxcore-log entries. 

https://drive.google.com/file/d/0B0bdCx3BDBCLMEJvVzFQakRXY1E/view?usp=sharing

**Comment by ktrzeciaknubisa** [comment]
Does it happen when you start the app, or e.g. restore from background? I'm asking, because the log contains *Starting JXcore engine* twice, at different times.

**Comment by oriharel** [comment]
You're right. I'll see what I can do to avoid that. closing for now.

**Comment by oriharel** [comment]
Still happens. Here's the logs:

https://drive.google.com/file/d/0B0bdCx3BDBCLSTZBSTVQakNLLXM/view?usp=sharing

**Comment by obastemur** [comment]
Can you please share the `/proc/stat` from the device;

```
adb shell
cat /proc/stat
```

**Comment by oriharel** [comment]
This is AFTER the crash:

https://drive.google.com/file/d/0B0bdCx3BDBCLVk5pNVFTOTZMT2M/view?usp=sharing

**Comment by obastemur** [comment]
Please download https://drive.google.com/file/d/0B36_OUVtfH-KeUtYV3hrWWZES2M/view?usp=sharing 

after unzipping jx for Android ARM from the link
```
adb push jx /data/local/tmp/
adb shell
cd /data/local/tmp/
chmod 777 jx
./jx -e "0"
```

please post the output.

**Comment by oriharel** [comment]
cpu0 39063 3487 45709 693832 2936 20 2537 0 0 0

SC:1,  NM: 0, LN: 5
cpu2 25790 2234 18638 737767 3766 1 0 0 0 0

SC:1,  NM: 1, LN: 5
Segmentation fault

**Comment by obastemur** [comment]
Thanks. See this if this -> https://drive.google.com/file/d/0B36_OUVtfH-KeUtYV3hrWWZES2M/view?usp=sharing will segfault.

**Comment by oriharel** [comment]
No output. which means no segfault...?

**Comment by obastemur** [comment]
Yes. :+1: Okay, I'm going to push the fix after a bit more testing.

**Comment by obastemur** [comment]
Just want to make sure, could you please run 

```
./jx -pe "require('os').cpus()"
```

on device ?

**Comment by oriharel** [comment]
ok. got:

[ { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 652600,
       nice: 443500,
       sys: 5556200,
       idle: 80424600,
       irq: 2200 } },
  { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 0,
    times:
     { user: 689400,
       nice: 224000,
       sys: 1908700,
       idle: 86561000,
       irq: 100 } },
  { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 640100,
       nice: 325800,
       sys: 2661200,
       idle: 84593100,
       irq: 100 } } ]

**Comment by obastemur** [comment]
Please download from the same link again and try

**Comment by oriharel** [comment]
[ { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 300900,
       nice: 490300,
       sys: 6413100,
       idle: 88936900,
       irq: 2200 } },
  { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 533500,
       nice: 263200,
       sys: 1630300,
       idle: 97072800,
       irq: 100 } },
  { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 802300,
       nice: 228200,
       sys: 2018700,
       idle: 96445700,
       irq: 100 } },
  { model: 'ARMv7 Processor rev 0 (v7l)',
    speed: 1400,
    times:
     { user: 985400,
       nice: 340500,
       sys: 3046900,
       idle: 93944400,
       irq: 100 } } ]

**Comment by oriharel** [comment]
Also tried the -e "0" command and no segfault

**Comment by obastemur** [comment]
Fix is available on 0.3.0.6 branch. Thanks for all the details.

**Comment by oriharel** [comment]
Thanks. Is there any way I can get the Android binaries?

**Comment by obastemur** [comment]
I will update the binary on https://github.com/jxcore/jxcore-cordova-release after some tests.

**Comment by dortzur** [comment]
Great news! This definitely solved a lot of grief for us.

**Comment by obastemur** [comment]
release binaries are available under `jxcore/jxcore-cordova-release` repo. If you are not using `cordova` plugin, you may simply grab the binaries there.

**Comment by obastemur** [comment]
@dortzur glad to hear that

**Comment by oriharel** [comment]
Don't I also need the arm/ia32/mipsel/x64 versions?

**Comment by obastemur** [comment]
That's a fat binary. They are all in. (arm + intel)

**Comment by oriharel** [comment]
After pulling jxcore/jxcore-cordova-release I ran:
jx io.jxcore.node.jx
and got various files and folders. I only saw binaries under io.jxcore.node > bin, and the files are libcares.a, libchrome_zlib.a, etc. 
Whereas in the 'Download' section of the jxcore website, there are android zip files available to download that wen extracted I get
libcares.a, libcares_ia32.a, libcares_mipsel.a, etc....

Should I use what's bin folder's files?

Thanks

**Comment by obastemur** [comment]
Those are ios binaries. You should find the `.so` files under `src/android` those you can directly use with any Android project. We will be releasing the archives separately with the 0.3.0.6 release.

**Comment by oriharel** [comment]
I can't use the .so. I've altered jxcore.cpp so I'm compiling my own .so. also I have a separate android library that wraps jxcore so the ndk methods signatures are my own. So I guess I'd have to wait for the official 0.3.0.6 release. when is it due?

**Comment by oriharel** [comment]
Still happens
