### ISSUE TITLE
Packaging performance

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#499]
While working with #490 (nodegit module) I realized that for projects of that size (10k files, 150 MB in file system) the packaging process may last annoyable long. I know, it is not a good idea to pack this kind of solutions (jx package has 68 MB) but I gave it a while to see what can be done in order to make packaging faster (in general).

So for the good start this fda9424d5b68f50e5922e9194f12dd5c4d399dd3 commit optimizes `console.log()` operations and reduces single packaging duration on my machine from 173 sec into 142 sec (above 20% gain)! Same output, but faster. And this is just console printing part!

In addition to this, there is new [--show-progress](https://github.com/jxcore/jxcore/blob/0.3.0.6/doc/api/jxcore-feature-packaging-code-protection.markdown#--show-progress) option which allows to change the way each packed file gets displayed in console. When set to `none` - the packaging performance is 2x faster on my env (97 secs instead of 173!).

I still think it can be boosted up even more, e.g. by using multithreading tasks. I'll check it out.

**Comment by obastemur** [comment]
How about the actual usage of that package ? Better optimize that part (memory, performance)

**Comment by ktrzeciaknubisa** [comment]
> How about the actual usage of that package ? Better optimize that part (memory, performance) 

Yeap, I guess we can work on this too.

___

As for employing multi tasking into packaging itself - I've tried two options applied per each packaged file:
* parallel async `fs.readFile()` calls
* reading files inside `jxcore.tasks.addTask()` 

In both tests they were running `getThreadCount()` instances at a time.

Unfortunately it didn't bring any performance gain (`fs.readFile()` was actually slower) and it appears to be useless here.

However optimizing GC cleanup interval 0ea6f674222826d1c74b91b58ec2242cf831315e brought significant performance. Now the same package that needed 173 secs to be created with V8, now takes just 30 secs (with full progress display)!

**Comment by ktrzeciaknubisa** [comment]
I've created a PR https://github.com/jxcore/jxcore/pull/504 with slightly faster startup on package execution. Not a rocket speed up at this time, but still may matter on slower devices.

**Comment by ktrzeciaknubisa** [comment]
This ticket is no longer meaningful as we have already implemented better, binary packaging - see https://github.com/jxcore/jxcore/issues/508
