### ISSUE TITLE
Difference between jxCore and nodejs?

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#511]
JXCore basically has built in multi threaded abilities w/o having to mess around with clusters, right?

**Comment by ktrzeciaknubisa** [comment]
It is not just multithreading, but yes: no need to use clusters (although they are still working same with JXcore as with Node.JS.

Apart from multithreading JXcore introduces much many added features, like:

* packaging, native packaging (self executables), 
* process/thread monitoring, 
* multiple engines (V8 and SpiderMonkey at the moment)
* extension for Plesk control panel
* mobile aplications

Those are the most important. See also http://jxcore.io/.

**Comment by McFarts** [comment]
Okay great. Because I'm using the `ws` module and I need multi threading for my action RPG Websocket gameserver :)

I hate the way cluster's are setup in regular node so was looking for an alternative. Definitely will give JXCore a try, thank you @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
All right. You can also take a look at our messaging system http://jxm.io for easy client-server communication.

**Comment by matrixreal** [comment]
+ jxcore has better memory management right ?
so jxcore is better ..
