### ISSUE TITLE
Processes are not being created

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#512]
I used mt-keep:6, but..

![](https://i.gyazo.com/da9c0eec1ec451ed8ffb5a73f12b2d9f.png)

Only 1 main process is being run, is that normal?

**Comment by obastemur** [comment]
Yep. mt is multi-thread and those threads work seperately under the same process.

**Comment by ktrzeciaknubisa** [comment]
Yes. One process contains multiple separate subthreads/instances.

**Comment by McFarts** [comment]
Hmm, what is the difference between multithreading and clusters?  I want to use multiple cores and threads, is that possible?

**Comment by obastemur** [comment]
By using either task or mt you are already utilizing multiple cores

**Comment by McFarts** [comment]
Is multithreading better than utilizing more cpu's? (clustering from nodejs)?

**Comment by obastemur** [comment]
Multithreading also utilize multiple cpu/cores as cluster. MT lets you have it under a single process

**Comment by McFarts** [comment]
@obastemur can I message you on skype for more questions? I am coming from nodejs and want to utilize all 6 cores and do MT. I'm a bit confused :(

**Comment by McFarts** [comment]
http://stackoverflow.com/questions/11835046/multithreading-and-multicore-differences

I read here.

Seems like MT will use more cores when needed! Way better than clustering! Alot more easier too! Thanks guys <3 LOVE JXcore!
