### ISSUE TITLE
Example code is out of date:

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#513]
http://jxcore.com/multithreaded-javascript-tasks/#post-1225

```
jxcore.tasks.addTask(method, {count: 1000}, function (result) {
    // this block of code executes back in the main thread,
    // after method() completes.
    console.log("This is result from subthreaded method:", result);
});

```

the addTask takes 2 arguments from the return function (err, result)

![](https://i.gyazo.com/205d038b29599848230527c5cbe15b6a.png)

Got an error here so just thought I'd let you know :)

**Comment by obastemur** [comment]
This warning is for you. Change result to err, result pair. Probably we did not update a sample or tutorial so you saw and used it in old way

**Comment by ktrzeciaknubisa** [comment]
Thank you @McFarts . The tutorials are updated now.
