### ISSUE TITLE
Question about Multithreading

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#520]
So basically, from my latest benchmark here:

https://github.com/jxcore/jxcore/issues/514

It performs iterations about 50% faster (JXCORE does) on large objects.

My question is: Exactly how? Is it because JXCore is forked to be multi threaded and takes use of a multicore system, which in essence speeds up iterations? Right? If this is true, I wonder why multithreading isn't added to the core of nodejs?

**Comment by plika** [comment]
JXcore uses a thread pool. In other words, warm instances ready for tasks. Whenever you give a task, that task is taken care of by the first available thread. This indeed brings significant JS performance on CPU heavy tasks.

**Comment by McFarts** [comment]
I see, can the number of cores you have on a system effect that thread pool? (positive or negative)

**Comment by plika** [comment]
Not the initial thread pool (by default it's 2) but the overall performance.

**Comment by McFarts** [comment]
Hmm okay, thanks. I'm just seeing a massive increase of performance since I ported my app over to JXcore... It felt like magic :)
