### ISSUE TITLE
Is JXcore going to be implementing Web Workers?

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#522]
http://stackoverflow.com/a/29088224/1254837

Looks like a couple more bugs are left under windows and it will make it in.  What's JXcore's stance on this will they add it? I would love to use a couple of them for my separate gameserver loops ~

(while taking advantage of jxcore's default mt that increases performance)

**Comment by McFarts** [comment]
Update, Webworker tree is here:

https://github.com/petkaantonov/io.js/tree/ea143f72fc6845668716bd7a5da22771011defe4

I'm going to be building it and testing the workers out.

How hard would it to be to add these files to a JXcore source and would it still work? Would love to use JXcore with Webworkers ~

**Comment by obastemur** [comment]
@McFarts current JXcore.tasks has more features comparing to webworkers yet for node compatibility we are going to implement the interface. Since we have a separate upgrade issue is open, closing this one. Thanks
