### ISSUE TITLE
Buffer.compare as a native function?

### ISSUE THREAD

**Issue by jacopofar** [jxcore/jxcore#523]
Porting a code from iojs to jxcore I found that there's no `Buffer.compare` function, is there any plan to support it natively ?

I can change the prototype to compare the two buffers byte by byte but probably a native one would be faster.

**Comment by obastemur** [comment]
That is pretty easy to implement on native side. We may ship this as a part of 0.3.0.6

**Comment by jacopofar** [comment]
Great news!

**Comment by obastemur** [comment]
@jacopofar if you have environment to compile JXcore from master / 0.3.0.6, both Buffer.compare and Buffer.indexOf are implemented.
