### ISSUE TITLE
Windows 8.1: error running extracted package

### ISSUE THREAD

**Issue by karaxuna** [jxcore/jxcore#525]
I have packaged app with `-extract` flag. When running with `jx ghost` files are successfully extracted, but it fails to run `index.js` file. I think the problem is in path name where jxcore is installed.
![error](https://cloud.githubusercontent.com/assets/2152815/9715886/e5a6027e-5575-11e5-9a6d-c9ee6bb0e312.png)

**Comment by ktrzeciaknubisa** [comment]
@karaxuna I'll bet, that you are using jx 0.3.0.5 from download page? With 3.0.0.6 I don't get this error (but I do receive with 0.3.0.5).

**Comment by karaxuna** [comment]
@ktrzeciaknubisa yes, I'm using 0.3.0.5

**Comment by ktrzeciaknubisa** [comment]
All right. 0.3.0.6 already contains multiple packaging extraction improvements and fixes, including this one. Let me know when you'll see the problem with 0.3.0.6. Closing for now.
