### ISSUE TITLE
Missing GLIBC.2

### ISSUE THREAD

**Issue by McFarts** [jxcore/jxcore#530]
I installed jxCore using
```
$ curl http://jxcore.com/xil.sh | bash -s v8
```

But I'm receiving this error when trying to run jx

```
jx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by jx)
jx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by jx)

```

Debian 7 Wheezy 64 bit, any idea fellas?

**Comment by McFarts** [comment]
Edit: I also tried:
```
apt-get install libc6
```

But, it still says I am up to date.. Hmm

**Comment by ktrzeciaknubisa** [comment]
Not sure about this. I've just checked on our Debian:

```bash
$ ldd --version
ldd (Debian EGLIBC 2.13-38+deb7u8) 2.13
```

and it looks like I don't even have 2.15, but jx works normally. 

How about `apt-get update` or `apt-get install build-essential` ?

**Comment by McFarts** [comment]
Hmm. I tried build-essential and update.

![](https://i.gyazo.com/3fb2e9da9e0f8e6d339ab69d47f760ad.png)

Still getting this... Hmmm

**Comment by brodybits** [comment]
Can you specify which Linux distribution and version you see this on?

**Comment by McFarts** [comment]
@brodybits  Yeah

```
root@testwebsocket:~# uname -a
Linux testwebsocket 2.6.32-openvz-042stab104.1-amd64 #1 SMP Thu Jan 29 13:06:16 MSK 2015 x86_64 GNU/Linux
root@testwebsocket:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy

```

**Comment by brodybits** [comment]
@McFarts please do `ldd --version` and post your results. I just tried `curl http://jxcore.com/xil.sh | bash -s v8` on a new Debian Wheezy VM (with `build-essential` installed and `sudo apt-get update` done) and it is working fine for me.

FYI a couple of references:
- #34 - someone else had the same problem last April, it is not clear to me if he got it to work or not
- similar issue on atom in atom/atom#2020

**Comment by McFarts** [comment]
```

root@testwebsocket:~# ldd --version
ldd (Debian EGLIBC 2.13-38+deb7u8) 2.13
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@testwebsocket:~#
```

@brodybits  There is ldd --version.

Do you think it might be an issue with the OS Template my provider is using?

**Comment by McFarts** [comment]
I installed Debian 8 Wheezy instead, and did:

apt-get update

apt-get install curl

curl http://jxcore.com/xil.sh | bash -s v8


done. Works fine.

Closed, thanks!
