### ISSUE TITLE
Legacy jx license code in lib/module.js?

### ISSUE THREAD

**Issue by brodybits** [jxcore/jxcore#536]
While fixing some jslint errors, I discovered what looks like old code to handle commercial licensing in https://github.com/jxcore/jxcore/blob/master/lib/module.js#L1282-L1286:
```Javascript
    } else if (process.argv[2] == 'license') {
      if (obj.license) {
        console.log(jxt._ucmp(new Buffer(obj.license, 'base64')).toString());
      } else {
        jxcore.utils.console.log("JX file doesn't have a license definition.\nThis might be a bug or the package doesn't have a license file.\nIf this is a bug, please let us know from support@jxcore.com\n", 'green');
      }
      exito = true;
    }
```

Do we still need this?

**Comment by obastemur** [comment]
No it's not commercial licensing. While packaging JXcore tries to embed node module license in a special way.

**Comment by brodybits** [comment]
Thanks. Is this documented somewhere?

**Comment by ktrzeciaknubisa** [comment]
This we have: [licence_file](http://jxcore.com/docs/jxcore-feature-packaging-code-protection.html#licencefile).

**Comment by brodybits** [comment]
Very nice, thanks!
