### ISSUE TITLE
`jx exec` command

### ISSUE THREAD

**Issue by nuxlli** [jxcore/jxcore#552]
We're developing a command line tool written in Node.js, you can check it here: https://github.com/azukiapp/azk

The goal is azk to be an stack-agnostic tool (for the final user) and that's the reason we're trying to make its installation as simple as possible, using all-inclusive packages (avoiding the user to install even Node.js). Using tools like "make" and "gulp" that was possible.

jxcore caught our eyes with a more advanced and smart purpose to reach that goal, so we'd like to use and contribute with the project.

About the `jx exec` command: since we're using tools such as http://babeljs.io, we need extra steps to transpile code and run jshint and jscs checks.

In the scenario above, we'd like to propose one more command to jxcore: `jx exec`, which behavior should be similar to http://bundler.io/v1.3/man/bundle-exec.1.html or com https://docs.npmjs.com/cli/run-script

The idea is provide commands like:

```sh
jx exec gulp  -- watch:test
jx exec babel -- script.js --out-file script-compiled.js
```

In this context, jx loads and adds Node.js to the PATH and calls `./node_modules/.bin/[binary]`.

We're willing to work on this and add this feature to jxcore if you agree it makes sense.

**Comment by obastemur** [comment]
> In this context, jx loads and adds Node.js to the PATH and calls ./node_modules/.bin/[binary].

Would you elaborate the statement above ?

In general `exec` sounds cool but we would rather prefer something like `-ce` instead of exec. For example, `-e` evaluates, `-pe` prints the evaluation, and maybe `-ce` evaluates in special manner that I would like to understand better.

**Comment by nuxlli** [comment]
@obastemur I'm sorry for making it blurry. English is not my mother tongue, so I end messing up sometimes :)

The idea of using `exec` is to follow the trend of other tools which offers similar functionality, such as http://bundler.io/v1.3/man/bundle-exec.1.html. But it was only a suggestion, `-ce` looks good as well.

About how it works: when we install something like `gulp`, `npm` adds the `binary` (actually a script) `./node_modules/.bin/gulp`. I can easily call this script if `node` is in my `PATH`, because its first line is `#!/usr/bin/env node`

However, when using `jx` and don't having any other `node` installation, I can't directly call this script. I need to use `jx ./node_modules/.bin/gulp`, making this proccess less straightforward. If we take into account that packages like `gulp`, `grunt` and many others can be installed with `-g`, this is even more complicated.

There are cases in which the scripts in `node_modules/.bin` aren't `node` scripts, but `bash` scripts that can call `node`

My suggestion to `js exec` is a kind of alias, something like the script below:

```sh
#!/bin/bash

# Create a symlink and add it into PATH
mask="jx.temp.XXX"
node_path=`mktemp -d -t "$mask"`
ln -s `which jx` $node_path/node
export PATH=$node_path:$PATH

# Add current node_modules in PATH
extra_path=`pwd`/node_modules/.bin
[ -d "$extra_path" ] && { export PATH=$extra_path:$PATH; }

# Exec original command
"${@}"

# Clean symlink
rm -Rf $node_path
```

Saving it as `jx-exec` and giving it the execution permission (`chmod +x`), I'm able to run:

`./jx-exec gulp`
`./jx-exec babel script.js --out-file script-compiled.js`

What do you think about it?

**Comment by ktrzeciaknubisa** [comment]
Once you'll install an npm module with `jx install` command instead of `npm install`, the shebang line is replaced into `#!/usr/bin/env jx` and is executable with jx as well. Does it help you?

**Comment by plika** [comment]
Yes. @ktrzeciaknubisa right. But I also got the point of @nuxlli . 

@nuxlli are you suggesting to somehow implement that bash fail builtin to jxcore?

**Comment by ktrzeciaknubisa** [comment]
@nuxlli Can we close this ticket? I believe `jx install` is all you need.
