### ISSUE TITLE
Two questions about `jxcore.utils.pause()` and `jump()`

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#554]
1. My bad, but I was kind of convinced, that if I call `jxcore.utils.pause()`, then process stops at that line. And if stops, it doesn't exit, no? Exits anyhow. Test case:

    ```js
jxcore.utils.pause();
```

2. `jump()`: modified version of our docs sample taken from [here](http://jxcore.com/docs/jxcore-utils.html#pause):

```js
setTimeout(function(){
  jxcore.utils.continue();
}, 1000);
jxcore.utils.jump();  // jump() instead of pause()
```

always displays a warning: 

> jump interrupted. Make sure the thread wasn't paused already

unless I delay process exitting:

```js
setTimeout(function(){
  jxcore.utils.continue();
  process.nextTick(process.exit);
}, 1000);
jxcore.utils.jump();
```

Is that alright?

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/743677f9a90caeefd10933d71c2cce81d7071a7d should fix it. sync to 0.3.0.6

**Comment by ktrzeciaknubisa** [comment]
Thanks, that fixes the "jump interrupted" warning (no 2.).

Any comment regarding 1st ?

**Comment by obastemur** [comment]
> My bad, but I was kind of convinced, that if I call jxcore.utils.pause(), then process stops at that line. And if stops, it doesn't exit, no? Exits anyhow. Test case:

> jxcore.utils.pause();

Surely it exits. `pause` as an implementation, pauses the execution of logical JS interpreter on given line. If there is no active `ref` for the process, it exits anyways. However you are right that, developer may expect the process is going to be there. We should document this clearly.
