### ISSUE TITLE
Windows: jx.exe version in file properties 

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#556]
While watching benchmark from https://github.com/jxcore/jxcore/issues/555 it reminded to me that in fact we don't display JXcore version at all in file properties:

![jx_file_properties](https://cloud.githubusercontent.com/assets/5946844/9977931/c1832a40-5f19-11e5-9613-ba593da93ae4.png)

It's the underlying node's version written there.

Are we going to change it?

**Comment by McFarts** [comment]
Ha, good catch. I didn't even notice.

**Comment by obastemur** [comment]
Lets do it along with the copyright and description though.

**Comment by ktrzeciaknubisa** [comment]
This PR https://github.com/jxcore/jxcore/pull/557 proposes the changes.

**Comment by ktrzeciaknubisa** [comment]
This is already implemented by https://github.com/jxcore/jxcore/commit/b8dae775eac391f6e920655c382d20638f74c7fc .
