### ISSUE TITLE
iOS compile fails for ARM

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#559]
When running `build_scripts/ios_compile.sh`, it works for ia32 and x64, however each of ARMv7, ARMv7s, ARM64 fails:

```bash
clang: clang: error: errorunknown argument: '-fembed-bitcode': 
unknown argument: '-fembed-bitcode'
make[1]: *** [/Users/nubisa_krzs/Documents/GitHub/jxcore/out/Release/obj.target/cares/deps/cares/src/ares__close_sockets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/Users/nubisa_krzs/Documents/GitHub/jxcore/out/Release/obj.target/cares/deps/cares/src/ares_cancel.o] Error 1
make: *** [jx] Error 2
```

Not sure if this matters here, but this happens on xCode downgraded to 6.0.1.

**Comment by obastemur** [comment]
> First, you need a MAC! and the latest XCode installed with iPhone device and simulator SDKs. 

This is from ios compile docs. Latest Xcode is needed.
