### ISSUE TITLE
The wrong URL is on the installation page

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#562]
I tried to submit a PR for this from the GitHub website but while it lets me create a PR the 'Propose File Change' button is greyed out. I have no idea why.

In any case the URL advertised on https://github.com/jxcore/jxcore/blob/master/doc/INSTALLATION.md is wrong. It points to the HTML version of the jx_install.sh page which needless to say bash won't respond well to.

The correct URL is https://raw.githubusercontent.com/jxcore/jxcore/master/tools/jx_install.sh

**Comment by ktrzeciaknubisa** [comment]
Hi @yaronyg 

Thanks, however I never witnessed a problem with  that url when used in command:

```bash
$ curl http://jxcore.com/xil.sh | bash
```
Doesn't it work for you?

The point is that we wanted to have as short and easily remembered url as possible, that's why we didn't link it it github.

**Comment by yaronyg** [comment]
The xil link did work. But the page still advertises the github link and its wrong.  I would suggest that you either remove the github link on that page or correct it as given above.

**Comment by ktrzeciaknubisa** [comment]
Ah, yeah. I see now. Despite of your description somehow I missed that github link. 

I've just updated it. 
Thanks!
