### ISSUE TITLE
Is there a 0.3.0.6?

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#563]
http://jxcore.com/downloads/ advertises a 0.3.0.6 version but when I use jx_install.sh it says my 0.3.0.5 install is the latest. Is there a 0.3.0.6?

**Comment by ktrzeciaknubisa** [comment]
Yeap, the binaries are ok. We just missed to update latest.txt used by `jx_install.sh`. Thanks for the info! :)

Now this should work.
