### ISSUE TITLE
Need leveldown to work with JXcore on desktop

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#564]
Feature Request: Please make jx npm link work as it does with Node.js

Problem: When I try to run jxcore on my mac in a directory that uses npm link to connect a dependency to another directory I get:

```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup
```

Why anyone cares: Developing in Cordova is typically really painful because one has to have one repo with the code and then a separate stand alone project that pulls in the code, installs things correctly and lets one deploy to a device. However in the specific case where we are developing pure Node.js code we can actually develop directly out of our Cordova depot. The way we do this is by having two directories, both in our repro. One directory (thali) contains the node.js code we are developing. The other directory (test) has our test code. We use npm link to connect the thali code to the global machine registry. Then we use npm link again to connect from the global machine registry to the test sub-directory. Now we can run and edit files in place. It's a wonderful thing! It works flawlessly with node. Unfortunately it doesn't work with JXcore.

Work around: It's not a huge deal to work around this. The only thing that goes wrong when we test against node.js is that we get an error when we use the jxcore object (for things like jxcore.utils.OSinfo().isMobile). It's not a huge deal to polyfill these if we have to but I'd much rather actually test against JXcore since that is our primary environment.

Note: I did try to use 'jx npm link' and 'jx npm link thali' to fix this. The commands did appear to run successfully but I still got the error above. An error I don't get when I use mainline node.js and npm.

**Comment by ktrzeciaknubisa** [comment]
> The commands did appear to run successfully but I still got the error above.

Did the error occur when executed  `jx npm link` command or when you run thali (after jx linking)?

**Comment by yaronyg** [comment]
When I try to run a .js file against jx I will get the error. In other words, after link has completed.

**Comment by ktrzeciaknubisa** [comment]
I saw few similar issues on the net, related to `npm link` and `Symbol not found: _node_module_register` error. One of them is this: https://github.com/webpack/webpack/issues/720 .

This may sound ridiculous, but how about trying `jx npm rebuild` after `jx link` ?

**Comment by yaronyg** [comment]
I tried a test where I did an install that doesn't use link at all. That helped me understand that link is a red herring. The real problem is that jx doesn't like the way that leveldown is built. That is what is causing the errors above. After a normal `jx npm install --autoremove="*.gz"` (no links in site, I checked node_modules and our project is not linked, it's physically in the directory) I can run files just fine using node but I get the binding failures above with jx.

Just for fun I tried 'jx npm rebuild' (even though there i no jx link) and I got:

```
Yarons-MacBook-Pro:jxcore yarongoland$ jx npm rebuild
npm WARN invalid config local-address=undefined
 
> leveldown@1.4.1 install /Users/yarongoland/Desktop/depots/ThaliTest/www/jxcore/node_modules/leveldown
> prebuild --download

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/yarongoland/Desktop/depots/ThaliTest/www/jxcore/node_modules/leveldown/node_modules/.bin/prebuild:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.1 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/yarongoland/.jx/npm" "rebuild"
npm ERR! cwd /Users/yarongoland/Desktop/depots/ThaliTest/www/jxcore
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/yarongoland/Desktop/depots/ThaliTest/www/jxcore/npm-debug.log
npm ERR! not ok code 0
```

Help!

**Comment by yaronyg** [comment]
The plot thickens. I updated to leveldown 1.4.1 and now 'jx npm install' can't even install it without getting an unspecified error. But if I use 'npm install' it runs just fine. Seems like 0.3.0.6 might be having some kind of problem with leveldown.

**Comment by ktrzeciaknubisa** [comment]
I cannot confirm this. I'm successfully installing leveldown with jx 0.3.0.6. Even `jx npm rebuild` works fine`.

Can I ask you to remove `~/.jx`and `~/.node_gyp/jx*` and try things again?

**Comment by yaronyg** [comment]
Just to be pedantic, I think you meant:
``` bash
rm -rf ~/.jx/
rm -rf ~/.node-gyp/jx*
```

That did seem to clear up the compile issue.

I then tried 'jx foo.js' and it failed with the same error. I ran 'jx npm rebuild' just for fun. It compiled fine. But 'jx foo.js' failed with the same error afterwards. Note that 'node foo.js' works just fine.

I then tried an experiment where I created a new project and did not use link at all. I ran into exactly the same dyld errors as above with the same new line. Again, using node ran fine.

jx -jxv = v 0.3.0.6
node -v = v0.12.7

**Comment by yaronyg** [comment]
Because I needed to run on the same version of node as used in JXcore I downgraded from 0.12.7 to 0.10.40 and the same problems are showing up! So this doesn't look like a JXcore issue, it looks like an issue with using leveldown on any node 0.10.* release.

**Comment by ktrzeciaknubisa** [comment]
Can I have some package.json or repo to play with in order to reproduce your scenario?

Is your error still related to leveldown or any other module?

**Comment by ktrzeciaknubisa** [comment]
During leveldown install yesterday I saw:

```
> prebuild --download
```

line and that worried me. 

I've checked on leveldown README.md and it seems that leveldown is downloading prebuilt binaries instead of compiling them. Thus `jx npm install` does not get leveldown.node compiled against jx. Please see: [prebuilt-binaries](https://github.com/Level/leveldown#prebuilt-binaries).

This would explain, why it works always with node, but not with JXcore.

**Comment by yaronyg** [comment]
That makes sense but this is going to be a generic problem for JXcore. More and more folks are switching over to prebuild and obviously that won't work for JXcore due to engine and header issues. My understanding is that prebuild is designed to fall back to doing a gyp build if it doesn't work (e.g. can't find the right binary, network is done, etc.). So doesn't this mean that JXcore has to figure out how to 'trigger' a prebuild failure to make sure it gets a chance to do that build?

Also for popular libraries (like leveldown), any hope that we can get them to include JXcore binaries? That would be pretty sweet.

**Comment by ktrzeciaknubisa** [comment]
For now we're going to make `jx install` aware of some known libraries (starting from leveldown) and we plan to post an update before this weekend.

In a meantime I've tested the following commands and they all worked great and rebuilded leveldown for me:

```bash
$ jx install --build-from-source
$ jx npm rebuild --build-from-source
$ jxv8 install leveldown@1.4.1 --build-from-source
```

**Comment by yaronyg** [comment]
That works! Thanks for the work around! I can't wait until 0.3.0.7 comes out.

**Comment by obastemur** [comment]
@ktrzeciaknubisa can't we just make build from sources default for all and ship it?

**Comment by ktrzeciaknubisa** [comment]
I was thinking about this, however I'm trying to figure out if there would be any cons of this, which we may not be aware of. First of all we would apply this not only for the `install` command, but also `rebuild`, `update` etc. 

For the start I was just going through documentation on what exactly is this option and from where it comes. It doesn't belong to npm - it is used by [node-pre-gyp](https://github.com/mapbox/node-pre-gyp). However from the description looks like this is exactly what we need.

**Comment by yaronyg** [comment]
This all happened because more and more people are using node.js who are just node programmers. They don't necessarily have the compilers, linkers, etc. that are needed for native code. This was causing a lot of support headaches, especially on Windows. So this led to node-pre-gyp. Developers could create pre-defined binaries for the most popular platforms and that way their users didn't need to install a compiler and related tools.

My own two cents is that:
1) Y'all really need to talk to the node-pre-gyp folks and add in a switch that can detect when the user is using JXcore
2) Y'all need to identify the top native modules (and [here](https://www.npmjs.com/package/node-gyp-counter) is a project that will even tell you what they are) and supply pre-compiled binaries for them

Step 1 is the key. If you add the ability for node-pre-gyp to detect JXcore then at a minimum you can disable any further node-pre-gyp processing and that will just cause normal gyp to run.

Step 2 is a very nice, nice to have.

**Comment by ktrzeciaknubisa** [comment]
Thanks @yaronyg .

As for now we took care of node-pre-gyp by adding `--build-from-source` and also of [prebuild](https://github.com/mafintosh/prebuild) (which uses [node-gyp-install](https://github.com/mafintosh/node-gyp-install) - by forcing node-gyp rebuild instead of download https://github.com/jxcore/jxcore/issues/569#issuecomment-144092801). 

This is all part of JXcore 0.3.0.7.

So the leveldown should now work as expected :)
