### ISSUE TITLE
JXcore's http.IncomingMessage behavior is inconsistent with Node 0.10.40

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#567]
I'm using the nock library for testing which in request_overrider on line 88 makes a call to new IncomingMessage with a single argument of new EventEmitter(). This behavior seems consistent with Node v0.10.40's definition of IncomingMessage as defined [here](https://github.com/nodejs/node/blob/0439a28d519fb6efe228074b0588a59452fc1677/lib/http.js#L289).

Unfortunately JXcore's implementation of IncomingMessage is different, see [here](https://github.com/jxcore/jxcore/blob/afad271bf3c989db20fc93eff585d028ea98a273/lib/jx/_jx_incoming.js#L29). JXcore depends on receiving an info object and so the Nock code causes an internal exception [here](https://github.com/jxcore/jxcore/blob/afad271bf3c989db20fc93eff585d028ea98a273/lib/jx/_jx_incoming.js#L39)

Given Nock's popularity (205K downloads in the last month) it seems like it would be worth making it work on JXcore.

**Comment by yaronyg** [comment]
As a side note, I do understand that IncomingMessage's constructor is private (per [here](https://nodejs.org/docs/latest-v0.10.x/api/http.html#http_http_incomingmessage) where no constructor is defined) but Nock is really popular and now it won't work! :(

If I can't use Nock do you know of any equally friendly and easy to use library I can use to test web requests?

**Comment by obastemur** [comment]
@yaronyg thanks for the details. I'm on it.
