### ISSUE TITLE
Add new methods from node 0.12.7

### ISSUE THREAD

**Issue by karaxuna** [jxcore/jxcore#571]
Compared node 0.12.x and jxcore apis. See [compare results](https://gist.github.com/karaxuna/5bba8f412e90e73fe699).
See also useful [post](https://strongloop.com/strongblog/node-js-v0-12-new-apis/) about changes after node v0,10.

Features already added:

`util.debuglog` for conditional debugging.
`Writable.cork` method that forces buffering of all writes. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_cork).
`Writable.setDefaultEncoding` method. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_setdefaultencoding_encoding)
`path.isAbsolute` method. [See docs](https://nodejs.org/docs/latest-v0.12.x/api/path.html#path_path_isabsolute_path)
`lookup` event when calling `socket.connect` (triggers after `dns.lookup`). [See docs](https://nodejs.org/docs/latest-v0.12.x/api/net.html#net_event_lookup)
`reset` event to repl. Triggers when calling `.clear` from repl client. [See docs](https://nodejs.org/docs/latest-v0.12.x/api/repl.html#repl_event_reset)
`Writable._writev` method. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_writev_chunks_callback)

**Comment by brodybits** [comment]
See https://github.com/jxcore/jxcore/issues/535#issuecomment-139660624: The plan is to skip Node 0.12.7 and target Node 4.0 (which is already released).

**Comment by obastemur** [comment]
@brodybits this work is for upcoming 0.3.x. I'm almost finished with Chakra (v8 3.28+) support. We will be adding missing API (comparing to 0.12) to 0.3.x series until 0.4.x is ready.

**Comment by obastemur** [comment]
better merge new API into 0.3.1.x (since we are updating the API) IMHO, It's important not to add anything breaking node 0.10.x compatibility.

**Comment by brodybits** [comment]
:+1:

**Comment by brodybits** [comment]
Also adding a reference to #402 where Node 0.12.x was discussed before. Nice to include whatever we can from 0.12.

**Comment by obastemur** [comment]
@karaxuna can you mark the ones (on comparison list) already part of 0.3.1.0 ?

**Comment by ktrzeciaknubisa** [comment]
Implemented with https://github.com/jxcore/jxcore/pull/582 .
