### ISSUE TITLE
Cannot find *any* way to sign a JXCore compiled executable

### ISSUE THREAD

**Issue by Gray1989** [jxcore/jxcore#583]
The furthest I've gotten was an error from signtool that says the file isn't a valid win32 application. Had to do that manually as the code to initiate the call is broken. I don't care about that as long as I can sign the file myself. Could anyone *please* fix this? 
![image](https://cloud.githubusercontent.com/assets/10122452/10325752/4005d3b8-6c62-11e5-9595-a5b83c21ebc3.png)
![image](https://cloud.githubusercontent.com/assets/10122452/10325802/aae1d79a-6c62-11e5-94c4-237dd255a287.png)

**Comment by Gray1989** [comment]
After further investigating I think this has something to do with the original jx.exe file being signed. If I run delcert on the file it deletes the certificate information but presumably also extra data in the PE header which corrupts ends up corrupting the executable in some way. It still runs after using delcert but it seems to render my resource editing application useless and still doesn't let me sign it (same error). However if I run delcert directly on jx.exe before using it to compile the native executable I am able to sign the application afterwards. However simply the action of signing the executable seems to render it useless (it just quickly flashes the black box [of instant return]). Which I find really weird. If anyone can get back to me on this issue it would be greatly appreciated.

**Comment by Gray1989** [comment]
If anyone could make available a compiled 32-bit Windows executable (jx.exe, unsigned/signable) for me to use that would be amazing. It seems that's the only way I'll be able to actually utilize the proposed ability to sign the resulting executable.

**Comment by Gray1989** [comment]
Update: I managed to get JXCore to compile using VS2013. I got past the first error by removing a few lines in a file, which allowed that part to compile successfully and it all brought me down to literally one error and I realized that it was specific to VS2015. It had to do with an expected but deprecated input/output thing with OpenSSL.

**Comment by Gray1989** [comment]
Update 2: After successfully signing the compiled native executable using the unsigned jx.exe that I compiled using VS2013 I was brought with this error (it worked perfectly fine just before actually signing it)

![image](https://cloud.githubusercontent.com/assets/10122452/10334560/ea20dbf8-6cb8-11e5-9b8d-1282331b66e9.png)

**Comment by ktrzeciaknubisa** [comment]
Thanks for all the inputs. I'm going to look at it. BTW, which JXcore branch are you compiling?

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 The very first screen that you attached is the result of calling `jx package ...` with  `--sign` option or rather you edited *.jxp file and added "sign" definition manually?

**Comment by ktrzeciaknubisa** [comment]
Yes, the first error needed a fix (it's already done, but will be posted later).

However breaking a package after successful signing is indeed an issue. The signing process is called at the end of creating a package. I've tried few other options e.g. to sign the package before the actual contents embedding or sign `jx.exe` before creating a package (as you mentioned), but at the end the digital signature is gone, so that's not really helpful, even if package executes alright.
 
I'm still researching for a solution.

**Comment by Gray1989** [comment]
@ktrzeciaknubisa  I'm using the latest version of the main branch (this one). And yeah the only way I was able to get the file to try signing after compilation was to add the sign option to the jxp file. I peeked at the source code a bit. Are you the person who created the compilation algorithm? I don't really understand how it works at all or I would probably offer to help fix it.

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 The above commit restores command line support for `jx package --sign` and fixes `finalName` error. However we still have a "Package corrupted" thing.

> Are you the person who created the compilation algorithm? 

Nope, but we all maintaining it. 

> I don't really understand how it works at all or I would probably offer to help fix it. 

If you have any fixes/improvements suggestions, they are more than welcome. Just create a pull request.

**Comment by ktrzeciaknubisa** [comment]
BTW. the commit is not on at master yet. Until then, you can switch to 0.3.1.0:

```bash
$ git checkout 0.3.0.1
```

and then compile.

**Comment by Gray1989** [comment]
After extensive testing I can almost confirm that the build process is not at fault, I am almost positive that it is the read process. I was able to dump a copy of the buffer where it was failing from both a successful run and a failed run due to signing. After comparing the dumps using a hex editor, I first confirmed that the certificate for the signature is making the buffer basically garbage to the interpreter. Then I went to somewhere in the middle of the dump and copied a 4-byte spot. I then compared the location of that 4-byte spot to the dump from the good run. It was exactly 972 bytes off from my calculation (probably the exact change in filesize from adding the certificate). I went on further to see if the same 4 bytes would be offset by the same amount in the full signed file compared to the original and low and came to the conclusion that the positions were completely unchanged by the signing process, as I suspected. I'm going to complete my test by trying to force a read from the buffer at exactly 972 bytes closer to byte 0 (by subtracting 972 bytes from the read location) and I will post my results. But I will probably take a break for now. I think I need it.

**Comment by Gray1989** [comment]
Actually I just want to briefly share something. If you're wondering how I managed to do all of that it wasn't easy. I went ahead and made an on-the-spot implementation to run an entire native executable package from within another. I did that in order to force the application to use external .js files to do so, which I copied directly from the source files which I conveniently have on my computer that I compiled JX itself with. I know that in the source code it creates semi-random markers in the executable. I decided not to break that by having the compiled app loaded by a direct copy of itself. I think it's pretty cool that it actually works, and without any errors. Well, the road to getting there had a bunch of errors but I'd say all-in-all it went pretty smooth. It beats the hell out of anything else I can think of for debugging build and run issues with native JX packages. I figure since I'm not the only one who can benefit from using the code I might as well share. Here is a copy for anyone interested:

```javascript
var fs = require('fs'), node = {}, runFn, tmp;
var requireTwo = function(packageName) {
	var exports = {};
	(new Function(['require','exports'], fs.readFileSync(packageName+'.js').toString()))(require, exports);
	return exports;
	};
var inputTransfer = {module: {}, NativeModule: null,
		require: function(packageName) {
		if(packageName === 'native_module')
			return inputTransfer.NativeModule;
		else if(packageName !== 'module')
			return require(packageName);
		if(inputTransfer.module.exports === undefined) {
			(new Function(['require','module'], fs.readFileSync('module.js').toString()))(inputTransfer.require, inputTransfer.module);
			}
		return inputTransfer.module.exports;
		}
	};
var bindp = function(fnToBind) {
	return Function.prototype.bind.call(fnToBind, process);
	};
var _process = {
	binding				:	bindp(process.binding),
	moduleLoadList		:	[],
	env					: 	process.env,
	cwd					:	bindp(process.cwd),
	argv				:	['jx'],
	isPackaged			:	true,
	reallyExit			:	function() {
								console.log("It seems there was an error.");
								process.exit();
								},
	execPath			:	process.execPath.replace('pk.exe','pk_test.exe'), // pk.exe opens pk_test.exe as a package for testing
	maxTickDepth		:	process.maxTickDepth,
	_tickInfoBox		:	{},
	_needTickCallback	:	bindp(process._needTickCallback),
	dontRun				:	true // will be true when pk_test.exe is loaded using custom files
	};
var startRepl = function(startNotification) {
	console.log(startNotification);
	console.log("For debugging purposes, this tool runs custom source-code for compiling");
	console.log("native executables. You may use compileJXP(projectName, jxpFileName) to");
	console.log("build a native executable using custom code. After compiling this file");
	console.log("from source, make one copy called pk_test.exe When running the compiled");
	console.log("binary, it will attempt to load the code inside pk_test.exe using the");
	console.log("custom source-code files. If anything fails, the custom source-code");
	console.log("files can be changed and the process can start over again. If pk_test.exe");
	console.log("is started directly this screen will be shown");
	require("repl").start({
		  prompt: "> ",
		  input: process.stdin,
		  output: process.stdout,
		  useGlobal: true,
		  eval: function(cmd, context, filename, callback) {
			callback(null, eval(cmd));
			}
		});
	};
//runFn = (new Function(['_process','process','require','requireTwo','isAfter','testReturn'], fs.readFileSync('process.js').toString()));
var jxp = requireTwo('_jx_package');
var compileJXP = function(projectName, jxpFileName) {
	jxp.compile(['jxp','compile',jxpFileName,projectName]);
	};
if(process.argv[1] !== undefined)
	startRepl("Compile this file to a native executable to test it against itself.");
else if(process.dontRun) startRepl("Successfully loaded package from external executable.");
else if(process.execPath.indexOf('pk_test.exe') === -1) {
	console.log("Attempting to load data from copy (pk_test.exe) using custom source");
	//runFn(_process, process, require, requireTwo, false, "");
	tmp = fs.readFileSync('node.js').toString();
	tmp = tmp.replace("(function(process) {", "(function(process, _inputTransfer) {");
	tmp = tmp.replace("NativeModule.require = function(id) {","NativeModule.require = function(id) { if(id && id === 'module') { _inputTransfer.NativeModule = NativeModule; return _inputTransfer.require(id); }");
	NativeModule = (new Function(['process'],'return '+tmp)).call(node).call(node, _process, inputTransfer);
	//runFn(_process, process, require, requireTwo, true, "");
	}
else startRepl("This is a working testing file used for signing.");
```

**Comment by Gray1989** [comment]
This one change made the signed file run, and proved my hyphothesis. However I don't know how the value could be dynamically derived. Maybe somebody more experienced can take over from here. But I will probably end up looking into it myself as-well, however as of yet I have no clue how I'm going to do that.
![image](https://cloud.githubusercontent.com/assets/10122452/10358508/ff9ce158-6d5c-11e5-8b33-515a3c4378c7.png)

**Comment by Gray1989** [comment]
I finally managed to get it working, it's kinda rough but it works. Maybe someone will find a better method. Right at the very end of module.js, this is what it looks like now:

`````javascript
  con = null;
  var obj = JSON.parse(jxt._ucmp(buffer, 1)), err;

  if (!obj.project && !(obj = function(expectedBufferSize){
	// Patch for fixing signed native package reading
	var sz = fs.statSync(process.execPath);
    var fd = fs.openSync(process.execPath, 'r');
	var readAmount = Math.min(10240 + expectedBufferSize, sz.size); // 10kb max signature
    var buffer = new Buffer(readAmount);
	var checks = [0x82, 0x30, 0, 2, 2, 0, 0, 0];
	var checksComplete = 0, obj, minBytes = expectedBufferSize + 22;
	var i = readAmount-1, l = checks.length, certSize;
    fs.readSync(fd, buffer, 0, readAmount, sz.size - readAmount);
	fs.closeSync(fd);
	while(i>=minBytes&&checksComplete<l) {
		if(checks[checksComplete] === buffer[i--])
			checksComplete++;	
		else checksComplete = 0;
		};
	if(checksComplete !== l) return false;
	certSize = (buffer[i--] << 8) + buffer[i];
	if(certSize === readAmount-i-- && buffer[i--] === 0
	 && buffer[i--] === 0 && buffer[i--] === 0) { i -= 17;
		buffer = buffer.slice(i-expectedBufferSize, i);
		}
	else return false;
	obj = JSON.parse(jxt._ucmp(buffer, 1));
	if(!obj.project) return false; return obj;
	}(buffer.length)))
		throw new Error('Package is either corrupted or not ' +
                        'compatible with this JX binary. (' + f + ')');
  ec = null;
  buffer = null;
  jxcore.tasks.forceGC();
  return readX(m, f, obj, pa, obj.project.extract);
};
`````

I haven't had a chance yet to try it out on anything but my testing certificate but I'm sure it will work. Might require some testing as I'm not 100% sure if it's completely bug-free. But again it seems to work.

**Comment by Gray1989** [comment]
@ktrzeciaknubisa let me know what you think :)

**Comment by ktrzeciaknubisa** [comment]
Well, looks like you've made a hell of the work :) Let me test it how it works against multiple engines/package architectures.

**Comment by Gray1989** [comment]
Sounds good :)

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 from where the values `var checks = [0x82, 0x30, 0, 2, 2, 0, 0, 0];` come from? Are they related to your cert file? 

Unfortunately it doesn't work for me. The execution arrives to the last line of your method, but the `obj = JSON.parse(jxt._ucmp(buffer, 1));` sets `obj` to false.

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 You can mail me at ktrzeciak@nubisa.com, so we can switch to skype for better communications?

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 Thanks to your research and the whole effort I was able to solve it by extending your first approach (finding dynamically the position for source reading).

That works for me 64/32 (so far only V8 tested). Can you please try to use this code and see on your end?

```diff
+++ c:\jxcore\jxcore_64v8\lib\jx\_jx_package.js Thu Oct  8 14:46:52 2015
@@ -860,7 +860,8 @@

   var c = JSON.stringify(contents);
   var cmped = scomp._cmp(c);
-
+  var rev = nativePackageMarker.split('').reverse().join('');
+  cmped = Buffer.concat([new Buffer(rev), cmped]);
   c = null;
   jxcore.tasks.forceGC();

@@ -1159,3 +1160,6 @@

   return id !== -1;
 };
+
+exports.binaryFileIndexOf = binaryFileIndexOf;
+exports.nativePackageMarker = nativePackageMarker;
```


```diff
+++ c:\jxcore\jxcore_64v8\src\node.js   Thu Oct  8 14:45:23 2015
@@ -1425,9 +1425,12 @@
         process.exit(1);
       }
       try {
+        var jx_package = NativeModule.require('_jx_package');
+        var rev = jx_package.nativePackageMarker.split('').reverse().join('');
+        var id = jx_package.binaryFileIndexOf(process.execPath, rev);
         var fd = fs.openSync(process.execPath, 'r');
         var buffer = new Buffer(sz.result);
-        fs.readSync(fd, buffer, 0, sz.result, sz.size - (sz.result + 16));
+        fs.readSync(fd, buffer, 0, sz.result, id + rev.length);
         fs.closeSync(fd);
         process.appBuffer = buffer.toString('base64');
         buffer = null;
```

**Comment by Gray1989** [comment]
The array values were a similar marker that I found both in my signed compiled native package and the officially signed jx.exe using a hex editor. It's very possible that I may have added an extra zero where there didn't need to be one. After the marker I found are two bytes which exactly equal the length of the certificate (hence the extra checks). Then there are three zeros (accounting for 5 bytes after the certificate) making the total extra bytes at the bottom the size of the certificate plus 5. However at that point it was just more efficient to calculate with i. I will try out your method though. Seems to be much more to-the-point than mine.

**Comment by Gray1989** [comment]
@ktrzeciaknubisa So, I was hoping that your changes would work but unfortunately I still landed at the same error, that the package was corrupt. However I was also able to reproduce your error with my patch. It turns out I didn't end up trying it enough times to realize that the pattern of the two bytes equaling the size of the certificate is not always true, and that the amount of bytes offset from the certificate is not always the same. I made modifications to my script which seem to work for the newly signed files and logically should work for my older test-case as-well. I will keep testing but in the meantime here is the supposedly-more-stable version:

`````javascript
  con = null;
  var obj = JSON.parse(jxt._ucmp(buffer, 1)), err;

  if (!obj.project && !(obj = function(expectedBufferSize){
	// Patch for fixing signed native package reading
	var sz = fs.statSync(process.execPath);
    var fd = fs.openSync(process.execPath, 'r');
	var readAmount = Math.min(10240 + expectedBufferSize, sz.size); // 10kb max signature
    var buffer = new Buffer(readAmount);
	var checks = [0x82, 0x30, 0, 2, 2, 0, 0, 0];
	var checksComplete = 0, obj, minBytes = expectedBufferSize + 22;
	var i = readAmount-1, l = checks.length, certSize;
    fs.readSync(fd, buffer, 0, readAmount, sz.size - readAmount);
	fs.closeSync(fd);
	while(i>=minBytes&&checksComplete<l) {
		if(checks[checksComplete] === buffer[i--])
			checksComplete++;	
		else checksComplete = 0;
		};
	if(checksComplete !== l) return false;
	// If it made it past here, it found the digital signature marker,
	// Code below was fixed from the original
	certSize = (buffer[i--] << 8) + buffer[i];
	if(certSize === readAmount-i--) {
		while(buffer[i] === 0) i--; } i -= 15;
	buffer = buffer.slice(i-expectedBufferSize, i);
	obj = JSON.parse(jxt._ucmp(buffer, 1));
	if(!obj.project) return false; return obj;
	}(buffer.length)))
		throw new Error('Package is either corrupted or not ' +
                        'compatible with this JX binary. (' + f + ')');
  ec = null;
  buffer = null;
  jxcore.tasks.forceGC();
  return readX(m, f, obj, pa, obj.project.extract);
};
`````

I'm not sure which patch I like better though. Yours adds extra dependencies to node.js but is cleaner (as long as it's working). Mine is uglier but it's more contained as a patch which I find as a bonus (it doesn't execute the code unless a rare fatal error might be thrown).

**Comment by Gray1989** [comment]
@ktrzeciaknubisa I also modified the debugging file code I wrote (for pk.exe/pk_test.exe) very slightly to work better better for debugging your code and fixed also fixed a small error in it. You should try it out, it's quite handy. I can easily switch back and forth between trying different methods and implementations in the source code files and I'm able to test it all instantly. I probably wouldn't even be attempting all of this otherwise.

**Comment by Gray1989** [comment]
@ktrzeciaknubisa  As for trying to find out what was wrong with your method, I really don't see why it doesn't work. `binaryFileIndexOf` seems to be failing and returning -1. That probably has something to do with the fact that it's being loaded dynamically, perhaps it's breaking something somehow and would work using it as it should be used. However, having said that, looking inside `binaryFileIndexOf` I see it is unnecessarily complicated and uses way more cycles than it should for the type of operation it's performing. My code is actually designed to do pretty much the exact same thing but only with the marker automatically put there by the signer. If you look at the difference in code between the two you could probably see the unnecessary complication with the nested loops. Anyways here is a screenshot of how far I did manage to get using your code. I think the `binaryFileIndexOf` method deserves a rewrite that I could probably help with.

![image](https://cloud.githubusercontent.com/assets/10122452/10386206/063393ca-6e22-11e5-89a3-0c431f751303.png)

**Comment by ktrzeciaknubisa** [comment]
The issue discussed here is already implemented with https://github.com/jxcore/jxcore/pull/615 , so ticket can be closed. Thanks again @Gray1989
