### ISSUE TITLE
Some simple test failures in 0.3.1.0

### ISSUE THREAD

**Issue by brodybits** [jxcore/jxcore#585]
- `./jx test/simple/test-api-tasks.js` - hangs in V8 build (OK in Mozilla-JS build)
- `./jx test/simple/test-crypto.js` - prints error message; crash in Mozilla-JS build only
- `./jx test/simple/test-process-config.js` - fails with the following error message: `AssertionError: test-process-config.js-config.gypi_v8 file not found. Please run configure.`

In addition, `make jslint` reports 15 errors in 7 files; `make jslintfix` reduces them to 5 errors in 3 files.

**Comment by obastemur** [comment]
Indeed this branch will be a bit shaky until Chakra integration is done.

**Comment by brodybits** [comment]
`make test-message`, which is part of `make test` in Node.js 0.10.x and 0.12.x, does not work at all. Should be investigated when we get a chance.

`make test-http1` also fails with a few errors, including `test-api-tasks.js`.

`make test-internet` passes with no errors.

`make test-pummel` has a few errors, does not look so urgent right now.

**Comment by obastemur** [comment]
`make test-message` depends on exact output comparison. That should be the reason.

**Comment by brodybits** [comment]
When I configure with the `--engine-v8-3-28` option and run the test suite on the `0.3.1.0` branch, I get quite a few failures. I suspect we shouldn't worry too much about it for now. I will investigate some of these if I get a chance.

After almost a day of testing and debugging, I discovered that background jobs are broken in the default V8 configuration and came up with the following quick fix:

```diff
--- a/src/jx/jx_instance.cc
+++ b/src/jx/jx_instance.cc
@@ -42,9 +42,18 @@ void JXInstance::runScript(void *x) {
 #endif
     do {
 #ifdef JS_ENGINE_V8
+#ifdef V8_IS_3_14
+      v8::Isolate *isolate = v8::Isolate::New();
+      v8::Locker locker(isolate);
+      v8::Isolate::Scope isolateScope(isolate);
+      v8::HandleScope handle_scope;
+#else
       JS_ENGINE_LOCKER();
+#endif
+
       JS_SET_ENGINE_DATA(isolate, &com->threadId);
       com->node_isolate = isolate;
+
       JS_DEFINE_STATE_MARKER(com);
 
       JS_NEW_CONTEXT(context, isolate, NULL);
```

In addition, `test/simple/test-process-config.js` can be fixed by simply copying the version from Node 0.10.x/0.12.x.

**Comment by obastemur** [comment]
Great to hear. Can we apply the change into JS_ENGINE_LOCKER instead?

**Comment by brodybits** [comment]
Yes (looks like this was already done in `src/jx/Proxy/V8_3_28/V8Environment.h`). The following change seems to do the trick and pass the tests in the case of default V8 engine configuration:
```diff
--- a/src/jx/Proxy/V8_3_14/V8Environment.h
+++ b/src/jx/Proxy/V8_3_14/V8Environment.h
@@ -100,10 +100,11 @@ typedef void (*JS_FINALIZER_METHOD)(JS_HANDLE_VALUE_REF val, void *data);
 
 #define JS_MAKE_WEAK(a, b, c) a.MakeWeak(b, c)
 
-#define JS_ENGINE_LOCKER()                          \
-  v8::Locker locker;                                \
-  v8::Isolate *isolate = v8::Isolate::GetCurrent(); \
-  v8::HandleScope scope
+#define JS_ENGINE_LOCKER()                   \
+  v8::Isolate *isolate = v8::Isolate::New(); \
+  v8::Locker locker(isolate);                \
+  v8::Isolate::Scope isolate_scope(isolate); \
+  v8::HandleScope scope;
 
 #define JS_ENGINE_INITIALIZE() v8::V8::Initialize()
``` 

I will probably update PR #588 tomorrow night to reflect this change and *may* also add the V8 x64 arch fix.

I also noticed that `src/jx/Proxy/JSEngine.h` is able to support multiple V8 engine versions right now. From the comments I gather suspect that the old 3.14 support (and perhaps the `src/jx/Proxy/V8_3_14` tree) will go away once the newer V8 version is properly integrated. Am I right about this or am I mistaken somehow?

**Comment by brodybits** [comment]
I have now updated PR #588 and added another minor fix to tcp_wrap.cc, which fixes a bunch of child-process and cluster tests in the case when the `--engine-v8-3-28` configure option is used. The following tests still fail when `--engine-v8-3-28` is used:
- `test-domain.js`
- `test-event-emitter-memory-leak.js`
- `test-repl.js`

In addition, `test-signal-handler.js` crashes when `--engine-v8-3-28` is used, and `test-crypto-binary-default.js` *sometimes* crashes when `--engine-v8-3-28` is used.

**Comment by obastemur** [comment]
Thanks for the details. Think this is no longer an issue
