### ISSUE TITLE
JXCore Plesk Extension - req.connection.remoteAddress always 127.0.0.1

### ISSUE THREAD

**Issue by gopumon** [jxcore/jxcore#592]
I am running a nodejs server with express on my VPS with JXCore Plesk Extension. There is a log output whenever someone access the server which logs the client's IP. But in the log all I can see is IP 127.0.0.1. (I am using request-ip module to get IP from 'req')

**Comment by obastemur** [comment]
@gopumon Plesk runs on front of nginx. Nginx proxies web etc. clients to localhost.

**Comment by gopumon** [comment]
@obastemur I tried `proxy_pass` in nginx config and a lot more but failed to get the remote_addr. Is there any workaround know?

**Comment by gopumon** [comment]
@obastemur Finally I edited `/etc/nginx/jxcore.conf.d/mynodesite.com.conf` and added

```
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Accel-Internal /internal-nginx-static-location;
```
under the location of each server section.

Now I am getting both `req.header['x-real-ip']` and `req.header['x-forwarded-for']` with client's ip.

I was editing `/var/www/vhosts/system/mynodesite.com/conf/latest_nginx.conf` and banging my head. How stupid!

**Comment by gopumon** [comment]
The file `/etc/nginx/jxcore.conf.d/mynodesite.com.conf` got reverted to its previous state...

**Comment by ktrzeciaknubisa** [comment]
Why don't you use `nginx directives` field on domain's configuration form?

**Comment by gopumon** [comment]
I tried... it is not helping.

When I edited the `/etc/nginx/jxcore.conf.d/mynodesite.com.conf` file it was working. But when jxcore restarts the file reverts to its original.

**Comment by ktrzeciaknubisa** [comment]
> I tried... it is not helping.

What do you mean? Does not the field's value get saved into `/etc/nginx/jxcore.conf.d/mynodesite.com.conf`? 

> But when jxcore restarts the file reverts to its original.

Yes, the file is not for manual modification. Hence the `nginx directives` field.

**Comment by gopumon** [comment]
@ktrzeciaknubisa in `nginx directives` i will not be able to set 
```
location / {
       #Proxy set headers, proxy bypass etc
}
```

jxcore is taking `location / {}` from `/etc/nginx/jxcore.conf.d/mynodesite.com.conf` and not from 
`/var/www/vhosts/system/mynodesite.com/conf/latest_nginx.conf` which have all the proxy set header rules.

That is why I am not to able to get `req.headers['x-real-ip']` or `req.headers['x-forwarded-for']` in my node application. (I am using express and I have set `trust proxy` to `true` in the script.

**Comment by ktrzeciaknubisa** [comment]
If I get you right, and you're setting `nginx directives` with:

```
location / {
       #Proxy set headers, proxy bypass etc
}
```

then it's wrong. Just paste the contents of location's curly bracket:
```
proxy_set_header Host             $host;
proxy_set_header X-Real-IP        $remote_addr;
proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
```

***

I'm not aware of `/var/www/vhosts/system/mynodesite.com/conf/latest_nginx.conf` file. Is it coming from Plesk? JXcore has nothing to do with it.

**Comment by gopumon** [comment]
@ktrzeciaknubisa  I know thats wrong and the form will show an error too... 

placing the content without location will also not work.  I can see now `/etc/nginx/jxcore.conf.d/mynodesite.com.conf` is like this

```
server{
  root /var/www/vhosts/mynodesite.com/;
  listen 127.0.0.1:80;
  server_name www.mynodesite.com mynodesite.com;
  location / {
    proxy_pass http://127.0.0.1:10026;
    proxy_read_timeout 9999999;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
  #plan`s directives
  proxy_set_header Host             $host;
  proxy_set_header X-Real-IP        $remote_addr;
  proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
}

```

What I need is the directives under `#plan`s directives` should come within `location / {}` to get `req.headers['x-real-ip']` or `req.headers['x-forwarded-for']`


The file `/var/www/vhosts/system/mynodesite.com/conf/latest_nginx.conf` is the plesk's nginx conf file for that particular domain.

**Comment by ktrzeciaknubisa** [comment]
Ok, I see now. I missed the part, that your settings must go into `location` itself. Well, sorry to say, currently JXcore extension doesn't offer a way for editing the default location. I'm not sure whether nginx allows to override it either. 

I guess we need to add a way for user to redefine `location /`.

**Comment by ktrzeciaknubisa** [comment]
After looking into nginx documentation, I've found out that you may also use `=` sign to override default location:

```
location = / {
       # copy here values rendered by JXcore
       #Proxy set headers, proxy bypass etc
}
```

**Comment by gopumon** [comment]
@ktrzeciaknubisa I tried this solution, this works only on route `/` and if need it for another route like `/authenticate`,  I need to add

```
location = /authenticate {
       # copy here values rendered by JXcore
       #Proxy set headers, proxy bypass etc
}
``` 
This need to be repeated for each route.

In my opinion the the below three are needed by Node developers. Plesk put these settings standard for PHP. It would be great if you can add these three along with the `Upgrade` and `connection` headers.

```
  proxy_set_header Host             $host;
  proxy_set_header X-Real-IP        $remote_addr;
  proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
```

**Comment by ktrzeciaknubisa** [comment]
Well that still would not be a robust solution. I'm trying to figure out, why those fields defined in **server** context are not passed to `req.headers`. The [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) supports this context too.

```
Context: 	http, server, location
```

**Comment by gopumon** [comment]
I think the headers in request object is created with headers passed through location context and not the server context.

**Comment by ktrzeciaknubisa** [comment]
Ok. You were right. Plesk itself sets those headers in its configs, too. So I added them as default, until we'll know, why node is receiving headers only from location context. 

You may fetch the dev version of [JXcore_Plesk0273.zip](https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk0273.zip) and test it out.

**Comment by gopumon** [comment]
@ktrzeciaknubisa The test was successful! Now getting  `Host` `X-Real-IP` `X-Forwarded-For` header in the `request` object.

I have some feature request for Plesk extension's NPM section
> 1. Multiple Package Installation (for example : coma seperated package names will be parsed and installed in one go. This will help developers while deploying their node application)
> 2. Check for package update and provision to update the package (A feature to notify user that the npm package have an update available and A button to update it)

Thank You for your support!

**Comment by ktrzeciaknubisa** [comment]
@gopumon Thanks for the test. And suggestions. You may post them into separate ticket.

I'm closing this one :) 
Thank you.
