### ISSUE TITLE
How can I NodeJS at NPM modules Install and activate?

### ISSUE THREAD

**Issue by Shorty1968** [jxcore/jxcore#594]
What exactly do I have to register with NPM modules?
I have it with node and NodeJS tried but without erfrolg.

**Comment by obastemur** [comment]
A bit more details pls?

**Comment by Shorty1968** [comment]
I have installed on my server node js and want it now with JXcore Plesk Extension for Node at a domain anwenden.was I have it at NPM modules eigeben and how can I start with JXcore Plesk Node Extension for NPM?

**Comment by ktrzeciaknubisa** [comment]
Probably you're using Google Translate and so it's hard do catch a meaning of your question.

But of you ask: "how to install NPM modules for JXcore Plesk Extension for Node", this is the answer:

Go to JXcore Extension in Plesk, and:

1. click tab 'NPM Modules'
2. enter name of the module, you wish to install
3. click OK


![plesk_npm](https://cloud.githubusercontent.com/assets/5946844/10430417/5ea93b74-70ff-11e5-9e8b-1e0927f7d301.png)

**Comment by Shorty1968** [comment]
Thats my troble i dont no the name for nodejs or npm start?

**Comment by ktrzeciaknubisa** [comment]
You will not be able to run `npm start` command under Plesk. Why do you need this?

**Comment by Shorty1968** [comment]
I need this for starting the push server

**Comment by ktrzeciaknubisa** [comment]
Is your push server on npm respository? Can you post a link?

**Comment by Shorty1968** [comment]
what exactly does NPM repository?
Sorry I set up the first time a push sevrer
Do you think a link to the domain?

https://computer-base.net/

**Comment by ktrzeciaknubisa** [comment]
I meant link to the push server, which you want to install and start (not your domain)

**Comment by Shorty1968** [comment]
https://computer-base.net/:10000

**Comment by ktrzeciaknubisa** [comment]
What is just the name of your push server module... 

How did you install it?

**Comment by Shorty1968** [comment]
understand not what exactly they mean by name of push server?

I have it installed on Putty NodeJS and then set up the plug-in for the forum software.
