### ISSUE TITLE
JXcore 0.3.0.5 updaten to JXcore v0.3.0.7?

### ISSUE THREAD

**Issue by Shorty1968** [jxcore/jxcore#598]
How can I update my extension in Plesk catalog it is not yet available as an update?

**Comment by ktrzeciaknubisa** [comment]
In Plesk catalog there is always the newest version of JXcore extension: https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support .
