### ISSUE TITLE
What exactly can I do with JXcore Plesk Node Extension for?

### ISSUE THREAD

**Issue by Shorty1968** [jxcore/jxcore#599]
What exactly can I do with JXcore Plesk Node Extension for?

NodeJS is installed by Plesk JXcore Extension for Node or do I have to do it yourself and JXcore Plesk Extension for node can only manage it?

**Comment by ktrzeciaknubisa** [comment]
> What exactly can I do with JXcore Plesk Node Extension for?

We have a few blog post on what JXcore Plesk Node Extension is for. Basically it allows you to run Node.JS application under your internet domain. 

> NodeJS is installed by Plesk JXcore Extension for Node or do I have to do it yourself

The extension does not install Node.JS - it installs JXcore, which is able to execute Node.JS applications. Once you install the extension, you need to enter its pages and additionally install JXcore (by clicking a button).

With extension you can also configure your application: instruct, how you want to run it under the domain.

**Blog posts:**

- [Managing Node.JS Applications with JXcore Plesk Extension](http://jxcore.com/managing-node-js-applications-with-jxcore-plesk-extension/)
- [JXcore Plesk Extension v0.2.5 released](http://jxcore.com/jxcore-plesk-extension-v2-0-5-released/)
- [JXcore Plesk Extension v0.2.6](http://jxcore.com/jxcore-plesk-extension-v2-0-6/)
- [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/)

**Comment by Shorty1968** [comment]
thank you can I use it for a node Push Server?

**Comment by ktrzeciaknubisa** [comment]
I was asking you previously in https://github.com/jxcore/jxcore/issues/594#issuecomment-147424061 for a link to this Push Server, but we coudn't understand each other. 

Is this your Push Server: https://github.com/Smile-SA/node-pushserver ?

**Comment by Shorty1968** [comment]
No My nodePush server should be running if he can be contacted at https://computer-base.net:10006

But I know, unfortunately, not exactly what I have to do at JXcore Plesk Extension for Node to use Node.js can so that the server is running?
