### ISSUE TITLE
SIGABRT in JXcore.m

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#601]
The output is [here](https://gist.github.com/yaronyg/09b1fc43bc89a714142d). I'm still using Cordova 0.0.5. The exception happened on line 443 of JXcore.m. Please take a look at the very end of the output to see the actual exception which is:

```
2015-10-13 20:11:51.221 ThaliTest[1905:2169627] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM insertObject:atIndex:]: index 1 beyond bounds for empty array'
*** First throw call stack:
(0x18411822c 0x195de40e4 0x183fff160 0x10010573c 0x100106d4c 0x100107188 0x10010c6a0 0x10010c5d4 0x10010c514 0x1001131c0 0x100988fd4 0x100988f94 0x10098dc28 0x1840cf544 0x1840cd5ec 0x183ff8f74 0x18da536fc 0x188bfad94 0x100101188 0x19648ea08)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

I currently have it live in my debugger. I'll see if it survives until tomorrow.

**Comment by obastemur** [comment]
AFAIK @tobybrad mentioned this issue before and it seemed to me a none jxcore related issue. I should try this on my end, what are the repro steps exactly ?

**Comment by yaronyg** [comment]
I'll close his issue here until we have a repo.

**Comment by tobybrad** [comment]
See here for probable fix - https://github.com/jxcore/jxcore-cordova/commit/5e4cfb175d37ec1331e701f044bb87d3f4c01817
