### ISSUE TITLE
Is there a way to build static libs with libc++ instead of libstdc++ on OS X?

### ISSUE THREAD

**Issue by zsszatmari** [jxcore/jxcore#603]
Hi!

I am trying to embed jxcore into an existing large-ish project. It is using libc++ and can not go back to libstdc++ due to other constraints. libstdc++ is also not really supported by Apple anymore exactly because of the more modern libc++ runtime. I guess I am not alone with this issue.
(I know one workaround that might work here is to build jxcore dynamically, I'll try that, but the question remains)
 
Thanks!

**Comment by brodybits** [comment]
That was already answered in #596 by @shinichy:

> I made it work by changing MACOSX_DEPLOYMENT_TARGET in common.gypi and setting CXX env variable below.
> Thanks!
> ```diff
> diff --git a/common.gypi b/common.gypi
> index 95f71dd..bbab63b 100755
> --- a/common.gypi
> +++ b/common.gypi
> @@ -241,7 +241,7 @@
>            'GCC_ENABLE_PASCAL_STRINGS': 'NO',        # No -mpascal-strings
>            'GCC_THREADSAFE_STATICS': 'NO',           # -fno-threadsafe-statics
>            'PREBINDING': 'NO',                       # No -Wl,-prebind
> -          'MACOSX_DEPLOYMENT_TARGET': '10.5',       # -mmacosx-version-min=10.5
> +          'MACOSX_DEPLOYMENT_TARGET': '10.7',       # -mmacosx-version-min=10.5
>            'USE_HEADERMAP': 'NO',
>            'OTHER_CFLAGS': [
>              '-fno-strict-aliasing',
>```
>```shell
> export CXX="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -std=c++11 -stdlib=libc++"
> make
>```

Should be documented!

**Comment by treasurebox** [comment]
Thanks for the very quick answer! Maybe there could be a ./configure option for that, or at least mentioned in Embedding_Basics? Of course I understand you have other things to do, no worries.

**Comment by brodybits** [comment]
I am not an owner so I cannot make these decisions. I do agree that this should be covered in the Embedding_Basics, and IMO OSX pre-Lion should not be supported by default configuration. Also `MACOSX_DEPLOYMENT_TARGET` is set to `10.5` in `common.gypi` and to `10.7` in `jx.gyp`, should only be defined in one place.

**Comment by obastemur** [comment]
`10.7` is SM only requirement. I have no problem making `libc++` optional. You can PR that.

i.e. 
```
./configure ---use-libc
```

**Comment by treasurebox** [comment]
Personally I seem to have decided to go the dynamic library route after all, so as far as I am concerned, this issue is not that urgent now, but I imagine that there could be others who really want a static lib :) Thanks for helping me out!

**Comment by obastemur** [comment]
> I am not an owner so I cannot make these decisions. 

@brodybits  `Owner` is just a Github tag. Somebody needs to do the ugly work ;)

@treasurebox Making `libc` optional is not that hard. BTW; we could also support compiled JXcore as a dynamic lib. on OSX too. For now, it's Windows only build setting though.

**Comment by treasurebox** [comment]
@obastemur I am not sure I can follow. I just tried and tested ```./configure --shared-library``` and it seems to work well, at least as far as my hello world is concerned, on OS X.

**Comment by obastemur** [comment]
@treasurebox good to hear tough. I'm just not sure if it will be fine with all the other combinations.  

Okay taking this item on me. We can make this proper (if it's not) for 0.3.1.0

**Comment by obastemur** [comment]
I didn't see any issue with `shared-library` option under *nix. We might mention this on the documentation (build / native libs). @zsszatmari would you like to contribute mentioning shared library ? (since you have discovered there is no issue there)

**Comment by zsszatmari** [comment]
Okay, sent a pull request!

**Comment by ktrzeciaknubisa** [comment]
Issue clarified by doc comment https://github.com/jxcore/jxcore/pull/627
