### ISSUE TITLE
Can I access javascript Buffers as char * pointers from native side?

### ISSUE THREAD

**Issue by treasurebox** [jxcore/jxcore#605]
I see there is ```JX_SetBuffer()``` but I'd like to read it :) This is pretty urgent now for me, so I am all in for hacks and workarounds. Thanks!

**Comment by obastemur** [comment]
Did you see the docs ? https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_API_Details.md . It's also used in jxcore-cordova project.

**Comment by treasurebox** [comment]
I am sure it's me to blame, but I can't see the solution in the docs, could you hint me?
```JX_GetString()``` is documented as it returns ```char *``` to buffer, but as the returned value must be ```free()```d, I assume it copies, which is not good for my use case. Also, it does not seem to do any good with RT_Buffer in the switch statement, it defaults to ```.toString()```. Also, my buffer contains binary data (not zero terminated).

I cannot seem to find other reference to Buffer in the docs.
Thank You!
