### ISSUE TITLE
Unable to activate after adding JXCore Plesk Extension (Plesk 12.0.18)

### ISSUE THREAD

**Issue by gopumon** [jxcore/jxcore#606]
My mediatemple (shared) DV have a 'Plesk 12 Web Host Edition' license. Where I can manage Resellers and Customers. But When I add the JXCore extension it is not going beyond the "Terms and Conditions" page. Coming back to the same "Terms and Conditions" page when I hit OK.

**Comment by ktrzeciaknubisa** [comment]
Which is your platform? Is it mentioned on JXcore [download](http://jxcore.com/downloads/) page?

**Comment by gopumon** [comment]
The its **CentOS release 5.8 (Final)**  as saw in `cat /etc/redhat-release`, and I believe Plesk will show only compatible extensions.

**Comment by ktrzeciaknubisa** [comment]
I'll bet it's x32? https://github.com/jxcore/jxcore/issues/425#issuecomment-119219564. 

But eve if it is, you should  receive a message when pressing `OK` button on *Terms and Conditions* page. I assume you don't?

**Comment by gopumon** [comment]
I am getting no such message.

**Comment by ktrzeciaknubisa** [comment]
Never tested, but for the first install 50 MB should be enough (JXcore zip gets downloaded and unpacked). Are you having space issues?

**Comment by gopumon** [comment]
I have more than 7GB free. Still don't know why it is not getting installed.

**Comment by ktrzeciaknubisa** [comment]
I'll provide you with the debug version these days, so we can solve this out. May I use for that your mail address from your profile page?

**Comment by gopumon** [comment]
yes please!

**Comment by gopumon** [comment]
I installed the debug version. There is no on screen error display. Will it create any debug.log??

**Comment by ktrzeciaknubisa** [comment]
Thank you. Would you send me by mail a printscreen? If you don't see any screen message, than we have other problem too.

**Comment by gopumon** [comment]
Please find attached screen shot. When I pressed OK, it comes back to the same screen. This is a screenshot after I pressed OK.

![screenshot-70 32 104 20 8443 2015-10-19 21-57-51](https://cloud.githubusercontent.com/assets/3767710/10586420/19c76248-76ad-11e5-9232-fb30cd19d782.png)

**Comment by ktrzeciaknubisa** [comment]
Thank you. 

Can you download again dev version again, install again and then navigate
to:

modules/jxcore-support/index.php/debug

?



From:  Gopakumar <notifications@github.com>
Reply-To:  jxcore/jxcore
<reply+005abddce3c3cec6216f46ebd3f719e02c391e3de71ec5b792cf00000001123cf2de9
2a169ce06a7570c@reply.github.com>
Date:  Monday, October 19, 2015 at 8:05 PM
To:  jxcore/jxcore <jxcore@noreply.github.com>
Cc:  Krzysztof <ktrzeciak@nubisa.com>
Subject:  Re: [jxcore] Unable to activate after adding JXCore Plesk
Extension (Plesk 12.0.18) (#606)


Please find attached screen shot. When I pressed OK, it comes back to the
same screen. This is a screenshot after I pressed OK.

 <https://cloud.githubusercontent.com/assets/3767710/10586420/19c76248-76ad-
11e5-9232-fb30cd19d782.png>


Reply to this email directly or view it on GitHub
<https://github.com/jxcore/jxcore/issues/606#issuecomment-149299788> .

**Comment by gopumon** [comment]
I got a screen as attached.
![screenshot-70 32 104 20 8443 2015-10-21 11-03-56](https://cloud.githubusercontent.com/assets/3767710/10629867/909561ae-77e3-11e5-8740-7d0337d7f0ca.png)

**Comment by gopumon** [comment]
I tried the new debug version too... it is not passing the "Terms and Conditions"

**Comment by ktrzeciaknubisa** [comment]
I know, but still no messages on screen?

**Comment by ktrzeciaknubisa** [comment]
Just to make sure: I'm talking about https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/debug/JXcore_Plesk.zip .

**Comment by gopumon** [comment]
Yes! Just now also I downloaded the version from link above and tried. Absolutely no messages...

**Comment by ktrzeciaknubisa** [comment]
Hi @gopumon . For the platform, where extension does not install JXcore - I've updated the debug link above. Could you please try again? And If there is no messages on the screen, there should be */opt/psa/var/modules/jxcore-support/debug.log* created.

**Comment by gopumon** [comment]
@ktrzeciaknubisa there is no log file created at path `/opt/psa/var/modules/jxcore-support/debug.log`

**Comment by ktrzeciaknubisa** [comment]
This is annoying :) Which user owns the folder? Or would you send me result of:
`ls -al /opt/psa/var/modules/jxcore-support/` ?

**Comment by gopumon** [comment]
The `/opt/` contains no directories or files, it's empty and owner is `root`.

`ls -al /opt/psa/var/modules/jxcore-support/` is returning `ls: /opt/psa/var/modules/jxcore-support/: No such file or directory` as expected.

**Comment by ktrzeciaknubisa** [comment]
That's weird. I Plesk properly installed? Is it used for production and working?

How about `ls -al /usr/local/psa/var/modules/jxcore-support/` ?

**Comment by ktrzeciaknubisa** [comment]
Or you may try to find jxcore extension on filesystem:

```bash
find / -name jxcore-support
```

**Comment by gopumon** [comment]
Its a mediatemple.net DV for production
Finally found the debug file at `/usr/local/psa/var/modules/jxcore-support/`

The content is 
```
status : 1
clear
initAction 1
jx valid ?
initAction 2
downloadAndUnpack_JXcore 1: err , zip: /usr/local/psa/var/modules/jxcore-support/jx_rh64v8.zip
downloadAndUnpack_JXcore 2: err 1, msg: Cannot execute `jx -jxv`. Is the binary downloaded for the right platform?
download: err: 1, msg:
```

**Comment by gopumon** [comment]
The OS is x64 as in `cat /proc/version`
```
Linux version 2.6.32-042stab102.9 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Fri Dec 19 20:34:40 MSK 2014
```

**Comment by ktrzeciaknubisa** [comment]
But it looks like [jx_rh64v8](https://jxcore.s3.amazonaws.com/0307/jx_rh64v8.zip) doesn't work there. Can you confirm this by downloading it manually? You can help yourself with the following command. Installs jxcore to the current folder:

```bash
$ curl http://jxcore.com/xil.sh | bash -s local
```

and then:

```bash
$ ./jx -jxv
```

**Comment by gopumon** [comment]
After running the `curl` i got this 

```
JXcore installed locally in current folder.
/usr/local/psa/var/modules/jxcore-support/jx: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /usr/local/psa/var/modules/jxcore-support/jx)

/usr/local/psa/var/modules/jxcore-support/jx: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /usr/local/psa/var/modules/jxcore-support/jx)

Cleaning up...

```

**Comment by ktrzeciaknubisa** [comment]
Someone had something similar before: https://github.com/jxcore/jxcore/issues/530 .

> How about apt-get update or apt-get install build-essential ?

**Comment by gopumon** [comment]
The `jx` is must be compiled in `glibc version 2.7` and I just found mine is `glibc version 2.5`.

As it is a production server I will not be able to upgrade it.

**Comment by ktrzeciaknubisa** [comment]
The thing is, that on our RH compilation platform we have 2.12:

```bash
$ ldd --version
ldd (GNU libc) 2.12
```

You can also try to compile jxcore on your own on that exact platform. There are ways to tell to Plesk's extension to use compiled binary instead of downloaded one.

**Comment by ktrzeciaknubisa** [comment]
New JXcore Plesk Extension v0.2.8 has been officially [released](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). 

We wrote a [blog post](http://jxcore.com/enhanced-npm-modules-management-with-jxcore-plesk-extension-v0-2-8/) describing all updates.

One of them is an extra debug logging option added supporting such scenarios, where no message is being displayed, as @gopumon mentioned in this thread.

Since we already know, that JXcore needs to be recompiled for the platform, I'm closing the ticket.
