### ISSUE TITLE
Apply NPM installed modules and use?

### ISSUE THREAD

**Issue by Shorty1968** [jxcore/jxcore#609]
I had to get up and running and running with screen NPM start on when I close my Putty node push server via Putty with NPM start.

How can I do with JXcore Plesk Node Extension for that now?

How exactly do I apply the NPM installed modules and use?

**Comment by ktrzeciaknubisa** [comment]
Same as usual: `require('module_name')`.

**Comment by Shorty1968** [comment]
do not understand what is meant by, as always, I've never done that start just starting to work with it and learn.

I have to run in Putty or where and how?

**Comment by ktrzeciaknubisa** [comment]
This is basics for running Node.JS application. If you start to work with it, probably you need to see some tutorials, e.g. http://www.nodebeginner.org/.

I'm very sorry, but we can help only with detailed problem descriptions.

**Comment by Shorty1968** [comment]
I need to start my node push server in a specific location with putty npm install and start running NPM, how can I do that with JXcore Plesk Node Extension for?
