### ISSUE TITLE
Packed executable size

### ISSUE THREAD

**Issue by dluciv** [jxcore/jxcore#611]
... is very big.

It is easily compressable, but it strongly relies on its internal layout, so compressing it with, for example, upx, breaks everything.

**Comment by obastemur** [comment]
/cc @ktrzeciaknubisa 
Solution: https://github.com/jxcore/jxcore/issues/508

**Comment by dluciv** [comment]
So It will be improved soon, right?

**Comment by obastemur** [comment]
@ktrzeciaknubisa can we make this part of 0.3.1.0 ? It could help the size of `jxcore-cordova` release package.

**Comment by ktrzeciaknubisa** [comment]
Let's try then! You might want to merge https://github.com/jxcore/jxcore/pull/589 first.

**Comment by dluciv** [comment]
Ok, guys, thank you very much!

**Comment by obastemur** [comment]
This must be fixed with 0.3.1.0
