### ISSUE TITLE
Plesk: global NPM install

### ISSUE THREAD

**Issue by einzelkind** [jxcore/jxcore#612]
Hi,
how is it possible to install a NPM like EJS globally via plesk? npm install -g package ?
Can't find any documentation for this procedure…

Best regards
david

**Comment by ktrzeciaknubisa** [comment]
There is no global support for installing npm modules through JXcore extension for Plesk. Anyway you don't really need NPM, do you? Please note, that JXcore uses its own `install` command for greater compatibility.

**Comment by einzelkind** [comment]
Hi Krzysztof,

I need to use the EJS NPM. The installation was successful. But after loading it in the index.js for example - I got the following error.
	I thought it is an installation issue.

Error: Cannot find module 'ejs'
at Function.Module._oldRes (module.js:774:9)
at Function.Module._resolveFilename (module.js:1606:15)
at Function.Module._load (module.js:335:17)
at Module.require (module.js:451:15)
at require (module.js:469:13)
at new View (/opt/psa/var/modules/jxcore-support/native_modules/node_modules/express/lib/view.js:78:30)
at EventEmitter.render (/opt/psa/var/modules/jxcore-support/native_modules/node_modules/express/lib/application.js:569:12)
at ServerResponse.render (/opt/psa/var/modules/jxcore-support/native_modules/node_modules/express/lib/response.js:961:7) 

=(

**Comment by ktrzeciaknubisa** [comment]
Do you have shell access? Does the following folder exists?
*/opt/psa/var/modules/jxcore-support/native_modules/node_modules/__ejs__*

**Comment by einzelkind** [comment]
Hi,
Yes The folder exists.

**Comment by ktrzeciaknubisa** [comment]
If you make a simple test.js and call:

```js
require('ejs');
//or
require('/opt/psa/var/modules/jxcore-support/native_modules/node_modules/ejs');
```

does it also fail?

**Comment by einzelkind** [comment]
> Yes. It fails. 
Module not found.
;(

**Comment by ktrzeciaknubisa** [comment]
And what info you have on `NPM Modules` tab in Plesk next to ejs module? Is version number displayed?

**Comment by einzelkind** [comment]
Everything Looks quiet normal. Ill send you the log from The Monitor in an hour.

**Comment by einzelkind** [comment]
Sorry for the delay.

this is shown in the NPM Module tab:
ejs	2.3.4	Embedded JavaScript templates
—————————————————————————————— 
—————————————————————————————— 
JXCORE configuration tab:
Xcore version 
Installed v 0.3.0.7. This is the latest.
JXcore path /opt/psa/var/modules/jxcore-support/jxcore/jx
—————————————————————————————— 
—————————————————————————————— 

Following lines are an extract of the JXCORE APPLICATION LOG:

Error: Cannot find module '/opt/psa/var/modules/jxcore-support/native_modules/node_modules/ejs'
at Function.Module._oldRes (module.js:774:9)
at Function.Module._resolveFilename (module.js:1606:15)
at Function.Module._load (module.js:335:17)
at Module.require (module.js:451:15)
at require (module.js:469:13)
at Object. (/var/www/vhosts/PATH-TO-VHOST/index.js:4:11)
at Module._compile (module.js:595:24)
at Object.Module._extensions..js (module.js:625:8)
at Module.load (module.js:416:30)
at Function.Module._load (module.js:380:8)
Spawner error:	Application exited by itself with code: 8
Spawner info:	Spawner could not kill the app when exiting: Error: kill ESRCH
Spawner info:	Subscribing is delayed by 2000 ms.
Spawner info:	Subscribed successfully (as root): Successfully subscribed process 11155 to the monitor.
Spawner info:	Restart manager is active.

**Comment by ktrzeciaknubisa** [comment]
Thank you. I really cannot say what's wrong. I'm testing it on my end and cannot find a problem.

Maybe some permission issues. Could you please check if *node_modules/ejs* doesn't have different owner than the other modules? Or better paste the result of:

```bash
$ ls -al /opt/psa/var/modules/jxcore-support/native_modules/node_modules/
$ ls -al /opt/psa/var/modules/jxcore-support/native_modules/node_modules/ejs
```

**Comment by einzelkind** [comment]
Thank you Krzysztof, for your very very fast support.
I just want to know what the problem is =) - looking forward to fix it =)
Now, here are the results. I installed ejs in the same way as the other packets - but obviously the permissions are different… 

ls -al /opt/psa/var/modules/jxcore-support/native_modules/node_modules/
—————
drwxr-xr-x 24 root   root   4096 Okt 16 16:57 .
drwxr-xr-x  4 psaadm psaadm 4096 Okt 10 14:55 ..
drwxr-xr-x  3 root   root   4096 Okt 10 10:26 async
drwxr-xr-x  2 root   root   4096 Okt 10 14:42 .bin
drwxr-xr-x  3 root   root   4096 Okt 16 16:57 connect
drwxr-xr-x  4 root   root   4096 Okt 10 10:30 css
drwxrwxrw-  4 root   root   4096 Okt 10 14:49 ejs
drwxr-xr-x  4 root   root   4096 Okt 10 10:26 express
drwxr-xr-x  2 root   root   4096 Okt 10 12:35 fs
drwxr-xr-x  6 root   root   4096 Okt 10 10:30 hapi
drwxr-xr-x  7 root   root   4096 Okt 10 10:30 html
drwxr-xr-x  5 root   root   4096 Okt 10 14:42 jade
drwxr-xr-x  7 root   root   4096 Okt 10 10:26 jxm
drwxr-xr-x  4 root   root   4096 Okt 10 10:32 koa
drwxr-xr-x  5 root   root   4096 Okt 10 10:32 mean
drwxr-xr-x  2 root   root   4096 Okt 10 14:48 module
drwxr-xr-x  4 root   root   4096 Okt 10 10:27 mongodb
drwxr-xr-x  4 root   root   4096 Okt 10 10:29 mysql
drwxr-xr-x  4 root   root   4096 Okt 10 10:29 php
drwxr-xr-x  6 root   root   4096 Okt 10 10:29 sails
drwxr-xr-x  4 root   root   4096 Okt 10 10:33 socket.io
drwxr-xr-x  4 root   root   4096 Okt 10 12:34 socket.io-client
drwxr-xr-x  2 root   root   4096 Okt 10 12:33 tcp
drwxr-xr-x  3 root   root   4096 Okt 10 15:32 xmlhttprequest


——



ls -al /opt/psa/var/modules/jxcore-support/native_modules/node_modules/ejs
—————
drwxrwxrw-  4 root root  4096 Okt 10 14:49 .
drwxr-xr-x 24 root root  4096 Okt 16 16:57 ..
-rw-rw-rw-  1 root root 32552 Sep  7 06:06 ejs.js
-rw-rw-rw-  1 root root 15789 Sep  7 06:06 ejs.min.js
-rw-rw-rw-  1 root root  1016 Sep  7 06:06 Jakefile
drwxrwxrw-  2 root root  4096 Okt 10 14:49 lib
-rw-rw-rw-  1 root root  1866 Okt 10 14:49 package.json
-rw-rw-rw-  1 root root  5393 Sep  7 06:06 README.md
drwxrwxrw-  4 root root  4096 Okt 10 14:49 test

**Comment by ktrzeciaknubisa** [comment]
I wonder why they all have 'root root', except for 'Okt' module.

For me this looks like you have installed 'Okt' through JXcore extension pages, while the rest of modules from the ssh command line. Is that right?

**Comment by einzelkind** [comment]
no, I installed every single module by using the JXcore extension.

**Comment by ktrzeciaknubisa** [comment]
Ok. Now *ejs* folder has "drwxrwxrw-" mode. Could you please remove it, install again and check the new mode?

**Comment by einzelkind** [comment]
okay, I uninstalled it and installed it again via JXcore extension:

drwxrwxrw-  4 root   root   4096 Okt 16 22:36 ijs

still same same	=(

**Comment by ktrzeciaknubisa** [comment]
I need to take a deeper look into this. In a meantime, you can run `chmod +x ejs` and see if that helps you.

**Comment by ktrzeciaknubisa** [comment]
One more thing: when installing `ejs` you just type "ejs" or some other `--` options?

**Comment by einzelkind** [comment]
Just ejs... Thank you so far...

**Comment by ktrzeciaknubisa** [comment]
You're welcome. But the `chmod +x ejs` may actually work. Let me know :)

**Comment by einzelkind** [comment]
Good morning Krzysztof,

what a lucky new day.
I have changed the permissions to 755 and now it works.

Thank you very much. =)

Best regards
David (=

**Comment by ktrzeciaknubisa** [comment]
Thank you David.

I'll make some changes to JXcore extension to avoid this kind of situations later. Then I'm going to ask you to make a test on your platform. Would that be ok for you? :)

**Comment by einzelkind** [comment]
sure.

=)

**Comment by ktrzeciaknubisa** [comment]
Hi David, I've prepared a dev version of JXcore extension which sets chmod 755 for newly downloaded module's folder and its subfolders, while 644 for each file (recursively).

https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk0273.zip
Would you test it and let me know? 

You may remove ejs from the panel, install again and check the folder permission.
Thank you!

**Comment by einzelkind** [comment]
Hi,

can you please tell me how to install the patch, I’ve no dev environment… so the installation process must be absolutely clear for me.

THX

**Comment by ktrzeciaknubisa** [comment]
Ok, so this is nothing more than the latest official + fix (for you scenario). You can install it exactly the same way as always. Contains only the extra fix, so nothing else should be broken.

In case of any doubts you can always revert to previous version by installing it the same way.

**Comment by einzelkind** [comment]
Hi Krzysztof,

your fix works for me.
I uninstall and install ejs after updating jxcore to v 0.3.0.7.

This is the result:
drwxr-xr-x  4 root   root   4096 Okt 20 12:29 ejs

Thank you !

**Comment by ktrzeciaknubisa** [comment]
Glad to hear that. Thank you! 
On next official release of JXcore extension this will be included too.

In case of any other problems, please let us know.
