### ISSUE TITLE
crypto.generateHKDF documentation is not quite correct

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#618]
The argument titled 'public_key' should actually be called 'IKM' for input keying material. IKM is actually used in the description but for some reason the method definition says 'public_key'. I can guess how this mistake happened (read: it's out fault) but it should be changed in the docs.

**Comment by ktrzeciaknubisa** [comment]
Thanks!

**Comment by yaronyg** [comment]
BTW, http://jxcore.com/docs/crypto.html#cryptogeneratehkdfbytestogenerate-publickey-salt-digestbuffer shows that the docs are still wrong. :(

**Comment by ktrzeciaknubisa** [comment]
Oh, right. Somehow the crypto.html file did not get updated. Thank you!
