### ISSUE TITLE
Thread Communication Performance

### ISSUE THREAD

**Issue by milonas115** [jxcore/jxcore#626]
How is thread communication currently implemented? (thread 0 sends a message to thread 1, who reads the message, does fun stuff, and then sends a message back to thread 0).

We are seeing a massive performance drop (Went from handling 32k HTTP req/sec down to 4.5k req/sec) when trying to do this (with a 1000% increase in response times) VS just having thread 0 do all the fun stuff (fun stuff = CPU work).

**Comment by obastemur** [comment]
@milonas115 how much time it takes on main thread to have that single op. completed ?

**Comment by obastemur** [comment]
The golden rule with tasking small tasks is that a small task that does not have any heavy logic shouldn't be tasked. (i.e. a task way under a millisecond). One good use case could be a blocking crypto task.
