### ISSUE TITLE
jx install babel windows 7 user with space in name fails

### ISSUE THREAD

**Issue by leerlemoniii** [jxcore/jxcore#642]
in addition I tried creating a node.config / jx.config file in the c:\program files (x86)\JXcore folder to try and overrife the npmjxPath but that has no affect on the problem...

c:\source\tempdoc> jx install -h
Preparing NPM for JXcore (v 0.3.0.7) for the first run
Make sure the user account has a write permission to it's home folder. >> A subdirectory or file C:\Users\Lee already exists.
Error occurred while processing: C:\Users\Lee.
A subdirectory or file Lemon\.jx already exists.
Error occurred while processing: Lemon\.jx.

 Consider using a custom path from jx.config file's 'npmjxPath' property.

**Comment by ktrzeciaknubisa** [comment]
Thanks, I'm reproducing both of the problems.

**Comment by leerlemoniii** [comment]
thanks for quick response.

**Comment by ktrzeciaknubisa** [comment]
It's fixed on 0.3.1.0. Thanks @leerlemoniii !

**Comment by leerlemoniii** [comment]
will build and test it today and let you know the results.... Thanks again for the quick response...

**Comment by leerlemoniii** [comment]
still have a problem

Preparing NPM for JXcore (v 0.3.1.0) for the first run
Make sure the user account has a write permission to it's home folder. >> A subdirectory or file C:\Users\Lee already exists.
Error occurred while processing: C:\Users\Lee.

 Consider using a custom path from jx.config file's 'npmjxPath' property.

**Comment by ktrzeciaknubisa** [comment]
You have this fix https://github.com/jxcore/jxcore/commit/2393bed306a4e9dd952248eda012dbd3e1558c91 in your code, right?

Are you using `npmjxPath` righ now? Please check if you have jx.config and/or node.config. The second wasn't really working before, but was documented and now will work due to https://github.com/jxcore/jxcore/commit/92e80affe2cb48b795a36d4a5abc45fda6067606 . So try to see if you still have any of them and what `npmjxPath` they define?

**Comment by leerlemoniii** [comment]
was not in there, added the change, and am now trying again.. Thanks again... this change makes sense though, so will probably work :).

**Comment by leerlemoniii** [comment]
for some reason when I pulled the brach it did not change from master to 3.1.0 now seems good... Again many thanks for quick responses.

**Comment by ktrzeciaknubisa** [comment]
All right. Thank you :)
