### ISSUE TITLE
vcbuild.bat broken for Visual 2010 C++ Express

### ISSUE THREAD

**Issue by dustmop** [jxcore/jxcore#643]
Bad commit is a3fc681b2bb7691c491b82a13f87f983cb256c4f. The error is:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'cares.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\path\to\jxcore\deps\cares\cares.vcxproj]
...repeats 17 times, for each vcxproj file...
```

Working on a fix.

**Comment by dustmop** [comment]
The culprit seems to be this change:
https://github.com/jxcore/jxcore/commit/a3fc681b2bb7691c491b82a13f87f983cb256c4f#diff-e2d5a00791bce9a01f99bc6fd613a39dL480

I am in fact running on an AMD64 cpu. So before this method "host_arch_win" would return "ia32", but it's now returning "x64". What was the original purpose of making this change? I do not understand the commit description.

Perhaps the root of the problem is that my processor supports 64-bit but the compiler I'm using doesn't? Or are the project files being generated incorrectly? Seems like the bit-ness should depend upon the compiler, not cpu, so that the build doesn't fail.

There's some other error in this commit, as even reverting the above few lines leaves build artifacts but no linked output. Trying to track it down...

**Comment by obastemur** [comment]
Interesting. I don't think it is AMD64 etc related though.  let me test it with VS10 also.

**Comment by dustmop** [comment]
Note I'm using Visual C++ 2010 Express, which according to [this](http://stackoverflow.com/questions/1865069/how-to-compile-a-64-bit-application-using-visual-c-2010-express), doesn't support 64-bit. AMD64 isn't the problem per se, it just has weird bit-ness detection, and this commit changed how detection works. If anything, the fact that I have AMD64 was masking the larger issue which is using a 32-bit compiler with 64-bit cpu.

Maybe the fix is to always use the compiler's bit-ness, not the processors. That would involved changing this line https://github.com/jxcore/jxcore/commit/a3fc681b2bb7691c491b82a13f87f983cb256c4f#diff-e2d5a00791bce9a01f99bc6fd613a39dR618. Is there any reason not to do so?

**Comment by obastemur** [comment]
Changing that line to ? and is that enough ?

**Comment by obastemur** [comment]
I've just tried with `vcbuild.bat x64` and it went well with VS2010

**Comment by dustmop** [comment]
> Changing that line to ? and is that enough ?

Sorry, I meant changing
```
host_arch = host_arch_win() if os.name == 'nt' else host_arch_cc()
```
to
```
host_arch = host_arch_cc()
```

i.e. never depending on the cpu architecture detection. Seems reasonable unless there was a good reason to check the cpu architecture on windows.

> I've just tried with vcbuild.bat x64 and it went well with VS2010

Makes sense. I suppose VS2010 has 64-bit support.

**Comment by obastemur** [comment]
Looks like this is a VC2010 problem. Probably you were developing a 32 bit app before (hidden `ia32` set by vcbuild etc.) see http://stackoverflow.com/questions/1865069/how-to-compile-a-64-bit-application-using-visual-c-2010-express

**Comment by dustmop** [comment]
Yes, that's the same stackoverflow link I posted earlier. Is VC2010 not supported then? And is the build script supposed to ignore the compiler's capability and only follow the processor architecture? I'm sure there could be other 32-bit compilers that may be run on 64-bit cpus.

**Comment by obastemur** [comment]
It is supported though but I'm not sure if you were able to compile 64bit already. Did not tried but the answer says installing SDK solves the problem. http://www.microsoft.com/en-us/download/details.aspx?id=8279

**Comment by dustmop** [comment]
No, I don't believe 64bit ever worked in my case. I'll try the workarounds for a temporary fix, but is the build script doing the right thing?

**Comment by obastemur** [comment]
IMHO Yes

**Comment by dustmop** [comment]
Okay, closing.
