### ISSUE TITLE
lwip problem with jx install

### ISSUE THREAD

**Issue by eajimmy** [jxcore/jxcore#644]
Hi, all.
I have a problem with the installation of lwip (^0.0.8) node module (https://www.npmjs.com/package/lwip).

On Ubuntu:
- npm 2.11.3 compiles the modules correctly
- JXcore 0.3.0.7 doesn't compile correctly, it fails with error: /.node-gyp/jxb304/src/zconf.h:12:22: fatal error: mozzconf.h Missing file or directory

Do you have some hints?

Thank you.

**Comment by ktrzeciaknubisa** [comment]
I see it on OSX too. At first I thought this is because JXcore uses npm 1.4.14, but it seems that for npm 1.4.14 it works, while for jx doesn't. I'll look into it.

**Comment by ktrzeciaknubisa** [comment]
Well, that's because `mozzconf.h` is under `~/.node-gyp//jxb304/deps/zlib/` and not under `/.node-gyp/jxb304/src/`, while zconf.h is in those both locations.

**Comment by ktrzeciaknubisa** [comment]
Copying `mozzconf.h` from `deps/zlib` into `src` seems to skip that error, but I don't thing that would be a solution. Besides the build fails somewhere else later:

```
In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
```

**Comment by eajimmy** [comment]
Hi, sorry but I have to resume this issue:
the solution of link the mozzconf.h resolved the problem (using lwip 0.0.7).
Now i have the same problem on Windows with the difference that .node-gyp/deps is empty for the Windows version of jxcore.
Any hints on how to face the problem?

P.S.: I'm using the jx version 0.3.0.7

**Comment by ktrzeciaknubisa** [comment]
@eajimmy Did you try with latest jx 0.3.1.0 ?

**Comment by eajimmy** [comment]
yep, and the issue remains the same

**Comment by eajimmy** [comment]
Maybe I solved the issue, but I don't know if this is a valid solution :-/
I take the content of  the /.node-gyp/0.10.40/deps/zlib (the zlib version for node 0.10.40) and I have put it in /.node-gyp/jxb310/src. (overwriting already present files). 
All compiles fine and the mozzconf.h wasn't requested...

**Comment by ktrzeciaknubisa** [comment]
Yeap, this seems to work.

**Comment by ktrzeciaknubisa** [comment]
It's fixed now. In order to use it with jx 0.3.0.0 please remove `~/.node-gyp/jxb300` and run the `jx install` again. 

Thanks @eajimmy for help.
