### ISSUE TITLE
Unable to install packages from NPM on OpenWrt

### ISSUE THREAD

**Issue by meetyg** [jxcore/jxcore#648]
Hello,
I have successfully compiled JXCore for OpenWrt using the instructions supplied.
I installed the ipk and it dependencies on my router (mips) running OpenWrt 15.05, and it works!

The problem is that I'm unable to install any npm packages using jx. This is what I get for example, when trying to install express:

````
root@OpenWrt:~# jx install express
Error: Cannot find module '/root/.jx/npm' (module.js 801:14)
    at Module._oldRes (module.js:801:15)
    at Module._resolveFilename (module.js:1633:1)
    at Module._load (module.js:359:18)
    at Module.runMain (module.js:843:5)
    at startup (node.js:374:11)
    at node.js:1485:3
````
 Is the install feature supposed to work on OpenWrt ?

**Comment by obastemur** [comment]
@meetyg It's nice to hear that :+1: Considering the available tools under OpenWRT and limited resources of the device, why don't you use npm / `jx install` locally and move `node_modules` folder there ?

**Comment by meetyg** [comment]
I didn't try to use npm locally, because I wasn't sure how some npm modules would behave on the router. I know that modules are downloaded by npm using a specific CPU architecture, so I thought it would be useless. 
I guess that simple modules that don't use compiled libraries will probably work this way, just by copying. 

In short there are probably workarounds, but I wanted to know if jx install is supposed to work on Openwrt, in general.

**Comment by obastemur** [comment]
Closing this issue for now. I saw it's a disk space issue. Running `npm` on 16Mb / 64MB etc. device is really tricky. Since none of the `C, C++` modules are expected to work on OpenWRT, deploying `node_modules` folder along with the application is best way to go. Thanks for bringing this up.
