### ISSUE TITLE
windows Jxcore installed v0.10.40

### ISSUE THREAD

**Issue by ricmed205** [jxcore/jxcore#649]
Hi,

I installed Jxcore via the windows installer. On cmd i got "v0.10.40" on jx -v. I understand you are on +v0.30. Is that correct? thanks.

**Comment by ktrzeciaknubisa** [comment]
`jx -v` print corresponding node's version and it's what you have received as output. What do you mean by "+v0.30" ?

**Comment by ktrzeciaknubisa** [comment]
Currently the latest released version is 0.3.0.7 ([downloads page](http://jxcore.com/downloads/)). To find out the version number from the command line, use `jx -jxv` rather than `jx -v`. See also `js --help`.

**Comment by ricmed205** [comment]
Got it...A bit confusing though...thanks!

**Comment by ktrzeciaknubisa** [comment]
You're welcome, however I wouldn't say it's confusing :) Since JXcore originates from node, and we want to keep maximum compatibility, it's consistent to have `-v` argument working same way.
