### ISSUE TITLE
Packaging: Allow Glob strings in "files" and "assets" paths

### ISSUE THREAD

**Issue by jpillora** [jxcore/jxcore#65]
See https://github.com/isaacs/minimatch and https://github.com/isaacs/node-glob

Basically `**/*.js` would match all `.js` files in all directories and subdirectories.

For example, this could allow assets to simply be: `(images|documents)/**` (all files inside `images/` and `documents/`)

**Comment by ktrzeciaknubisa** [comment]
We've added new feature for packaging, which allows to use wildcards `*` and `?` for `jx package` `-add` and `-slim` options: [#213](https://github.com/jxcore/jxcore/issues/213#issuecomment-94777140) .

It is not a glob string approach, as probably it will not be implemented in JXcore itself. There is a concept to make a separate module out of it: [#131](https://github.com/jxcore/jxcore/issues/131#issuecomment-91500051)
