### ISSUE TITLE
Corrupted package

### ISSUE THREAD

**Issue by Minishlink** [jxcore/jxcore#651]
Hi.

I'm on Windows, using latest (0.3.0.7) jxcore (v8) 64bit. My final target is Android using Cordova (and jxcore-cordova) but for now I focus on making it work on my desktop. For the context, I would like to package my node_modules (and app.js) because there are very long paths in node_modules and everything is not correctly copied by Cordova in www platform folder.

So I have in my www/jxcore folder:
- nodes_modules/
  - dependancies (express, pouchdb, express-pouchdb, leveldown, leveldown-mobile...)
- app.js
- package.json

At this point, doing `jx app.js` works great.

Now I want to generate the package using:
`jx package app.js --extract-what "*.node" --extract-app-root --extract-verbose --extract-message "Extracting" --show-progress percent`

The final result is "[OK] compiled file is ready (app.jx)".

But doing `jx app.jx` throws me `Package is either corrupted or not compatible with this JX binary.`.

Some clues:
- When compiling, there are no messages "Extracting" and I don't see anywhere any .node (they are supposed to be in www/jxcore/ right ?)
- If I compile without --extract-*, I do have a warning about .node files which may cause the application to fail (leveldown.node) and the package is still corrupted
- Maybe it comes from the long paths of dependancies ?

Any ideas ? Thanks for your help.

**Comment by ktrzeciaknubisa** [comment]
Are you running `jx app.jx` by using same jx version (`jx -jxv`) ? I mean are you sure, that this is the same `jx` executable ?

**Comment by Minishlink** [comment]
Thanks for your help. Yes I am quite sure of that. Running `jx -jxv` inside `jxcore/www` correctly tells me it is jx v0.3.0.7. And I never installed any other jx version. Where would the other version come from ? Also, I execute both `jx package ...` and `jx app.jx` in the same folder and the same CLI.

**Comment by ktrzeciaknubisa** [comment]
Would you paste package.json dependencies section, so I can test it?

**Comment by Minishlink** [comment]
Yep.

```json
{
  "name": "A6",
  "version": "0.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "dependencies": {
    "express": "^4.13.3",
    "express-pouchdb": "^1.0.1",
    "leveldown": "^1.4.2",
    "leveldown-mobile": "^1.0.10",
    "pouchdb": "^5.1.0",
    "thali": "^2.0.2"
  }
}
```

**Comment by ktrzeciaknubisa** [comment]
Thanks :)

However the bad news is, that I couldn't reproduce the error on Windows 7 x64. As a side note, `thali` constantly refuses to be installed no matter if with jx, npm 2.7.4, or latest npm 3.4.0. But the *node_modules* folder is still big. The `jx app.jx` runs normally though and even extracts the files:

```bash
[OK] compiled file is ready (app.jx)
Extracting
extracting .\node_modules\leveldown\build\Release\leveldown.node
extracting .\node_modules\leveldown-mobile\build\Release\leveldown.node
``` 

Which is your Windows version?

**Comment by ktrzeciaknubisa** [comment]
Let me also refer to one of your clues:

> When compiling, there are no messages "Extracting" 

The "Extracting" message (`--extract-message` param) is supposed to be displayed on package extraction (first execution of `jx app.jx`) - not during package creation. But since you had `package corrupted`, that explains why you never saw the "Extracting" message.

> and I don't see anywhere any .node (they are supposed to be in www/jxcore/ right ?)

Depend from where you run the `jx app.jx` command. If you do it from *www/jxcore* (same place where you created the package?), and since you have also used `--extract-app-root`, they will not even be saved, because those files already exist: 

```
Extracting
skipping (file already exists) .\node_modules\leveldown\build\Release\leveldown.node
skipping (file already exists) .\node_modules\leveldown-mobile\build\Release\leveldown.node
```

**Comment by Minishlink** [comment]
Well it's also a Windows 7 x64. I'm going to test on my Windows 10 x64.

A quick question though, you mentionned using npm 2.7.4 or 3.4.0, it is possible to update npm in jx ? If that's the case I can simply update to 3.x and not package. (node_modules will be on one level)
Am I right ? (I doubt it though)

But in any case that doesn't solve the bug in jxcore, if it exists.

Thanks for your explanations on the clues. The way extraction behaves is clearer now.

**Comment by Minishlink** [comment]
I think thali fails installing on your machine because it has a post install script which deals with cordova plugins. (see [their project page](https://github.com/thaliproject/Thali_CordovaPlugin))

It still throws package corrupted on Windows 10. I'm going to test without thali dependancy to see if it is the culprit.

**Comment by ktrzeciaknubisa** [comment]
> A quick question though, you mentionned using npm 2.7.4 or 3.4.0, it is possible to update npm in jx ?

Nope. I just used `npm` installed separately. JXcore uses it's own npm 1.4.14. However you may try to manually replace it by switching `~/.jx/npm` folder contents, but bear in mind, that it may be overwritten by future JXcore releases.

>  If that's the case I can simply update to 3.x and not package. (node_modules will be on one level)

I don't quite follow here :)

**Comment by Minishlink** [comment]
> I don't quite follow here :)

I had the impression that with npm > 3.0, there was no nesting of node modules anymore. Or is it due to a newer version of node ?

Ok, so it's much faster without thali dependancy and it works great. The problem is, I need this dependancy. ;)

The fact that one of the folder inside thali contains another node_modules may corrupt the package ? Like this:
- thali
  - node_modules
  - install
     - node_modules <--

**Comment by ktrzeciaknubisa** [comment]
> The fact that one of the folder inside thali contains another node_modules may corrupt the package ?

No it shouldn't. 

Ok, I gave it another try and this time I installed things inside cordova app (under *www/jxcore* to be exact). Thali got installed as well. However `jx package` runs fine as well as `jx app.jx`. 

You must have something else there or doing something more. For the start could you pack your *www/jxcore* folder, then place somewhere and share the link for it?

**Comment by Minishlink** [comment]
Did a fresh install of all the stack (Visual Studio included) and it packages and executes well. So it's very much likely that the problem came from my installation... Maybe native modules were corrupted. That's a shame the build when doing `jx install` didn't throw an error though.

Thanks for your help ! (and sorry that it didn't depend on you..)

**Comment by ktrzeciaknubisa** [comment]
> That's a shame the build when doing jx install didn't throw an error though.

Well, we don't know for sure if the problem came from `jx install`. I still wonder what kind of file or folder structure could trigger `package corrupted` error. Let us know if you meet this again!

> (and sorry that it didn't depend on you..)

The best is not to depend on anyone :)
