### ISSUE TITLE
An issue with a package that builds successfully, but fails during runtime.

### ISSUE THREAD

**Issue by vjrantal** [jxcore/jxcore#654]
Tried to use a project that has optional dependencies (https://github.com/diversario/node-ssdp/blob/master/package.json#L16-L19) that build successfully with "jx npm install”, but during runtime, I get a failure like this:

```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: <...>/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

To reproduce:

```
$ git clone https://github.com/diversario/node-ssdp.git
$ cd node-ssdp
$ jx npm install
$ jx index.js
```

**Comment by ktrzeciaknubisa** [comment]
Thank you!

This kind of errors are known for SpiderMonkey build of JXcore, and I have just checked, that doing the same steps with V8 does not bring any problem. V8 build is still more suitable to compile modules with native addons.

I understood, that you need to have it working on iOS and Android. How are you going to deploy? By using jxcore-cordova?

**Comment by vjrantal** [comment]
> By using jxcore-cordova?

Yes.

**Comment by ktrzeciaknubisa** [comment]
@vjrantal The thing is, that anyway *.node* files (native addons) will not work with jxcore-cordova when deployed to mobile device. Similar talk is also here: https://github.com/jxcore/jxcore-cordova/issues/103#issuecomment-157886735

Better avoid using such modules (containing native addons) in cordova project.

**Comment by ktrzeciaknubisa** [comment]
@vjrantal although I don't see it on my end, this issue reminds me another one #492, where pre-built *.node* file was downloaded by the install script instead of rebuilt against jxcore. If you look at your output or npm log - do you have anything that suggests e.g. "Binary downloaded and installed at..." ?
