### ISSUE TITLE
documentation needed for Windows10 jxcore.uwp

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#673]
JXcore build script adds `uwp` helper when it compiled under Windows 10 with `chakra` engine support;
```
vcbuild.bat --engine-chakra
```

See `js` test files for basic `jxcore.uwp` support and prepare a documentation.

**Comment by ktrzeciaknubisa** [comment]
I've built chakra jx successfully on Win 10, VS 2015, however while simple commands `jx -jxv` etc. work, I get an error with running `console.log(1)` javascript file, or even `jx -e "console.log(1);"` command. So that's not even referring to `jxcore.uwp` yet.

```bash
FATAL ERROR: Failed to initialize context
```

**Comment by obastemur** [comment]
@ktrzeciaknubisa Can you give me the whole environmental / build details ? @vjrantal also saw it on WinIOT RP2 but I'm not able to reproduce it.

**Comment by ktrzeciaknubisa** [comment]
This is VM hosted on Windows 7 x64. VMware Workstation 12 Player. 4 GB RAM enabled for VM, 2 cores.

* **Microsoft Windows 10 Pro x64** (10.0.10586 Build 10586).
* Visual Studio Pro 2015 x64
* Python 2.7.9
* vcbuild --engine-chakra

Is this what you asked for?

**Comment by ktrzeciaknubisa** [comment]
I've installed SP1 for VS 2015 and rebuilt JXcore with chakra, but it doesn't seem to change anything: same error.

**Comment by ktrzeciaknubisa** [comment]
OK. looks like the latest chakra updates made it work.
