### ISSUE TITLE
make install doesn't respect `--prefix` given to configure

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#675]
Looks like make install doesn't respect the path prefix as specified to `.configure --prefix={PREFIX}`. If given an absolute path, it treats the path as relative.

```
./configure --prefix=/usr/local/var/nodenv/versions/jxcore-v8-0.3.0.7
make -j 4
make install
```

Expected -> installed to `/usr/local/var/nodenv/versions/jxcore-v8-0.3.0.7`

Actual -> installed to `./usr/local/var/nodenv/versions/jxcore-v8-0.3.0.7`

**Comment by ktrzeciaknubisa** [comment]
I would understand this behavior if makefile you have used was from master, since we made some relevant changes recently https://github.com/jxcore/jxcore/commit/0db3f49500bd6635459642c038440c2e4e48a5f1 (https://github.com/jxcore/jxcore/issues/657). However it looks like it needs adjustment to cover your case.

**Comment by jasonkarns** [comment]
i believe 0db3f49500bd6635459642c038440c2e4e48a5f1 should be reverted. `--prefix` is only supposed to accept absolute paths, so that commit solved a problem that isn't a problem. (To pass relative paths, just prefix with `$PWD/`)

**Comment by ktrzeciaknubisa** [comment]
Then we need to modify our build scripts to conform this. @obastemur What do you say?

**Comment by obastemur** [comment]
Agree with @jasonkarns . However we can support both ways (as we used to) We just need to check whether the path is absolute or relative. @ktrzeciaknubisa I think you can get the rest.

**Comment by ktrzeciaknubisa** [comment]
Done on 0.3.1.0 and merged with master.

**Comment by jasonkarns** [comment]
tested. works great! node-build successfully compiles from master after this change

thanks!

**Comment by jasonkarns** [comment]
for reference, if anyone wants to use node-build to compile jxcore from master, this is the custom definition you'll need to do so: (the name of this file is what the installed version will be within nodenv)

``` sh
after_install_package() {
  fix_jxcore_directory_structure
}

install_git "jxcore-0.3.1.0" "https://github.com/jxcore/jxcore.git" master
install_package npm "https://s3.amazonaws.com/nodejx/npmjx307.tar.gz#7b99397f17f5fdb592842ccd62e25806b2a05ae9997c4508b47412f194e8ba6e" jxcore_npm
```

The file should be in `$(nodenv root)/plugins/node-build/share/node-build/` or in a directory that is listed in `NODE_BUILD_DEFINITIONS`

We don't typically include edge/head/devel definitions in node-build, only actual releases, so this exact definition won't be available in node-build directly.
