### ISSUE TITLE
jxcore on nodenv and node-build

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#676]
Master issue for discussions relevant to getting jxcore working with [nodenv](https://github.com/OiNutter/nodenv) and [node-build](https://github.com/OiNutter/node-build).

Carried over from https://github.com/jxcore/jxcore/issues/137

**Comment by jasonkarns** [comment]
So far issues to address:

1. #675 (`configure --prefix=` must be absolute)
2. would like source tarballs linked from downloads page, including checksums
3. would like downloads/index.json manifest that includes links/checksums for all binary downloads and source tarballs (this would enable our scraper to add definition files automatically for new releases)
4. binary packages ought to reflect the same directory structure as a from-source build. that is: 

    ```
    ├── bin
    │   └── jx
    ├── include
    │   └── node
    ├── lib
    │   ├── dtrace
    │   └── node_modules
    └── share
        └── man
    ```

Number 1 is the only blocker to getting rudimentary support for jxcore into node-build (and by extension, nodenv) Once that's fixed, at least source builds will work. We can then progress to supporting the precompiled binaries and later to getting the scraper working.

**Comment by jasonkarns** [comment]
PR for adding jxcore to node-build definitions.

https://github.com/OiNutter/node-build/pull/90

This pr only adds the from-source builds (no precompiled binaries yet) and it only builds against v8 at the moment.

It adds the versions to nodenv as `jxcore+v8-0.3.0.x`.

Preferences as to the name of spidermonkey builds?
- jxcore+sm-0.3.0.x
- jxcore+spidermonkey-0.3.0.x

**Comment by jasonkarns** [comment]
question: if multiple (conflicting) `--engine-*` flags are given to `configure`, which takes precedence? First one wins? Or last one wins?

**Comment by ktrzeciaknubisa** [comment]
This is almost like "which `--prefix` flags takes precedence". I never tested none of them. Why would you provide multiple `--engine-*` flags?

**Comment by jasonkarns** [comment]
I'm creating node-build recipes for jxcore_spidermonkey and jxcore_v8_328,
each of which will set the CONFIGURE_OPTS flags appropriately. But I can't
simply set CONFIGURE_OPTS since that will overwrite the user's value. So I
either need to prepend or append the `--engine-*` flag. If the user, for
whatever reason, set an engine flag, I want to make sure that the correct
one takes precedence. So if configure takes the first one it finds, I'll
*prepend* the engine flag to ensure that it wins over subsequent engine
flags. But if the last engine flag wins, then I'll *append* the flag to
ensure it wins over any preceding engine flags.

On Tue, Dec 1, 2015 at 4:16 PM, Krzysztof Trzeciak <notifications@github.com

**Comment by ktrzeciaknubisa** [comment]
I see. From what I can tell, the first one wins. You can check it easily. 

Without going into details, how your *prepend* or *append* work: can't you just *replace* when it's there or *add* when it's not? I'm not sure if relying on order is a good idea.

**Comment by jasonkarns** [comment]
Probably, but doing that level of string manipulation in bash (portably)
doesn't sound fun.

On Tue, Dec 1, 2015 at 4:30 PM, Krzysztof Trzeciak <notifications@github.com

**Comment by jasonkarns** [comment]
Next issue that is rather frustrating: the tarball package names don't match between the precompiled binaries and the source tarballs.

The way node-build works, it needs to know the package name, which is (should be) common regardless of source build or precompiled binary.

For example, for node 4.2.1, the source tarball (https://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz) and every binary tarball regardless of platform (https://nodejs.org/dist/v4.2.1/node-v4.2.1-darwin-x64.tar.gz) each extract to the same directory name. In this case, that's `node-v4.2.1`.

The jxcore binaries having different tarball names than the source tarballs is going to be very difficult to workaround. (It would require changes to node-build itself, not simply part of the jxcore recipes.)

This is really part of the larger theme that the release tarballs are all inconsistent. (binaries have different folder structure and different archive names. source tarballs aren't officially released but handled by github and thus have different archive names and are missing checksums)

**Comment by jasonkarns** [comment]
This seems like it ought to be a simple thing to fix. Whatever release script is currently doing builds could just run the build and tar up the output directory (not only the bin, but the whole directory bin, lib, man, etc) Using the same archive name for all builds (like `jxcore-v0.3.0.x`). The script would also tar up the source itself using the same archive name, rather than relying on github (which presently uses project-tag as the archive name)

**Comment by jasonkarns** [comment]
Looks like I've been able to route around the package name issues so no worries there.

Any chance of the files being compressed as actual gzipped tarballs .tar.gz instead of .zip?

**Comment by jasonkarns** [comment]
I believe I have a working PR https://github.com/OiNutter/node-build/pull/90 that does binaries for OS X and from-source compilation for others (and OS X, too, if desired)

The OS detection for jxcore seems to be much more involved than for nodejs/iojs, so I'm punting on that for now. If none of the binaries match, then it falls back to compilation.

The result is `jx` is in path and `node`is in path, each pointing to the activated version of jxcore. Nothing to do with npm has been attempted yet.

#675 will become a blocker again when the next release drops, thanks to #660

**Comment by jasonkarns** [comment]
What kind of ideas do you have on getting npm working? Since your npm is customized, what possible ways are there to get your npm into a nodenv-managed jxcore version's bindir? I realize that `jx install` drops it into `~/.jx` but is there a way to control that destination directory? env-var or cli argument? What about pulling it down from the registry? Is your modified npm published to the registry? (That would be the easiest, I think)

I've tried simply symlinking from `bin/npm` to `~/.jx/npm/bin/npm-cli.js` and it works fine. (locally installing modules works, and globally installed moduled are dropped into the jxcore installation directory under lib/node_modules, with bin's symlinked from `bin/`. Symlinking isn't the ideal solution since switching jxcore versions wouldn't update the version of npm the symlinks are pointing to. I'd rather figure out a reliable way to make `jx install` drop its npm package into a specified directory. That way, each nodenv-managex jxcore would have its own npm. No need to worry about jx/npm version mismatches.

**Comment by ktrzeciaknubisa** [comment]
> I'd rather figure out a reliable way to make jx install drop its npm package into a specified directory.

This can be achieved by using [npmjxPath](https://github.com/jxcore/jxcore/blob/master/doc/api/jxconfig.markdown#npmjxpath-string) in `jx.config` file.

**Comment by jasonkarns** [comment]
Is that `npmjxPath` required to be absolute? Or can it be relative? If
relative, I'm assuming it's relative to the config file? (or to the jx bin?)

**Comment by jasonkarns** [comment]
Setting `npmjxPath` doesn't seem to be working:

``` sh
$ tree -L 2
.
├── JXCORE_LICENSE
├── bin
│   ├── jx
│   ├── jx.config
│   ├── node -> jx
│   └── npm -> ../libexec/npm/bin/npm-cli.js
├── lib
│   └── node_modules
├── libexec
│   └── npm
└── releaseLogs.txt

5 directories, 6 files
```

``` sh
$ cat bin/jx.config 
{
  "npmjxPath": "/usr/local/var/nodenv/versions/jxcore+v8-0.3.0.7/bin/npm"
}
```

But when invoking `jx install` or `jx npm install` I get errors:

``` sh
$ nodenv which jx
/usr/local/var/nodenv/versions/jxcore+v8-0.3.0.7/bin/jx
$ jx install
Preparing NPM for JXcore (v 0.3.0.7) for the first run
Make sure the user account has a write permission to it's home folder. >> mkdir: /usr/local/var/nodenv/versions/jxcore+v8-0.3.0.7/bin/npm/.jx: Not a directory

 Consider using a custom path from jx.config file's 'npmjxPath' property.
$ jx npm install
Preparing NPM for JXcore (v 0.3.0.7) for the first run
Make sure the user account has a write permission to it's home folder. >> mkdir: /usr/local/var/nodenv/versions/jxcore+v8-0.3.0.7/bin/npm/.jx: Not a directory

 Consider using a custom path from jx.config file's 'npmjxPath' property.
```

**Comment by jasonkarns** [comment]
Upon further testing, I don't think that config value helps at all. The documentation implies it should be the path to the jxnpm executable. But instead, it's supposed to be the path for where jxcore will write the `.jx` dir (and npm). But if you provide a path that *already* contains `.jx/npm` as necessary, jx overwrites it! So it doesn't seem to be something that can prevent jx from downloading/installing npm. It's just a replacement for `~`.

I found that adding the `v 0.3.0.7` file (sidenote: can we fix the space after the v? doesn't make sense in a version string and is even more annoying in a filename) into the `./nodenv/versions/jxcore-0.3.0.7/libexec/.jx/` directory successfully prevented npm from being installed again. However, requiring the `.jx` directory be in the path is frustrating. There's no reason for the directory to exist if we're manually specifying the path to the npm executable. And there's definitely no reason for it to be hidden.

A couple thoughts: the `npmjxPath` sounds like it should instead be named `jxhome` or something, and it should default to `~/.jx`. (That is, it shouldn't point to where .jx goes, it should *be* the .jx dir.) This would be useful if there are other things that go in this directory besides npm.

If the `jxhome` config exists, then `npmjxPath` could be reserved to literally be the path to the npm executable. (Which would default to `$jxhome/npm/bin/npm`) This way, the `jxhome` could be set for general jx files. But a custom npm installation could be used without requiring any specific `.jx` ancestry.

As it stands, I don't think nodenv will be using the npmjxPath at all. npm should go under jxcore's `libexec/` (or alternatively, `lib/node_modules/`). Requiring a `.jx` dir *and* a version-string file is cruft that's really unnecessary. nodenv already has npmjx working; the only difference is that you must use `npm` as a top-level command. `jx install` and `jx npm *` would need to be avoided (within nodenv installs that is). And really, this is the preferred setup. Switch nodes and `node` is `jx`, `npm` is `jx npm`. No need to change the commands you run; just continue using `node` and `npm` as per usual.

**Comment by jasonkarns** [comment]
Here's an experimental branch that uses npmjxPath config, but I'm still not convinced it's worth it. (The branch is compared against the main jxcore branch)

https://github.com/OiNutter/node-build/compare/jxcore...jxcore-npm-config

**Comment by jasonkarns** [comment]
The last bit of the npm stuff is the npmrc file. It looks like jx takes a dump of the current `npm config get` and persists it as `npmrc` under `.jx/npm/`. But the file looks significantly larger than a simple `npm config get`. What else is in there? What's critical? And what's the minimal amount of npmrc contents that can be written? My main concern with having a full npmrc dump is... what happens when a user's main .npmrc file is updated? Are those changes somehow merged into jx's npmrc file? Or will the drift apart and get out of date? What about vice versa?

**Comment by ktrzeciaknubisa** [comment]
> It looks like jx takes a dump of the current npm config get and persists it as npmrc under .jx/npm/

I fact this is `npm config ls -l`, maybe that's why it's larger. It is rewritten per each `jx install` call, so current user's settings should fetch too.

**Comment by jasonkarns** [comment]
Yep! found it here https://github.com/jxcore/jxcore/blob/f8645636334d0b94f35bad18260e1c48dcf6b142/tools/npmjx/index.js#L170

Working on getting this done during installation as well.

Though, I am curious why this is necessary. The built-in npmrc is generally only necessary for distributions to provide their own defaults. Most standard npm distributions (like via node-build, homebrew) have an npmrc file that's empty. So the only thing it does is persist CLI/ENV/user/global/built-in settings to a file. The cli, env, user and global settings don't need copied over because npm picks them up on each execution anyway. The only settings that *would* need copied over are an existing npm's built-in settings. Which are usually empty, and even when not empty would be distribution specific. IOW, shouldn't npmjx's builtin settings be specific to jx? (Which don't seem necessary now, anyway.)

**Comment by ktrzeciaknubisa** [comment]
The reason why we started to copy the settings was to force same output between `jx install` and `npm install`. There were for example `--loglevel` differences. https://github.com/jxcore/jxcore/issues/209#issuecomment-100368217

**Comment by jasonkarns** [comment]
I've done some more digging.

I'm comparing a jxcore install (including npmjx installed as npm) to a fresh nodenv installation of node 0.10.40 (with npm downgraded to match npmjx's version @ 1.4.14)

`npm config ls -l` provides identical output between standard npm and npmjx. (npmjx being the one installed by nodenv from https://s3.amazonaws.com/nodejx/npmjx307.tar.gz) The only differences being paths: `globalconfig`, `globalignorefile`, `prefix`.

So npmjx and npm both are configured the same out of the box. This suggests that the act of writing the npmrc file is effectively a no-op. Is it possible that the log-level issues experienced in #209 were due to the native npm having a non-empty builtin npmrc? 

When I run jx install` and the npmrc file gets (over)written, the subsequent output of `npm config ls -l` now contains the previous effective config output, titled as `; builtin config undefined`

Some differences, though, between the previous `npm config ls -l` output and the newly written npmrc file:

``` diff
-cache-max = null
+cache-max = 0

-depth = null
+depth = 0

-local-address = undefined

-node-version = "v0.10.40"
+node-version = "0.10.40"

-onload-script = false
+onload-script = null

-tmp = "/var/folders/sv/3941ksds4v18r9y1kyptw1jw0000gn/T/"
+tmp = "/var/folders/sv/3941ksds4v18r9y1kyptw1jw0000gn/T"

-umask = 18
+umask = 1
```

Clearly, most of these differences are superficial. (null -> 0, trailing slash dropped, 'v' prefix on version number dropped) I'm struggling to account for *why* these values changed, since the new config file is literally the printing of the previous `config ls` output. But regardless, none of the values change in a meaningful way. So that still supports the notion that the persisting of defaults into the builtin config file is effectively a no-op.

All this to say, I don't want to delve too deeply into the internals of `jx` itself. But I'm skeptical that there wasn't a different root cause to #209, and the writing of the config file addressed the issue as a side effect. Regardless, there doesn't seem to be any point to nodenv writing an npmrc file. I'll wait for actual jxcore-with-nodenv usage to see if there is an edge-case I'm missing.

**Comment by jasonkarns** [comment]
support for jxcore (both source builds, and precompiled binaries, including npmjx) has landed in node-build! works with nodenv out of the box!

``` sh
[system] [2.1.5] /usr/local (master $= origin/master)
$ nodenv shell jxcore+v8-0.3.0.7 
[jxcore+v8-0.3.0.7] [2.1.5] /usr/local (master $= origin/master)
$ node -v
v0.10.40
[jxcore+v8-0.3.0.7] [2.1.5] /usr/local (master $= origin/master)
$ node -jxv
v 0.3.0.7
[jxcore+v8-0.3.0.7] [2.1.5] /usr/local (master $= origin/master)
$ node -jsv
Google V8 v3.14.5.9
[jxcore+v8-0.3.0.7] [2.1.5] /usr/local (master $= origin/master)
$ npm -v
1.4.14
```

assuming one already has nodenv; and latest node-build (from git, jxcore support isn't in homebrew yet) then:

`nodenv install jxcore+v8-0.3.0.7` installs jxcore w/ v8. provides `jx` bin, aliased as `node` and `npm` symlinks to npmjx

for spidermonkey: `nodenv install jxcore+sm-0.3.0.7`

to compile from source: `nodenv install --compile jxcore+v8-0.3.0.7`

**Comment by jasonkarns** [comment]
As a result of the exercise of adding jxcore to node-build, I've opened a list of issues and feature requests:

#675 #682 #683 #684 #685 #686

**Comment by obastemur** [comment]
@jasonkarns thanks for amazing work you have done. Which items are blocker for you at the moment ? In order not not to brake later, are there any possible test cases those we can run ?

**Comment by jasonkarns** [comment]
@obastemur none of them are _current_ blockers. 

#686 is a blocker for adding jxcore to our release scraper; but the workaround is that jxcore definitions have to be added by hand (which means it will happen only when/if I am notified of jxcore releases *and* have time to add the definition. for node/iojs the entire process is entirely scripted: the checking for new releases, creation of definitions and pushing a new node-build release/homebrew update)

#675 will *become* a blocker. As [mentioned here](https://github.com/jxcore/jxcore/issues/675#issuecomment-161057374), 0.3.0.7 compiles successfully, but master does not. So unless the `--prefix` issue is addressed, the *next* jxcore release will not be supported.

All the rest are just things that I found odd or surprising while working with jxcore

As for tests, we do have a test suite (bats) in node-build. It can be run as `npm test`. But most of the tests are unit-y type tests so they're unlikely to catch any regression issues introduced by changes in jxcore. (the test suite is only meant to cover node-build's codebase) Most of the code added in node-build just adjusts jxcore's directory structure post-install to match what nodejs/iojs ship with, and creates symlinks for `node`/`npm` (and configures jx.config's `npmjxPath`).

**Comment by obastemur** [comment]
@ktrzeciaknubisa can we make sure we will cover #686 and #675 on our 0.3.1.0 scope?
