### ISSUE TITLE
all files under .jx/npm have executable bit set

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#677]
I noticed that all of the precompiled binary zips, when extracted via tar (I know) have the execute bit set on every file (release notes, license, everything that's not a directory). I assumed this was simply because I was using tar instead of unzip on the zip files. However, having done a fresh install of 0.3.0.7, and then `jx install`, I noticed that the same issue is affecting all the files in `~/.jx/npm/`.

```
[system] [2.1.5] ~/.jx/npm
$ ls -al .
total 304
drwxr-xr-x  24 jasonkarns  staff   816B Dec  2 00:07 ./
drwxr-xr-x   5 jasonkarns  staff   170B Dec  2 00:07 ../
-rwxr-xr-x   1 jasonkarns  staff   444B Jun 16 04:30 .npmignore*
-rwxr-xr-x   1 jasonkarns  staff    44B Jun 16 04:30 .npmrc*
-rwxr-xr-x   1 jasonkarns  staff    54B Jun 16 04:30 .tern-project*
-rwxr-xr-x   1 jasonkarns  staff    78B Jun 16 04:30 .travis.yml*
-rwxr-xr-x   1 jasonkarns  staff   5.6K Jun 16 04:30 AUTHORS*
-rwxr-xr-x   1 jasonkarns  staff   380B Jun 16 04:30 CONTRIBUTING.md*
-rwxr-xr-x   1 jasonkarns  staff   9.6K Jun 16 04:30 LICENSE*
-rwxr-xr-x   1 jasonkarns  staff   5.8K Jun 16 04:30 Makefile*
-rwxr-xr-x   1 jasonkarns  staff   7.6K Jun 16 04:30 README.md*
drwxr-xr-x   7 jasonkarns  staff   238B Dec  2 00:07 bin/
-rwxr-xr-x   1 jasonkarns  staff    46B Jun 16 04:30 cli.js*
-rwxr-xr-x   1 jasonkarns  staff   521B Jun 16 04:30 configure*
drwxr-xr-x   6 jasonkarns  staff   204B Dec  2 00:07 doc/
drwxr-xr-x   8 jasonkarns  staff   272B Dec  2 00:07 html/
drwxr-xr-x  57 jasonkarns  staff   1.9K Dec  2 00:07 lib/
-rwxr-xr-x   1 jasonkarns  staff   156B Jun 16 04:30 make.bat*
drwxr-xr-x   6 jasonkarns  staff   204B Dec  2 00:07 man/
drwxr-xr-x  55 jasonkarns  staff   1.8K Dec  2 00:07 node_modules/
-rw-r--r--   1 jasonkarns  staff    73K Jun 16 04:30 npm.jxp
-rwxr-xr-x   1 jasonkarns  staff   3.6K Jun 16 04:30 package.json*
drwxr-xr-x   8 jasonkarns  staff   272B Dec  2 00:07 scripts/
-rwxr-xr-x   1 jasonkarns  staff   646B Jun 16 04:30 wercker.yml*
```

Since I didn't do any extracting or otherwise touch the jx-installed npm, I'm assuming there is something else going on. Perhaps with whatever automated process is creating these file archives?

**Comment by ktrzeciaknubisa** [comment]
`jx install` downloads the npm also as a tar file: https://github.com/jxcore/jxcore/blob/master/tools/npmjx/index.js#L198

**Comment by jasonkarns** [comment]
Thanks! Looks like the tar file itself is bad. The tar file as linked (https://s3.amazonaws.com/nodejx/npmjx307.tar.gz) has the executable bit set on all the files as described above.

**Comment by ktrzeciaknubisa** [comment]
Apparently that's because *deps/npm* has this flag too, as well as basically entire jxcore git repo.

**Comment by obastemur** [comment]
@jasonkarns which files needs to have this flag under npm folder ? Can you contribute the solution ?

**Comment by jasonkarns** [comment]
I could, but it sounds like this is a problem with the entire jxcore git
repo. It's not limited to npm.

**Comment by obastemur** [comment]
I've just updated majority with the appropriate permissions. Closing this issue for now. @jasonkarns thanks for all the details.

**Comment by ktrzeciaknubisa** [comment]
However the downloadable npmjx files will still have the old flags, unless we re-upload it. Should we do that?
