### ISSUE TITLE
jx install dtrace-provider

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#678]
I've located the reason why `jx install dtrace-provider` fails with "cannot locate npm install". 

This is `npm/package.json` fragment:

```js
  "main": "./lib/npm.js",
  "bin": "./bin/npm-cli.js",
```

Dtrace-provider install script assumes, that npm was executed by `npm/bin/npm-cli.js` (**bin**) whereas `jx install` calls the npm through **main**. 

Two solutions come to my mind:

* either we set "main" to same value as "bin" (I've checked, it works), but I wouldn't to it, since probably for a reason npm uses them distinctly.
* or `dtrace-provider` team (@chrisa) needs to add an extra path finding condition at [scripts/install.js](https://github.com/chrisa/node-dtrace-provider/blob/master/scripts/install.js#L19-L33) (relative to /lib/npm.js)

**Comment by obastemur** [comment]
Maybe didn't get what you were saying buy what if we had npm-cli is under lib/npm.js ?

**Comment by ktrzeciaknubisa** [comment]
Nope. Let me try to redraw:

1. when we call `npm install dtrace-provider`, it executes `./bin/npm-cli.js`. Now `dtrace-provider` assumes that it is in **bin** folder and searches for the *../node-bin-gyp/node-bin*.
2. but with `jx install dtrace-provider` it calls `jx [...]/lib/npm.js` and now we're in **lib** folder, so  *../node-bin-gyp/node-bin* pattern doesn't work.  

I would tend to ask the authors to add the following:

```js
//npm_execpath: '[...]/npm/lib/npm.js',
if (!fs.existsSync(nodegyp))
  nodegyp = path.join(process.env.npm_execpath,
                        '..',
                        '..',
                        'bin',
                        'node-gyp-bin',
                        'node-gyp');
```

**Comment by obastemur** [comment]
Can we make `jx` calling npm-cli similarly ?

**Comment by ktrzeciaknubisa** [comment]
I would disadvice this just because we've found one module not working. As a side note, if one would call npm though node (`node [...]/lib/npm.js`) rather than npm-cli, the module installation would fail too.

**Comment by ktrzeciaknubisa** [comment]
I'm not sure what have changed, but I don't reproduce it on OSX anymore. Neither with 0.3.0.7 nor later. 
The dtrace-provider package also doesn't seem to be updated...

**Comment by obastemur** [comment]
@ktrzeciaknubisa how about the whole npm update you were doing recently ?

**Comment by ktrzeciaknubisa** [comment]
I've found the case when it works: when `node-gyp` is installed globally, then it is used and there is no problem. Otherwise we get "cannot locate npm install". 

I've added a feature request (referenced right above of this comment) to `dtrace-provider` maintainers for adding support of `--node-gyp` / `process.env.npm_config_node_gyp` (as npm team did https://github.com/npm/npm/pull/4887)

**Comment by ktrzeciaknubisa** [comment]
BTW. current npmjx does not force using our `node-gyp` bundled into npm package, especially when we talk about `package.json` scripts section or `.gyp` files. The new npm is going to be much improved here.

**Comment by ktrzeciaknubisa** [comment]
> Can we make jx calling npm-cli similarly ?

Actually I've done some testing and it looks alright to do it.

**Comment by ktrzeciaknubisa** [comment]
Starting from 0.3.1.1 `jx install` will call the npm by `npm-cli.js` so installing dtrace-provide will work. 

However I left the backdoor open and we may force previous behavior with `--use-main` option, e.g.:

```bash
$ jx install some_module --use-main
```
