### ISSUE TITLE
Getting the NAN API to be updated 

### ISSUE THREAD

**Issue by lygstate** [jxcore/jxcore#691]
https://github.com/nodejs/nan.git

**Comment by obastemur** [comment]
@lygstate can you elaborate on the problem a bit more ?

**Comment by lygstate** [comment]
I means does the jxcore supports for newest version of nan?
So that I could be able use it with node-ffi and other C/C++ nodejs libraries?

**Comment by obastemur** [comment]
JXcore can't support NaN explicitly. Hopefully one day NaN will have SpiderMonkey support.

**Comment by darrrk** [comment]
How difficult to release NAN bindings to SpiderMonkey engine? As I see ChakraCore almost do it.
I think, this a last thing, which don't allow SpiderMonkey to be competitive to V8 and even ChakraCore soon.
