### ISSUE TITLE
arm architecture

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#695]
What version of the ARM architecture are the precompiled binaries for Android and Debian compiled against? node-build currently relies on `uname -m` to provide the architecture; The nodejs releases are specially tagged `arm64`, `armv6l` and `armv7l`, which is the exact `uname -m` output.

I'm trying to match up our architecture matching code for arm systems so that the arm binaries can be used.

**Comment by plika** [comment]
All the ARM release binaries are compiled against `ARM7` which also run on ARM64/8. There is no JXcore binary release for `ARM6`

**Comment by jasonkarns** [comment]
cool!

since I don't have access to an arm device or vm, does anyone happen to know what `uname -m` emits on ARM v8/64 ?

**Comment by obastemur** [comment]
AFAIK `aarch64`

**Comment by jasonkarns** [comment]
can that be confirmed at some point? node-build relies on `uname -m` to choose which binary to install. The currently definitions (in master) only have binaries listed for OSX. everything else falls back to source compilation. I have a branch that adds most of the other binaries to the definitions, but presently it only matches arm7 (which emits `armv7l` from `uname -m`). To make the arm binaries applicable to arm8/64, I'll need to know the exact output of `uname -m`.

**Comment by obastemur** [comment]
@jasonkarns this is the value I got.  Instead of comparing exact string, you might search for `64` for 64 bit and `aarch` / `arm` for ARM. This would cover all the possibilities.

**Comment by jasonkarns** [comment]
@obastemur 

> This would cover all the possibilities.

I assume you mean it would cover armv7 as well as arm64? The issue is that even though jxcore only builds for `armv7l`, nodejs and iojs each have separate builds for `armv6l`, `armv7l` and `arm64`. So the architecture slug that node-build reports back for the system must be specific, not generic. (Otherwise the nodejs/iojs definitions would have no way to choose the appropriate arm binary.)

``` sh
binary darwin-x64 <osx url>
binary linux-armv6l <linux arm6 url>
binary linux-armv7l <linux arm7 url>
binary linux-x64 <linux x64 url>
binary linux-x86 <linux x86 url>

install_package "node-v4.0.0" <source url>
```

Since jxcore uses the same arm build for both arm7 and arm64, I'll just duplicate the binary url:

``` sh
binary darwin-x64 <osx url>
binary linux-armv7l <linux arm7 url>
binary linux-x64 <linux x64 url>
binary linux-x86 <linux x86 url>

install_package "node-v4.0.0" <source url>
```

``` sh
binary darwin-x64 <osx url>
binary debian-armv7l <arm url>
binary debian-aarch64 <arm url>
binary debian-mips <mips url>  

install_package jxcore-0.3.0.7 <source url>
install_package npm <npm url> jxcore_npm
```

**Comment by obastemur** [comment]
@jasonkarns there is no 32 bit arm8. So uname -m will print 64. Since it's ARM based, it will also print `arm` or `aarch`. If you want to figure out the platform-arch, this might be the solution for you.

**Comment by jasonkarns** [comment]
ARMv8-R is 32 bit  :troll:

but it seems that arm64 aarch64 would cover what i need

**Comment by jasonkarns** [comment]
thanks

**Comment by obastemur** [comment]
> ARMv8-R is 32 bit :troll:

ARMv8-R has no MMU hence can't power Ubuntu, Windows etc.. So there is 32 bit arm8 for the platforms node is targeting..

**Comment by obastemur** [comment]
typo: So there is **no** 32 bit arm8 for the platforms node is targeting..

**Comment by jasonkarns** [comment]
Right, sorry. That's why I added :troll:

:)
