### ISSUE TITLE
v0.2.3.7 listed as a previous release, missing tag on github

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#697]
On the previous releases page, it appears that the first (remaining archived) release is v0.2.3.7. However, the only git tags are v0.3.0.0 - v0.3.0.7.

Can v0.2.3.7 be tagged in git?

**Comment by jasonkarns** [comment]
related, since this version doesn't have spidermonkey/v8 specific builds, I'm assuming all the binaries for this release were built against v8?

**Comment by obastemur** [comment]
Yes. You may skip v2.3.7 since it was a closed source binary under a separate license. Starting from v0.3.0.0, it's open source under MIT.

**Comment by jasonkarns** [comment]
Ah. I might create a build definition for it, then, that only lists the binaries.
