### ISSUE TITLE
Change node_modules path?

### ISSUE THREAD

**Issue by Shorty1968** [jxcore/jxcore#699]
Hello my path for node_modules is /var/www/vhosts/computer-base.net/httpdocs/node_modules/ but is false application for my NodeJS takes this wcf / ACP / be.bastelstu.wcf.nodePush / node_modules loud where can I change this?

**Comment by ktrzeciaknubisa** [comment]
Yes, the 'node_modules' folder path is under your domain's home directory (*/var/www/vhosts/computer-base.net/httpdocs/node_modules/*) and we did not design to move it somewhere else. But you can try to use `Environment variables` textbox (in JXcore extension pages / pick your domain) and add:

```
NODE_PATH=wcf / ACP / be.bastelstu.wcf.nodePush / node_modules
```

**Comment by Shorty1968** [comment]
I now have variable at Environment it with the following two variants tried NODE_PATH = / WCF / ACP / be.bastelstu.wcf.nodePush / node_modules and NODE_PATH = / var / www / vhosts / computer-base.net / httpdocs / WCF / ACP / be.bastelstu.wcf.nodePush / node_modules and install the modules of my extension but there are no modules in the corresponding domain displayed / found?

**Comment by ktrzeciaknubisa** [comment]
Only one variant is allowed. If you have defined two - only the latest will be used.

**Comment by Shorty1968** [comment]
I have only this NODE PATH = wcf / ACP / be.bastelstu.wcf.nodePush / node_modules variant variable at Environment entered the path is true but no Installed modules angezeigt.Ich must still say the modules were Putty (SSH) not installed on the JXcore extension anderst'll never forget.
