### ISSUE TITLE
Build fails for chakra engine

### ISSUE THREAD

**Issue by karaxuna** [jxcore/jxcore#700]
Error when running:

```bash
vcbuild.bat --engine-chakra
```

![crypto1](https://cloud.githubusercontent.com/assets/2152815/11668245/8f3df62a-9e0f-11e5-9916-42a45825d3ae.png)

**Comment by obastemur** [comment]
@karaxuna perhaps you mixed up with your branch vs actual JXcore '0.3.1.0' that piece of line doesn't exist on this repo.

**Comment by karaxuna** [comment]
@obastemur I have synced my fork and was working on master branch. I see [this line](https://github.com/jxcore/jxcore/blob/master/src/wrappers/node_crypto.cc#L3338) on master branch of jxcore/jxcore repo

**Comment by obastemur** [comment]
ohh It came with your Public/Private impl. PR to master. Please send the fix then.

**Comment by karaxuna** [comment]
@obastemur https://github.com/jxcore/jxcore/pull/701
