### ISSUE TITLE
0.3.1.0 V8 on Windows: running ghost gives "Cannot convert null to object"

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#713]
Windows 7, x64

```bash
> jx install ghost
> cd node_modules\ghost
> jx index.js 

<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
```

This is **0.3.1.0** V8. Error is similar to #519 (although that was SM).

However 0.3.0.7 V8 works OK.  Also 0.3.1.0 SM is not failing here (it only fails with known #540)

I'm going to trace the exact error line.

**Comment by ktrzeciaknubisa** [comment]
OK, the exact error line is not even related with ghost...

**Reproducible on OSX** (0.3.1.0 V8).

```js
require('domain');
console.log('something');
```

```bash
$ jx index.js
something
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
```

**Comment by obastemur** [comment]
@karaxuna can you locate the source of the problem ? It is also reproducible on Windows.

**Comment by karaxuna** [comment]
Here is stack trace. obj is undefined, that's why this error is thrown. But I don't know reason why it's undefined.

![err](https://cloud.githubusercontent.com/assets/2152815/11824811/50bf6178-a395-11e5-85cc-e99b8f99bc37.png)

**Comment by obastemur** [comment]
@karaxuna very good catch. Found the problem.
