### ISSUE TITLE
Is  memory store standalone?

### ISSUE THREAD

**Issue by xxxman2008** [jxcore/jxcore#715]
Hi, all

     I just wonder if  the process( or tasks) crashed ,what will happen about JX Memory Store? 
 
    if  the data in the  store  will gone?

**Comment by ktrzeciaknubisa** [comment]
Hi, yes, when process crashes, the store contents is gone. But you can subscribe to `process.on('restart')` event and use it to e.g. save the data. See [Internal Process Recovery](http://jxcore.com/docs/jxcore-feature-internal-recovery.html#internal-process-recovery)
