### ISSUE TITLE
how about store Object/Buffer to Memory Store?

### ISSUE THREAD

**Issue by xxxman2008** [jxcore/jxcore#716]
Currently , Memory Store only accept String value . So, if we should store Other type ,I'm use JSON .  
Is there any plan that Memory Store will support other native type ?

**Comment by ktrzeciaknubisa** [comment]
The buffer support was just recently implemented and is part of 0.3.1.0. Take a look docs for [jxcore.store](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-store.markdown#storegetkey)
