### ISSUE TITLE
Managing memory when calling JS function from native

### ISSUE THREAD

**Issue by helmutkian** [jxcore/jxcore#721]
I'm unclear on what the convention is for managing the lifetime of arguments passed to a JavaScript function from native code.

In particular, how are non-persistent objects to be handled? If create a closure over an argument and place it on the event queue, but then invoke ``JX_Free`` on it before ticking the event loop forward, am I potentially causing problems?

Here's an example of what I'm referring to:

````c
void sampleMethod(JXValue *args, int argc)
{
  JXValue fnc = args[0];
  JXValue param;

  JX_New(&param);
  JX_SetBoolean(&param, true);

  JX_CallFunction(&fnc, &param, 1);
  
  JX_Free(&param);
}

void callback(JXValue *args, int argc) 
{
  // do nothing
}

void main (int argc, void **argv) 
{ 
  char *mainContents = "console.log('Engine Started');";
  
  JX_Initialize(argv[0], callback);
  JX_InitializeNewEngine();
  JX_DefineMainFile(mainContents);
  JX_DefineExtension("sampleMethod", sampleMethod);

  JX_StartEngine();

  JX_Loop();

  JXValue out;
  JX_Evaluate(
     "process.natives.sampleMethod(function(x) {"
     "  setTimeout(function () { console.log(x); }, 5000);"
     "});",
     "test",
     &out);
  JX_Free(&out);

  JX_Loop();

  JX_StopEngine();
}
````

**Comment by helmutkian** [comment]
I think I may have found my answer here:

https://github.com/jxcore/jxcore/blob/master/test/native-interface/set-native-method/test-posix.cpp#L46

This comment, however, was confusing me at first:

**Comment by obastemur** [comment]
@helmutkian I've also updated the docs with more explanation. JX_Free only removes the hard reference on native land. It's up to JS engine to collect that variable. If there is any reference to that variable, JS engine wouldn't GC it anyway. Shall we close this issue ?

**Comment by helmutkian** [comment]
Took a look a the docs--much clearer, thank you. Closing this issue.
