### ISSUE TITLE
Is  memory store available in Cluster mode?

### ISSUE THREAD

**Issue by xxxman2008** [jxcore/jxcore#722]
Hi, 
Is  memory store available in Cluster mode?
i cann't make my code working at multi-thread  mode. but  i need  share data with several modules .

any advise will be  appreciate.

Raymond

**Comment by ktrzeciaknubisa** [comment]
> Is memory store available in Cluster mode?

Not really. Memory store is tied to the process and in cluster mode you have multiple processes, so they are separate.

> i cann't make my code working at multi-thread mode

do you mean `jxcore.tasks` or `jx mt` ?

**Comment by xxxman2008** [comment]
i'm using function  like  "jxcore.tasks.addTask(task,2);"  but failed .  the error message like  :

Maximum call stack size exceeded
or
****  no "end" method on undefined..

i will post my code for refference .

**Comment by ktrzeciaknubisa** [comment]
> i will post my code for refference .

Yes please.

**Comment by xxxman2008** [comment]
OK, Code is attached .  It's a zip file ,but  github not allow me upload. so ...please change name first.

what  i want is : 
1.  start 'multicore.js'  first .
2.  running 'prestarttask.js '  ,single thread ,  doing some prepair job ,such as  download config ,verify  running Env  ,etc.
3. start  "RaythonHttpServer" ,accept  request ,and  service for HLS Streaming (not ready yet)
RaythonHttpServer  will work in "MT mode" ,and load HLS file in memory.  SO ,it need  something  like  Memory Store to  share cache data  between threads.

Infact ,Memory store is a great job ,at least for me..


[raythonmediacloud.zip.txt](https://github.com/jxcore/jxcore/files/62641/raythonmediacloud.zip.txt)

**Comment by ktrzeciaknubisa** [comment]
Thanks @xxxman2008 for the code, however I was rather expecting a small piece which demonstrates your `jxcore.tasks.addTask(task,2);` failure. 

> SO ,it need something like Memory Store to share cache data between threads.

You can already use `jxcore.store.shared` between threads of the same main process. Not between clusters though.

**Comment by xxxman2008** [comment]
thanks ,ktrzeciaknubisa  , i will try to  resolve my problem  piece by piece ...Good advise.  i'm just too lazy to review the code.

I write some code before to test the shared store,it's  worked ,so i continue my work. 
appreciate for your help . bye.

**Comment by ktrzeciaknubisa** [comment]
Ok, see you later than, once you get into details. Feel free to open a new ticket if you find something specific.

**Comment by xxxman2008** [comment]
Ok. This is just an Report ,i'm not sure  you can see it ....

The project is worked  on MT mode now .
And finally, i want to Fu******K ASYNC module .
As  an  popular Node.Js module  ,i was  so  trust Async without any condition . But , async has a bad bad bad  behavior , in most of time ,it repeat call function without any delay(or interval).  So..that's  the  problem  of " Maximum call stack size exceeded ".
!@#$%^&  .

**Comment by ktrzeciaknubisa** [comment]
Hmm, but would your Async code work in a single thread (without mt or jxcore tasks?). If it happens only under a thread, maybe there is something we could do, though.

**Comment by xxxman2008** [comment]
Ok, to be honest , It's need ...luck..
if somebody only use one or two times ( we say Async function like until/dountil....),and  the condition in User code is  satisfied ASAP . Async works well .

In my code ,Async crashed process both on  Single thread or Multi threads . I'm using Async.until function  to check my mongodb-connection/ redis-connection/ Memory-share key exists .. ,lots of them..

I've modify my code to use Async.retry  ,which  has "call interval " setting. That's work fine.
