### ISSUE TITLE
listen EACCES - at errnoException (net.js:835:11)

### ISSUE THREAD

**Issue by aleReimondo** [jxcore/jxcore#726]
Hi,
I am trying to set a simple server in an android application that embedds jxcore.
It is basically the sample android app, and it requires http to create the
 most simple server returning always the same text contents.
The server is created and then set to
     listen: 1337 host: '127.0.0.1'
    ( I also tried other port numbers, like 8000, 8080, etc )
Just after  starting the following error is reported in console
---------------
12-15 11:09:47.349 9521-9521/net.smalltalking.s8.jx8 I/jxcore-log: Server running at http://127.0.0.1:1337/
12-15 11:09:47.368 9521-9521/net.smalltalking.s8.jx8 E/jxcore-log: Error: 
12-15 11:09:47.368 9521-9521/net.smalltalking.s8.jx8 E/jxcore-log: listen EACCES
12-15 11:09:47.368 9521-9521/net.smalltalking.s8.jx8 E/jxcore-log:  (net.js 835:10)
12-15 11:09:47.368 9521-9521/net.smalltalking.s8.jx8 E/jxcore-log:
    at errnoException (net.js:835:11)
    at Server.prototype._listen2 (net.js:949:19)
    at listen (net.js:995:5)
    at Server.prototype.listen/< (net.js:1076:9)
    at asyncCallback/< (dns.js:49:9)
    at _tickCallback (node.js:803:13)
    at Module.runMain (module.js:821:3)
    at startup (node.js:374:11)
    at node.js:1
12-15 11:09:47.368 9521-9521/net.smalltalking.s8.jx8 W/jxcore-log: JXcore engine is started
---------------

Don´t know what I am doing wrong, but the same code works on console, etc.
IMHO It should be something related with Android...
Should I set anything on the app project to enable server?

[hello.st.txt](https://github.com/jxcore/jxcore/files/62595/hello.st.txt)

thanks in advance,
Ale.

**Comment by obastemur** [comment]
On the same device, can you run (require('os').networkInterfaces()) and JSON.stringify / console.log the results ?

device has either WiFi / Cell Network right ?

**Comment by aleReimondo** [comment]
Yes, the results of networkInterfaces are:
networkInterfaces={
	"lo":[{"address":"127.0.0.1","family":"IPv4","internal":true}],
	"wlan0":[{"address":"192.168.1.117","family":"IPv4","internal":false}]
}
The device has wifi network and is connected, also wired to debuggin via USB.

**Comment by obastemur** [comment]
interesting indeed. Can you try 0.0.0.0 for IP address ?

**Comment by aleReimondo** [comment]
Same exception, at the same place.
server listen: 1337 host: 0.0.0.0

**Comment by obastemur** [comment]
BTW; do you have the internet permission set ?

```
<uses-permission android:name="android.permission.INTERNET" />
```

**Comment by aleReimondo** [comment]
The AndroidManifest.xml file was corrupted.
I edited the permission and now the error is not thrown.
I could not access the server from other compute, nor the chrome browser in the device, but I should be anotehr issue on Android side.
thank you for your help!

**Comment by obastemur** [comment]
Try listening to public (192.168...) IP address
