### ISSUE TITLE
Running on Android and iOS.

### ISSUE THREAD

**Issue by trusktr** [jxcore/jxcore#727]
Where's the tutorial for that?

**Comment by obastemur** [comment]
See https://github.com/jxcore/jxcore-cordova for quick starter

**Comment by ktrzeciaknubisa** [comment]
There is also an article we wrote [How to Run Node.js with Express on Mobile Devices](http://www.sitepoint.com/how-to-run-node-js-with-express-on-mobile-devices/).

**Comment by trusktr** [comment]
@obastemur @ktrzeciaknubisa Thanks guys! So what happens, does an Android app get the filesystem permissions, and then you can manipulate the "sdcard" in any way you want as you normally would with Node's `fs`, etc?

**Comment by obastemur** [comment]
As long as you have the `write` permission, yes.

**Comment by trusktr** [comment]
That is extremely awesome.
