### ISSUE TITLE
SM on Windows: rare error with process.sendToMain()

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#736]
Windows 7 x64, SM.
On very rare occasion I get a crash when running:

```bash
> Release\jx.exe test\run.js -file test\jxcore\test-tasks-sendToMain-encoding.js -r 10

=== release test-tasks-sendToMain-encoding.js ===
Path: _auto_jxcore_single/test-tasks-sendToMain-encoding.js
Command: c:\Users\azureuser\Github\jxcore_32sm\Release\jx.exe c:\Users\azureuser\Github\jxcore_32sm\test\_auto_jxcore_single\test-tasks-sendToMain-encoding.js
--- CRASHED --- with exit code -1073741819
[00:20|% 100|+   9|-   1]: Done
```

Note, that this happened only 1 time per 10 runs.

This is one of the annoying errors, which seem **not to be visible** when you run a test file **without a python**. I didn't see it even within a loop:

```bash
> for /L %i IN (1,1,10) DO @( echo %i && Release\jx.exe test\jxcore\test-tasks-sendToMain-encoding.js )
```

**Comment by obastemur** [comment]
@ktrzeciaknubisa I wasn't able to repro this with 0.3.1.1. Could you give it a second shot?

**Comment by ktrzeciaknubisa** [comment]
I don't get the error too with 0.3.1.1. With 100 runs 100% are good.
