### ISSUE TITLE
C:\Program Files (x86) bug

### ISSUE THREAD

**Issue by willstdueswissen** [jxcore/jxcore#740]
Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! electron-prebuilt@0.36.1 postinstall: `C:\Program Files (x86)\JXcore\jx.exe install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.1 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     C:\Program Files (x86)\JXcore\jx.exe install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\JXcore\\jx.exe" "C:\\Users\\*****\\.jx\\npm" "install" "electron-prebuilt" "-g" "--build-from-source"
npm ERR! cwd C:\Users\*****
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\*****\npm-debug.log
npm ERR! not ok code 0

**Comment by obastemur** [comment]
What is the jxcore version?

**Comment by willstdueswissen** [comment]
v0.3

**Comment by ktrzeciaknubisa** [comment]
@willstdueswissen This version number is too short. What `jx -jxv` command is saying?

**Comment by ktrzeciaknubisa** [comment]
I've got this with latest 0.3.1.0, but this probably also happens for all other versions. Looks like when we replace `node` occurrence into `jx` in *package.json* of installed module (the `scripts` section), somehow the full jx path is not wrapped with quotes. In @willstdueswissen case this applies for `postinstall` script. 

I haven't found the exact line for this yet.

**Comment by willstdueswissen** [comment]
v0.3.1.0 like ktrzeciaknubisa
And thank you :+1:
JXCore is nice :)

**Comment by ktrzeciaknubisa** [comment]
Hi @willstdueswissen . 

@karaxuna has fixed the issue with https://github.com/jxcore/jxcore/pull/744 .

Please remove your *%HOME%/.jx* folder and re-run your `jx install` command.

**Comment by ktrzeciaknubisa** [comment]
Fixed and working. Closing the issue.
