### ISSUE TITLE
npmjx from 0.3.1.0 isn't properly executable

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#749]
`deps/npm/bin/npm-cli.js` (and others) used to be and should be executable, but is not anymore (changed in https://github.com/jxcore/jxcore/commit/1f546cbcad3d4fe9cd9756dcb9023bcd335582d6). This breaks the symlink that nodenv puts in place to make npm work with jxcore.

PR #748 addresses this issue (and the larger issue of incorrect executable permissions). Opened this issue, though, to track the specific issue of npm not being correctly executable. (In case #748 doesn't get merged)

**Comment by plika** [comment]
@jasonkarns saw #748 has merged. Thank you.

**Comment by jasonkarns** [comment]
@plika has the 0.3.1.0 tarball but re-uploaded to s3? It doesn't matter to me if you use the same url (https://s3.amazonaws.com/nodejx/npmjx310.tar.gz) or a new one, but the 0.3.1.0 and -dev node-build definitions are broken until they can be pointed at a functioning npm package.

**Comment by ktrzeciaknubisa** [comment]
@jasonkarns `npmjx310.tar.gz` is now re-uploaded to S3.

**Comment by jasonkarns** [comment]
thanks!
