### ISSUE TITLE
JXCore not run on boot Linux

### ISSUE THREAD

**Issue by MastaCoder** [jxcore/jxcore#751]
I don't know if this is because I am missing something or a privilege issue, but JXCore doesn't seem to boot on Linux. I have tested this on CentOS and Debian latest and previous versions and they don't seem to work.

I have a script that makes a screen running an JavaScript game server. JXCore seems fine from me running the script and does the work right. But when I set init.d or crontab to run the job on boot, it doesn't seem to work. I get no errors in crontab and it works when I use node instead of jx. I didn't change anything or install anything other then JX on this machine. Any idea?

Thanks!

**Comment by karaxuna** [comment]
I placed [this script](https://github.com/chovy/node-startup/blob/master/init.d/node-app) in `/etc/init.d` folder (named "jx-app"), changed `NODE_EXEC=$(which node)` to `NODE_EXEC="<path_to_jx>"` and set `APP_DIR` to my app directory.

Then added jx-app to the default runlevels:

```bash
update-rc.d jx-app defaults
```

When rebooting OS, `app.js` is executed with jxcore as expected. See node startup [sample repository](https://github.com/chovy/node-startup).

**Comment by ktrzeciaknubisa** [comment]
@MastaCoder jxcore executed with crontab (`@reboot` flag) also works - we do this in JXcore Plesk Extension. In fact in our case the cron is launching a bash script which in turn calls jxcore application. Is this also your way or you try to run jxcore without any bash script?

Try to set up some logging steps, e.g. redirect the output to a file?

**Comment by MastaCoder** [comment]
@karaxuna I am going to try your method quite soon, just need to get a mini-VPS up so I can reboot it a couple times.

@ktrzeciaknubisa I have tried the crontab @reboot function, that doesn't seem to launch the script, only with nodejs it works.

**Comment by MastaCoder** [comment]
UPDATE: 

@karaxuna I am following your steps but I wanted to know for the path to JX, I used the installer that is on the official JX Website, what would the path to install be on Debian? (Ubuntu based system)

**Comment by ktrzeciaknubisa** [comment]
@MastaCoder JXcore gets installed into `/usr/local/bin/jx`. Anyway you may find out by `which jx` command.
