### ISSUE TITLE
on() function returns undefined (instead of the receiver) in Android

### ISSUE THREAD

**Issue by aleReimondo** [jxcore/jxcore#752]
Hi,
I am implementing a server with jxcore under android, with node-static library.
An error is thrown in function streamFile (node-static.js)
The stream is created and correct, but the construction to set
 events serializing .on() calls fail because undefined is returned
 by calling on().
If I separate calls it works as expected, so I suspect that it is a bug
 in on() implementation.
The piece of code that fail in function streamFile follows
-----------------------------------------------------------------------------
```js
(function streamFile(files, offset) {
        var file = files.shift();

        if (file) {
            file = path.resolve(file) === path.normalize(file)  ? file : path.join(pathname || '.', file);

            // Stream the file to the client
            fs.createReadStream(file, {
                flags: 'r',
                mode: 0666,
                start: startByte,
                end: startByte + (buffer.length ? buffer.length - 1 : 0)
            }).on('data', function (chunk) {
                // Bounds check the incoming chunk and offset, as copying
                // a buffer from an invalid offset will throw an error and crash
                if (chunk.length && offset < buffer.length && offset >= 0) {
                    chunk.copy(buffer, offset);
                    offset += chunk.length;
                }
            }).on('close', function () {
                streamFile(files, offset);
            }).on('error', function (err) {
                callback(err);
                console.error(err);
            }).pipe(res, { end: false });
        } else {
            res.end();
            callback(null, buffer, offset);
        }
    })(files.slice(0), 0);
};
```
-----------------------------------------------------------------------------

hope this helps to guide finding the possible bug.
(I would like to help in the finding if someone can point me to the implementation of on for readStream)

thanks in advance,
Ale.

**Comment by ktrzeciaknubisa** [comment]
Hi @aleReimondo . Are you doing this with jxcore-cordova or running with standalone jx ?

**Comment by karaxuna** [comment]
@ktrzeciaknubisa error may be happening because this [function](https://github.com/jxcore/jxcore/blob/master/lib/fs.js#L1617) shall return `_this`.

**Comment by ktrzeciaknubisa** [comment]
@karaxuna you're right. @obastemur has fixed this in https://github.com/jxcore/jxcore/issues/775
