### ISSUE TITLE
JXcore compiled and Android

### ISSUE THREAD

**Issue by athtest800** [jxcore/jxcore#755]
Hello,
I want to run JXcore executable (compiled) when a button is pressed in my Android app but i have not success.
I use "Runtime.getRuntime().exec".
I think that it runs but it exits if full loaded ( i tested a big file, i see it in the processes but it then terminates).
Do you have a solution?
Is this wrong way or is there another way?
Thank you!

my code:
 ``` 
StringBuffer output = new StringBuffer();
String command = "/data/data/com.example.admin.myapplication/JXapp";

        Process p;
        try {
            p = Runtime.getRuntime().exec(command);
            p.waitFor();
            BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));


            String line = "";
            while ((line = reader.readLine())!= null) {
                output.append(line + "n");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String response = output.toString();
```
=========================

**Comment by ktrzeciaknubisa** [comment]
@athtest800 Hi, what kind of app are you expecting to run with JXcore? What is `JXapp`? Is this `jx` binary renamed? I have never tried your approach, but shouldn't your `command` be something like:
`jx some_file.js` ?

**Comment by athtest800** [comment]
I make native file with "jx compile project_file.jxp -native" and save it to sdcard.
The produced native file does not execute from inside my app with the above procedure. But it runs fine in terminal.

**Comment by ktrzeciaknubisa** [comment]
> But it runs fine in terminal.

Do you mean terminal on android (e.g. through `adb shell`) or terminal of desktop computer. Because if you created native file on desktop computer - it will not be runnable on android.

**Comment by ktrzeciaknubisa** [comment]
@athtest800 If I understand correctly and you have created a package on desktop computer (`jx compile project_file.jxp -native`) and then moved to android device - this cannot work. You'd better create a package on the device itself. 

Closing this. Let us know if something shows up. Thanks.
