### ISSUE TITLE
node-expat failed to run on OS X and Windows

### ISSUE THREAD

**Issue by vu-bui** [jxcore/jxcore#761]
I have a problem running the sample scripts from `node-expat` manual:
```javascript
(function () {
  "use strict";

  var expat = require('node-expat')
  var parser = new expat.Parser('UTF-8')

  parser.on('startElement', function (name, attrs) {
    console.log(name, attrs)
  })

  parser.on('endElement', function (name) {
    console.log(name)
  })

  parser.on('text', function (text) {
    console.log(text)
  })

  parser.on('error', function (error) {
    console.error(error)
  })

  parser.write('<html><head><title>Hello World</title></head><body><p>Foobar</p></body></html>')

}())
```
The `jx install node-expat` was fine without any error, but when running `jx index.js`, I get the following error:
```
➜  test-node-expat  jx index.js 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/vubui/development/test-node-expat/node_modules/node-expat/build/Release/node_expat.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/vubui/development/test-node-expat/node_modules/node-expat/build/Release/node_expat.node
  Expected in: dynamic lookup

[1]    22587 trace trap  jx index.js
```
This error only occurs on OS X and Windows. Everything seems to run well on my Linux machine.

**Comment by ktrzeciaknubisa** [comment]
Is this SpiderMonkey build of JXcore?

**Comment by vu-bui** [comment]
It is v8 build.
```
➜  ~  jx -jsv
Google V8 v3.28.71.19
```

**Comment by ktrzeciaknubisa** [comment]
Same version for Windows? Please re-download binary for OSX, it should work:

```bash
$ curl http://jxcore.com/xil.sh | bash -s force
```

**Comment by vu-bui** [comment]
Yeah, just noticed the different V8 version. Everything works fine on OSX now. I'll try getting the new version on my Windows machine tomorrow and get back to you later. Thanks!

**Comment by ktrzeciaknubisa** [comment]
Thanks, I've checked the Windows binaries, and they look OK. And your sample works too.

**Comment by vu-bui** [comment]
It seems that everything is fine now. Thanks for your support. I'm able to resolve this simply by pulling new JXcore version.
