### ISSUE TITLE
JxCore not working on Plesk 12.5 on Linux running Centos 6

### ISSUE THREAD

**Issue by deusoz** [jxcore/jxcore#769]
JxCore was working at one point. Now is frozen  Can't go to tabs "Jxcore Configuration" nor "Domains", when either tab is clicked the page acts like it's loading forever. Same thing if you click "Manage" button from side of either webspace on "Subscriptions" tab. Could not "remove" the extension from the level up Plesk extensions.  Please give command line instructions to reset, fix, upgrade or remove if it's not going to work.  It was not working before I just ran successful Plesk upgrade to 12.5 from 12.0 and still not working.  It worked earlier this year before perhaps a failed Plesk upgrade.

**Comment by ktrzeciaknubisa** [comment]
> Now is frozen Can't go to tabs "Jxcore Configuration" nor "Domains"

Is JX Monitor running? Are the tabs still frozen when you turn it off? I cannot be done through tabs, you can run `pkill -9 jx`

>  Could not "remove" the extension from the level up Plesk extensions.

Why, what happens? 

Which JXcore Extension version are you using? 
Which JXcore version?

**Comment by deusoz** [comment]
Hold on, it seems the tab was taking too long as it took minutes to finally open, but just got the configuration tab to open for first time just now.  Am upgrading now to 3.1.  Stand by and thanks for your help.  Maybe I've got it to respond now

**Comment by deusoz** [comment]
"Please Wait" is still spinning after requesting upgrade minutes ago.  This seems very slow as I don't even have it enabled anywhere.  I'm still waiting for the upgrade to happen. Message in red states: Submitting the form may result in restarting the monitor together with all running applications. SO, I'll just leave the tab open for a while.

**Comment by ktrzeciaknubisa** [comment]
Upgrading JXcore should take max 90 sec (if failed), but when success - max 60 sec. If it takes longer, there might be a problem.

**Comment by deusoz** [comment]
I'm not sure which JXcore version, I only see JXCore Extension on Plesk panel. 
Installed v 0.3.0.7. New version is available: 0.3.1.0
JXcore path 
/usr/local/psa/var/modules/jxcore-support/jxcore/jx
Update to 0.3.1.0
If you reinstall JXcore, all the running node applications will be restarted after updating JXcore binary.

Yeah I'm still waiting, what to do

**Comment by ktrzeciaknubisa** [comment]
> I'm not sure which JXcore version, 

Ok, you have just said: Installed v 0.3.0.7

Isn't you machine busy with something else that slows everything down?

**Comment by deusoz** [comment]
No, not that I can see, Everything in statistics shows very little activity.  Processor less than 3% most of time.
The operation finally stopped, or was stopped by Plesk.  So now I can navigate to "Welcome" and "NPM Modules" "Subscriptions" tabs but not others, or else is taking too long.

**Comment by ktrzeciaknubisa** [comment]
All right, let's come back then: 

So monitor is not started, right? Could you `pkill -9 jx` just for case and see if tabs are responding?

**Comment by deusoz** [comment]
Yes those messages were from JXCore Configuration tab, when it finally came up earlier.  Right now.
OK I see your message, hold on

**Comment by deusoz** [comment]
OK so I should just type that command as root?

**Comment by deusoz** [comment]
"invalid option" -- 9

**Comment by deusoz** [comment]
Maybe just pkill jx ??  it says -9 is not valid

**Comment by deusoz** [comment]
I'm running BASH shell logged in as root

**Comment by ktrzeciaknubisa** [comment]
Did you use single dash or double dash? You may also use `pkill -KILL jx`

**Comment by deusoz** [comment]
I did a single dash like you showed, it showed me back a double dash. OK did -KILL jx

**Comment by deusoz** [comment]
Ok so now.  I actually successfully removed the extension from Plesk configuration.
Should I install again from their catalog JXCore 0.2.8 and  upgrade?  Or do you have a direct command to install newer version via SSH?

**Comment by ktrzeciaknubisa** [comment]
We recommend installing from Plesk Catalog.

**Comment by deusoz** [comment]
ok will try again

**Comment by ktrzeciaknubisa** [comment]
But if this is Centos x32 - the extension will not work.

**Comment by deusoz** [comment]
Not sure about that, but this is 64 bit, if that's what you mean.
OK I've reinstalled and it automatically installed the upgraded version 0.3.10
It seems to be responding now.  Thanks for your help

**Comment by ktrzeciaknubisa** [comment]
So it looks like after some of Plesk upgrades (you've mentioned two: one failed and another successfull) JXcore extension needed to be reinstalled after all?

**Comment by deusoz** [comment]
Yes, But I couldn't kill it so couldn't remove it to reinstall it.  I needed the kill command.:)

**Comment by ktrzeciaknubisa** [comment]
Alright. I'm glad it worked out. Thanks!

**Comment by deusoz** [comment]
Thank you!
