### ISSUE TITLE
jxcore 0.3.1.0 OSX spidermonkey build sha changed

### ISSUE THREAD

**Issue by jasonkarns** [jxcore/jxcore#774]
Was the 0.3.1.0 OSX spidermonkey build (https://jxcore.s3.amazonaws.com/0310/jx_osx64sm.zip ) re-uploaded?

On Dec 19th the sha was: b902a3943588de0688355ffb1ee78f98eac44eca8000d78af8e799ba3b998e92 but now it seems to be a3f21624178c13050da3e7f968bc7ae7e9ca0707a9938d791c126996d6be4eb7

Unsure when the package was modified, but at some point between Dec 19 and Jan 10, it was changed.

**Comment by obastemur** [comment]
on jxcore.com/downloads the SHA for the zip file is "ac5d9335033306fd2d7765f3411e593d78302727"

**Comment by jasonkarns** [comment]
@obastemur that's the sha1, node-build uses sha256. but the underlying issue is that the checksum changed at some point between Dec 19 and Jan 10. I wanted to confirm that the file that is on AWS now is legit and that node-build should update the checksum we have for that package.

**Comment by obastemur** [comment]
Just checked it @jasonkarns yes it is legit. After the release, we did update both of the OSX packages after observing there was a minor problem with the binary inside the zip file and updated SHA on jxcore.com/downloads accordingly.

**Comment by ktrzeciaknubisa** [comment]
@jasonkarns Probably you noticed by differences in prototype index.json manifest file we're working on? I just updated it for you.

**Comment by obastemur** [comment]
@ktrzeciaknubisa lets make that `updating index.json` part of our release process / scripts etc.

**Comment by jasonkarns** [comment]
@obastemur thanks

@ktrzeciaknubisa nah, one of the scripts that we have in node-build verifies URLs/shas. It's included as part of our test process, so it runs on travis automatically whenever there is a PR. It verifies the shas of any URL it can find in any file that's modified as part of the PR.

(There's currently a bug in the way Travis sets the commit range affected by a PR/push, so there is occasionally a test run that accidentally runs our verification script across all share/node-build files in the repo. It just so happened to catch this file change.)

However, it's a larger concern that the files were updated after being uploaded. Node-build expects a version to uniquely identify a package online. If the package changes, node-build expects that to be considered a new version with a new checksum. I realize there are edge cases, but in general one would hope that buggy builds are fixed by new releases and not silently updating the package file. (Considering that so long as a version doesn't uniquely identify a single package, it's entirely possible for two people to install the same version of jxcore, yet end up with different bytes on disk.)

**Comment by ktrzeciaknubisa** [comment]
@obastemur sure, we just haven't decided yet where we're going to host the file, once it is ready (I just need to complete the last part https://github.com/jxcore/jxcore/issues/686#issuecomment-165534128). 

Will it stay on root of jxcore git repo or just on jxcore.com?

**Comment by ktrzeciaknubisa** [comment]
@jasonkarns Same applies to V8 for OSX. This is a sha256:

4961cc3d890b331e3b780e85ba6b60188b975ab4d5bbce64f7d9008b0c8d8b4b

**Comment by jasonkarns** [comment]
@ktrzeciaknubisa thanks! since the verify script exits at first error, it didn't catch the V8 mismatch :)
