### ISSUE TITLE
Can  fs.createReadStream() be used with assets

### ISSUE THREAD

**Issue by nevf** [jxcore/jxcore#775]
Can someone please let me know if ```fs.createReadStream()``` can be used with files in assets. My jx app is failing using it.

I've read "Accessing Files and Assets from a Package" at http://jxcore.com/docs/jxcore-feature-packaging-code-protection.html which suggests it can't be. And I've also read https://github.com/jxcore/jxcore/issues/77 which suggests it can. So I'm a bit confused.

**Comment by obastemur** [comment]
Are you trying to read source files ? (.js) ? If so, add `"fs_reach_sources": true` to `jxp` file.

**Comment by nevf** [comment]
They are .html & .css files.``"fs_reach_sources": true``` is set.

**Comment by ktrzeciaknubisa** [comment]
@nevf Are you having problems with `fs.createReadStream()` for assets? Although it is not mentioned explicitly in the docs, it should work. We even have a test cases for this, e.g. [test/jxcore/test-assets-fs-createReadStream.js](https://github.com/jxcore/jxcore/blob/master/test/jxcore/test-assets-fs-createReadStream.js) . Why don't you try and let us know in case of some problems?

**Comment by nevf** [comment]
@ktrzeciaknubisa Yes I am having a problem as I mentioned in my first post. I am using node-static https://github.com/cloudhead/node-static which uses ```createReadStream()``` and it is failing. 

Before I spent time debugging I wanted to know if createReadStream() should work. I'll reply again once I work out where it is going wrong.

**Comment by nevf** [comment]
Ok, got it. node-static chains event handlers as follows:
````
            fs.createReadStream(file, {
                flags: 'r',
                mode: 0666,
                start: startByte,
                end: startByte + (buffer.length ? buffer.length - 1 : 0)
            }).on('data', function (chunk) {
                // Bounds check the incoming chunk and offset, as copying
                // a buffer from an invalid offset will throw an error and crash
                if (chunk.length && offset < buffer.length && offset >= 0) {
                    chunk.copy(buffer, offset);
                    offset += chunk.length;
                }
            }).on('close', function () {
                streamFile(files, offset);
            }).on('error', function (err) {
                callback(err);
                console.error(err);
            }).pipe(res, { end: false });
````

If I remove the ```.on``` chains and use ```stream.on()``` it works. Otherwise I get ```cannot call undefined of on.``` So this appears as an api inconsistency with node.js?

**Comment by obastemur** [comment]
@nevf can you grab 0.3.1.1 / compile and test if it works for you ? https://github.com/jxcore/jxcore/commit/d28d6c56c1f01e30c9040cf454a9fbb79db01531 should fix the problem.

**Comment by nevf** [comment]
@obastemur Yes that fixes it. Thank you for the very quick fix. 

Can I just confirm that all I need is the new jx.exe, not other libraries, files etc.?

**Comment by obastemur** [comment]
> Can I just confirm that all I need is the new jx.exe, not other libraries, files etc.?
exactly

**Comment by obastemur** [comment]
@nevf Thanks for the details. Closing this issue then.
