### ISSUE TITLE
Compile fail on MAC..

### ISSUE THREAD

**Issue by cube60** [jxcore/jxcore#778]
Compiling fails with...

/bin/sh: jx: command not found
make[1]: *** [/Users/MacPat/Desktop/jxcore/out/Release/obj/gen/jx_natives.h] Error 127
make[1]: *** Waiting for unfinished jobs....
2 warnings generated.
make: *** [jx] Error 2
compilation aborted for ia32 target

Any help would appreciated.

**Comment by obastemur** [comment]
So you either compile one of the `ios, android etc. targets` or enabled `compress-internals` flag ? Install jxcore on your system from https://jxcore.com/downloads

**Comment by cube60** [comment]
When I download and try to use the iOS FAT files by adding them (11) as linked libraries in xcode, the build process fails in xcode with this error....

ld: library not found for -lcares
clang: error: linker command failed with exit code 1 (use -v to see invocation)

However, libcares.a is there in the linked libraries in xcode. I'm developing an iphone app on my mac of course, using xcode. Also, I downloaded the ios sample file you have at /jxcore/jxcore-ios-sample, thinking I can use it as a starting point. It builds nicely on xcode in the iphone simulator, but not the device. Maybe it only has the libraries for the x86 simluator and not arm builds.

**Comment by cube60** [comment]
Here's the error I get when trying to build the ios sample JXcoreHTTPServer, on a 5s device:

ld: '/Users/MacPat/Downloads/jxcore-ios-sample-master/JXcoreSample/JXcore/bin/libjx.a(jx_result.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by obastemur** [comment]
@cube60 This error a bit strange. Most probably you have ios9.x on the device and xcode project settings are not matching with the binary / device. BTW; `bin/` folder under `jxcore-ios-sample` is outdated. (updating now!)

**Comment by obastemur** [comment]
@cube60 `jxcore-ios-sample` is updated with latest JXcore and it works now. Closing this issue for now. Feel free to open back if it doesn't work for you.

**Comment by cube60** [comment]
jxcore-ios-sample works on device now!... thx
