### ISSUE TITLE
request: API for error handling

### ISSUE THREAD

**Issue by grrrwaaa** [jxcore/jxcore#779]
When calling JX_Evaluate or JX_CallFunction, a result code is returned, which is helpful -- but if the result is a failure, how can we access the error? I get something printed to stderr, but in the embedded context I'm working with this isn't visible. Is there a way to redirect the stdout/stderr of the JX engine (hopefully only the engine, not anything in the host)? I tried redirecting process.stderr.write, but this isn't helping. 

Alternatively (or in addition), is there a way to get more information via the embedded API?

**Comment by obastemur** [comment]
@grrrwaaa Is that a kind of uncaught exception ?

**Comment by grrrwaaa** [comment]
Can JX_Evaluate() throw an exception? If so it would be good to note that in the documentation -- along with how to handle it. 

Perhaps I should add some detail. I'm embedding jxcore within an OSX application. The example I was working with was rather simple -- an attempt to require() a module that could not be found on disk. The "module could not be found" error goes to stderr (as I can see it in the console, or if I launch the app from a terminal), but a normal user of the app would not have access to this. I really need a way to capture this error in order to display it within the app itself. I attempted to redirect process.stderr.write in my main file before the offending code, but this does not appear to have any effect. On the other hand, it is not viable to redirect stderr for the host app as a whole, as it would pick up messages from other libraries unrelated to jxcore. 

Should I be modifying the JavaScript code to include a try/catch and log the error that way?

**Comment by obastemur** [comment]
> Can JX_Evaluate() throw an exception? If so it would be good to note that in the documentation -- along with how to handle it. 

Sure it can like any other JavaScript. The plan is to make it return as a return value. 

> Should I be modifying the JavaScript code to include a try/catch and log the error that way? 

I'm on it.

**Comment by obastemur** [comment]
@grrrwaaa I've added a sample on `catching exception`. See https://github.com/jxcore/jxcore/blob/0.3.1.1/test/native-interface/test-throw-exception/test-posix.cpp

It works as is with the current release.

**Comment by obastemur** [comment]
Closing this one for now. @grrrwaaa feel free to open it back if you think this is still an issue
