### ISSUE TITLE
Jxcore crash

### ISSUE THREAD

**Issue by mefffis** [jxcore/jxcore#780]
Hello,

I got this issue in my application:

01-15 16:20:11.617: A/libc(3564): ../deps/uv/src/unix/stream.c:1231: uv__read_start_common: assertion "uv__stream_fd(stream) >= 0" failed
01-15 16:20:11.617: A/libc(3564): Fatal signal 6 (SIGABRT) at 0x00000dec (code=-6), thread 3564 (com.app.debug)

I'm using jxcore builded for android. This error happening in my module that i'm using as i see (i don't have any other logs). In this module i'm using: 

```javascript
var Duplex = require('stream').Duplex;
```

And then i read write data from created stream.

If you interesting, i'm using this module, and this file: https://github.com/mafintosh/peer-wire-protocol/blob/master/index.js

I will work on issue, and provide more info step by step. And i want to try js (not native) implementation of Duplex stream.

**Comment by obastemur** [comment]
@mefffis is it possible to reproduce the issue on one of the sample projects on this repository ? Do you think you can tweak one of them to show the problem?

**Comment by mefffis** [comment]
In my project issue happens randomly, but i will test some small cases, will report if there is result

**Comment by obastemur** [comment]
@mefffis are you using the latest jxcore-cordova?

**Comment by mefffis** [comment]
@obastemur i don't use jxcore-cordova now, i'm using jxcore build for android, latest version

**Comment by mefffis** [comment]
@obastemur not sure, but maybe it is related to https://github.com/nodejs/node/issues/987

**Comment by mefffis** [comment]
@obastemur i have example for you

Try to run this gist:
https://gist.github.com/mefffis/8e9eaabb86d46f1d40b3

It's required module https://www.npmjs.com/package/simple-get

**Comment by mefffis** [comment]
@obastemur result of execution for me is:

    Assertion failed: (uv__stream_fd(stream) >= 0), function uv__read_start_common, file ../deps/uv/src/unix/stream.c, line 1231.

If i'm using [request.js](https://www.npmjs.com/package/request) instead of [simple-get](https://www.npmjs.com/package/simple-get) i get same result. Because i don't think this is module problem or something like it.

**Comment by mefffis** [comment]
@obastemur if you need other examples, i can send, i have few

**Comment by SyRenity** [comment]
@mefffis Good find!

I've passed over my sources and found one that caused this crash - blacklisting it solved the issue for now.

@obastemur would be great if you guys look in what might be causing this crash and have a proper solution.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/46738fb878ea88f45399b107b6a2c9b002f8123b fixes this issue. Thanks for all the details. Fix should be part of 0.3.1.1

**Comment by mefffis** [comment]
@obastemur thanks!

**Comment by mefffis** [comment]
@obastemur thank you, fix works for me
