### ISSUE TITLE
Approach for node-gyp listed in package.json dependencies

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#781]
During extensive npm testing I've realized a problem for packages, which have `node-gyp` listed in its dependencies (e.g. node-sass in #492) . 

 ```js
  "dependencies": {
    "node-gyp": "^3.0.1"
  },
```
If they would call `node-gyp` **explicitly**, there would be no problem, since we can easily replace the path (BTW. current npm is not doing that! - but new one will), e.g.:

```js
 "scripts": {
    "install": "node-gyp rebuild",//-> jx ~/.jx/npm/node_modules/node-gyp/bin/node-gyp.js rebuild
  },
```

But if they call a custom script, it may do practically anything in terms of finding node-gyp.

```js
  "scripts": {
    "install": "node scripts/install.js",  // here we can only replace node -> jx
  }
```

**I see some few ways to go around this:**

1. prevent installing `node-gyp` as dependency and use our own (I guess by copying `~/.jx/npm/node_modules/node-gyp` into the path where the package is installed, because this is the expected location) or
2. alter child_process `spawn` / `fork` / `exec` etc. to detect if `node-gyp` is executed (but only through jx install) and then replace its path into our own (`jx ~/.jx/npm/node_modules/node-gyp/bin/node-gyp.js `)

The second seems to be more universal.

**Comment by obastemur** [comment]
We can override node-gyp within npmjx  as long as no specific version is given. IMHO, this is the way to go.

**Comment by ktrzeciaknubisa** [comment]
But if we want the `node-gyp` to use our `jxb310.tar.gz` etc. then it has to be **our** `node-gyp,` regardless the version specified in dependency. Otherwise the package will be compiled against node downloaded by `node-gyp` from https://nodejs.org/dist/v0.10.40/xxx.

**Comment by obastemur** [comment]
So, patching node-gyp on the fly solves the node-sass issue ?

**Comment by ktrzeciaknubisa** [comment]
Short answer - **yes**. Once I replaced `node_modules/node-gyp` on the fly - it builds correctly. 

Long answer: the `node-sass` is specific package and it also needs an extra env variable `SASS_FORCE_BUILD` set to `true`. I did that by hard-coding  `process.env["SASS_FORCE_BUILD"] = true` inside npm (this value is passed to child process executing build script of `node-sass`), but I wonder if hard-coding is a good idea. Different packages may need different env variables to be set. I'm thinking about some `def.json` file hosted online and fetched by our npm.

Nevertheless users can use `export SASS_FORCE_BUILD=true && jx install node-sass`, but it's less convenient.

**Comment by ktrzeciaknubisa** [comment]
Further notice: replacing `node_modules/node-gyp` on the fly may not always work. First of all we should probably check two paths:

> ./node_modules/node-gyp
> ./node_modules/node-sass/node_modules/node-gyp

This is acceptable for local install, but with `--global` we should be very careful - I would disadvice replacing then.

I seriously start to consider patching jx itself rather than npm. For example if any script calls:

```bash
$ jx /some/path/to/node-gyp.js build etc. --jxcore-npm-override
```

**and** we have e.g. `--jxcore-npm-override` (special npm use-case), then jx would easily switch the path to `~/.jx/npm/node_modules/node-gyp/bin/node-gyp.js`

**Comment by ktrzeciaknubisa** [comment]
A simple path to `module.js` does the trick. Switching `node-gyp` folders is no longer necessary! The usage is that our npm will set `process.env.JX_NODE_GYP_OVERRIDE` (rather than `--jxcore-npm-override` mentioned before):

```diff
 Module.runMain = function() {
   else if (process._EmbeddedSource) {
     Module._load('_jx_source', null, true);
   }
-  else
+  else {
+    if (process.env.JX_NODE_GYP_OVERRIDE) {
+      var bn = path.basename(process.argv[1].toLowerCase());
+      if (bn === 'node-gyp' || bn === 'node-gyp.js' && fs.existsSync(process.env.JX_NODE_GYP_OVERRIDE)) 
+        process.argv[1] = process.env.JX_NODE_GYP_OVERRIDE;
+    }
+
     Module._load(process.argv[1], null, true);
+  }


 Module._resolveFilename = function(r, p, ___, ____, __subCheck) {
+
+  if (process.env.JX_NODE_GYP_OVERRIDE) {
+    var bn = path.basename(r.toLowerCase());
+    if (bn === 'node-gyp' || bn === 'node-gyp.js' && fs.existsSync(process.env.JX_NODE_GYP_OVERRIDE)) 
+      return process.env.JX_NODE_GYP_OVERRIDE;
+  }
+
+
   if (NativeModule.exists(r)) {
     return r;
   }
```

Those two changes take care of two separate cases:

1. jx [...]/node-gyp.js build etc.
2. `require('[...]/node-gyp.js')`

Which seem to be sufficient.

**Comment by ktrzeciaknubisa** [comment]
Alright, the above commit allows our npm to override node-gyp.js used during `jx install`.
