### ISSUE TITLE
Could jxcore support nodeJs version > 4.0?

### ISSUE THREAD

**Issue by syter** [jxcore/jxcore#785]
As I known, jxcore is based on nodejs v0.10.x.
But nodeJs version has already greater than 4.x.
My problem is I have some server projects which used nodejs language. The version is v.0.10.x. And My team decide to upgrade version to 4.2.x, but we find that if we do so, jxcore is no longer support it. 

Is there any solutions for this?

Thank u.

**Comment by ktrzeciaknubisa** [comment]
@syter We've started some work already for this (see 0.4.0.0 branch) but AFAIK the release date is unknown yet. See also related discussion: #535 .
