### ISSUE TITLE
How to load JX package in embedded JX on Android?

### ISSUE THREAD

**Issue by jeffskla** [jxcore/jxcore#786]
I have a JX package file in my apk assets folder that I'd like to use instead of loading multiple JS files. I tried a suggestion from https://github.com/jxcore/jxcore/issues/283, but the file is not found:

<pre><code>JX_DefineMainFile("require('myfile.jx');");</code></pre>

I also tried:

<pre><code>JX_DefineMainFile("require('file:///android_asset/myfile.jx');");</code></pre>

If I copy the file to sdcard, the following works fine:

<pre><code>JX_DefineMainFile("require('/sdcard/myfile.jx');");</code></pre>

In addition to getting the embedded file working, I'm also wondering if there's a way to load remote JX packages from my Android app.

**Comment by obastemur** [comment]
> JX_DefineMainFile("require('myfile.jx');");

This wouldn't work because of `main.js` we use i.e. for `jxcore-android` project extends jxcore's vfs with APK contents. 

See https://github.com/jxcore/jxcore-cordova/blob/master/src/android/java/io/jxcore/node/jxcore.java#L263-L309

and https://github.com/jxcore/jxcore-cordova/blob/master/app/jxcore_cordova.js#L321-L509

**Comment by obastemur** [comment]
@jeffskla feel free to open this issue if you think it is the fault of jxcore. Thanks for sharing

**Comment by jeffskla** [comment]
I was able to get it to work by copying the package from assets to Context.getFilesDir().getAbsolutePath(), and using that path in the require statement.

**Comment by obastemur** [comment]
@jeffskla that also works but we wanted to provide more seamless experience with jxcore-cordova

**Comment by jeffskla** [comment]
Understood. I'm trying to integrate into existing, non-Cordova apps, hence taking the path less traveled.
