### ISSUE TITLE
cannot find module express

### ISSUE THREAD

**Issue by markon1** [jxcore/jxcore#788]
Hi, I have simple app.js, it has 3 requires: url, alasql and express.
I have them installed via npm, and when I export my app to exe file with jx, I can take that exe file wherever I want on my PC(Win10 x64), and it works as it should.
But when I take it to my friend's pc (Win7 x64), it gives me error like "cannot find module express" in console and closes.
What could be the problem? I even tried installing node.js and these 3 requires in folder where my exe file is located on friend's pc, but I get same error..
Shouldn't jx pack everything in one exe file, so it can be run even on pcs without node.js installed?

My express version is 4.13.3, and node is v4.2.3

**Comment by obastemur** [comment]
@markon1 can you please share all the steps command by command here ? so we can reproduce and help.

**Comment by markon1** [comment]
OK.
I used npm install url, npm install alasql and npm install express to install these 3 requires in folder where my app.js is located.
Then I installed jxcore, navigated to my folder containing app.js and typed:
jx package app.js myapp -native

I get the myapp.exe file which works great on my pc, no matter from which folder it is run, but won't work on my friend's PC, which is Win7 64bit (my is Win10 64bit), as I get that "cannot find module express" error when I start myapp.exe.

**Comment by ktrzeciaknubisa** [comment]
@markon1 Please check if on your computer, in the folder where is your app located is there any `node_modules\express` folder? I know that you made an install, but sometimes can happen, e.g. if you have any `nodule_modules` in parent directory that the packages will be installed exactly there instead of your current working directory. 

You can also check from you app directory where the express is : `npm ls express`

**Comment by markon1** [comment]
There is no node_modules\express folder, there is only app.js file in my folder

When I type npm ls express, it says:
C:\Users\stefan

And folder where is my app.js located is:
C:\Users\stefan\Desktop\nodeapp

How can I fix this? I'm pretty new to node.js and npm, sorry if it's noobish.

**Comment by ktrzeciaknubisa** [comment]
It is clear now. Your myapp.exe does not contain `node_modules` and so it cannot work in other computer. I suggest you to create `node_modules` manually in your app folder and then install all those 3 packages, but we recommend to use `jx install` instead of `npm install`.

**Comment by markon1** [comment]
It's working now, thank you very much for help!
