### ISSUE TITLE
Crash when shutting down subengine in embedded JXCore 0.3.1.1

### ISSUE THREAD

**Issue by JorisKoster** [jxcore/jxcore#789]
Hi, I experience I crash when having started multiple JX engines (on different threads) and trying to stop them. I attached a small cpp example that demonstrates this, [jxbug.zip](https://github.com/jxcore/jxcore/files/99148/jxbug.zip). It crashes in ``JXEngine::Destroy`` when going out of scope.  It seems that the ``AutoScope`` object causes to do some stuff with members of the ``main_node_`` object in it's dtor that already have been deleted in the ``node::removeCommons()``. The crash no longer occurs when I modify the ``Destroy`` method such that the ``AutoScope`` object goes out of scope before doing the ``node::removeCommons(); ``, see patch file in attached zip.

I'm not 100% sure if this is the proper solution, as I do not fully grasp the flow of things that are supposed to happen, I hope somebody can confirm and merge it mainstream.

**Comment by obastemur** [comment]
@JorisKoster you can't have another instance in the same thread of (first thread/instance). Each instance needs it's own thread.

**Comment by JorisKoster** [comment]
I know, that's what I meant to say and what I'm doing, "starting multiple JX engines (**each on its own  separate thread**)". After my patch I can spin and more importantly spin down the engine-threads. But as said, I have no clue whether I'm breaking some logic doing so. Please take a look at my example/patch.

**Comment by obastemur** [comment]
@JorisKoster saw it. Patch makes sense. Good catch

**Comment by obastemur** [comment]
Free free to PR.

**Comment by JorisKoster** [comment]
Ok, will do, ty!

**Comment by obastemur** [comment]
@JorisKoster Thanks for the PR and the issue details
