### ISSUE TITLE
Using custom SQLite Library Ubuntu fails

### ISSUE THREAD

**Issue by kesav02** [jxcore/jxcore#798]
Hi,

I am using custom SQLite library based on [see](https://www.sqlite.org/see/doc/trunk/www/index.wiki)
I am trying to get JXCore to work with it following issue [129] (https://github.com/jxcore/jxcore/issues/129)
I did the following:
1. I have installed node v0.10.25, I guess that more advanced node libraries are not yet supported
2. I built my own sqlite3 node file by running "npm install sqlite3 --build-from-source" 
3. I renamed sqlite3 to sqlite3enc
4. I changed sqlite.js binding path to var binding_path = path.join(process.cwd(), "node_sqlite3.node") ;
5. I ran jx package to produce the app.jx and app.jxp
6. I removed node_sqlite3.node entries from app.jxp
7. I then ran jx app.jx

But got this error when trying to run my sample app :(

/root/dev/node_modules/sqlite3enc/lib/binding/node-v11-linux-x64/node_sqlite3.node.jx:2
ELF
^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:589:25)
    at Object.Module._extensions..jx (module.js:1912:7)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (/root/dev/node_modules/sqlite3enc/lib/sqlite3.js.jx:3:15)
    at Module._compile (module.js:619:26)
    at Object.Module._extensions..jx (module.js:1912:7)
    at Module.load (module.js:440:36)

**Comment by ktrzeciaknubisa** [comment]
@kesav02 When using native addons with JXcore you should better use `jx install sqlite3` rather than `npm install`.

**Comment by kesav02** [comment]
Thanks for the quick respond.
I am getting the same error if I am using jx install sqlite3 and then the same steps.
Looks like I am missing something here and I am not sure what

**Comment by ktrzeciaknubisa** [comment]
Don't you want to use JXcore embedded sqlite3? No install needed in that case. Just `require()`.

**Comment by kesav02** [comment]
No :(
I am using a custom SQLite library that provide encryption [see](https://www.sqlite.org/see/doc/trunk/www/index.wiki)

**Comment by ktrzeciaknubisa** [comment]
Your 6th step is not affecting 7th. Editing .jxp file makes sense only if you want to recompile the package with `jx compile` command. If your goal was to exclude .node files from packaging, you may use the following instead:

```bash
$ jx package myapp.jx -slim "*.node"
```

However for narrowing the problem you could try running your custom library with plain `jx` (no packaging). Or even with node itself.

Also, the error points to `/root/dev/node_modules/sqlite3enc/lib/binding/node-v11-linux-x64/node_sqlite3.node`. Isn't the path wrong, as you have changed the binding path to `path.join(process.cwd(), "node_sqlite3.node");`? Maybe you still need to replace something. 

Or instead of replacing the path, maybe replace the file?

**Comment by kesav02** [comment]
hmmm... 
I ran the jx package command with -slim "*.node"
I cleaned up the sqlite folder under node_modules top so it only contain the JavaScript files and made sure the binding_path is updated in the sqlite3.js file

But now I am getting "Segmentation fault (core dumped)"

Note that it works with plain node

**Comment by ktrzeciaknubisa** [comment]
There is still something unclear for me. You said: 

> 2. I built my own sqlite3 node file by running "npm install sqlite3 --build-from-source"
3. I renamed sqlite3 to sqlite3enc

What is "your own" ? Do you mean that you modified sources of installed sqlite3 and then renamed to sqlite3enc ?

**Comment by kesav02** [comment]
I will try making it clear.

Eventually I will be compiling node-sqlite3 against my own sqlite3 lib. Something similar to the way [sqlcipher is integrated to node-sqlite3](https://www.npmjs.com/package/sqlite3#building-for-sqlcipher)
I've done that and that works fine with node.

I am starting the integration with JXCore step by step so I am just building my own node_sqlite3.node using jx install sqlite3, it seem to create a new node_sqlite3.node every time it runs, even without the --build-from-source flag

After that I took the following steps:
1. I changes the node_modules\sqlite3\lib\sqlite3.js binding path to:
var binding_path = path.join(process.cwd(), "node_sqlite3.node") ;
2. moved node_sqlite3.node to the root of the project
3. renamed sqlite3 to sqlite3enc
4. cleaned up the node_moduels\sqlite3enc from everything beside the Javascript files, it had C code and object files

Note that if I run my sample app using node it works fine, but it crashes with jx

**Comment by ktrzeciaknubisa** [comment]
OK, I was also able to receive `Segmentation Fault` on OSX, so it looks like it is not related to your custom SQlite library, but in general SQlite build against JXcore. Those are my steps:

1. jx install sqlite3
2. mv node_modules/sqlite3 node_modules/sqlite3enc
3. save this [sample](https://github.com/mapbox/node-sqlite3#usage) as index.json (just rename `require('sqlite3')` to `require('sqlite3enc')`)
4. jx index.js

**Comment by obastemur** [comment]
Could you please compile jxcore without sqlite embedded before using a custom one? 

```
./configure --no-sqlite
```

**Comment by kesav02** [comment]
That did the trick :+1: 
Thanks!

**Comment by masterperas** [comment]
Not sure why this issue was closed since recompiling jxcore is not a solution.

I'm running on windows and when compiling to native and using better-sqlite3 i get the same error as above.
