### ISSUE TITLE
jxcore util.inherits incompatible with node 5.x behavior

### ISSUE THREAD

**Issue by kzc** [jxcore/jxcore#799]
The following code runs against node 5.x:

    var util = require('util');
    
    function Base(a) {
        this.a = a;
    }
    
    Base.prototype.jump = function() {
        console.log("Base.prototype.jump:", this.a);
    };
    
    function Foo(x) {
        Foo.super_.call(this, x * 3);
        this.x = x;
    }
    
    Foo.prototype.run = function() {
        console.log("Foo.prototype.run:", this.x);
    }
    
    util.inherits(Foo, Base);
    
    var o = new Foo(7);
    o.run();
    o.jump();

and produces this output:

    Foo.prototype.run: 7
    Base.prototype.jump: 21

jx and all versions of node prior to 5.x, produce this error:

    TypeError: o.run is not a function

The reason for this is that jxcore and node 4.x and earlier use this implementation of util.inherits:

```js
exports.inherits = function(ctor, superCtor) {
  ctor.super_ = superCtor;
  ctor.prototype = Object.create(superCtor.prototype, {
    constructor: {
      value: ctor,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
};
```
https://github.com/jxcore/jxcore/blob/91a71e8fe4b6622730da8d7fcef0d1c0011ecbb5/lib/util.js#L548-L558

whereas node 5.x uses this implementation:

```js
exports.inherits = function(ctor, superCtor) {

  if (ctor === undefined || ctor === null)
    throw new TypeError('The constructor to "inherits" must not be ' +
                        'null or undefined');

  if (superCtor === undefined || superCtor === null)
    throw new TypeError('The super constructor to "inherits" must not ' +
                        'be null or undefined');

  if (superCtor.prototype === undefined)
    throw new TypeError('The super constructor to "inherits" must ' +
                        'have a prototype');

  ctor.super_ = superCtor;
  Object.setPrototypeOf(ctor.prototype, superCtor.prototype);
};
```
https://github.com/nodejs/node/blob/e2f47f5698c9eff9b160572811e3804482193dfe/lib/util.js#L791-L807

The older implementation of util.inherits that jxcore uses does not copy the prototypes of the derived class (Foo.prototype.run in the example above).

Would it be possible for jxcore to adopt the node 5.x implementation of util.inherits?

**Comment by obastemur** [comment]
> Would it be possible for jxcore to adopt the node 5.x implementation of util.inherits?

`Object.setPrototypeOf` is not supported by `v8 3.14` however it can be implemented.

**Comment by kzc** [comment]
I see. I only tried the new implementation on jx/spidermonkey where it worked.

Is there any plan to upgrade V8 in jxcore to get this and other features? I don't know how difficult it would be to backport JSObject::SetPrototype().

**Comment by kzc** [comment]
Perhaps for v8 3.14 the [Object.setPrototypeOf polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf#Polyfill) is sufficient?

```js
// Only works in Chrome and FireFox, does not work in IE:
Object.setPrototypeOf = Object.setPrototypeOf || function(obj, proto) {
  obj.__proto__ = proto;
  return obj; 
}
```

It allows the test case with node 5.x implementation of util.inherits to run on jx/v8.

**Comment by kzc** [comment]
See PR #807.

**Comment by kzc** [comment]
#807 was merged. Closing.
