### ISSUE TITLE
MS ChakraCore support (instead-of or in-addition-to Chakra.dll)

### ISSUE THREAD

**Issue by d3x0r** [jxcore/jxcore#801]
1) is there more of a forum or mailing list for such discussions?
2) the question/issue really is trying to use *CH on windows complains 'no CHakra.dll' on Windows 7; without IE upgrades of any sort.  ChakraCore exists as a git repository that builds easily enough with VS 2015 Community... but the DLL it outputs can't simply be renamed 'Chakra.dll' and have it work.

So... maybe should support the open version?

https://github.com/Microsoft/ChakraCore

**Comment by obastemur** [comment]
@d3x0r 0.3.1.0 released before ChakraCore is open sourced publicly. I agree you on supporting open version and that was the plan.

**Comment by d3x0r** [comment]
Work in progress probably.. growing pains with MS as usual.
