### ISSUE TITLE
using npm scripts with jxcore plesk

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#810]
I have some build scripts in my package.json that I'd like to run at startup which would normal work by using `npm start ` but I can't work out how to achieve this with jxcore for plesk

**Comment by ktrzeciaknubisa** [comment]
Do you need to run this each time the app starts (or restarts)? If so, you may add e.g.  `startup.js`, which would become the app main file. Run there your script and exec the actual `index.js` afterwards.

**Comment by dottodot** [comment]
Yes it's so I can do things like browserify my code so I have something like the following

```
"scripts": {
    "start": "npm run build && node app.js",
    "debug": "npm run build && node debug app.js",
    "build": "npm run postcss && npm run frontend-build-js && npm run admin-build-js",
    "frontend-build-js": "browserify -t hbsfy assets/frontend/js/main.js -o assets/build/frontend.js",
    "admin-build-js": "browserify -t hbsfy assets/backend/js/main.js -o assets/build/backend.js",
    "postcss": "postcss --use autoprefixer -c postcss.json -o assets/styles/frontend.css assets/styles/frontend.css"
  }
```

**Comment by ktrzeciaknubisa** [comment]
@dottodot The feature to run e.g. `npm start` from JXcore Plesk extension is not supported. You may either use the approach I've mentioned above or if you have ssh access - type it from the command line.
