### ISSUE TITLE
Is it safe to use c++11 std::thread in native code?

### ISSUE THREAD

**Issue by kangjoni76** [jxcore/jxcore#812]
Is it safe to use c++11 std::thread in native code? I want to use this for my rest api backend from database from c++. thanks

**Comment by obastemur** [comment]
> Is it safe to use c++11 std::thread in native code?

What do you mean?

**Comment by kangjoni76** [comment]
My point is that I want to handle native c++ code for heavy database processing and handle seperate jxcore thread and my db controller thread in c++ but still in the same jxcore context.

**Comment by obastemur** [comment]
@kangjoni76 I'm not sure that I quite understand it but as long as you access to VM from it's own thread, there is no problem I can see.
