### ISSUE TITLE
Erroneously builds .so instead of .dylib on OS X

### ISSUE THREAD

**Issue by zsszatmari** [jxcore/jxcore#817]
Hi!

  When building a shared library, 0.3.1.1 now produces an .so file instead of .dylib . On OS X .dylib is the preferred format, and .so is very rarely used. If I nevertheless try to dynamically link with my own app, it simply does not find it, because it expects .dylib extension. If I rename extension, I get from Xcode:

```
can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file 'lib/x64/libjx.so' for architecture x86_64
```

  0.3.0.6  was correcly building .dylib.
  Any quick workarounds you could suggest? Thanks a lot!

**Comment by obastemur** [comment]
Can you share the exact command line for compiling ?

**Comment by zsszatmari** [comment]
Sure:

```bash
./configure --shared-library --prefix=/Users/zsszatmari/jxlib/
make
```

```make install``` at this point throws an error, as it expecting a dylib (correctly):

```bash
IOError: [Errno 2] No such file or directory: 'out/Release/libjx.dylib'
```

**Comment by obastemur** [comment]
Please checkout the latest 0.3.1.2 and see if it works for you

**Comment by zsszatmari** [comment]
Seems cool, Thanks!
