### ISSUE TITLE
 SM: out of memory when unzipping ios.zip from jxcore-cordova

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#822]
SM has a problem with unpacking of `io.jxcore.node.jx` as @vjrantal reported. The package itself gets extracted successfully, but then it unzips a large ios.zip file by using `adm-zip` ([jxcore-cordova/index.js#L5-L8](https://github.com/jxcore/jxcore-cordova/blob/master/index.js#L5-L8)) and it ends up with out of memory exception. Indeed, the process grows up to 2GB RAM usage and then crashes.

I'm not sure yet if this is adm-zip or jx SM related issue, however V8 handles that task correctly and never skips 250 MB of RAM.

**Comment by obastemur** [comment]
jxcore-cordova 0.1.1 package has this issue is fixed.
