### ISSUE TITLE
SM: process.versions.ch missing

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#829]
The following code [node.cc#L2034-L2048](https://github.com/jxcore/jxcore/blob/master/src/node.cc#L2034-L2048) makes that `process.versions.ch` is not present for SM build:

```js
{ 
  ...
  v8: 0,
  sm: 34,
  ...
}
```
For consistency shouldn't we add `ch : 0` ?

**Comment by obastemur** [comment]
Sure

**Comment by ktrzeciaknubisa** [comment]
Done. How about related https://github.com/jxcore/jxcore/issues/814 ?
