### ISSUE TITLE
jxcore.utils.getOS() vs linaro

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore#833]
In relation to this commit eb372d56a3b6933ccf884e24577c4e8794877c89, what is expected result of `jxcore.utils.getOS()` for *linaro* keyword?

Currently all "linaro" gets detected as debian

* example 1. This is ubuntu detected as debian.

```bash
$ cat /proc/version
Linux version 3.13.0-74-generic (buildd@lgw01-34) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #118~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015

$ jx -p "jxcore.utils.getOS()"
debian-x64
```

* example 2 taken from #760 . Do we know for sure that this is debian? We might add some extra check here.

```bash
$ cat /proc/version 
Linux version 3.18.11-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) 
(crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 SMP PREEMPT Tue Apr 21 
18:07:59 BST 2015

$ jx -p "jxcore.utils.getOS()"
debian-x64
```

**Comment by ktrzeciaknubisa** [comment]
I've checked on raspberry with similar distro to no 2. above:

```bash
$ cat /proc/version 
Linux version 3.18.11+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) 
(crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 PREEMPT Tue Apr 21 
18:02:18 BST 2015
```

and we can get an extra info with the following command:

```bash
$ cat /etc/issue
Raspbian GNU/Linux 7 \n \l
```
which definitely suggests debian.

**Comment by obastemur** [comment]
Search for Ubuntu, Debian etc. first and finally check Linaro and default to Debian?

**Comment by ktrzeciaknubisa** [comment]
The above commit should do it. Tested on `(Ubuntu/Linaro 4.6.3-1ubuntu5)` and raspbian.
