### ISSUE TITLE
JXCore Plesk Extension - Running grunt file instead of index.js/app.js?

### ISSUE THREAD

**Issue by paulcanning** [jxcore/jxcore#843]
My node app requires me to run grunt in order to start the application.

Is there a way to do this with the JXCore Plesk Extension?

**Comment by ktrzeciaknubisa** [comment]
Nope. There is a similar talk https://github.com/jxcore/jxcore/issues/810:

> you may add e.g. startup.js, which would become the app main file. Run there your script and exec the actual index.js afterwards.

**Comment by paulcanning** [comment]
Could you provide an example of what you mean? Where do you "add" startup.js? What should the code in this file look like?

**Comment by ktrzeciaknubisa** [comment]
If you'll give few more details how you want to use grunt to start the app, then I can share my thoughts.
