### ISSUE TITLE
Windows Defender thinks JXcore_setup.exe is malware

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#845]
I was trying to install [this release](https://jxcore.s3.amazonaws.com/0311/jx_winsetup.zip) on Windows and Windows Defender won't allow it, it says that JXcore_setup.exe is malware and automatically removes it. What's going on?

**Comment by obastemur** [comment]
This is an issue with Windows Defender update. It recognize InnoSetup signature as a malware. Try earlier releases and you will have the same problem. AFAIK, this has been reported to MS but don't know what's happened.

**Comment by ktrzeciaknubisa** [comment]
There is some talk related: https://github.com/oneclick/rubyinstaller/issues/273 .
