### ISSUE TITLE
Compile for MIPS with v8 engine

### ISSUE THREAD

**Issue by darrrk** [jxcore/jxcore#852]
Hello, I follow guide https://github.com/jxcore/jxcore/blob/master/doc/OpenWrt_Compile.md and compile jxcore for MIPS and receive binary with sm engine. But project require some `node-gyp` modules and need compile with v8 for MIPS. Can I do this?

**Comment by obastemur** [comment]
You might edit build scripts and make it using V8 instead. Search for `--engine-mozilla` reference and remove it

**Comment by darrrk** [comment]
Thank's you for help!
