### ISSUE TITLE
precompiled binaries link empty?

### ISSUE THREAD

**Issue by arniesaha** [jxcore/jxcore#853]
Hello! 
Im looking for the pre-compiled binaries/installer for windows x64 but the link http://jxcore.com/downloads shows, " There aren’t any uploads for this repository." 

Am I missing something here?

TIA,
Arnab

**Comment by ktrzeciaknubisa** [comment]
Don't worry, we're moving things. They are going to be back online soon. I'll let you know.

**Comment by ktrzeciaknubisa** [comment]
We've changed the downloads location into: https://github.com/jxcore/jxcore-release . It's already available there.

**Comment by arniesaha** [comment]
Thanks! :)

**Comment by jasonkarns** [comment]
Just an FYI for anyone who stumbles on this... node-build has extracted the jxcore build definitions to their own plugin: https://github.com/nodenv/node-build-jxcore (and updated the urls/checksums)
