### ISSUE TITLE
Webpage is broken

### ISSUE THREAD

**Issue by siuying** [jxcore/jxcore#855]
The homepage http://jxcore.com/ all redirected to github page now.

**Comment by fbmx** [comment]
+1

**Comment by pirog** [comment]
+1

**Comment by darrrk** [comment]
:+1:

**Comment by ktrzeciaknubisa** [comment]
So is this good or bad for you guys? :) It's not that webpage is broken, we just decided to do it that way.

**Comment by siuying** [comment]
This is bad, for many links on Internet or readme point to now 404 links. I could not find documents or pre compiled library download links.

**Comment by siuying** [comment]
Search "jxcore download" get nothing. Search cli like jxcore package previously return helpful document now return nothing.
