### ISSUE TITLE
Is the source protected when packaged with jxcore?

### ISSUE THREAD

**Issue by ashking** [jxcore/jxcore#857]
I'm going through this doc and it nowhere mentions about source code protection. I'm wondering if the source is actually protected? https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-feature-packaging-code-protection.markdown

Can someone reverse engineer the source packed with jxcore?

**Comment by obastemur** [comment]
I've fixed that statement. JXcore as an open source project does not provide source code protection.
