### ISSUE TITLE
 http://jxcore.com/xi.sh missing

### ISSUE THREAD

**Issue by Ciao121** [jxcore/jxcore#860]
As title, so peopla cannot install i typing
`curl http://jxcore.com/xi.sh | bash`

**Comment by ktrzeciaknubisa** [comment]
There is an alternative link mentioned on [INSTALLATION.md#for-linuxosx](https://github.com/jxcore/jxcore/blob/master/doc/INSTALLATION.md#for-linuxosx):

```bash
$ curl https://raw.githubusercontent.com/jxcore/jxcore/master/tools/jx_install.sh | bash
```
