### ISSUE TITLE
Why no updates?

### ISSUE THREAD

**Issue by voxsoftware** [jxcore/jxcore#866]
Node.js is currently in version 5.8.0, and JxCore is in version 0.10.40

**Comment by mccloud-jeff** [comment]
Would like to hear more about this as well? Strongly considering jxCore, but concerned it hasn't been moved up to at least Node.Js v4.x.x

**Comment by yieme** [comment]
+1

**Comment by brodybits** [comment]
Guys you may want to look at the discussion in #535 which I had raised to update with Node 4.0 and just renamed to update with Node 4.0 (+). The two biggest challenges I can think of are:
- Integrate the customized version of V8 from Node 4.x/5.x in this project
- The C/C++ part of this project was based on something like Node 0.8.x/0.10.x but was reworked to work with the JX interface, which is supported for multiple JavaScript engines.

So far some Node 0.12.7 changes have been integrated as discussed in #571.

**Comment by obastemur** [comment]
We are not planning a future version. See Readme.
