### ISSUE TITLE
website (http://jxcore.io/ ) is down

### ISSUE THREAD

**Issue by mtrabelsi** [jxcore/jxcore#883]
I noticed that http://jxcore.io/  inaccessible, whenever i try to enter i get : 

> This site can’t be reached
> 
> jxcore.io’s server DNS address could not be found.
> Search Google for jxcore io
> ERR_NAME_NOT_RESOLVED

Could you guys confirm this issue?
Cheers

**Comment by obastemur** [comment]
See http://www.nubisa.com/nubisa-halting-active-development-on-jxcore-platform/
