### ISSUE TITLE
Cannot apply file description information. The '.ver' file not found.

### ISSUE THREAD

**Issue by aleReimondo** [jxcore/jxcore#885]
(jxcore windows)
I am using the following expression to build an executable with javascript file and other resource files.

jx package default.snapshot.js --name "jx8" --slim "build,bin,*.sh,*.bat" --native --extract-app-root

It worked ok in the past (up to version 0.3.1.0); but with an executable built from current version of sources it is reporting the message:

-------------------------------
Cannot apply file description information. The '.ver' file not found.
..
[OK] compiled file is ready (C:\C\v8\s8\release\platforms\jx8\jx.exe)
-------------------------------

When executed, the built executable do start decompressing all resource files, but after that it exits without error report and no output.

How can I provide a .ver file? Can anyone provide a sample file? (I searched the source tree and could'nt find a .ver file there)

**Comment by ktrzeciaknubisa** [comment]
The `.ver` file should be available in install directory (if you used JXcore installer). Even if you're using different `jx.exe` (like manually compiled), same `.ver` file will be used. 

Otherwise you can rename `jxcore/tools/msvs/node.exe.ver` into `jx.exe.ver` and keep in your `jx.exe` folder.

**Comment by aleReimondo** [comment]
it worked!
thank you
