### ISSUE TITLE
--max-old-space-size does not work in JXcore with multiple threads

### ISSUE THREAD

**Issue by gh-andre** [jxcore/jxcore#89]
If I run this code 

```
var strings = new Array();
var block;
var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

for(var j = 0; j < 100000; j++) {
    block = new String();
    for(var i = 0; i < 1024; i++)
        block += alphabet.charAt(Math.random() * alphabet.length);

    strings.push(block);
}
```

, under original node or in the new JXcore you just released without `mt:x` option and with `--max-old-space-size=4200`, then the code runs and exits after allocating about 4GB of RAM. If I run it with `mt:2` on the command line, JXcore runs out of memory at about 2.9GB, which means that it's still on 1.5GB per v8 Isolate.

**Comment by jiangzhuo** [comment]
If already compiled into native,, how can I use --max-old-space-size param?
./testNative --max-old-space-size param=42000 not work.

**Comment by ktrzeciaknubisa** [comment]
Nope, sorry. See #165 for the answer.
