### ISSUE TITLE
ReferenceError: require is not defined in embedded lib

### ISSUE THREAD

**Issue by Tunga37** [jxcore/jxcore#919]
I followed tutorial from : https://github.com/jxcore/jxcore/blob/master/doc/native/Embedding_Basics.md
and compiled project as ./configure --static-library --prefix=./targetFolder --engine-mozilla --compress-internals --fully-static
then i did make -j4 install

And everything went fine, this example worked :

...
 JXValue result;
  JX_Evaluate(
    "var arr = process.natives.sampleMethod('String Parameter', {foo:1}); \n"
    "console.log('result: ', arr, 'length:', arr.length ); \n"
    "setTimeout(function() { \n"
    "  console.log('end!'); \n"
    "}, 100);",
    "myscript", &result);

  JX_Free(&result);
  // loop for possible IO
  // or JX_Loop() without usleep / while
  while (JX_LoopOnce() != 0) Sleep(1);

  JX_StopEngine();
}

The problem is : if you put into the script require statement like e.g. "var fs = require('fs'); and run
 JX_Evaluate(script,...);
you will get the message "ReferenceError: require is not defined"

How to fix that?

**Comment by 1424667164** [comment]
did you fix this?? I get this error too.....

**Comment by 1424667164** [comment]
I have fix this.
all you need do is:
char *contents = "global.require = require;";
// define the entry file contents
JX_DefineMainFile(contents);

yes, require can visit in main.js

.....

**Comment by Tunga37** [comment]
Thank you so much, I will test this tomorrow, however there was same problem with function exports and module and maybe something else also. I hope it can be fix by the same approach.
Regards
