### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by alexluoli** [jxcore/jxcore#926]
![wechatimg189](https://cloud.githubusercontent.com/assets/14903888/25306260/1fb4bebe-27bc-11e7-8b99-49f9358d762d.jpeg)

**Comment by alexluoli** [comment]
![wechatimg190](https://cloud.githubusercontent.com/assets/14903888/25306300/d2382562-27bc-11e7-861f-eb4ce4ee09a2.jpeg)

**Comment by alexluoli** [comment]
![wechatimg191](https://cloud.githubusercontent.com/assets/14903888/25306311/044105b0-27bd-11e7-9b7e-405947d84f96.jpeg)

**Comment by alexluoli** [comment]
![wechatimg191](https://cloud.githubusercontent.com/assets/14903888/25306315/2868c126-27bd-11e7-802d-e114ee2bb280.jpeg)

**Comment by obastemur** [comment]
The project is no longer maintained. If you need to use it anyway, you might better follow the instructions and build.
