### ISSUE TITLE
[ curl http://jxcore.com/xil.sh | bash ] can't install jx

### ISSUE THREAD

**Issue by JaneLMF** [jxcore/jxcore#939]
```shell
curl http://jxcore.com/xil.sh | bash
```
when i paste above command to terminal in macOS, my computer do Nothing. Please help.

**platform: macOS Sierra 10.12.6**

**Comment by westtrade** [comment]
Because site is dead. and i think project too...

**Comment by sparcbr** [comment]
I hate when ppl do that. At least they could have put a msg here

**Comment by obastemur** [comment]
Please read the readme. Thanks
