### ISSUE TITLE
mac install fail ???

### ISSUE THREAD

**Issue by wenhuichen** [jxcore/jxcore#947]
ChenWenhuis-MacBook-Pro:~ chenwenhui$ curl http://jxcore.com/xil.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24  100    24    0     0     39      0 --:--:-- --:--:-- --:--:--    39
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<h1>404: Not Found</h1>'
ChenWenhuis-MacBook-Pro:~ chenwenhui$ curl https://raw.githubusercontent.com/jxcore/jxcore/master/tools/jx_install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5224  100  5224    0     0  14087      0 --:--:-- --:--:-- --:--:-- 14080
JXcore Installation Script for X systems
 
Testing for a BSD distro 
Downloading latest version info 
Could not fetch

**Comment by wuweiyan2012** [comment]
You can refer to #912 
The pre-compiled binaries of JXcore available from [https://github.com/jxcore/jxcore-release](url)，You can download it directly!
